### ISSUE TITLE
Develop a practice for incorporating feedback from the feedback tool

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1009]
Per the discussion in our sync up today, @onezerojeremy will help establish a practice for taking feedback from the tool, synthesizing it and presenting it to the full team in our Friday meetings so that we can choose what we want to act on.

Personally, I think this discussion makes the most sense to do on the mid-sprint Friday meetings.

**Comment by noahmanger** [comment]
I know this is done, but I forget where it's documented. @onezerojeremy ?

**Comment by onezerojeremy** [comment]
Draft process:

we've got a spreadsheet in google docs:
https://docs.google.com/spreadsheets/d/1_0at7HqTaKKYaMk6PsUy5XYm_LNUD4O9N72fYJeHBUk/edit#gid=1759743196

This is very much a draft, as it's still a pretty manual process where by someone takes a look at the the feedback on https://github.com/18F/fec/issues?page=2&q=is%3Aissue+is%3Aopen
and try to make it useful not just for bug fixes and feature requests, but for the attention it shows for each of the site sections. The idea is that can help us prioritize: the (obviously flawed, possibly useful) assumption is that in order to make a request, a user needs to 1. have looked at the page (hey, great, attention) and 2. care about a thing. So if we're seeing more feature requests or bugs in an issue, we should consider prioritizing it. 

Going to need someone else to tag in on this for the upcoming weeks.

**Comment by noahmanger** [comment]
How's this going @brethauer ? Can I help at all?

**Comment by brethauer** [comment]
Hey @noahmanger I'd be glad for some help- I chatted with @leahbannon a few days ago and I believe she is doing some thinking about this, so she may want to chime in here too.

Two questions:
1) How important is it to look for trends here? I like the idea generally, but obviously there is a time/effort cost and someone needs to own it (not sure I have the bandwidth)
2) What has been most useful about the feedback that has come in so far?

**Comment by noahmanger** [comment]
I'd say the utility of the feedback tool so far has been one part catching bugs and one part getting a general sense of need (such as when a bunch of people requested downloads). I don't think this should take a ton of time, but someone should have their eye on it.

We can talk about this more at our meeting tomorrow, but I've been thinking about how this fits into some process improvements I want to make, and I think it probably makes sense for me to own. So let's talk then.
