### ISSUE TITLE
Design interaction based on partitioned transaction tables

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1023]
In order to a) provide downloads for large tables, and b) provide more years of data to the transaction tables, we're going to be partitioning these tables, which has consequences for how you can search and filter them. 

Whether as part of the overall browse IA work or separate, we need to figure out how this interaction is going to work. 

As currently planned, users will only be able to search through one year of data at a time. So we need to find a painless way to do this, or figure out a different approach.

**Comment by jenniferthibault** [comment]
@jmcarp do you have time to talk with me about this today?

**Comment by noahmanger** [comment]
@jenniferthibault lemme know if you want to pair on this.

**Comment by jenniferthibault** [comment]
A first inclination at a straightforward approach:

Partitioning by year or two-year period will allow users to compare all transactions in election cycles within one table – if they want to compare across election cycles or years, they'd have to change the view. This seems like a way that would constrain results in a way that still fits within a mental model of elections as cycles and time-based periods.

Here's how we could require (though gently) that the user first selects a year or two year period to view events for. I believe two-year period is more desirable than one year at a time. It would be nice to integrate the 2/4/6 year view to create consistency across the site, but I get the sense that that is too much data. Correct @jmcarp ?

![screen shot 2016-01-26 at 10 56 37 am](https://cloud.githubusercontent.com/assets/11636908/12588028/cb558e6c-c424-11e5-83de-ebf1ac0ac983.png)

- the 2015–2016 cycle (or otherwise most recent two-year period) would be applied by default upon landing
- this would be the first-ordered field in the filter list
- if it needs explanation, we could add the text (or similar) seen here. Keep it short & sweet though. (cc @emileighoutlaw for a thing we will eventually want to test and microcopy preview)

Keen on your thoughts, @noahmanger

**Comment by noahmanger** [comment]
Cool cool. Yeah, I think two-year period will be better, especially as the aggregates on committee pages are all based on the two-year period. 

What do you think of having the message as an info tooltip like we have on the "unique only" filter?

**Comment by emileighoutlaw** [comment]
Curious to hear what @jenniferthibault thinks about the tooltip. I think it makes sense either way. 

*Con tooltip*: It's more noticeable if it's always visible (not a tooltip)
*Pro tooltip*: The filters will be easier to take in with less text clutter (if it is a tooltip)

I like the text you have suggested there.

**Comment by LindsayYoung** [comment]
Are we partitioning by filing date or receipt/disbursement date @jmcarp ? I have a strong preference for the receipt and disbursement dates because that will be the year the record is describing, we will get funky results because of amendments if we go by the filing date.

**Comment by noahmanger** [comment]
Good question. When we show aggregates on committee pages is that by
receipt date or by filing date?

On Tue, Jan 26, 2016 at 12:00 PM, Lindsay Young <notifications@github.com>
wrote:

> Are we partitioning by filing date or receipt/disbursement date @jmcarp
> <https://github.com/jmcarp> ? I have a strong preference for the receipt
> and disbursement dates because that will be the year the record is
> describing, we will get funky results because of amendments if we go by the
> filing date.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/1023#issuecomment-175202194>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by LindsayYoung** [comment]
That goes by the `rpt_yr` which is the year the report applies to not necessarily the year it was filed.

**Comment by noahmanger** [comment]
Great. Good that that lines up.

The other part of this, then, that we need to address is how the date filters work below. We need to restrict them to just dates within the selected year.

**Comment by jenniferthibault** [comment]
Yeah, I was anticipating needing to line up the date filters. We need to get this into the mega filter spreadsheet.

I'd rather have a tooltip, just wasn't sure if we wanted this info to be omnipresent.

**Comment by emileighoutlaw** [comment]
I can give my :+1: to tooltip!

**Comment by jenniferthibault** [comment]
Tooltip closed:
![screen shot 2016-01-26 at 3 56 24 pm](https://cloud.githubusercontent.com/assets/11636908/12594712/6ab973cc-c445-11e5-920e-76e613744707.png)

Tooltip open:
![screen shot 2016-01-26 at 3 56 13 pm](https://cloud.githubusercontent.com/assets/11636908/12594711/6ab43f10-c445-11e5-8f58-25cad54c748c.png)
