### ISSUE TITLE
Make filter tags work for ranges

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1029]
Filter tags need to show up correctly for range inputs. Currently, we have two types: money and time. 

Here's a proposal for how it would work for both:

![tags](https://cloud.githubusercontent.com/assets/1696495/12272459/7154037c-b915-11e5-87db-fcceab3514a2.png)

The thing that I'm least sure about is how to handle an undefined min value, especially for date ranges. Do we set it to the min date we have in the data? The min date based on real world constraints (like when the FEC first started getting the data)? Or do we come up with a language solution that doesn't require defining a value? Looking to @jenniferthibault and @emileighoutlaw on this.

Also, in the case of the time filter where there's also radios, I think we should only generate tags for the actual dates, so that you don't see "Current year" as well as "1/1/2016 - 12/31/2016".

**Comment by emileighoutlaw** [comment]
Interesting thought. I'm going to think about this for a sec — will make recommendations by COB tomorrow.

**Comment by emileighoutlaw** [comment]
### General thoughts:
When we're applying ranges, let's make sure we're using an `n` dash and no spaces. Like so: "$200–$300." Consequently, if you want me to review that content when you put it in, I can do that no problem!

### Undefined max:
**Money:** I like `$200 and up`. It's the same content construct used by most other websites I like (I'm looking at you, Amazon). I think we should go with that and see how it tests with users.
**Dates:** `1/10/2015–present` feels like the best option. That said, I do wonder how many folks might mistakenly think this includes all data (through the day they apply the filter), as opposed to the most recent data available, which might be weeks or months behind the date on which they search. We could test this, and I think the possibility of confusion is outweighed by the difficulty of reading a longer and more technically precise filter. 

### Undefined min:
**Money:** I like `$200 and under`, for consistency with `$200 and up` as the undefined max.
**Dates:** For the same reason I paused about the word "present" above, I am excited by setting the min based on the actual constraints, a la `1/1/1976`. Knowing the actual date data is starting seems most useful, from a research and reporting standpoint— if you want to write about the data or use it as evidence to prove any point, you'll need to know when the it actually starts.



**Last thing:** This isn't really helpful to us, but it is interesting: When you apply a range filter on Amazon, it shows up top as "Advanced Search."

<img width="597" alt="screen shot 2016-01-12 at 6 22 26 pm" src="https://cloud.githubusercontent.com/assets/10552702/12280103/894ffb36-b959-11e5-8c8a-245e07d2e9e6.png">

**Comment by jmcarp** [comment]
One issue that came up while talking to @noahmanger is how to handle the "X" button on filter tags with multiple values. Does closing the tag clear both fields? Do we allow users to clear one value or the other separately?

I'm wondering if we might consider a simpler approach, such that each filter field gets its own closable filter tag:

Min only: ">= $500"
Max only: "<= $1000"
Min and max (two filters): ">= $500" "<= $1000"

**Comment by jmcarp** [comment]
Ping @emileighoutlaw @jenniferthibault

**Comment by emileighoutlaw** [comment]
Thanks for the ping— I chatted with Michelle about this yesterday. EITI is doing their minimums and maximums separately but haven't done any user testing yet. So I'll keeping tabs on what they find out.

I'd be up for having separate tags and seeing how they test.

*If* we want to do this,

- I'd like to use language, as opposed to `>` or `<`, which readers often struggle with. How about:

> `after xx/xx/xxxx`, `before xx/xx/xxxx`, `more than $200`, `less than $1,000`

- Can we make sure the min and max filters appear next to each other (for both dates and money)? That way we wouldn't have a situation where the tags look like:

> `after 1/1/2016`, `more than $200`, `individuals`, `less than $1,000`, `before 5/1/2016`

which could be confusing for readers?

Thoughts on this @jenniferthibault

**Comment by jenniferthibault** [comment]
I'm working on mockups to keep up with y'all. Only addition to @emileighoutlaw 's thoughts would be to make sure that the filter tag text is inclusive of the limits the users apply (greater than or equal to $ // less than or equal to $) (before and up until date // date and after)

@emileighoutlaw could you take a quick swipe at your preferred language for that?

**Comment by jenniferthibault** [comment]
(I'm also cool with trying mins and max's separately!)

**Comment by emileighoutlaw** [comment]
Ohhhh, interesting question. How about:

> `$200 or more`
`$1,000 or less`

and for dates:

> `1/1/2016 and later`
`5/1/2016 and before`


I'm also thinking about how we visualize dates (xx/xx/xxxx)— do we have flexibility to try writing them differently? 

For example `Jan. 1 2016 and later`. (that probably looks too long, right?) 

Admittedly, most U.S. folks expect to see dates as `mm/dd/yyyy`, so I'm not sure if we anticipate confusion around this point? Another option someone threw out in g-content was showing dates as `yyyy/mm/dd`

**Comment by jenniferthibault** [comment]
@emileighoutlaw chatted on slack, and she is researching and fine-tuning a few more language bits ad will have final text soon. In the meantime, here's what the two-tag system would look like.

<img width="856" alt="screen shot 2016-01-14 at 12 25 22 pm" src="https://cloud.githubusercontent.com/assets/11636908/12331941/e95e8306-bab9-11e5-920d-4513f8565111.png">

To tie up the strings on Noah's question above, when only max is defined, how do we handle the backend parameters for $ and time?
- For money, it seems more straightforward because if $0 was donated, there won't be a data entry. This leads me to believe we don't need to automatically fill in $1 as the minimum, and can leave a max only as entered.
- Dates sound less straightforward, but I agree with @emileighoutlaw 's take in her first comment. I've included two ways to show this (A/B) A is more clear, B is more concise.
- Overall date formatting: I'd be keen to hear about what the data limits are and if it's possible to re-order to yyyy/mm/dd

**Comment by emileighoutlaw** [comment]
Per brainstorming and chatting with Jen, I think we're interested in testing:

> `$200 or more`, `$1,000 or less`
> `after 1/1/2000`, `before 5/1/2016`,

And then for the the undefined min, `after 1/1/1976 (earliest available)`

I like the earliest available note. But does that make the tag look too long?

**Comment by jenniferthibault** [comment]
Sorry for trailing off here, I had mentally checked it as resolved. To wrap up and transfer to implementation status, here's what @emileighoutlaw 's above summary would look like.

![screen shot 2016-01-20 at 11 10 53 am](https://cloud.githubusercontent.com/assets/11636908/12454736/d1566894-bf66-11e5-99f2-96c4d3e89d66.png)

I like the clarity that the longer "(earliest available)" tag brings, and would be in favor of implementing it to see how it plays out in real scenarios. If it's problematic in testing, let's drop the "(earliest available)".

Ping to @jmcarp - this is ready for implementation, but I'm not sure it's _required_ for testing this week.

**Comment by jmcarp** [comment]
@jenniferthibault there's a version of this on dev now, e.g. https://fec-proxy.18f.gov/data/receipts/. I didn't implement the "earliest available" piece, since I have a few questions / concerns about it:

* I'm not sure when the "earliest available" tag should be displayed--always, unless the user specifies an explicit minimum? Only when the user specifies a maximum?
* What happens when the user clicks the "close" button on the "earliest available" tag?

FWIW, I think tags are simpler to implement and use if we have a one-to-one correspondence between tags and filter inputs: if and only if a filter has a non-null value, it has a corresponding tag.

**Comment by jenniferthibault** [comment]
Nice! Thanks for explaining your thoughts here. 

The intent of "earliest available" tag would be to make a parameter being applied to the data anyways based on when we have records available for more explicit. In the case of receipts, 2011.  (though now I'm a little confused, because when I just went to poke around, it's showing receipts from the 2000's).

Since the results wouldn't actually change if a user _were_ able to "close" that tag....then I'm kind of stumped, and ok with keeping it as is. @emileighoutlaw @brethauer - would you be interested in looking into the 1-tag per 1-filter entry approach this week? (As currently implemented https://fec-proxy.18f.gov/data/receipts/ )

**Comment by emileighoutlaw** [comment]
Ah this is a really good point. I think based on Josh's comments (particularly, `what if you close it?`), it doesn't make sense to add the earliest available tag. 

I think this is definitely something Nick and I will test this week.

**Comment by noahmanger** [comment]
Agree that I think it makes sense to not show "earliest" if that date field is null.

**Comment by noahmanger** [comment]
This works well now. Will keep the main tag issue open until we merge into develop.
