### ISSUE TITLE
Usability: States drop-down

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1051]
If you select a state from the drop-down menu, the drop-down stays active, even if you scroll away. We noticed in usability sessions that users had trouble finding the filters behind the active state drop-down. 

![states](https://cloud.githubusercontent.com/assets/10552702/12557324/36fa8136-c358-11e5-9964-cacbfb34041a.gif)

**Comment by noahmanger** [comment]
This isn't a bug so much as not sure what the expected behavior should be. Currently the dropdown stays open so that you can select multiple items without having to open it again, and the datatable reload happens on each selection. The dropdown remains open until you click anywhere else on the page.

Is there a more intuitive way to handle this?

**Comment by emileighoutlaw** [comment]
Ahhh, good question— @brethauer, do you have thoughts on this?

**Comment by brethauer** [comment]
Other possibilities could include collapsing it when mouse leaves the area, but this could make it trickier to select multiple states.

Let's keep it as is and continue testing it to get more data.
