### ISSUE TITLE
Bug: Open in new tab doesn't work on authorized committee pages

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1052]
This bug is visible from committee pages.

If you try to open one of the other tabs in a new window (with `control + click`), it doesn't work. It opens the same tab in the new window. 

![tabs](https://cloud.githubusercontent.com/assets/10552702/12557876/db72a566-c35a-11e5-913b-f5e9464bd02f.gif)

**Comment by evankroske** [comment]
I'm working on this. The issue is caused by a call to `preventDefault` from the event listeners on the tabs. The plan:
- [ ] Move tablist initialization from top-level scope to exported function.
- [ ] Write tests for tablist.
- [ ] Change tablist to use anchor links and popstate instead of pushState.

**Comment by noahmanger** [comment]
Thanks, @evankroske ! Sounds like a great place to plug in. This is really old code, so it will be great to get it updated and tested.
