### ISSUE TITLE
Invalid XSS header on candidate and committee pages

### ISSUE THREAD

**Issue by evankroske** [18F/openFEC-web-app#1055]
Browser: Chrome 47.0.2526.111 (64-bit)
OS: OS X 10.11
URL: https://beta.fec.gov/data/candidate/P00003392/

When I open the Chrome developer tools on this page, I see the following error in the console:

> Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.

**Comment by noahmanger** [comment]
Thanks for catching, @evankroske !

**Comment by jmcarp** [comment]
If I remember correctly, we're getting this error because requests go first through a proxy app (fec-proxy) and then to either the CMS app (fec-cms) or the data app (openfec-web-app). All three apps are hosted on cloud.gov, and I believe that cloud.gov always adds the `x-xss-protection` header, even if it's already set. In other words, the header is being set twice.

As far as I know, users of cloud.gov don't currently have the ability to change this header. @dlapiduz, what would you recommend here? Can the configuration be changed so that headers that are already set don't get duplicated or set to invalid values?

**Comment by dlapiduz** [comment]
@jmcarp here is a card for it: https://trello.com/c/P6DknfSK/659-avoid-duplication-of-xss-headers-in-nginx-secureproxy

Basically you are right, the fact that you are proxying to an app that already has the header duplicates it.

**Comment by konklone** [comment]
I just noticed this in the console for beta.fec.gov myself. Since the error says "The default protections will be applied.", I think that means that the `X-Xss-Protection` header is functionally inactive while this bug is present.

That said, it's very difficult for me to figure out what this header actually does. It [seems to](http://zinoui.com/blog/security-http-headers#x-xss-protection) trigger browser-specific best effort XSS protection behavior. In any case, Cloud.gov should let the header pass through if it's present already, the same way it does for HSTS headers.
