### ISSUE TITLE
Figure out "sort_hide_null" frontend behavior

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1065]
When we moved the "Hide null when sorting" checkbox to be a regular filter, some things changed:

Previously, it was set using table options and it was hidden from the visible URL. This meant we would set it by default, which is useful when sorting by date so that results with no date don't show up at the top. 

But now, because it's a regular filter there's no way to set it without also setting a parameter in the URL. 

Also, now that we have filter tags, it means that treating it as a regular filter generates a tag for it, which is kind of weird:

<img width="1085" alt="screen shot 2016-02-02 at 3 57 27 pm" src="https://cloud.githubusercontent.com/assets/1696495/12768614/af22b3ea-c9c5-11e5-82c5-1d6ab7f50dd6.png">

I'd like to figure out what we want the behavior to be:
- Do we want it to be checked by default?
- Do we want it visible in the URL?
- Do we want it to generate a tag?

Would love your thoughts on this @jenniferthibault .

**Comment by emileighoutlaw** [comment]
I'll let Jen chime in, but my content gut is saying we don't won't it to generate a tag.

**Comment by jenniferthibault** [comment]
I second that. I think we should keep it as is now on beta.fec.gov and not apply it by default. Users can select it, and it's not hidden under an accordion view, so it's exposed.

**Comment by noahmanger** [comment]
What about the other two questions:
- Do we want it visible in the URL?
- Do we want it to generate a tag?

**Comment by jenniferthibault** [comment]
If we're not applying the filter (and thus the criteria) by default at page load, then no to those two questions as well!

What I'm trying to say/think is: Don't check the box, don't apply to "hide results with missing values while sorting" as a filter. So therefore it would not even apply to the URL, the data, or the tags.

**Comment by noahmanger** [comment]
Sorry, that was confusing. I mean, _when_ you check it, should it do those things?

**Comment by LindsayYoung** [comment]
It is really useful to have that pre-checked, otherwise you get things like pages and pages of records with missing dates (or missing whatever) first.

**Comment by emileighoutlaw** [comment]
I hear that, Lindsay. Here's my understanding:

Having this filter defaulted on helps lots of general users— people who don't want to deeply understand the data but need (for example when sorting earliest to most recent expenditures) not to be blocked by pages and pages of blank data.

That said, we still want the filter to exist as an option for our super advanced users to un-check, should they want to.

Is it possible to default this the filter to pre-checked but *not* create a tag? 

I think it's fine if it's part of the URL.

**Comment by jenniferthibault** [comment]
This has been tricky because its challenging us to define principles of behavior AND functionality here.

Here are the principles we've been using:
- If a filter is applied, show a tag so that users know what they're seeing data for
- If a filter is applied, reflect that in the URL so that searches can be saved and shared w/ permalinks
- Create a download manifest that shows users what filters were applied to their download
- Define filters in the manifest so that users understand what the filter codes mean

Before I move on to address the scenario above, do these principles reflect YOUR understanding @noahmanger & @emileighoutlaw ? Are there other points not listed?

That will lead us to form a principle based on this scenario: 
- We (will)/(will not) sometimes apply default filters to the data set before a user applies their desired filters

**Comment by emileighoutlaw** [comment]
That is precisely the principles I understand. Thanks for setting them out here for us, Jen.

### Thoughts
`- If a filter is applied, show a tag so users know what they're seeing data for`

I *think* like the underlying assumption here is that *knowing which filters are applied* helps people understand what the data they're looking at. But in this specific case, the filter is complicated and requires longer explanation than fits comfortably on a tag. 

That being the case, should we:
- Write a longer filter tag that makes the applied filter more clear (but might be visually icky)?


### Idea
Here's a crazy idea that can only come from someone who doesn't understand coding very well (but I want to ask it anyway): Is there a way to wrangle the data so that when you sort it, null values always appear at the end (for both sorting low–high and high–low). 

That way we wouldn't ever be hiding data for power users but it wouldn't be getting in the way of novice users? (And maybe wouldn't need the filter at all?)

**Comment by noahmanger** [comment]
@emileighoutlaw I was just about to lob out the same crazy idea. Glad I read to the bottom first :) @jmcarp what do you think of Emily's idea? 

@jenniferthibault I think those principles are right on. I'd add one more:

- Filters can be added and removed 

This is to differentiate from the kind of pre-filtering we will be doing for the specialized datatable pages.

Also, I think there's a somewhat bigger meta question about "What is a filter?" There's a notable difference between this checkbox and the other filters in that this filters the results based on the column you're sorting on, and furthermore I _believe_ that all results are actually included in the download. So is this even a filter? Or is it more of view control in the same way as the pagination? 

If we say a filter reduces the real number of results on both the web app and the download, then I think maybe this isn't a filter that should behave like the others.

Of course, all this is obviated if we just don't need it in the first place, so fingers-crossed for that.

**Comment by jenniferthibault** [comment]
If the logic statement could be something like “If a category has no data, put that entry last when sorting” and we don't need a filter at all, my :fingers-crossed: hard for 
![obliviate](https://cloud.githubusercontent.com/assets/11636908/12902611/3512bb2a-ce90-11e5-957d-5b26b10b14d5.gif)

**Comment by jmcarp** [comment]
So we can easily tell the database to always return `null` values last, whether sorting ascending or descending. The caveat is that we'd then have to create two indexes for every column on every column that we want to support this behavior:

```
create index on table (column nulls first);
create index on table (column nulls last);
```

Especially for the bigger tables, that's going to eat up a lot of space on disk and in memory. As usual, we can do whatever we want for the smaller tables.

It's been long enough that I don't remember why we can't just hide all rows with `null` values on the sorted column in the browse views (but leave them available via the API). What bad things would happen if we always hid rows with missing values on the current sort column? Especially when there are many pages of results, users would very rarely even see pages with `null` values on the sort column.

cc @LindsayYoung @ccostino

**Comment by noahmanger** [comment]
Great question. Practically speaking, it would have the same effect and effectively look the same to the user. This seems like an option we can keep for API users, but we can get rid of on the front-end. This would be my strong preference if there's no overwhelming reason to keep it.

**Comment by ccostino** [comment]
From a user experience perspective, this looks messy seeing this "filter" show up as a tag across the top as well.  I would argue that this bit of functionality is not the same as the other filters if the idea is to always have that data available regardless and it's just a quality of life improvement when viewing the web site.  Is it okay that we always hide information that missing?  If so, should we just hide it automatically on the site?  Otherwise, would it be possible to investigate a way that we can make this an option outside of the filters?

**Comment by LindsayYoung** [comment]
I think that there is value in making this user controlled and explicit. I think that when there is a lot of data messaging, and no explanations or controlI we risk people loosing faith in the data. If people want all the data, they will want to uncheck that box. Also it would not make sense why the number of results changes when you sort differently, unless we tell you.

I am a bit concerned with always sorting null last, because making data unavailable (without paging through a 100 pages) on the webapp on the theory that it is ugly, seems a bit over-protective to me. I think that behavior would also be confusing to API users. 

I liked the solution where this is a checkbox that people could un-check. We are trying to make a tool that helps people explore this very valuable data I like the idea of having welcoming defaults but I don't want to sacrifice user control for power users that are not comfortable with using APIs.

**Comment by jmcarp** [comment]
For context, the "hide null" control wasn't located inside the filter panel until the latest release--@noahmanger and @jenniferthibault can explain why.

It might be time to move this issue to FEC or usability testing. I think we've spent more than enough time talking in circles around it and revising behavior without coming to a conclusion.

**Comment by noahmanger** [comment]
Just talked with Lindsay on this over the phone and she agrees that @jmcarp 's solution of just permanently setting the hide null filter on the front end (but not exposing it in the UI ever) is a fine way to go. And just to clarify, this filter isn't passed through to the downloads, correct?

**Comment by jmcarp** [comment]
@noahmanger correct!
