### ISSUE TITLE
Test new navigation mockups

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1088]
In order for users to navigate between browse pages, design a sub-navigation system.

@jenniferthibault already made good progress on this, but we should test it and refine the designs before moving this to implementation.

Tasks:
- [x] Prep for usability testing
- [x] Test
- [ ] Refine based on feedback

## Update:
This should also address how users may navigate between "processed" data and efiling data.

**Comment by noahmanger** [comment]
With the pending merge of the candidate office datatable pages, this has been on my mind so I wanted to get some thoughts out / work through some of our design backlog. These are all just glorified sketches...not submitting for visual recommendations :)

I think there's a few goals this design update needs to address:
- How do users find (and understand) the various alternative datatable pages?
- How can we condense some of the vertical space that's currently taken up by the filter button?
- Is there a way to accommodate  additional methodology or background information?

This isn't a current priority, so no rush to give feedback, but here's some ideas:

## Option 1: Horizontal row of all sub-pages
![option 1 - committees](https://cloud.githubusercontent.com/assets/1696495/13307767/9aefbfe4-db22-11e5-8103-29965d098814.png)

![option 1 - filters open](https://cloud.githubusercontent.com/assets/1696495/13307769/9cfda846-db22-11e5-9173-daad84b8b3a3.png) 

Pros
- All items are visible

Cons:
- Long lists quickly run out of room
- Lack of subheadings to explain the type of info on different pages (e.g. "Financial totals" or "forms")

## Option 2 and 3: Dropdown menus
![option 2](https://cloud.githubusercontent.com/assets/1696495/13307835/3df3cab4-db23-11e5-9673-c21244c965d5.png)

or 

![option 3](https://cloud.githubusercontent.com/assets/1696495/13307915/d6994924-db23-11e5-84a9-41ca209ad995.png)

## Option 4:  Nested menus
![option 4](https://cloud.githubusercontent.com/assets/1696495/13307864/6d81a8f0-db23-11e5-8149-8a9162a6d0d2.png)

![option 4 committees](https://cloud.githubusercontent.com/assets/1696495/13307863/6d810c60-db23-11e5-9f2e-5bc999d81916.png)

Pro: Makes it easier to group the main types of pages (especially useful for committees)

## Info panel
Here's one idea for how table info could be incorporated
![info panel](https://cloud.githubusercontent.com/assets/1696495/13307889/a8d3bf2e-db23-11e5-818b-149377c52596.png)

## Alternate filter toggle
And one other idea for toggling the filter panel:
![alt filter toggle](https://cloud.githubusercontent.com/assets/1696495/13307896/b3501fba-db23-11e5-81e4-84dff15dcf6f.png)
![alt filter toggle - open](https://cloud.githubusercontent.com/assets/1696495/13307897/b5fbb760-db23-11e5-9417-7fd2625acc77.png)

**Comment by jenniferthibault** [comment]
@noahmanger !! I'm super into the alternate filter toggle idea, and it's also been on my mind that we should try to encourage people to close the filter panel more often and benefit from the experience of a full-width data table.

I have three screens below that show how we could integrate that with a slight tweak to your nav. Instead of individual dropdowns, I've tried using the mega-menu format for this section. Since we'd be removing the dropdown from the top-level main nav, I don't think it will be overwhelming here. I've also done some top area rearranging that will impact the filter pattern we see on the Calendar page. (also below)


**Here is the "All Candidate Data" view with filters applied.**
![all candidates copy 4](https://cloud.githubusercontent.com/assets/11636908/13657578/67af2422-e63e-11e5-881b-d913524ca778.png)



**Here's that same view with the menu for Candidates opened** 
(based on the info organization here 
https://github.com/18F/openFEC-web-app/issues/1003#issuecomment-183534712 )

![all candidates copy](https://cloud.githubusercontent.com/assets/11636908/13657581/703218b6-e63e-11e5-8fc4-535ed0538cc2.png)



**And here's that view with the filter bar closed (table categories not accurate, just for placement)**

![all candidates copy 3](https://cloud.githubusercontent.com/assets/11636908/13657586/7a0a49a8-e63e-11e5-895a-a9ab6c6bb874.png)


**ANNNNND here's how that would impact the calendar designs.** 
I think we should switch the section color to blue because it uses the API data (which is so cool) and so that the CMS sections are easy to find through the red headers...but this may also change soon....;-)

![calendar_monthly copy](https://cloud.githubusercontent.com/assets/11636908/13657527/f222a8a0-e63d-11e5-9df0-e6d80dceb239.png)

**Comment by jenniferthibault** [comment]
The one thing I forgot to ask (and I think might be a separate thing, so maybe we make a new issue?) is what's up with that "About this dataset" copy. Where's it coming from, what's the need? Why that instead of individual tooltips about the column headers, etc?

**Comment by noahmanger** [comment]
Thanks for tackling this. The mega-menu idea is interesting. Two thoughts though:

1. How would this work on smaller screens? This requires quite a bit of width to lay out all the links horizontally.
2. I'm not sure which level of hierarchy should be included in the sub-nav. Should it be the other parent categories (like you have), or the siblings (like I have). I'm not sure. What do you think?

**Comment by jenniferthibault** [comment]
Goooooood thoughts, and I have some thoughts, but no definitive answers

1: It looks like the largest parent category we have here is Committees, with 10 child entries, right?https://github.com/18F/openFEC-web-app/issues/1003#issuecomment-183534712
Can we accomplish that on tablet with three columns? On mobile, since removing the top-level dropdowns anyways, we might need to rethink some organization and interaction here. I don' tknow if I have it right (especially considering your second question) but this helped me think it though:

<img width="1206" alt="screen shot 2016-03-10 at 11 07 52 pm" src="https://cloud.githubusercontent.com/assets/11636908/13693095/858c17b6-e715-11e5-8386-0e4ff1926282.png">

2: I don't have a definitive answer, for sure, but the reason I tried it the way I did in the previous mockup is that I think it will be helpful to enable people to navigate between parent sections without needing to go back to the data landing page. (??)

**Comment by jenniferthibault** [comment]
To be clear, I want to make sure we know that we are really talking about three highly inter-related issues:
1. Redesigning the data table header space pattern to take up less space
2. Redesigning the filter panel interaction to encourage users to hide it more often
3. Designing the subnavigation

**Comment by noahmanger** [comment]
Long post alert :rotating_light:

There's a bunch of challenges we're trying to solve for when it comes to navigation:

1. Provide users with a clear sense of place in the hierarchy of all the pages (particularly the datatable pages)
2. Enable users to move between the different parent, children and sibling datatable pages.

Rather than trying to solve both of these challenges with a sub-navigation pattern specific to these pages, I think we're better served by addressing it through:

1. A revamped site-wide menu
2. A consistent breadcrumb interface (that also addresses the needs on the content pages as well)

This approach keeps navigation consistent throughout the site, and reduceds the number of page-specific controls on any given datatable page. 

### Breadcrumbs
For the breadcrumbs, I'd suggest something along these lines:
![image](https://cloud.githubusercontent.com/assets/1696495/13969239/cea4cd80-f03e-11e5-84f8-f00c0e0fc097.png)

The pattern is: `Home » [Parent section] » [Category] » [Category] » [Sibling] | [Sibling] | [Sibling]` where `[Category]` links serve to situate you in the hierarchy, even though they don't correspond to a specific page. 

So for reporting pages, it would look like what we recently implemented: `Home » Registration and Reporting » Essential: Finding a treasurer`


### Menu
And then for the menu, I'm imagining a mega-menu like so:
![image](https://cloud.githubusercontent.com/assets/1696495/13969315/5b180610-f03f-11e5-9dff-3d9910e181d9.png)

The idea is that each of the datatable categories opens up a subnav panel with all of the options inside. I have this interaction prototyped [in InVision here](https://invis.io/GU6M0QPCV).

Both of these designs introduce some language and organizing concepts that we definitely haven't nailed down yet (such as which overview pages we'll have; whether or not we have a single advanced datatable index page; etc). 

One specific question for @emileighoutlaw  though: The left column on the menu shouldn't actually be called "Profiles", but Jen and I agree that it makes sense to have some type of grouping for the candidate and committee pages. What should it be? Does this make sense as a grouping category?

## What's next
I think the most important thing to figure out at this stage isn't necessarily how everything is grouped, but does this combination of breadcrumbs + megamenu work for A) navigating between datatable pages and B) helping people understand their current place. I'd like to get the InVision prototype in front of users this sprint if at all possible, after we've finished with the dashboard stuff.

**Comment by jenniferthibault** [comment]
I'm all for trying this approach out! It seems like the interaction for discovering the child categories in the menu (such as the elements under `Advanced Data Tables` would be improved by hover functionality instead of click. InVision does have this option for hotspots, what do you think?

Open questions in my mind are how we handle categories with many siblings gracefully, such as Essentials lists. I know we talked about this yesterday, is it worth bringing a screen like that into the prototype? Or too complex for what we need to know now?

Heads up @brethauer ! ^

**Comment by noahmanger** [comment]
Good call on hover. I'll add that. 

I just talked about the breadcrumbs in my critique, and I think it may actually work best to simply not include the `Siblings` there. It keeps the breadcrumbs more focused, and avoids tricky problems when there's many many siblings.

**Comment by evankroske** [comment]
Hover doesn't work on iOS.

**Comment by jenniferthibault** [comment]
V true. We could have the expanded states initiate on tap for mobile/tablets. We do most of our usability testing on desktop (remotely) through screenshare, which is why we're leading with these for prototypes. I know @noahmanger also has mobile mockups waiting in the wings

**Comment by emileighoutlaw** [comment]
My immediate thought is
 
> **Candidates and committees**
Search a name or ID

That inclination is coming from trying to keep consistent language across all our filtering options. Do y'all think that's too technical sounding?

**Comment by noahmanger** [comment]
@emileighoutlaw the other headings are more categorical descriptions of the _type_ of thing you're looking at. Because so many people come to the site looking for one particular thing, I think it's good to draw them to that as the place to find those individual records. 

Profiles _kind_ of gets at that, but it's weird. 

That said, I think we _are_ talking about a departure from the way we've been talking about it.

**Comment by emileighoutlaw** [comment]
Okay — another long post coming (sorry :/ )

I completely see what you're getting at. This is a tricky one because the `Profiles` section is for both individual candidates as well as groups, so any word that implies "human" won't work. Meanwhile, technically accurate words like "filer" or "registrant" are too user unfriendly. 

"Profile" does seem close (but I agree, not quite right). Everything else I can think of also seems not right:
- Participants
- Actors
- Players

Soooooooo, I started brainstorming new ideas. I had the thought that the most important part of `Profiles` is that people are _searching_ for a specific person or committee. 

Going down that line of thinking, here's what it could look like:

>  **Finder** 
Search for a candidate or committee

> **Overviews
Fundraising
Spending

>  **Elections** 
Search by state, district or ZIP code

> **Advanced data**
You know what I am loving about this section? It's got so many words that I think it will finally look unappealing to novices. I'd like to either call it `Advanced data` or  maybe `Advanced data search`, unless there's a strong reason why we want to keep "tables" ?


Last note: "Start exploring" is really warm (and I love that), but it indicates to me something less specific than what users will get if they search a candidate or committee name. What if it said [go] or [look up] or something along those lines?

**Comment by noahmanger** [comment]
:thinking_face: "Finder" is interesting. Though sounds a little vague to me. A couple other ideas:

- Candidate and Committee Finder (very close to the current Candidate and Committee Viewer)
- Candidate and Committee Profiles
- Candidate and Committee Pages
- Candidate and Committee Records

I might like the "pages" option the most.

Interesting note on the "Start exploring button". What I was going for with that was a solution to the age-old problem of "what does a link to the top-level page in a menu" look like. So that's meant to take you to the data landing page. Perhaps just separating it from the "Profiles" (or whatever) section will do the trick? Or can you think of a better term?

**Comment by noahmanger** [comment]
Update: I just added a second option for how this could work that we can test, as well as the mobile designs, which are probably worth testing as well (even though it uses a familiar pattern).

**Comment by jenniferthibault** [comment]
Late to the party, but I LOVE ALL OF THESE

- Candidate and Committee Finder 
- Candidate and Committee Profiles
- Candidate and Committee Pages
- Candidate and Committee Records

I think "pages" is my least-preferred option, because that describes a website element more than the information on it. @emileighoutlaw what about a content test for these?

**Comment by emileighoutlaw** [comment]
I think testing is a *fantastic* idea, because I was struggling to decide which I thought was better. 

@brethauer, what do you think? My first thought is that (without having to do mockups) we could take just a few minutes to ask our users this week what they think they'd find behind each of these.

Jen and Noah— would the visual design be okay if that one section of content is so much longer than the others? (Overviews, Elections, etc.)?

**Comment by brethauer** [comment]
@emileighoutlaw yes! I think a simple content test could work- we probably would want to have a bit of context (could just be some text before or after) so it'd not totally devoid of context that might be important to decoding?

Before diving back into the specifics of how to test, I'd like to make sure I understand everything we want to try to learn this week.  If I'm understanding/following this whole conversation thread, there are a couple things we want to test:
1) What is the best language in the navigation to describe the Candidates & Committee _thing_
2) Does this navigation + breadcrumb concept (invision prototype by @noahmanger) succeed in helping people:
A) navigate between datatable pages
B) understand their current place (on the site)

**3) Other things???**
4) Another round of dashboard concept? (Either continue testing what we have or combine into one design, though I doubt Noah will have bandwidth for this)

**Comment by emileighoutlaw** [comment]
Yes yes! Thanks for jumping in Nick!

Everything you brought up about the breadcrumbs is spot on, but I think my usability eye was specifically focused on the "candidate and committee" language options. Basically, those options are for the top navigation on the beta site— so if someone were to click into the navigation menu and type "Hillary Clinton" into the accompanying search box (which we're trying to give a category name), they'd be taken to this page: https://beta.fec.gov/data/candidate/P00003392/

I think you're totally right that we might need a little context (i.e., show people that they're looking at a top level navigation menu item) in order to ask them any questions. The priority thing I'd like to discern is:

If we ask people to look at the four possible "candidate and committee" headers, what information do they think will be contained within each? We can use their answers see if any one option aligns most closely with what the search _would actually_ take them to. 

I think looking at that content question and maybe another look at the dashboard concept (probably continued testing, since Noah is busy conference learning (hurrah!)) would be a good plan for this week? What do you think @jenniferthibault ?

**Comment by noahmanger** [comment]
Sorry for the late response on this. Nick's right in that the main thing we're trying to figure out this sprint is: 

> 2) Does this navigation + breadcrumb concept (invision prototype by @noahmanger) succeed in helping people:
A) navigate between datatable pages
B) understand their current place (on the site)

The question of the exact wording of the "Candidate and Committee Thing" is important, but isn't as important as settling on an overall navigation pattern that will allow us to move forward with the additional datatables. So we should test it, but I think we shouldn't worry *too* much about it just this moment.

So towards testing that specific navigation component: there's two concepts in the InVision right now. One has the various sub-pages nested under categories, and one lists them all out (and a third is the mobile layout). I'll leave it to you smart folks as to how to test, but I'm thinking some set of navigation tasks and see which one works better for helping the A and B points above. 

I haven't gotten a chance to sync up on the synthesis from the dashboard testing, but if you thought more testing would be valuable (and my hunch is yes), then we should absolutely do more of that, as I'd expect this testing shouldn't take much time.

**Comment by emileighoutlaw** [comment]
I hear you, Noah. Definitely agree that navigation tasks should take precedence over the small content question. I am also hopeful that the content question will take only ~3 minutes and provide us some nice clarity. Perhaps we can move it to the end of the test?

**Comment by brethauer** [comment]
Awesome!  So tomorrow we'll do:
1) Navigation: ~5 or so min
2) Content: 3 min
3) Continue concept testing from last week with remaining time

@emileighoutlaw let's sync up with our time in the morning to write the content & navigation test
