### ISSUE TITLE
Duplicate transaction entries resulting from amendments

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#1146]
It appears if the committee amends a report, the transactions can be duplicated on the results page. For example, there should only be one entry for 1/14 and 1/6:
https://beta.fec.gov/data/receipts/?contributor_type=individual&contributor_name=Enrico%2C+Roger&min_date=01-01-2015&max_date=12-31-2016

**Comment by LindsayYoung** [comment]
Hi Amy, I am going to close this issue for now, since this data is coming from the data warehouse and we can't really fix it on our side.

Looking at these duplicates:
https://beta.fec.gov/data/receipts/?contributor_type=individual&contributor_name=Enrico%2C+Roger&min_date=01-06-2015&max_date=01-06-2015

first one:
http://docquery.fec.gov/cgi-bin/fecimg/?201507319000507360
(this is the first verison)
I see it in `sched_a` that table is supposed to have the amendments applied

 sched_a_sk | form_tp |  cmte_id  | cmte_nm | entity_tp | contbr_id |     contbr_nm     | contbr_prefix | contbr_f_nm | contbr_m_nm | contbr_l_nm | contbr_suffix |     contbr_st1     | contbr_st2 | contbr_city | contbr_st | contbr_zip | election_tp | election_tp_desc | contbr_employer | contbr_occupation | contb_aggregate_ytd | contb_receipt_dt | contb_receipt_amt | receipt_tp | receipt_desc | cand_id | cand_nm | cand_prefix | cand_f_nm | cand_m_nm | cand_l_nm | cand_suffix | cand_office | cand_office_st | cand_office_district | conduit_cmte_id | conduit_cmte_nm | conduit_cmte_st1 | conduit_cmte_st2 | conduit_cmte_city | conduit_cmte_st | conduit_cmte_zip | memo_cd | memo_text | amndt_ind |  tran_id   | back_ref_tran_id | back_ref_sched_nm | national_cmte_nonfed_acct | record_num | rpt_tp | rpt_pgi | form_tp_cd | receipt_dt | status | file_num | increased_limit | donor_cmte_nm | orig_sub_id |       sub_id        |       link_id       | line_num |     image_num      | rpt_yr | transaction_id | filing_type | filing_form |      load_date      | update_date |         pg_date         
------------|---------|-----------|---------|-----------|-----------|-------------------|---------------|-------------|-------------|-------------|---------------|--------------------|------------|-------------|-----------|------------|-------------|------------------|-----------------|-------------------|---------------------|------------------|-------------------|------------|--------------|---------|---------|-------------|-----------|-----------|-----------|-------------|-------------|----------------|----------------------|-----------------|-----------------|------------------|------------------|-------------------|-----------------|------------------|---------|-----------|-----------|------------|------------------|-------------------|---------------------------|------------|--------|---------|------------|------------|--------|----------|-----------------|---------------|-------------|---------------------|---------------------|----------|--------------------|--------|----------------|-------------|-------------|---------------------|-------------|-------------------------
  235984027 | SA11AI  | C00571380 |         | IND       |           | ENRICO, ROGER MR. | MR.           | ROGER       |             | ENRICO      |               | 500 CRESCENT COURT | SUITE 250  | DALLAS      | TX        | 752016995  | P           |                  | RETIRED         | RETIRED           |             5000.00 | 2015-01-06       |           5000.00 | 15         | CONTRIBUTION |         |         |             |           |           |           |             |             |                |                      |                 |                 |                  |                  |                   |                 |                  |         |           |           | SA11.28429 |                  |                   |                           |            | MY     |         |            | 2015-07-31 |      0 |  1019752 |                 |               |           0 | 4073120151248129756 | 4073120151248079478 | 11AI     | 201507319000507360 |   2015 |        4930447 | E           | F3X         | 2015-08-01 01:09:26 

second one:
http://docquery.fec.gov/cgi-bin/fecimg/?201507319000513715
(this is amended and should be in the records and is)

 sched_a_sk | form_tp |  cmte_id  | cmte_nm | entity_tp | contbr_id |     contbr_nm     | contbr_prefix | contbr_f_nm | contbr_m_nm | contbr_l_nm | contbr_suffix |     contbr_st1     | contbr_st2 | contbr_city | contbr_st | contbr_zip | election_tp | election_tp_desc | contbr_employer | contbr_occupation | contb_aggregate_ytd | contb_receipt_dt | contb_receipt_amt | receipt_tp | receipt_desc | cand_id | cand_nm | cand_prefix | cand_f_nm | cand_m_nm | cand_l_nm | cand_suffix | cand_office | cand_office_st | cand_office_district | conduit_cmte_id | conduit_cmte_nm | conduit_cmte_st1 | conduit_cmte_st2 | conduit_cmte_city | conduit_cmte_st | conduit_cmte_zip | memo_cd | memo_text | amndt_ind |  tran_id   | back_ref_tran_id | back_ref_sched_nm | national_cmte_nonfed_acct | record_num | rpt_tp | rpt_pgi | form_tp_cd | receipt_dt | status | file_num | increased_limit | donor_cmte_nm | orig_sub_id |       sub_id        |       link_id       | line_num |     image_num      | rpt_yr | transaction_id | filing_type | filing_form |      load_date      | update_date |         pg_date         
-----------|---------|-----------|---------|-----------|-----------|-------------------|---------------|-------------|-------------|-------------|---------------|--------------------|------------|-------------|-----------|------------|-------------|------------------|-----------------|-------------------|---------------------|------------------|-------------------|------------|--------------|---------|---------|-------------|-----------|-----------|-----------|-------------|-------------|----------------|----------------------|-----------------|-----------------|------------------|------------------|-------------------|-----------------|------------------|---------|-----------|-----------|------------|------------------|-------------------|---------------------------|------------|--------|---------|------------|------------|--------|----------|-----------------|---------------|-------------|---------------------|---------------------|----------|--------------------|--------|----------------|-------------|-------------|---------------------|-------------|-------------------------
236025416 | SA11AI  | C00571380 |         | IND       |           | ENRICO, ROGER MR. | MR.           | ROGER       |             | ENRICO      |               | 500 CRESCENT COURT | SUITE 250  | DALLAS      | TX        | 752016995  | P           |                  | RETIRED         | RETIRED           |             5000.00 | 2015-01-06       |           5000.00 | 15         | CONTRIBUTION |         |         |             |           |           |           |             |             |                |                      |                 |                 |                  |                  |                   |                 |                  |         |           |           | SA11.28429 |                  |                   |                           |            | MY     |         |            | 2015-07-31 |      0 |  1019891 |                 |               |           0 | 4080320151248188092 | 4073120151248079606 | 11AI     | 201507319000513715 |   2015 |        4930448 | E           | F3X         | 2015-08-04 00:53:26 |             | 2015-08-04 03:24:17.295


Flagging this for @PaulClark2 since this is in the underlying data. Also noting that this is a data warehouse table, and we want to get off of these soon.

**Comment by AmyKort** [comment]
Thanks!
