### ISSUE TITLE
Release: Sprint 14

### ISSUE THREAD

**Issue by anthonygarvan** [18F/openFEC-web-app#1235]
# Sprint 14 release checklist

## Documentation
- [x] Write simplified [release notes for FEC](https://docs.google.com/document/d/1AHBI06cGYIHzqdTxlRcPzwyn9VCZZpSgc13Cuy4wD2k/edit#) with instructions for review
- [ ] Update documentation in any relevant repo
- [ ] ~~Generate changelog for API [instructions](https://github.com/18F/openFEC/blob/develop/README.md)~~

### Communciations
- [x] Are there communications around this release from 18F or FEC?

## Reviews
- [ ] 18F QA review on staging
- [ ] FEC QA review on staging
- [x] File accessibility review request [here](https://github.com/18F/Accessibility_Reviews/issues/new)

## Deployment
- [ ] Push fec-proxy into production
- [x] Update fec-style and publish to npm as necessary
- [ ] Run update scripts in standalone app if necessary
  - [ ] Allocate additional resources for the database to help with the processing before starting if need be.
- [ ] Unbind & delete fec-search-prod (or fec-search-stage) and recreate. This will remove bad data.
- [ ] Make sure local copies of `master`, `develop`, and `release/[release name]` branches are up-to-date.
- [ ] Checkout the `release/[release name]` branch.
- [ ] Run `git flow release finish [release name]`
- [ ] Run `git push`
- [ ] Run `git push --tags`
- [ ] Confirm that the new `web` app is up and running successfully.
- [ ] Delete the `web-a` and `web-b` apps.
- [ ] Test the site.

## After release
- [ ] Review changes on production
- [ ] Alert #fec-partners of the successful release

**Comment by adborden** [comment]
Added link to release notes.

**Comment by noahmanger** [comment]
Here's the simplified release notes for the features. Starting the next release, we'll actually start saving these somewhere on Github, but here they are in an issue:

## New features
### Overall
- A redesigned site header that reduces vertical space, giving you more room to view the content
- A new mobile menu that supports multiple nested panels and allows users to search directly from the menu

### Campaign finance data
- Adds a new advanced data index page that lists all current and upcoming data sets
- Adjusts the "Contributor" filter on the receipts data table page so that if you have filtered to just receipts from individuals, you will no longer see suggestions for committees
- The filter bar that contains the tags of applied filters now sticks to the top of the screen so you can always see it

### Calendar
- You can now filter reporting and compliance periods by the state where they apply
