### ISSUE TITLE
Address design feedback on data landing page charts

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1316]
Separating feedback specifically about the data landing page Totals raised/spent in all elections graphs from the rest of the feedback on the data landing page in https://github.com/18F/openFEC/issues/1761

![screen shot 2016-06-30 at 12 00 22 pm](https://cloud.githubusercontent.com/assets/11636908/16495191/5767fcfe-3eba-11e6-9abf-6ec06eb7886d.png)

![screen shot 2016-06-30 at 12 00 42 pm](https://cloud.githubusercontent.com/assets/11636908/16495192/576b0e1c-3eba-11e6-9c1d-46d2571492ed.png)

## Graphs
- [ ] ⚠️ Since some committees report bi-annually on non-election years, it's creating differences in the time period lengths on the Y-axis, which isn't expected. I've tried using a double-wide for 6-month periods to make them indicate a longer time period, but I think this may prove problematic.
- [ ] ⚠️ Need to clarify rules for what data is shown when, & this should probably be workshopped synchronously. Noah's suggestions above copied:
  - 1. We have a different type of visualization up to a certain point (probably more than half-way through)
  - 2. We don't show any visualization during the early phase
  - 3. We use this visualization but it only has one or two sets of filled in bars (with or without the "coming soon" state). 
- [ ] ⚠️ What are the interactions between the graph and the table? (for mobile and desktop)

### Possible next steps:
- **Consider what the primary goal of the graph is to communicate or teach people**
- Consider what time period communicates that best 
- Consider what format communicates that best

cc @noahmanger @onezerojeremy

**Comment by noahmanger** [comment]
Ok! I had some time this afternoon so I took a stab at the first ⚠️  and the next step questions.

**Primary goal:** For me, the primary purpose of this figure is to give a bird's eye view of the entire system for the most relevant election (either the one coming up or the one that just happened, most likely), introduce key concepts, and answer some broad, common questions. 

There's several ways to achieve this goal, and I think a chart along these lines does so by:
- Showing the total amount of money in  the system, which is a broad common question people have;
- Introducing the three main types of actors and showing their relative scale to one another in order to spark ideas for further exploration
- Draw people into the Raising and Spending details pages by actually showing something useful 

**Time period:** The three time periods we could show are: the current two-year period, the two-year period that just happened, or the full range for as far back as we have data. I'm pretty sure that one of the first two will always be more important than the latter. This doesn't answer the question of when the view changes, or how it changes, but I think that sticking to the most relative time period is best for communicating those goals above.

**What format:** Here's where I started thinking slightly different from what we have, partially in order to try to address the first ⚠️  re: the irregular time axis. If the goal is to show the overall weight of each group in the system, charting out the *cumulative* amount raised and spent might be a more useful and interesting visualization. And doing so actually lends itself better to a line chart, which in turn is easier to do with irregular time intervals. 

Here's an idea with annotations:

![image](https://cloud.githubusercontent.com/assets/1696495/16638732/95a3ac96-439e-11e6-8893-987c730aaa56.png)

I did some research for how people handle irregular time series and the only examples I found are this type of line chart. To me, it works well because it both allows you to compare the relative position of one line to another, but stays true to the data (and has an added benefit of teaching about reporting periods!).

I think it also maybe scales better to accommodate different time periods. For instance, I could see having an X-Axis that starts at January 2015 and goes to July 2017, the first half of the first year after an election, perhaps with a clear delineator.

This doesn't address the question about the interaction between the graph and table, but I wanted to get it out there for target practice. We can discuss more here or in our crit session.

**Comment by onezerojeremy** [comment]
:heart: You're totally right, the line makes it much clearer what is going with the  reporting periods! Great, strong progress.

On the primary purpose: I like the idea of a bird's eye view idea of an election; my admission is that coming in cold I don't really know who these entities are, and i honestly don't know what it means that one is outspending another. I assume that this may be true of others who are coming in even colder than I. So, the question i guess, is there anything else we can do to help contextualize the information? Is the shape of this graph to be expected, or should I be surprised? 


Perhaps: somehow show how this election compares with past elections, but I'm not sure that's right at all either. Or maybe there's a non-cumulative view that helps prompt (but not answer) the question "well how did PACs raise so much money in April".

**Comment by jenniferthibault** [comment]
😱  ohmygod I am so late on responding to this. Feeling slightly overwhelmed by the amount of issues we have going. I stumbled into this one entirely by accident, but a lot of things from yesterday make a lot more sense now!

One questions I can't quite stumble past: What is the difference between cumulative and total? I understand the meanings of the words, but in this case, what's included and what's not? I think this is opaque enough that if we are showing both, as you have here, I think we really need to provide an explainer of some sort right on the page, and not behind the "Methodology" button.

The remaining open question, which we brought up yesterday: is it misleading to connect the lines? or Would a step graph be more appropriate?

**Comment by jenniferthibault** [comment]
One more, sorry—is there a way to do this without tooltips?

**Comment by noahmanger** [comment]
No worries! "Cumulative" means the total amount raised / spent up to this point in time, so the number will always be going up. As opposed to what we are showing now, which is how much was reported *for that period*. Does that make sense? And I think Jeremy's designs yesterday present a great way of doing this without the tooltip.

**Comment by noahmanger** [comment]
Ok, I believe this design feedback has been addressed.
