### ISSUE TITLE
Infoviz: Where money is spent to support and oppose candidates: Decide on how the financial range is broken down

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1319]
How many categories is the financial range broken into, and what are they?

![screen shot 2016-06-30 at 1 22 12 pm](https://cloud.githubusercontent.com/assets/11636908/16497578/afb1d6ea-3ec5-11e6-8544-63bc5b0a2e3a.png)

cc @noahmanger

**Comment by noahmanger** [comment]
I'd like to enlist @shawnbot 's expertise here. Currently we use a continuous scale, but I think agree with you that I think a scale of discreet buckets is better for legibility.

I don't have an answer for what the buckets should be, but I can think of two questions we'd want to answer to determine them:

1. Do the buckets adjust dynamically depending on the range of the data for the applied filters? Or do they stay the same across all?
2. Should the scale be linear (`0 - $100,000, $100,001 - $200,000`) or logarithmic to more easily distinguish differences at the upper end (`0 - $1mil`, `$1mil - $2mil`, etc)?

Are there best practices to be aware of here?

**Comment by thecapacity** [comment]
Not sure I quite understand the Q - but perhaps working in percentiles might be better than "absolute buckets" -- i.e. if there's a general spending level (like $1) across the states that probably shouldn't be highlighted even if it's >0 ... but if one state is an outlier (and I think your Q is what makes it an outlier) then I think that's what you want to highlight.

some thoughts on "defining outliers":
* The main reason I would balk at "absolute buckets" is that there is a lot of "per capita" effect there - but in terms of spending per markets as well as in terms of "value" (e.g. lots of electoral votes would likely "naturally" incite a lot of spending) -- so CA might not be an "outlier" in terms of typical behavior
* I think ideally you'd probably want to look at it "year to year" which might help normalize for other factors - e.g. even if a state had a large "value" in spending if it was definitively one party or another then "extra" spending is likely not going to be high in that area (because all parties would know it wasn't worth it)
* Rather than a fixed "outlier" classification (whether by bucket or by quantile) maybe you could make it "user defined" - e.g. a slider that changed the 50% of "average spending" would allow a bit more interactivity in the graph w/o codifying judgement.
* Ultimately I think I would really be interested in "which PACs spent abnormally in what state" - which (although complex) would mean I care about a state's "heat map" relative to the PAC's other spending -- that sounds complex but I think you could do some "aggregation logic" that did a heat map based on how much of an "outlier" that state was as a sum of it's "interesting-ness" of other PACs...
    - i.e. "For each PAC figure out the quantiles of spending across the country and group states based on those quantiles, i.e. if a PAC normally "on average 50% quantile" spent $1 but spent $100 in CA then CA would get a +1 (or maybe a weighted value) to it's "overall interesting-ness" -- then conduct that evaluation across all PACs (and all states) and I think you're really going to get more "interesting" than a heatmap based on overall/total spending -- particularly because it would help "normalize" for "abnormal" spending (e.g. if I was a small PAC and spent $100 as my highest value, out of $1 on average, but another PAC spent $1M out of it's $10,000 average than the small PAC's spending wouldn't be overshadowed by the big one's.

Again - sorry if that doesn't hit the mark just trying to provide some thoughts based on what I think you're going for. I can "call a lifeline" (my wife does stats and survey reporting) and also think @khandelwal may have some interesting theories.

**Comment by gemfarmer** [comment]
@noahmanger @shawnbot is OOO, but I'll chime in with what I know about scales and what we have been doing in EITI.

The primary two scales that people generally use to classify cholorpleth maps are [quantize and quantile scales](http://indiemapper.com/app/learnmore.php?l=choropleth)
* **quantize**: equal (or log) ranged buckets, with a variable # of observations in each
* **quantile**: variable ranged buckets, with a equal # of observations in each

I think the decision is largely based on what the data looks like and what you are trying to emphasize. More than likely, you are just trying to show the data "as it is", but in chunks. If this is the case, I would go with a [quantize](https://github.com/d3/d3-scale#quantize-scales) scale. The default quantize scale is linear, but you can make it logarithmic if need be.

If you trying to represent as many tiers as possible, [quantile](https://github.com/d3/d3-scale#quantile-scales) would be good because the data would be spread out evenly across the scale. I think for most people this is less intuitive (ranges like `0-1, 1-4, 4-15` are harder to conceptualize than ranges like `0-5, 5-10, 10-15` )

For EITI we have been breaking mapping data into linear quantize scales and rounding the thresholds like you did in your comment above `(0 - $1mil, $1mil - $2mil, etc)` to avoid weird numbers like `$1,030,545`. 

Our buckets adjust dynamically by altering what the [`d3.extent()`](https://github.com/d3/d3-array#extent) evaluates to and creating a quantize scale from there.

**Comment by OpenGlobe** [comment]
If you're expecting that your data ranges are going to be changing based on the variables selected (it's hard for me to tell what exactly these data represent when comparing the map to the table), I'd suggest you want to keep your ranges defined consistently, I think @gemfarmer comments above are a good place to start.  For example, consistently using quantiles across all maps.  It's not uncommon for folks to attempt to compare two different maps created with the same online system, so you obviously want to remove the room for error in misinterpreting the data.

In general I think you'd want to avoid situations where (a) the user is defining their own range interactively or (b) using a categorization that will be misinterpreted (for example, if someone sees 4 categories they may be likely to interpret those as quartiles of your data).  It's also a good idea to get a sense for how your data are distributed (look at the histogram), as that can also help you select an appropriate classification scheme for your data.

I would most certainly define somewhere on the visualization what the methodology is as I'm guessing you will based on the existence of the "methodology" button, and I would most certainly use what is most commonly accepted in practice.  

A good resource is https://www.e-education.psu.edu/geog486/node/1865 

Finally, I like that you're including a table.  I'd suggest expanding this idea a bit and providing a link back to the raw data (if possible) as anyone who wants to delve into your classes will be readily able to do so.  But, I would suggest that if a table is used it doesn't represent data that leads to a misinterpretation of the map (in the example above, I think you're showing a proportion in the choropleth map - SuperPAC / PAC and total $$ spent in each state - so since the two don't represent the same data I'd avoid this.)

Does that help?

**Comment by noahmanger** [comment]
Wow, thanks everyone for the insight. That's all _super_ helpful. 

@thecapacity raises really good points: there's a ton of factors that influence the meaning of the data. For good reason, we're only able to add so much context and editorial commentary in our presentation of the data, so I think any kind of "interestingness" measure is likely off the table. But weighting by population is certainly interesting. 

@gemfarmer and @OpenGlobe : thanks for the quantize / quantile explanation. Unfortunately we don't have these totals calculated just yet, so we're flying a little blind at the moment. But in general I agree that we'll want to go with a quantize scale, and that we should have the range be consistent across the filters so you can compare. @jenniferthibault I think move forward assuming 5 buckets of equal range, though as the article Brian linked to suggests, we should reserve the right to change this once we're actually able to look at the data in case this method doesn't do it justice. 

And good points @OpenGlobe on the methodology -- we originally meant that just to explain the underlying data, but speaking to the mapping methodology is valuable. And actually the table and map will always be showing the same data set. The idea is that while the map can help you more easily compare states and understand trends and patterns, the table is an easier way to understand a detailed ranking of states.

**Comment by jenniferthibault** [comment]
This is really great, all! Thank you for jumping in.

The next steps from this that I see are:
- Define scale of colors for 5 values ( @jenniferthibault ) I know we have older issues on this that I can reference.
- Document mapping methodology in implementation for this & other maps/graphics ( @noahmanger w/ @jeanninehunter ?)

**Comment by gemfarmer** [comment]
@jenniferthibault for defining the color scale, I would recommend [colorbrewer](http://colorbrewer2.org/). You might already be using or aware of it, but if not, you are in for a treat!

**Comment by thecapacity** [comment]
I agree with @gemfarmer colorbrewer is a good tool - I usually combine it with Adobe's color wheel to try to make it pop more; https://color.adobe.com/create/color-wheel/

**Comment by OpenGlobe** [comment]
@jenniferthibault I'd love to work on an addendum to our comms guide that incorporates recommendations for map / data viz standards.  I've worked on something similar in the past and I think it's a great way to give designers (and devs) a leg up when thinking about how to represent data visually.

**Comment by jenniferthibault** [comment]
@gemfarmer @thecapacity @OpenGlobe Thanks for the recs! You might enjoy this issue where we talked about color schemes and 0-value vs no data categories from last year: https://github.com/18F/openFEC-web-app/issues/445

I expect this work to pick up from that and help address areas we left open!

**Comment by noahmanger** [comment]
@jenniferthibault do you want to keep this issue open for figuring out the 5-value color scale? The question about mapping approach can be addressed when we move to implementation.

**Comment by jenniferthibault** [comment]
@noahmanger Let's try this:

It starts with a 5 category Colorbrewer sequential multi-hue palette, slightly tweaked to move toward our palette's aqua color scheme closer to green instead of blue, which could be interpreted as representing political party-specific data.

<img width="417" alt="screen shot 2016-07-13 at 12 41 31 pm" src="https://cloud.githubusercontent.com/assets/11636908/16811683/84054c20-48f7-11e6-91ee-b5fa67d63114.png">

#f0f9e8 : Lightest, smallest value.

#bae4bc

#7bccc4

#2A9291

#216A7A : Darkest, highest value.

**Comment by noahmanger** [comment]
Love it.
