### ISSUE TITLE
Implement new full-height filter panel on mobile

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1326]
So that mobile users can better understand the relationship between the filters and the data area, re-implement the mobile filter panel to be a full-height drawer that slides in above, rather than above, the data.

**Criteria for completion:**
- [x] Filter panel starts out offscreen on mobile
- [x] When the filter panel is open, it is absolutely positioned above the data 
- [x] When it appears / disappears, it slides
- [x] When it is visible it is full-height, and the data table cannot be scrolled to

**Comment by xtine** [comment]
Per discussion with @jenniferthibault and @noahmanger, changing interaction to slide in from the left, covering the datatable below until the filter panel is closed and slides back hidden from the left.

**Comment by jenniferthibault** [comment]
@xtine sleeeeek! All the new stuff looks 👌 to me!

One ongoing question I've been wondering about is if the X button needs to be automatically focused on when the panel opens. Is that for accessibility reasons or could we take the focus off that button? It's the first thing my eye catches on, since the outline overlaps the text and it's so bright. (I know this was already existing, and has nothing to do with your changes, but I thought it was a good opportunity to ask)

**Comment by noahmanger** [comment]
Good point @jenniferthibault . I just asked in the accessibility channel on Slack about this and it sounds like the consensus is that it's ok (and actually better) to have the focus be on the first filter in the panel, rather than the close button. @xtine do you want to add this functionality to this PR or deal with it separately?

**Comment by jenniferthibault** [comment]
HAPPY DANCE!!!
