### ISSUE TITLE
Interaction design for graph/map/tables of overview & breakdown pages

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1333]
@jenniferthibault commented on [Fri Jul 01 2016](https://github.com/18F/fec-style/issues/417)

What is the graphic/map/table interaction on desktop & mobile for
- "What's spend on day-to-day operating activities" topic page
- "Where money is spent to support and oppose candidates" topic page
- "Where contributions come from" topic page
- "Size of contributions" topic page
- "Total raised in all elections" topic
- "Total spent in all elections" topic

[Mobile prototype](https://invis.io/R97U6AEAU#/171023868_Landing-Mobile-Raising)
[Desktop prototype](https://invis.io/KH7TNKQEB#/170607544_Data-Landing-Overview)

**Comment by onezerojeremy** [comment]
Ok I've put some thinking into this, focusing on how the mobile ixd in particular. I don't have 100% coverage, or near it, but I want to get a sense of if this is on the right track, and give ppl (esp @jenniferthibault and @noahmanger) something to react to. 

Basically,  the map, line and bar graph all will likely have the same problem on mobile, which is that the targets will be very hard to hit with a thumb or finger. So for a responsive strategy, the thinking is that we can perhaps swap the interacting part, much in the way that embedded maps become still images on mobile. So while you interact with the graph or map on desktop to make the table change, the "table" becomes the interactive element on mobile, providing bigger targets. This might be making some functionality problems, and if so we dig into those; perhaps there are workarounds, perhaps I need to go back to the drawing board. 

Example 1: the map
Here, the user can either view a list of all the states, or move through the states sequentially, in descending dollar amount, by tapping the arrows on either side of the state. You'll also likely notice that I messed with our sentence structure: more on that below. 
![map](https://cloud.githubusercontent.com/assets/474916/16751362/ba0d4de2-478d-11e6-83b7-8b7b03cd5764.png)


Example 2: the line graph. Since the dots are too small to target with your finger, I thought it might make sense to allow a control below the graph that allows you to "page through" to see the data at any given point. 
![line dec](https://cloud.githubusercontent.com/assets/474916/16751312/32fb82d8-478d-11e6-9c75-0dc6ff859ef4.png)

Example 3: Horizontal Bars
In looking at the horizontal bars, I noticed that we're using two different patterns for them, and I wasn't sure exactly why (there is likely a reason I don't know). Anyway, I liked the people pattern and left it pretty nearly unchanged, and thought hey why not try that on operating expenditures. The only changes made were moving the extra actions (explore data, share) from in between the trigger and action (now down below). 
![horiz-bar-ppl](https://cloud.githubusercontent.com/assets/474916/16751535/34668832-478f-11e6-8a77-91c35a85bab5.png)

![horiz-bar-cat](https://cloud.githubusercontent.com/assets/474916/16751534/30a346d6-478f-11e6-9a6a-fbb880c47ce4.png)


Other notes: I messed with our sentence structure. The more I looked at it, the more I thought that perhaps selecting the category (PACs) and the item (Super PACs) should be the same interaction; this also saves one interaction and moves the action closer to the data you're changing, and reduces the number of interactable widgets (since if we go with this pattern we're essentially adding one in navigating the graphic: would've been cycle (e.g. 2015-2016), category (e.g. Candidates), item (e.g. Senate candidates), and state. Right now I have this selection as a separate screen, rather than a modal (matching our advanced data  table filter updated interactions) but that might be wrong here. I also really liked the sentence pattern; perhaps there's a way to do both. 

I've scheduled a synchronous session for tomorrow afternoon; I've *not* mapped everything back to desktop so there might be some things that we won't be able to do responsively.

**Comment by jenniferthibault** [comment]
Some notes from our chit chat:

**Maps:**
- keep context of geographic distribution: color maps, even when one state is selected
- move data from tooltip to below scroller window (probably some interaction thinking to be done here, with an eye toward page length)


**Totals in all elections**
- Look into best practices about connecting lines between graph points
- Data is below the graph: keep this pattern and look at how to integrate it into maps
have relatively large buttons on the side to be able to get between months
also be able to move the cursor by touch/drag—expected behavior we should build in
- Add context to Methodology:
 - You might be wondering why these totals don’t line up. Problem with this data: when a committee submits a report, there’s a field for total receipts. more often than not that number does not equal the sum total of the items reported on that form. We use the number as reported, not a computational 
 - For a month like October “the last known amount for this was…"


**Overall:**
- move Methodology, data table, and share buttons out from between sentence & graph, should be below data.


## Next steps
- @jenniferthibault to move to visual styling, with checks on remaining interaction elements w/ @onezerojeremy 
- @noahmanger Do you want to take a stab at coordinating the bits about data weirdness to be added to the methodology? That might be a separate issue

**Comment by noahmanger** [comment]
Sounds good. New issue: https://github.com/18F/openFEC-web-app/issues/1353

**Comment by jenniferthibault** [comment]
I'm trying to find the lightest way to show you the styling changes from these interaction mockups,  but if what I've posted below isn't working, let me know and I can bump up the priority of updating the InVision mockups. I'd recommend clicking the below images to open in a new window at a larger size. 

Heads up @emileighoutlaw : I think we're losing all forms of copy accuracy the more these get fussed, and I'm not sure where to reference master copy. :( 

**Raising breakdowns**
(Including a map/table changeover and bar charts without accordions)

![screen shot 2016-07-13 at 10 24 30 pm](https://cloud.githubusercontent.com/assets/11636908/16826179/145f0954-4949-11e6-9731-628805613af7.png)

**Spending breakdowns**
(Including a map/table changeover with accordions, and a bar chart with accordions)

![screen shot 2016-07-13 at 10 25 20 pm](https://cloud.githubusercontent.com/assets/11636908/16826187/27884018-4949-11e6-884d-1adf89eea707.png)


**Stylized singular choice for sentences** (heads up @emileighoutlaw, this is where things particularly get lost !)
This adopts a pattern more similar to the mobile menu than the filter panel, so would love your thoughts.

![screen shot 2016-07-13 at 10 26 01 pm](https://cloud.githubusercontent.com/assets/11636908/16826215/76bd3ada-4949-11e6-99e5-2a25f4d1b7ed.png)


**Cumulative line graphs**
This is the one I grok the data we're showing the least, so maybe I need to talk through it in person, but I tried to at least fuss some styles without getting it 100%

![screen shot 2016-07-13 at 10 35 51 pm](https://cloud.githubusercontent.com/assets/11636908/16826288/30a637f8-494a-11e6-942c-cad527b44251.png)


Since @onezerojeremy only had mobile, I also only have mobile. Would help to talk out what we want our process to be to get back there.

**Comment by noahmanger** [comment]
I think these are looking so good. That complex dropdown filter concept is _very_ interesting. I think it could work well, and I could see it being useful in other places as well. Curious what @onezerojeremy thinks of the interaction. 

My only bit of feedback is on the last one. I think in the expanded view of a row we should do a few things: 
- Include both the cumulative amount to date (which you have) as well as the amount reported in that period
- Include links to the reports that the numbers are derived from

Also, I wonder if the bars might end up being slightly confusing. Are they always relative to the others in that time period? I like the idea though.

**Comment by onezerojeremy** [comment]
Cool stuff!! I'm good to try that interaction for the dropdown, provided the targets are big enough to be thumb-able! In general I think it might make sense because it's a single selection, whereas the filter panel is potentially multiple selections. 

I also like the bars! I guess the tricky part (or opportunity for a fun tiny toggle) is making sure it's clear whether they are showing the cumulative to date, or for that period, per Noah's suggestion for it's inclusion above.

**Comment by jenniferthibault** [comment]
Here's exactly where I'm getting wrapped up:

`making sure it's clear whether they are showing the cumulative to date, or for that period` 

I think we should show one, not both. Cumulative to date or total per period in this graph.

Yes, for advanced users they will know the value of both. But this is the very first chart experience all users will see, and is meant to be a jumping off point to the others, so I'd like to ask it to do _one_ informative task. It sounds like that should be cumulative to date because we are no longer defining time periods as a range (Jan 1-March 31 2015), but instead using singular months (November 2015). 

If you're both ok with that concept, I can tweak the visuals to support it better, and add in the links to the reports in one swoop

**Comment by emileighoutlaw** [comment]
## Raising and spending content
For reference, here's our master doc of content for raising and spending: https://docs.google.com/document/d/1oWFr-pK--tccSOIhEDZpa-1Pfxddwm_5Clqbqgr8FYI/edit#


## Dropdowns:
I love this idea. Here are the group options that exist in the existing advanced data filters:

<img width="712" alt="screen shot 2016-07-18 at 2 13 39 pm" src="https://cloud.githubusercontent.com/assets/10552702/16930627/ef47c12c-4cf1-11e6-8043-0e8659f17e0a.png">
👆 That seems decidedly unfriendly to read and possibly too granular for what we're doing. Here’s a possible option for grouping:

<img width="675" alt="screen shot 2016-07-18 at 2 15 27 pm" src="https://cloud.githubusercontent.com/assets/10552702/16930669/1dc2f044-4cf2-11e6-8935-6b0e700fa26d.png">
- More “recognizable” group buckets 
- Subtopics are ordered based on my assumptions of what people are most interested in looking at
- When selected for a chart, the subtopics all make sense as sentence completers.

**Comment by noahmanger** [comment]
Good point @jenniferthibault . Let's keep it simple and just have it be the cumulative amount raised to that point.

**Comment by onezerojeremy** [comment]
sounds good to me!

**Comment by jenniferthibault** [comment]
Thank youuuuu for relinking that Doc, @emileighoutlaw !

When tinkering with the bars, they did start to feel a little bit confusing. In other scenarios, we use them to give context to the numbers we show, but in this scenario, the line graph above does that, so I think it's safe to remove them, and the cognitive lift they imposed.

For linking the reports, I'm certain that the place to to that is in the table, and probably in the accordions, but I'm not exactly sure what the framing would be. I took a stab but @noahmanger it sounds like you probably have a better grasp of this?

<img width="519" alt="screen shot 2016-07-19 at 11 43 06 am" src="https://cloud.githubusercontent.com/assets/11636908/16956332/007b9950-4da6-11e6-92bf-e2b73ec5ac65.png">

**Comment by noahmanger** [comment]
+1 to removing bars. 

Now that the bars aren't there, I think we can actually just make the number total the link to the reports, and then don't need the accordion interaction. What do you think of that?

**Comment by jenniferthibault** [comment]
I've been thinking about your last suggestion @noahmanger — and I think I disagree (_or, I still don't understand what we're linking to. Very possible_)

Here's why:
The text in the accordion in my last mockup above gives you a clear readout of why you are seeing two different times/dots on the graph: because filing schedules are different for different groups. this feels helpful for all user levels

Without that (see below) you are linked to just one set of filings, and don't have the opportunity to learn why the dots on the graph don't all line up.
<img width="304" alt="screen shot 2016-07-27 at 4 19 00 pm" src="https://cloud.githubusercontent.com/assets/11636908/17195954/f49bc56c-5415-11e6-9a66-c35626b2b013.png">


I've gotten most of the mockups updated in the mobile InVision  here, though it's probably missing an overlay screen here & there.

https://invis.io/2R83KPFJW#/175086276_Landing-Mobile-Raising

I would love help understanding how we want to move fwd with this all: do we want to test these invision prototypes? If so, what changes do they need? Also wondering what desktop interactions still need to be resolved. Overall this feels like it's been in progress for a while, and would love to sync up on the plan for taking it forward from here.

**Comment by noahmanger** [comment]
Oops! You're totally right. That is valuable context to give. So scratch my previous comment. 

As for what more we need, I think this would be good to test with static prototypes before we code, just because it's such a departure from what we have, and a relatively heavy lift. 

I think it would be good to test those with desktop as well as mobile. I don't think there's anything substantial to resolve with the desktop view.

**Comment by jenniferthibault** [comment]
Thanks @noahmanger — I will get the desktop InVision mockups up to date so we can test them. (cc @onezerojeremy )

**Comment by jenniferthibault** [comment]
The home page on desktop is all set up for testing in InVision, with at least one of each type of interactive hotspot enabled (except for the drag/sliding time setter on the graph)

https://invis.io/J285OU6DH#/178500260_Data-Landing-Overview

Notes:
- You can arrow forward once to January, and arrow back from that back to October, but I didn't make a "back in time" overlay from October.
- You can expand the "All groups" section in each, but not the others

If we need to add more for how you design the tests, let me know tomorrow and I can add on.

**Comment by noahmanger** [comment]
With the addition of the desktop desgins, this is done.

**Comment by jenniferthibault** [comment]
@LindsayYoung I don't think I can attach a new screenshot to a comment in InVision, so I want to make sure your question about what the dropdown options are gets answered here!

Here are the options expanded:
<img width="623" alt="screen shot 2016-08-03 at 4 08 20 pm" src="https://cloud.githubusercontent.com/assets/11636908/17384995/86a46210-5994-11e6-8e73-2c2e0dfc4ddd.png">

thoughts?
