### ISSUE TITLE
Sketch the research/design process on the FEC data project team

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1352]
In order to contribute to the documentation, and to lay the groundwork for an eventual blog post, create a process diagram (or other relevant visualization) for the research>design>testing cycle our team works in.

Dependency:
Defining our process as is. 

Mostly filing this issue in order to get it out of my head and onto a to-do list.

**Comment by jenniferthibault** [comment]
I've started blocking things out [in this mural](http://mur.al/vdrK2Z1p) in a Gannt chart-like format following Jeremy's outline of our [earlier discussion](http://mur.al/vOqN22e7). I'll keep working through, but wanted to get some existing resources out so that @nickykrause can take a peek!

**Comment by jenniferthibault** [comment]
@onezerojeremy / @ethanheppner can you take a look at the "new iteration" that's mocked up here in murally? http://mur.al/vdrK2Z1p

Before making this any more designed, I'd like to see if my sense of what would happen with a regimen of once-per-sprint usability testing is on track.

**Comment by ethanheppner** [comment]
@jenniferthibault: this looks pretty comprehensive (and spot on) from my perspective.

**Comment by noahmanger** [comment]
👍  from me. Looks solid. I really like the new iteration concept.

**Comment by onezerojeremy** [comment]
Really strong cut! Thanks for describing this process and laying out some tweaks which I think could cut the strain on the team considerably. I've added some comments to the mural and thoughts below! thanks for your patience; it feels like i've been in wall-to-wall meetings this week. 

To reflect back the changes, as I see them: 
## The new iteration's most substantial change formalizes a move from testing once a week to testing once a sprint. 
- I think that given how stretched everyone is, I think that moving formal usability testing to once a sprint makes sense, especially if it means we can have more team involvement (which is at stake in the more aggressive testing schedule). 
- Once-a-sprint testing does put a bit more stress on making sure recruiting is effective, unless we institute a fall-back testing day if we don't feel confident in the results we've received. 
- Moving to a two week cycle may allow us to experiment with moving testing day from Thursday to Wednesday, which would likely alleviate some of the crunch (documented in the comments on the mural) felt in moving from synthesis to documentation and report out in the few unmeeting'ed hours on Friday. 
- the team has also been considering experimenting with different kinds of testing (such as a just-in-time version of usability testing that uses ethnio as a web-intercept system, recruiting and offering testing sessions to users immediately as they come in, or perhaps less facilitated testing). This is more of a "yes and" though.

All the above is just based on what I've noticed about the existing process and how it might play out in the new one; I'm excited to now have @nickykrause at the helm from the research / ux perspective; her thoughts on where she wants to take the process carry much more import at this point. 

Finally, while I'm loathe to admit it, it feels like it might be faster to have a synchronous meeting on this, if there's questions in the comments you want to follow up on.

**Comment by noahmanger** [comment]
The idea of moving testing to Wednesday is intriguing. It moves it off of the day when we're prepping the release branch, leaves more time for synthesis, and leaves an extra day that can be used for overflow / make-up scheduling.

**Comment by jenniferthibault** [comment]
Thank you for writing out all the things I should have @onezerojeremy: a good reminder that even for internal things, it helps to document! This, especially is the purpose of this whole issue :)  

The idea of moving the testing a day earlier does ease up the race to the finish line at the end of the week (which just got some pressure relieved by moving our sprint planning to Mondays as well). Nice combo move. I'm super curious to hear what @nickykrause thinks!

**Comment by nickykrause** [comment]
_realizes I wasn't getting mention notifications..._ 

But, I'm here now, and my settings are changed! Thanks for your patience, everyone...

Here are my thoughts (a bit long, since I'm reacting to a lot all at once, after my extended silence):

- The item labeled "usability test plan decided on and designed" is somewhat of a mystery to me. I don't necessarily think that the process needs to be formalized or more explicitly documented, but I want to note that it was a point of confusion for me over the past two weeks (and it remains a point of confusion for me when looking at this visualization). For the one round of testing I've witnessed, the process was like this: In what appeared to be ad-hoc meetings, I spoke to both Noah and Porta about what they would want tested, and then I chose somewhat randomly what to put in the script (really, I chose Noah's features, because I understood them more at the time). Not sure if that is normal, but my question is: Do the data and legal teams feel like they are competing over testing time? Would a clearer process alleviate that, assuming it's even an issue? Maybe the new meeting on Mon will help, since we're recognizing the need for a "single pipeline" for design work, including usability testing? 

- Whatever it ends up looking like, I support the idea of having more time for synthesis. I haven't actually experienced the synthesis process yet, but I was nonetheless concerned about having a tight timeline at the end of the week. So, if one solution would involve moving the usability tests to Wed, then that makes sense to me. _However_, given the fact that we've had some difficulty recruiting users (or following through with the recruits), I wonder if we are limiting ourselves in the attempt to confine the test sessions to a single day? I understand that expanding the sessions across multiple days might open a logistical can of worms, but it seems worth discussing how that could work, in the service of talking to more users (and thereby making the whole testing effort more worthwhile).

- I actually like the idea of testing every week (rather than once a sprint), but then again, I have not yet become very familiar with the flow of sprints, and I don't have a strong sense of what is realistic to accomplish in the two-week timeframe. I am already realizing that usability recruiting/testing takes a significant amount of time (even without having done the synthesis part). 

Still, for what it's worth, here are some reasons that I would support testing every week, if workloads allow:
- It seems like there is more we could be testing, beyond the features that are being designed on a sprint-by-sprint basis. For example, we have touched briefly in our meetings on the idea of testing more holistic site elements, such as the site navigation or the experience of moving between different features that different teams are creating. 
- When we are recruiting users, they might not be available on the upcoming Wednesday/Thursday, but perhaps would be available the following week (which is what I saw in recruiting this week). It'd be nice to have more options for meeting their needs. (See my point above about offering appointment options on more days.)
- There is already an open issue (assigned to me) about documenting and refining the synthesis -> wiki process. Perhaps, if we can make that process even smooth, then testing each week wouldn't be quite as daunting.

That's all for now. I think.

**Comment by jenniferthibault** [comment]
Thanks for these good thoughts and fresh perspective @nickykrause ! Glad your notifications are all sorted now 😄 

You're right that this doc so far is more of a "what happens, when" than a "how does this happen".

Until this point, we didn't have any representation of the process down, so I started with what & when, but I could definitely see how "how?" and even "who?" components would be helpful next steps for getting a comprehensive sense of our process down.  A lot of it is ad-hoc, as you said, but some things have some structure, and it would be helpful to capture each.
- a quick solve to help from keeping you wondering on how what to test is decided and the test is designed would be for you and @onezerojeremy to sync on that part to see how he's been doing it.

On testing frequency, I don't think the door is closed on weekly cycles at all, but the team has been feeling that the way we were doing it was a bit too cramped. There was a lot happening each week and synthesis and documentation were feeling super rushed. The move to once-per-sprint testing (or once every two weeks) is our first attempt at relieving some of this pressure. This was the rotation we were about to start right when you joined, but we can certainly walk it back if you want to try a different direction.

If you do want to try it out, I see next steps for this issue to be to close this issue for now (since the sketch of the process is complete) and I'll make a new (backlogged) issue to fill in the "how" and "who"s in a more detailed version of the diagram in a later sprint. After 2 or so sprints, we could reflect back and see how this version of the process is going, and what changes we might want to make, then go about fleshing out more of the specifics to each stage.

**Comment by nickykrause** [comment]
@jenniferthibault - that all makes sense to me! 

I'm not sure that the "how" and "who" even needed to be added in the future. It would be helpful, possibly, for newer people (which is why it was on my mind), but a lot of this can also be learned via conversation / time.

**Comment by jenniferthibault** [comment]
Carried over to #1557 ⚡

**Comment by noahmanger** [comment]
Late to the game, but just wanted to say great thoughts @nickykrause . 

+1 to formalizing the process by which we decide what to test, and I think the new Monday meeting is the perfect place for that

I love that you're into the once a week testing, and think this will be good to try again, but I'd offer that while we're all under the gun to get certain things finished in the next 5 weeks, we might stick to the every-other-week plan for now and then give weekly testing a try in October.

Also +1 to the thoughts about expanding to more days in order to accommodate more users.
