### ISSUE TITLE
Implement new drop-down behavior

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1356]
So that users can better understand what's happening upon selecting items from a filter dropdown panel, implement the new [interaction design](https://github.com/18F/openFEC-web-app/issues/1328).

Here's the current behavior:
![gif](http://g.recordit.co/ksYhHtn7ci.gif)

The new interaction design consists of three main changes:
- In-context notifications 
- Not removing the dropdown item from the panel upon selection
- Allowing for the removal of a generated checkbox entirely, rather than just the ability to uncheck it

**Completion criteria:**
- [x] Dropdown items show the loading & selected state as designed
- [x] Dropdown items are not removed from the panel upon selection
- [x] The dropdown button shows the loading and selected state as designed
- [x] When hovering over a dropdown-generated checkbox, the remove button becomes visible
- [x] Clicking the remove button unselects and removes the checkbox
- [x] Clicking "Clear all filters" removes all dropdown-generated checkboxes
- [x] X-ing out a tag removes the related checkbox

**Comment by jenniferthibault** [comment]
I want to get clear on one bit both for documentation and for my own understanding. It seems like the following two have the same effect:
- Making a remove button available on hover and `Clicking the remove button unselects and removes the checkbox` 
- `Clicking "Clear all filters" removes all dropdown-generated checkboxes`

The usability desire I saw was for users to feel satisfied that they were starting from a clean slate by not just unselecting an option, but by totally clearing away the unchecked checkboxes generated by dropdowns.

The approach above offers two mechanisms for this: one through "clear all tags" and one through a hover state -> remove button. We are using two approaches because one (the remove button) is closer to the action the user is performing, and the other (clear all tags) is grouped with the summary actions that control the whole search. 

Am I getting that right?


I would also add that a prerequisite for implementing the new interaction designs of the confirmation messages is the validation pattern: https://github.com/18F/fec-style/issues/416

**Comment by noahmanger** [comment]
Yep, that maps to my understanding as well. Thanks for clarifying.

**Comment by xtine** [comment]
@jenniferthibault: when the text in the dropdown takes up the entire width, how do we account for spacing for the selected checkbox?

<img width="283" alt="screen shot 2016-08-01 at 6 11 34 pm" src="https://cloud.githubusercontent.com/assets/24054/17313787/9f7ddd34-5813-11e6-912d-686f416449f6.png">

**Comment by jenniferthibault** [comment]
Thanks for flagging @xtine !

Is it possible to do something like this, where we grid off the space for the checkmark, and treat it like a boundary that would force a line break?

I say _like this_ with sincerity. If building columns inside a dropdown is wackadoodle, any approach that gets the same spatial separation is what I'm going for!

<img width="621" alt="screen shot 2016-08-01 at 6 29 37 pm" src="https://cloud.githubusercontent.com/assets/11636908/17314043/0747c18a-5816-11e6-988a-82d1bca5168c.png">

**Comment by xtine** [comment]
@jenniferthibault: thanks! that design looks good, I'm now working on setting a max width for text in a dropdown to account for that checkmark now.

**Comment by xtine** [comment]
@jenniferthibault: how's this?

<img width="284" alt="screen shot 2016-08-02 at 5 58 17 pm" src="https://cloud.githubusercontent.com/assets/24054/17350337/c2dc7c96-58da-11e6-82a6-d196c158e0b7.png">
<img width="291" alt="screen shot 2016-08-02 at 5 57 56 pm" src="https://cloud.githubusercontent.com/assets/24054/17350339/c664aef6-58da-11e6-8626-a9b8a386806b.png">

**Comment by jenniferthibault** [comment]
Nice!

Adding piecemeal requests isn't ideal, I know, but is it possible to vertically center the confirmation mark on double-decker check boxes, instead of having it lined up with the last line? (Single-level, too, but I think they're already like that by default) That way it's uniformly positioned in the menu and in the filter panel.

<img width="285" alt="screen shot 2016-08-03 at 2 12 01 pm" src="https://cloud.githubusercontent.com/assets/11636908/17382164/5a9b5490-5984-11e6-95b9-d19cf3ea343e.png">

**Comment by xtine** [comment]
![2wmy8n56wy](https://cloud.githubusercontent.com/assets/24054/17394761/ad8e75b4-59df-11e6-961f-8df3421e4095.gif)
