### ISSUE TITLE
Styling and content for filter ranges

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1373]
On data filters, users have the option to input ranges for both contribution amount and dates. But their design is pretty different. My critique group had a lot of trouble understanding this was a range when I shared it with them (i.e., that they could enter amounts like "from $0 to $5,000")

<img width="267" alt="screen shot 2016-07-15 at 4 56 03 pm" src="https://cloud.githubusercontent.com/assets/10552702/16891391/db0a7614-4aad-11e6-9542-b85023da2931.png">

I think we should consider having a more unified content/design system for these. Something like:

<img width="271" alt="screen shot 2016-07-15 at 4 58 28 pm" src="https://cloud.githubusercontent.com/assets/10552702/16891404/ff6fd3dc-4aad-11e6-96cb-da4c09ef83fe.png">

Thoughts on this?

**Comment by noahmanger** [comment]
I think it's a great idea, and very relevant to the work we're doing elsewhere with these filters this sprint.

**Comment by emileighoutlaw** [comment]
I was just looking at our templates, and this involves a few more `div`s and `label`s and `class`es than I feel confident editing. By which I mean, I think I could do this with many hours of work, and I suspect @noahmanger or @xtine could do it in just a few minutes? Can I tap one of y'all in for implementation?

**Comment by noahmanger** [comment]
Sure thing, though this might need to wait until next sprint.

**Comment by jenniferthibault** [comment]
Oooh I hadn't seen this GitHub issue before, but yes this has been bugging me as well. When the fields are so (needlessly) wide, and stacked on top of each other, it's hard to read them as a single range.

I'd like to follow what's happening in the date filter issue https://github.com/18F/openFEC-web-app/issues/1375#issuecomment-237419973 to unify this pattern as well

**Comment by noahmanger** [comment]
Because it was very easy, here's a code sketch:
![image](https://cloud.githubusercontent.com/assets/1696495/17411677/1a78c19a-5a2e-11e6-8c68-27b75a8b7146.png)

**Comment by jenniferthibault** [comment]
And because it was ver very easy, here's a quick interaction style-over of that sketch to add the hyphen in between and $ in the fields :)

Curious to hear @onezerojeremy 's thoughts

<img width="256" alt="screen shot 2016-08-04 at 11 55 55 am" src="https://cloud.githubusercontent.com/assets/11636908/17414490/7ea3d7fc-5a3a-11e6-9b33-0223fdf1bff5.png">

**Comment by noahmanger** [comment]
One question on the above design: where does the loading indicator / success checkmark go?

**Comment by jenniferthibault** [comment]
Oh right we need that.

**Comment by jenniferthibault** [comment]
<img width="243" alt="screen shot 2016-08-05 at 8 22 28 am" src="https://cloud.githubusercontent.com/assets/11636908/17441408/c4041bee-5ae5-11e6-8bcd-dd3f5ffa6ab4.png">

**Comment by emileighoutlaw** [comment]
Just by the way, I love all of this.

**Comment by onezerojeremy** [comment]
100% agree! it's great!!

**Comment by noahmanger** [comment]
A challenge: adding the buttons (at their current width) doesn't leave enough room for larger numbers:
![image](https://cloud.githubusercontent.com/assets/1696495/17453402/5a353978-5b30-11e6-8051-5edcb59300b7.png)

**Comment by jenniferthibault** [comment]
This corresponds with the thinking in https://github.com/18F/openFEC-web-app/issues/1375#issuecomment-238433941 about how we might make ranges one unit for validation, and solve some space problems. 

We will never win 100% on this one, because people can enter any number they want, but if we anchor the cursor position on the right (which mirrors right-aligned financial columns) we can let the number go underneath a clear space created around the $ sign. A little layer-y, but feels more consistent. The catch is that it's dependent on the approach in #1375 for range filters.

<img width="308" alt="screen shot 2016-08-08 at 10 48 09 pm" src="https://cloud.githubusercontent.com/assets/11636908/17502981/3547dc88-5dba-11e6-8fe3-58bddde120fc.png">

**Comment by noahmanger** [comment]
👍 Looks good to me!

**Comment by noahmanger** [comment]
Closing in favor of new implementation issue here https://github.com/18F/fec-style/issues/458
