### ISSUE TITLE
Update and unify date filter patterns

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1375]
While discussing the [new date filter validation pattern](https://github.com/18F/openFEC-web-app/issues/1364) with @jenniferthibault and @xtine we uncovered a design issue we need to resolve. We currently have two date filter patterns. The original, which is used on the [filings](beta.fec.gov/data/filings) and [independent expenditures](beta.fec.gov/data/independent-expenditures) pages, is used in instances where the tables aren't partitioned, thus allowing users to enter any date range they want, as well as select from radio button options:

![image](https://cloud.githubusercontent.com/assets/1696495/16932696/f1ff13a6-4cfc-11e6-96ef-e6571d383af3.png)

The second is the newer version, used on pages like [receipts](beta.fec.gov/data/receipts), where the underlying tables are partitioned by two-year `transaction_period`. In this pattern, a two-year period is always set, and then users can refine their dates within that:

![image](https://cloud.githubusercontent.com/assets/1696495/16932732/22032e3e-4cfd-11e6-9165-dd2e8ff992b8.png)

Additionally, we also have an [open usability issue](https://github.com/18F/openFEC/issues/1727) around our date inputs, as some users have had difficulty using them. 

I think it makes sense to address these all together, and hold off on front-end implementation until we have a new pattern. 

I don't think we need to have a single pattern that is shared by both types of date filters; I don't think we should force those tables where you can enter an open-ended range to select a two-year period, for instance. But maybe there's a more elegant way to make the interaction feel consistent, while at the same time communicating the relationship between the transaction period filter and the specific dates.

**Criteria for completion:**
- [ ] Decide on approach for the two kinds of date filters
- [ ] Design new form of custom date input

@onezerojeremy is this something you'd be able to take on this sprint?

**Comment by onezerojeremy** [comment]
yup, on it!

**Comment by LindsayYoung** [comment]
Maybe this is not the right place to comment, but since the two-year transaction period is required and applied by default, we might want to un-nest it. That way, people can see that is applied and easily change it.

**Comment by onezerojeremy** [comment]
So after a bunch of looking around the good 'ol net, a visit to my critique group, etc, I've come to a couple conclusions. 
- date pickers are tricky! mostly because there are about 1,000 different ways people use dates. plus mobile, plus accessibility. 
- best practice: if you can help it, don't let them select invalid dates, but also don't go crazy trying to interpret and fix what a user is entering that doesn't make sense. 
- best practice seems to be to allow selection via some sort of a picker, but don't take away the ability to just type it in
- the cycle selection and the date tailoring are two parts of the same kind of thing, even if one is just a default based on the shape of the underlying data. Therefore, I propose that the two interactions should be tightly linked. 


based on this, i got to thinking about how it might make sense to provide a way for folks to select things, and how to tighten up the date entry. A couple options: 

### standard calendar picker
![time period- cal picker](https://cloud.githubusercontent.com/assets/474916/17230214/072f21fa-54e9-11e6-95b7-b008af086a28.png)
- pretty standard calendar picker interaction. Seems like best practice for accessibility is that the calendar widget does not get focus, even on click. 
- people (rightly or wrongly) seem to expect a calendar picker, and including one helps us put guard rails on the interaction.  We could, in the future, think about fanciness where we let them select a date outside the cycle, warn them that what they're doing will flip to the next cycle, and do so, but that sounds like a tricky thing to get right. 
- one additional benefit of the calendar widget is that it reinforces the date you've picked (especially useful for the dd-mm-yyyy crowd. 

### month slider picker
![time period - sliders](https://cloud.githubusercontent.com/assets/474916/17230217/0af15bf0-54e9-11e6-8d0f-0cda4654f258.png)
- based on the idea that there might not be _as much_ value in the actual date of a data row, because of the inherent lack of date precision of the reported data, and given that generally speaking we're dealing with 2 year partitioned data, i thought it might be fun to try a slider-selector. Inspired by this one: 
![period_selector_invoices](https://cloud.githubusercontent.com/assets/474916/17230327/87fc6edc-54e9-11e6-9c30-5fa20514a7f3.gif)



### in-situ checkbox tag filter action
Ok so with either of these, for the cycle-constrained data we should demonstrate the constraints. Here, the filter check boxes are doing the work of showing when you can mess with them, and when you need to play with the cycle selector. 
![time period check box filter actions](https://cloud.githubusercontent.com/assets/474916/17230222/0fd84624-54e9-11e6-8dcd-5f047fbafef1.png)

### Date filter typing tweaks: 
So the WDS (and GDS) calls for 3 fields, and I've always felt like it's a little clunky but I think I get why. There's the accessibility angle, but using three fields also clarifies user intent. I switched from the dash to the slash and made them bigger because it seemed like a stronger division between field sections. I don't know how much of this we can actually do, but the basic ixd principle is to mimic the functionality of three fields without necessarily sectioning out 3 fields.
![date entry detail](https://cloud.githubusercontent.com/assets/474916/17231574/d1179cfc-54f0-11e6-9515-8c00c210b6d0.png)




### additional provocation
There might be a way to better make this one interaction where the cycle dropdown is sort of advanced and lets you tailor right in it. 



Not married to any of this, of course. Hopefully at least good fodder for a synchronous session.

**Comment by jenniferthibault** [comment]
Good fodder indeed @onezerojeremy — you've presented lots of options, but I'm not sure what criteria should guide our decision, since these each meet the goals you set out at the beginning. I.e., 

- if you can help it, don't let them select invalid dates, but also don't go crazy trying to interpret and fix what a user is entering that doesn't make sense.
- allow selection via some sort of a picker, but don't take away the ability to just type it in
- the cycle selection and the date tailoring are two parts of the same kind of thing, so the two interactions should be tightly linked.

It also looks like some options presented are meant to be (or could be) combined with one another, but some are mutually exclusive. I.e., 

- The standard calendar picker _could be_ combined with the in-situ checkbox selecting and the date filter typing tweaks, but should it? with one or both?

and 

- the month slider picker _could be_ combined with the in-situ checkbox selecting and the date filter typing tweaks, but should it? with one or both?

but 

- you you wouldn't have the calendar picker _and_ the slider


Where is your preference leaning?




Your **additional provocation** has sparked a tiny idea that I may try to flesh out :)

**Comment by noahmanger** [comment]
Bunch of good thoughts here! My two cents: I really like where you're going with the slider idea. I think you're right: the date filters most likely to be used are probably not specific, but broad. (Though if you want to filter down to the day, you can). From what I've read, date pickers are best if users are a) looking to find a *specific day* and b) the *day* of the week is useful as a point of reference. I don't think those are true in our specific situation.

The other thing I like about a slider approach is that it saves people from having to type, which I think makes for a notably better interaction on mobile in particular, but also desktop as well. 

That said, it's a notably more complex component that would be harder to engineer.

**Comment by jenniferthibault** [comment]
Here's a loose take at one that combines the slider with a month only calendar picker. What @noahmanger picked up on is where I was leaning, it's less important to let people set specific dates, than for them to set the months. First day/last day of the month can be generated automatically.

<img width="538" alt="screen shot 2016-08-03 at 5 21 24 pm" src="https://cloud.githubusercontent.com/assets/11636908/17386368/0080a21a-599f-11e6-8e37-f8be0cc27c60.png">

This design would not generate checkboxes, but it would generate tags and confirmation messages, just like we have now.

**Comment by noahmanger** [comment]
Ooooh that's slick. I like it. Small thing: what do you think about putting the month picker above the dates?

**Comment by jenniferthibault** [comment]
Heh, I definitely had that at one point and then changed it because it seems _sliiiiightly_ like you'd miss it if you were looking for it to confirm what dates specifically you're looking at.

I don't know for sure though, that's something that a usability test might be able to tell us.

<img width="523" alt="screen shot 2016-08-03 at 5 53 55 pm" src="https://cloud.githubusercontent.com/assets/11636908/17386864/6a6c7d44-59a3-11e6-9250-c7b0bf684247.png">

**Comment by noahmanger** [comment]
Oooh i really dig that. Not sure why, but it feels better.

**Comment by noahmanger** [comment]
The thing that just occurred to me this morning is that we still need to address the question of whether this is how both kinds of date filters will work. Do we want all date filters to only be able to select dates within a two-year period? Or do we want to continue to allow those date filters that don't need that parameter to choose any dates? If so, how does that work with this new interaction?

**Comment by jenniferthibault** [comment]
I also had that thought when looking at the preliminary mockups for the AO landing page: https://gsa.invisionapp.com/share/AR7U3Y662#/screens/167711252

<img width="297" alt="screen shot 2016-08-04 at 10 11 44 am" src="https://cloud.githubusercontent.com/assets/11636908/17411153/e06215f8-5a2b-11e6-9a64-0393627bc849.png">

Where we don't need the two-year time period as the first limiter. Which type of pattern do you think works best there @onezerojeremy ?

**Comment by jenniferthibault** [comment]
I'm about to upload a whoooole lot of stuff, but it all hinges on this first date field mockup. My for including validation and keeping the range on one line depends on treating ranges as a single unit for applying as a filter and validating. This starts to hint at toward tag behavior, but for now let's look at the field interactions:

![date fields](https://cloud.githubusercontent.com/assets/11636908/17502252/6bbaa670-5db4-11e6-87ee-52d8c24655e0.png)


If this looks agreeable, it becomes our primary date selector and the base unit for our two-year period slide cycle, in which you can edit the time period within that cycle:

![date-default state](https://cloud.githubusercontent.com/assets/11636908/17502272/90da56da-5db4-11e6-8427-574cfdee3f69.png)


Hang on to your seats, interactions showing a lotttttt of options below.

![narrowing the period of time](https://cloud.githubusercontent.com/assets/11636908/17502301/cc2e0de4-5db4-11e6-94e1-fcb0700499f0.png)

![expanding the period of time](https://cloud.githubusercontent.com/assets/11636908/17502308/d38bf4c0-5db4-11e6-81d0-b0466caba132.png)

![narrowing the period of time to one month](https://cloud.githubusercontent.com/assets/11636908/17502333/f992c856-5db4-11e6-869e-88ce660605fe.png)

![expanding the period of time from one month](https://cloud.githubusercontent.com/assets/11636908/17502343/03b08bb6-5db5-11e6-9d1a-45c614fcb899.png)

What do you think @onezerojeremy @noahmanger ?

**Comment by onezerojeremy** [comment]
This stuff is looking so good! 

Some details:
date_fields.3: I don't think we should necessarily reset the ending date on clicking on the beginning date, but curious to hear your thoughts on why. 

default_state.1: I like the visual effect on the dates in the future, but I can't remember where we landed on the bad data that says it's from the future. Is it you can only get to them by the date fields, not the month picker? If so, because these two interact, what does the month picker look like when you type in a date that is disabled? 

Overall: 
I'm not sure, it could be that I just need to play with it, but the interaction with the month picker is feeling a mite complicated and I'm curious if perhaps there may be a simpler rubric (by simpler, I'm thinking: could we do something that isn't dependent on what you've picked?). For example, what if the interaction is just reset everytime a user comes to it. 
- clicking a month selects it
- clicking and dragging selects all months until mouse-up

Alternatively, 
- on loss of focus or after a small time-out, we consider all interactions with the month picker as intended to pick the starting month. 
- the next click after that picks the ending month. If they click that month again, or don't pick again after a time out, the ending and beginning are the same month. 

One final thought: 
we could use the "beginning" and "ending" date fields to hint the user which month they are picking. Changing the visual style, and possibly visually connecting the current element on hover might give folks a clue as to which they are picking. 

oh one last tiny thing: talk to me about what the angles on the display of the edge months are up to. I raise it because I think this visual might make it feel less contiguous.  

These designs might also be good fodder for a synchronous session

**Comment by jenniferthibault** [comment]
Aiming for slightly fewer mocks, and hoping that most of the missing pieces can be inferred from our conversation today & from corresponding states on other sheets here.

Based on our convo today, here's a list of some changes:

**Base date field pattern**
- We won't use in-field color validation yet. Start without it and test to see if users understand what fields are being changed sufficiently through usability testing.
- We won't auto-populate any field that a user does not edit themselves, even if it's to nudge them to good data. This could feel intrusive, confusing, and potentially frustrating
- Right-align the cursor in each text unit
- Two types of validation  errors: ( @emileighoutlaw , would appreciate your microcopy eye here!)
  - Error caused by date format (is it logical? Did you enter an end that is after the beginning date? Did you use dd/mm/yyyy instead of mm/dd/yyyy?)
  - Error caused by server/api

**Date field with date picker & 2-year cycle selector**
- Not new, but specify the principle that users can control the time by editing _either_ the date grid or the text field. If the text fields are edited, the date grid adjusts accordingly, and when the date grid is edited, the text fields adjust accordingly.
- Use visual indication so that users know when adjusting one field also changes another: this must be recognized in usability testing
- On the date picker, we'll use the mini open/close icon 
- Use rounded endpoints instead of pointed ones
- @onezerojeremy is working on the specifics of the click interactions for engaging and setting the start/end points on the date grid (it proved above my interaction weight class and end of day brain)

**Next steps:**
- @onezerojeremy filsl in the click interactions
- @emileighoutlaw 🔍 copy
-  @noahmanger / @xtine take a pass as integrating the visual styles here with Jeremy's click interactions. Take best guesses at any missing visual pieces, and move forward to testing.
- Usability test! Some key questions in the change list above^
- I'll pick up any outstanding visual questions when I'm back from vacation

![date fields](https://cloud.githubusercontent.com/assets/11636908/17541303/199172ba-5e8c-11e6-85c5-97db7006e5b7.png)

![default state copy](https://cloud.githubusercontent.com/assets/11636908/17541141/85870dce-5e8a-11e6-841f-305af358b31c.png)

![narrowing the period of time](https://cloud.githubusercontent.com/assets/11636908/17541305/21fda8ba-5e8c-11e6-9168-7a65d7051109.png)

![narrowing the period of time to one month](https://cloud.githubusercontent.com/assets/11636908/17541308/25096fc6-5e8c-11e6-9a21-4e13419496bd.png)


![expanding the period of time from one month](https://cloud.githubusercontent.com/assets/11636908/17541157/9d344f54-5e8a-11e6-9638-2fa449b8c173.png)

**Comment by onezerojeremy** [comment]
After sleeping on it, I think that perhaps the simplest way to make the month picker functionality understandable is to rely on the convention of a date picker, wherein our month selection is done as a child to the relevant date text entry field. 

Justification: 
- we can't know whether the users intent is to select an ending month or a beginning month first. To account for this, we either have to add an interaction where they tell us which they want to do first, and none of the options are seemingly totally clear. For instance, we could: 
 - use a slider drag pattern, which is probably the closest convention, but there are not many multiline sliders and the conversation yesterday left me with the impression that dragging has accessibility ramifications.  Possible click flow for this: [user clicks and drags either slider to the position they want it]
 -  use a modified slider pattern where the first click "unlocks" the month slider from its current position, hovering and moving the mouse shows where you could drop it, and the second click locks it in a new position. It's always 2 clicks, and it's a new pattern, i.e., likely not one people will be familiar with in this context (my main concern is getting people to understand in looking at a grid that you need to click once to unlock) Possible click flow for this: [click once to unlock the beginning-month or ending-month selector, click again on the month desired]
  -  make a design decision to always require selection of either a beginning or ending first. So as a user, you'd either always have to select the beginning month first, or always have to select an ending month first, before you could select the other This is what I was advocating for yesterday, but after sleeping on it, it feels a little problematic too: we don't know which the user wants to do, and we'll make the experience a little worse for those who want to do the opposite.  Possible click Flow for filtering by ending month: [grid shows beginning-month selector active, user must know to click the already selected first month, which then will select it and activate the ending-month selector, the user can then click on what they originally wanted]
 
![time-period-date-grid-rev3](https://cloud.githubusercontent.com/assets/474916/17559434/3cf63578-5eec-11e6-886d-208649fb1ffa.png)

Happy to chat more about this! If this seems like the right way to go, I think Jen's designs and ixd above covers off on the rest of the elements but maybe let's start here and i can verify the edge case interactions if this feels right.

**Comment by jenniferthibault** [comment]
This! `we can't know whether the users intent is to select an ending month or a beginning month first.` !!!

This makes sense to me, and will save space on the default load space without the grid being exposed all the time. I can picture it sliding the content below it down gently as it opens, much the same as the validation text does. Let's give it a go?

**Comment by noahmanger** [comment]
Love it. Super compelling. Let's move it to implementation.

**Comment by jenniferthibault** [comment]
Hold it there, Quick Draw McGraw. @emileighoutlaw this needs your content 👀 , ([look for your photo in the comment above](https://github.com/18F/openFEC-web-app/issues/1375#issuecomment-238759208) which can also happen in implementation, but I don't wanna rush your part of the process!
