### ISSUE TITLE
Refine loading & success interactions

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1397]
Some follow up tasks to polish up the filter loading, success and error states from our meeting just now:
- [x] Remove error states on success
- [x] Fix overlapping `.filter__remove` button and error x’s
- [x] Change open state on dropdown button to up-pointing arrow
- [x] Change check mark in selected dropdown items to gray
- [x] Fix the occassional extra loading state that is triggered when losing focus on a text input
- [x] Move the "unique only" tooltip to be in the label, rather than next to the checkbox
- [x] Typeahead generated checkboxes should show loading and success indicators when checked / unchecked
- [x] Ensure that typeahead-generated checkboxes trigger a filter count increment / de-increment in the accordion header and in the filter panel

And some content-specific tasks:
- [x] Update the language in the success messages (tweaking "adding" / "removed" language)
- [x] The success message when there's 0 results added or removed should have special language
- [x] Add error message

**Comment by xtine** [comment]
@noahmanger @jenniferthibault @onezerojeremy: while refining these interactions, I noticed that typeahead generated checkboxes can't be removed like dropdown generated checkboxes can be. What do you think about adding the ability to remove them as well?

**Comment by onezerojeremy** [comment]
i think its a great idea! good catch!

**Comment by noahmanger** [comment]
@emileighoutlaw do you have time to work on the few language tasks here?

**Comment by emileighoutlaw** [comment]
The content pattern here is:
- "Added" and "removed" for filters, because that's the action the user takes. 
- "Expanded" and "narrowed" for results, which feels more technically accurate. "Expanded" isn't perfect, but I believe it's understandable, and — importantly — it allows us to use "narrowed" as its opposite. "Narrowed" is the important piece here, because what we want to give the impression of honing in on results, not taking data away. The word we use for that moment is the most fraught with risk for misunderstanding.
- No punctuation on either line, which lightens the tone a little bit from the very serious period. I think the line break is a sufficient ending

## Increase in results messages
**Filter added**
Expanded by 22,201 results

**Filter removed**
Expanded by 22,201 results

## Decrease in results messages
**Filter added**
Narrowed by 22,201 results

**Filter removed**
Narrowed by 22,201 results

## No change messages
**Filter removed**
No change in results

**Filter added**
No change in results


I'd love to hear any thoughts on any of those options.


## Error messages
I'm posting a question here and not a solution (sorry!) because I let conference brain get in the way of my remembering what we decided last Friday. 

What I remember: We want our error messages to give folks information about how to correct their mistake. That would mean we'd need to tailor the message for the filter + the error. For example, we'd have a different error message for dates than we would a money than we would committee ID error. Right? 

Want to make sure we're on the same page before I start crafting these. ☺️

**Comment by xtine** [comment]
@emileighoutlaw: currently only failed connections to the API results in the error state with the red x, so we would need language to say that it is a connection issue that could be either on their end or our end.

The error message for invalid dates are different, and I think is being worked on in another issue.
<img width="274" alt="screen shot 2016-08-15 at 11 18 20 am" src="https://cloud.githubusercontent.com/assets/24054/17674436/632a5cb4-62da-11e6-816c-8be0d95457df.png">

I couldn't find other ways to get an error.

**Comment by xtine** [comment]
@emileighoutlaw: The messages you suggested look great. I applied them and they look like this:

<img width="292" alt="screen shot 2016-08-15 at 1 27 01 pm" src="https://cloud.githubusercontent.com/assets/24054/17678468/11c8aa62-62ec-11e6-9003-6c9a5abc005a.png">
<img width="286" alt="screen shot 2016-08-15 at 1 27 07 pm" src="https://cloud.githubusercontent.com/assets/24054/17678469/11cd0346-62ec-11e6-8c33-ea00e177536b.png">
<img width="295" alt="screen shot 2016-08-15 at 1 27 11 pm" src="https://cloud.githubusercontent.com/assets/24054/17678471/11d1a630-62ec-11e6-9944-f8ea1a02debc.png">
<img width="292" alt="screen shot 2016-08-15 at 1 27 17 pm" src="https://cloud.githubusercontent.com/assets/24054/17678470/11cee044-62ec-11e6-883a-f1a99762dda0.png">

**Comment by xtine** [comment]
@emileighoutlaw: Those message suggestions look great. Here's what they look like:
<img width="283" alt="screen shot 2016-08-15 at 1 32 28 pm" src="https://cloud.githubusercontent.com/assets/24054/17678641/d4a16f06-62ec-11e6-8778-d94a20904575.png">
<img width="274" alt="screen shot 2016-08-15 at 1 32 34 pm" src="https://cloud.githubusercontent.com/assets/24054/17678642/d4aab6a6-62ec-11e6-926f-600fe0131d95.png">
<img width="273" alt="screen shot 2016-08-15 at 1 32 37 pm" src="https://cloud.githubusercontent.com/assets/24054/17678643/d4bdb792-62ec-11e6-937c-9caa80d0a9cf.png">
<img width="285" alt="screen shot 2016-08-15 at 1 32 44 pm" src="https://cloud.githubusercontent.com/assets/24054/17678644/d4c8caba-62ec-11e6-8845-a5b939c9784b.png">

**Comment by noahmanger** [comment]
Nice. Re: error states, @xtine is right, we're just accounting for errors when connecting to the server, not validation errors.

Re: the language above, just remembered we have this issue as well https://github.com/18F/openFEC/issues/1851, which is specifically about accounting for the fact that our record counts are approximate when stating how many records were removed or added.

The other thing to think about is the fact that just because the number of records is smaller, it doesn't mean that same record set has been narrowed. For example, a search for "nike" yields 30 results and one for "adidas" yields 15. Those are 15 new results, not a subset of 15 results of the first 30. I worry that the "narrowed" / "expanded" frame gets confusing with this a bit.

**Comment by emileighoutlaw** [comment]
Interesting point about narrowing, Noah. Let me think on this for a bit, and I'll post an update here today (and also address the validation errors).

**Comment by emileighoutlaw** [comment]
Correct me if I'm wrong, but I think the same reason that "narrowed" doesn't work, "removed" also doesn't seem right. If you go from 30 results to 15, it's not necessarily because you "removed" 15 results from that original set of 30. 

What if our pattern looked like this:

> **Filter added**
15 more results

> **Filter removed**
15 fewer results

> **Filter added**
No change in results

Validation errors: I like error messages that give people an idea of what they should do next. Going back to our old, closed issue about unified error messages (https://github.com/18F/fec-style/issues/266#event-640253693), I think we could reuse some of the language we developed there for a more consistent, site-wide experience. 
> **We had trouble processing your request**
Please try reloading the page

Is reloading the page the right advice in this situation?

**Comment by noahmanger** [comment]
Yeah I agree that was a problem with the "removed" language. I like "more" / "fewer". Hard to say what the actionable step would be. It could be as simple as just re-applying the filter.

**Comment by xtine** [comment]
Ooh I like more/fewer.

Not sure what to suggest on the error. While reloading would make sense if their internet connection dropped, if our servers are down it wouldn't help to continue to load the server with reloads, either.

**Comment by noahmanger** [comment]
It could suggest one of the above, and then also say "Still having trouble? Let us know in the feedback box at the bottom of the page"

**Comment by emileighoutlaw** [comment]
I like those ideas! How about:

> **We had trouble processing your request**
Please try again. If you still have trouble _let us know_

(And clicking `let us know` could open the feedback box?)

**Comment by noahmanger** [comment]
I like it.

**Comment by xtine** [comment]
Updated the error messaging:

<img width="1217" alt="screen shot 2016-08-17 at 3 43 38 pm" src="https://cloud.githubusercontent.com/assets/24054/17755851/6f3ac8fa-6491-11e6-8269-9d5f87cbdd64.png">

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1532
