### ISSUE TITLE
Question: Which years included in candidate header

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1400]
.  I entered in a name in the “Profile” search, it appears that the default is 2016.  The following tells a different story:
![image](https://cloud.githubusercontent.com/assets/11817734/17479420/791a8cd2-5d40-11e6-8744-5d78b80a2d02.png)

Why is 2008 included?

**Comment by jwchumley** [comment]
Having inconsistent years and dates on the screen is confusing. 
Priority: High

**Comment by noahmanger** [comment]
I understand that there's some inconsistent dates, but in this case, the 2008 is there because she ran for president in 2008. The point is to give users a holistic view of a candidate's history for a certain office. Is this a matter of needing to clarify what the data means or of a disagreement about whether we should be showing that?

**Comment by jwchumley** [comment]
There are several levels of confusion here. One, It attempts to present a holistic view and a slice of time view on the same screen. 

Having chosen to view Hillary Clinton for 2013-2016 all the information on the screen should be from that time period. Such as:

In the header, listing both of her committees is confusing because even though the old committee existed and was a PCC in 2013 it was never the PCC for her 2016 race. It was the leftover PCC for the 2008 race.  It does belong lower on the screen where it already is but it doesn't belong in the header under Principal campaign committee. 

Other similar issues on the same screen:

Header - Elections - Same issue. Hillary was in 2008 and 2016 but since we've already said "Let's look at HIllary's 2016 race, we shouldn't list the older one. You can see them all in the election pulldown anyway and that is appropriate. 

The blue boxes for committees under the "Campaign Committees" label: Instead of listing years when the committees were active which for the current PCC is irrelevant because we've selected the 2016 election and for the older pcc is inconsistent with the selection of a time period, remove the dates and mark the terminated committee with "Terminated"

Lastly, the list of form 2s at the bottom is labeled "All Years" but it only shows current election form 2s. Should change the label

**Comment by LindsayYoung** [comment]
I would like to display the years that a candidate ran for election in some way, because that is the easiest way to tell if they were involved in a special election.

**Comment by jwchumley** [comment]
I'm having trouble looking at off year candidates. Try Adam Lopez. He is on the list but I get an Oops! If  I choose him. Similarly If I click on the older of Hillary's two committees I get an Oops.

**Comment by PaulClark2** [comment]
But the list of election years isn't always helpful

2015 - no
https://beta.fec.gov/data/candidate/H6NY11174/

2013 - no
https://beta.fec.gov/data/candidate/H4SC01073/

2013 - yes but I get oops is I select 2013 from the drop down
https://beta.fec.gov/data/candidate/H2IL02172/

2013 - no
https://beta.fec.gov/data/candidate/H4MO08162/

**Comment by noahmanger** [comment]
Addressed by new candidate page designs.
