### ISSUE TITLE
Add links to financial summary info in candidate profiles

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1405]
NONE of this information is clickable

![image](https://cloud.githubusercontent.com/assets/11817734/17479502/dcf0f66a-5d40-11e6-92c1-333ccfe7fbf7.png)

Why can’t I click on this to get more detailed information?  Currently in the Viewer, when I select a candidate, I can get detailed information….

**Comment by jwchumley** [comment]
Specifically this is speaking to not having all the categories of $$ presented on this level. All the receipt and disbursement and loan categories like are presented on a candidate committee page should be presented here so the user doesn't have to understand about committees or even click again if they do understand in order to get the information.
Priority: High

**Comment by noahmanger** [comment]
Addressed by new candidate page designs.
