### ISSUE TITLE
CSV should present information in alphabetical order

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1421]
The data on the website is presented in alphabetical order, the CSV does not:
Website:

![image](https://cloud.githubusercontent.com/assets/11817734/17480185/9b762f6c-5d44-11e6-971a-9fedd3d04f05.png)

CSV
![image](https://cloud.githubusercontent.com/assets/11817734/17480192/a734464a-5d44-11e6-8a6f-dbab26e11561.png)

The CSV should mirror the website in regards to the download

**Comment by jwchumley** [comment]
Yes. THe export files should reflect the grid order.
Priority: low but it should be done and not forgotten.

**Comment by noahmanger** [comment]
Just curious: why should the order of rows be the same? If you can order the CSV by any column, what difference does it make?

**Comment by LindsayYoung** [comment]
We can do that, but there are some downsides. 

Adding custom sorting to the cvs increases the amount of csvs that we would produce. Right now if 10 people wanted the same information, they will get the same file, if we add custom sorting, then, instead of making one file, and giving it to 10 people we need to make 5-10 files because the sort is different. 

That makes the downloads take longer and increased the work for the database. Since there is one line to make downloads, it could back up people with other requests too.

**Comment by LindsayYoung** [comment]
Maybe a good compromise would be to always apply the default sort order to the downloads- I think that would an improvement and not slow things down.

**Comment by jwchumley** [comment]
I think default order would be fine. In most cases it won't matter much but the default order of the filings tab should be very specific and difficult repeat in excel.
