### ISSUE TITLE
Request: Link receipts blurb to filing schedule

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1431]
I find this useful
![image](https://cloud.githubusercontent.com/assets/11817734/17480380/a4a44b5e-5d45-11e6-8ef0-459c09683f6b.png)

But, I would add a link to the reporting table/chart.

**Comment by jwchumley** [comment]
Priority: Low but if easy then goodwill points accrue

**Comment by noahmanger** [comment]
Could this link to a page on the calendar filtered down to reporting deadlines? Like https://beta.fec.gov/calendar/?category=report-E&category=report-M&category=report-Q

**Comment by jwchumley** [comment]
I don't know. I think it would be better if it were a page that explained the different filing schedules for different types of committees and showed the filing schedule for the current cycle rather than just a link to the filings scheduled in the current month. I think the answer here is  - Great suggestion but we'll have to revisit it once the content is migrated.
