### ISSUE TITLE
Known issue: Need remaining IE data

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1436]
Currently missing a chunk of IEs by only having F3X
![image](https://cloud.githubusercontent.com/assets/11817734/17480621/bceb038c-5d46-11e6-8944-aaf416155971.png)

**Comment by jwchumley** [comment]
Adding the non form 3x IEs is extremely important to entire group of content experts. Misleading without all of them.
Priority: High

**Comment by noahmanger** [comment]
This fits in nicely with our "Add remaining data" epic, so I want to drill into what we need to do yet. 

As I understand it, there's a two remaining data sets we need to include
- Form 5s
- 24/48 hour reports

Correct?

And then there's two instances where this data is displayed:
- The aggregates that are shown on candidate, committee and election pages
- The itemized data itself on beta.fec.gov/data/independent-expenditures

When we were first launching the itemized IE data, we had a long discussion about what could and could not be shown together in the same view. So the good news is I think we have all the data already, which means it's just a matter of working out the interface decisions.

Here's an educated guess about what I think we're going for:

Form 5s: 
- Aggregates: Include alongside F3X aggregates
- Itemized: Include alongside F3X itemized data

24 and 48 hour reports:
- Do not include in aggregates, as it will be a double-count
- Can include on the IE data page, but it should be an either/or toggle, similar to efiling/processed, so that the records aren't interspersed with F3X records, which would result in duplicates.

Is that right? I know @PaulClark2 is out this week, so if @jwchumley or @amykort

**Comment by jwchumley** [comment]
Pretty much yes.


There are some issues with form  5 filers that file 24/48 hour notices. They are supposed to follow up with a quarterly filing. IF they do then their summary figures are correct. IF they don't then their summary figures are incorrect or non existent.  We have some logic for this that we apply in very narrow circumstances but I think for now just including the notices and getting the form 5 summary data will be sufficient (Unless Paul has already talked to you about tracking quarterlies vs notices)


________________________________

**Comment by noahmanger** [comment]
Ok, I have a working solution that looks something like this:

![image](https://cloud.githubusercontent.com/assets/1696495/18107171/cac54996-6ebb-11e6-991b-a220869ca2c3.png)

- This removes the previous filter that only showed `F3X` figures, so `F5` data is now included.
- It adds a toggle filter for "Summary reports" vs "24 and 48 hour notices" (language needs to be changed, I'm sure). This filter defaults to show _only_ `F3X` and `F5` ("Summary reports") but can be toggled to show _only_ data from notices. 
- Aggregate links (e.g. from a total on a candidate page) default to only the "summary report" data

You can take a look here: https://fec-feature-proxy.18f.gov/data/independent-expenditures/

Including Form 5s in aggregates I _think_ is extra work, or maybe it's already done. @LindsayYoung would know. 

But what do you think @jwchumley ?

**Comment by jwchumley** [comment]
I think the concept works but I've been poking around in the data and haven't found any form 5 filers. They appear in the dropdown box when you search but when I select one there is no result.


Here are a few that should have results for 2016:

C90004185

C90005471

C90005786

________________________________

**Comment by LindsayYoung** [comment]
thank you for the examples!

**Comment by noahmanger** [comment]
Good catch. I wonder if this is just a matter of not being off the data warehouse. When I filter the API by `filing_form=F5` I see results, but it doesn't look like we have anything with an `expenditure_date` after 2002: https://fec-feature-api.18f.gov/v1/schedules/schedule_e/?api_key=&sort_hide_null=true&filing_form=F5&is_notice=false&sort=-expenditure_date&per_page=30

They're showing up on the app if you filter by one of those committees: https://fec-feature-proxy.18f.gov/data/independent-expenditures/?committee_id=C90004185&is_notice=false

**Comment by noahmanger** [comment]
This is now resolved by https://github.com/18F/openFEC-web-app/pull/1565 and will be deployed in the next release.
