### ISSUE TITLE
Request: get rid of the Individual Contributions and Disbursements tabs 

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1442]
The bar graphs are useless, I can’t get any detailed data
![image](https://cloud.githubusercontent.com/assets/11817734/17480702/27b63290-5d47-11e6-9ad1-6d956980803b.png)

Simple solution, get rid of the Individual Contributions and Disbursements tabs and incorporate both of them above.  Again, the bar graphs are useless.

**Comment by jwchumley** [comment]
Summed up:
The old display was better. Order everything like on the form because it puts like things together and summed things below the things that are summed. This display makes it really hard to find things at a glance. If you want to keep the bars put them beside each of the values and put the values in logical order.

Priority: High

**Comment by noahmanger** [comment]
No longer relevant.
