### ISSUE TITLE
Request: Make committee charts clickable

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1443]
Why isn’t any of this data clickable

![image](https://cloud.githubusercontent.com/assets/11817734/17480728/4334e5d4-5d47-11e6-9344-b1bb280bd21e.png)

I can go to the Report Summaries in the Viewer and click the information.

**Comment by jwchumley** [comment]
The comment isn't really correct because you can't currently click through on any of these categories. THey are all too broad.  I think if all the summary numbers were presented and you could click on all the ones that have a related specific transaction set and get the transactions (like individual contributors) the bar graph would not be an issue.

Priority: Low as long as the other issues are addressed.

**Comment by noahmanger** [comment]
These were removed with the committee page redesign.
