### ISSUE TITLE
Request: Include itemized contributors on individual committee page

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1444]
Individual Contributors tab, I feel that the Group By  and the “All individual contributions data” should be flipped, meaning that after I click on the tab, I would get a list of the contributors with the OPTION of Group By.

**Comment by jwchumley** [comment]
There was a lot of discussion about the tabs. The general consensus was:
From the detailed summary tab the amounts should be clickable to display the transactions for all kinds of transactions.

The things currently on the individual contributors, Disbursements and between committees tabs should be combined on a single tab for "Cool Stuff" that doesn't include simple lists of transactions but includes the aggregated and otherwise not simple data presentations. 

Priority: High but probably take a while to define and get done.
