### ISSUE TITLE
Complete styling changes for current MURs canonical pages

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1652]
A few straggling comments found in review didn't get into the PR before it was merged way back in https://github.com/18F/openFEC-web-app/pull/1596

So that we won't lose track, I'm making this issue as a new one for those changes.
- [x] Remove `class="main__content"` from Summary section, because there isn't a citations sidebar for current MURs, so we don't need to hold the space for it. Per @adborden 's [review comment](https://github.com/18F/openFEC-web-app/pull/1596/files/85e60f9cf99f87d8fd8735d6bba66b832ec57f58#r80328967)
- [ ] Remove extraneous floating `+ +` from line 104/105-ish that appear at the bottom of the page [per comment](https://github.com/18F/openFEC-web-app/pull/1596/files/85e60f9cf99f87d8fd8735d6bba66b832ec57f58#r80329366):
  <img width="734" alt="screen shot 2016-10-24 at 5 40 23 pm" src="https://cloud.githubusercontent.com/assets/11636908/19665031/0e00ec26-9a11-11e6-9d0e-758a9cf3a401.png">
  https://beta.fec.gov/data/legal/matter-under-review/4908/
- [x] Address [possible simplification comment](https://github.com/18F/openFEC-web-app/pull/1596/files/85e60f9cf99f87d8fd8735d6bba66b832ec57f58#r80329602)
- [x] The Document and Participant tables should use alternating background colors set by the left-most row. (Set up and explained to by @adborden here: https://github.com/18F/fec-style/pull/510#pullrequestreview-376278 ) 
- [ ] We should use the complete citation title in the column: For statutes, `30121` becomes `52 U.S.C. 30121` and for regulations, the format would be `11 C.F.R. 110.4(c)(2)` From https://github.com/18F/openFEC-web-app/pull/1596#issuecomment-250020339
- [ ] The linked text in each citation should not include the `11 C.F.R` or `52 U.S.C.` per @emileighoutlaw 's beautiful quest for consistency across citations in https://github.com/18F/fec-cms/issues/544

cc @anthonygarvan

**Comment by vrajmohan** [comment]
2 of these issues seem to have been addressed already in previous commits:
- the extraneous floating + + 
- using the complete citation title in the column

For the alternating background colors, @jenniferthibault and I decided that this should apply to Dispositions as well (in addition to Documents and Participants).

The issue re. unifying citations (a.k.a. @emileighoutlaw 's beautiful quest) would be handled as part of https://github.com/18F/fec-cms/issues/544.

- [ ] @jenniferthibault also requested that each citation be on a row by itself so that it is easy to see the number of citations at a glance.
