### ISSUE TITLE
Research and identify filters necessary for enforcement actions

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1703]
In order to add the ADR/AF data and to build out advanced filters for MURs, we need to do some user and technical research to scope what these filters can and ought to be. 

This requires
- Understanding the schemas for the ADR/AF data
- Understanding what users need to be able to find what they're looking for within this data

I know @nickykrause is planning on lining up conversations with advanced users at the FEC and Jennie at the FEC has also offered to help us understand the technical details.

**Criteria for completion:**
- [ ] Documentation around the schemas for ADR/AF/MUR data 
- [ ] List of desired filters
- [ ] Generate a set of issues for implementing filters: for the existing filters on the current site, what would the technical lift be to implement each of them?

**Comment by noahmanger** [comment]
For more background, @nickykrause wrote up great detailed thoughts over here https://github.com/18F/fec-eregs/issues/296#issuecomment-261817125

**Comment by noahmanger** [comment]
For starters, we're going to get a meeting with Jeff, Jennie and someone from Salient for next week.

**Comment by nickykrause** [comment]
**Existing MUR refinements in EQS:**

---

First, it is important to note that the EQS system allows users to search across all case types -- MURs, ADRs, and AFs -- via the same search screen. 

Users who wish to search for MURs alone can do so by checking the box for "Matters under review" within the "Case Type" list. (This list also includes ADRs and AFs.). This mechanism is shown here:

> <img width="414" alt="screen shot 2016-11-23 at 1 32 56 pm" src="https://cloud.githubusercontent.com/assets/1450173/20575972/6000dfa4-b181-11e6-935e-b9744ef883ba.png">

The availability of additional refinement options depends on which case types are selected. For example, selecting MURs as the case type enables the greatest number of additional refinement options, while selecting Administrative Fines (AFs) enables the fewest options.

---

***Refinement options for MURs***
Below is a list of the MUR refinement mechanisms that currently exist in EQS. (Meaning: If we desired to achieve feature parity with the existing MURs search system, we would need all of these.) 

- **Word/phrase** - Allows the user to enter one or multiple keywords

- **Document type** This is drop-down menu, with the following options:
    - Conciliation Agreements
    - Complaint, Responses, Designations of Counsel, and Extensions of Time
    - General Counsel Reports, Briefs, Notifications, and Responses
    - Certifications
    - Civil Penalties, Disgorgements, Other Payments, and Letters of Compliance
    - Statement of Reasons
- **Subjects** This is a drop-down menu, which includes the following options. Note that some of these options activate an additional drop-down menu containing relevant sub-topics. The "sub-topics" menu is always present, but it says "None" when no sub-topics exist):
    - Allocation
    - Committees - _Subtopics:_
            - Candidate
            - Multi-candidate
            - Non-party
            - PAC
            - Party
            - Political
            - Presidential
    - Contributions - _subtopics:_
            - Corporations
            - Excessive
            - Exemptions
            - In the name of another
            - Labor unions
            - Limitations
            - National bank
            - Prohibited
    - Disclaimer
    - Disbursements
    - Electioneering
    - Expenditures - _subtopics:_
            - Coordinated
            - Exemptions
            - Limits
            - Prohibitions
    - Express Advocacy
    - Foreign Nationals
    - Fraudulent misrepresentation
    - Issue Advocacy
    - Knowing & Willful
    - Loans
    - Non-federal
    - Other
    - Personal use
    - Presidential
    - Reporting
    - Soft money
    - Solicitation
- **Case #** This is a free-text field

- **Case/Committee Name** This is a free-text field

- _**Committee ID** This field is disabled in EQS when MURs are selected as the "case type" - Presumably, it does not apply to MURs._

- **AF challenged cases** This is a single check box.

- **Cases opened:** This mechanism includes fields for "After" [MM/DD/YYYY entry] and "Before" [MM/DD/YYYY]). Like this:

> <img width="485" alt="screen shot 2016-11-23 at 1 48 50 pm" src="https://cloud.githubusercontent.com/assets/1450173/20576453/a43ba012-b183-11e6-94df-9a15a76cb1ad.png">


- **Closes closed:** This mechanism includes fields for "After" [MM/DD/YYYY entry] and "Before" [MM/DD/YYYY])

- **Respondent(s):** This mechanism allows the user to input the names of up to 2 respondents: Respondent 1 has fields for LAST NAME [Free text] and FIRST NAME [free text], and then Respondent 2 has fields for LAST NAME [Free text] and FIRST NAME  [free text]). Like this:

> <img width="524" alt="screen shot 2016-11-23 at 1 47 47 pm" src="https://cloud.githubusercontent.com/assets/1450173/20576417/800a4374-b183-11e6-95d1-ed74a31ac914.png">


- **Complainant(s):** This mechanism allows the user to input the names of up to 2 complainants: Complainant 1 has fields for LAST NAME [Free text] and FIRST NAME [free text], and then Complainant 2 has fields for LAST NAME [Free text] and FIRST NAME  [free text])

- **Respondent’s Counsel(s)/Representative:** This mechanism allows the user to input the names of up to 2 people: Again, the first has fields for LAST NAME [Free text] and FIRST NAME [free text], and the second also has fields for LAST NAME [Free text] and FIRST NAME  [free text])

- _**Report type** This field is disabled in EQS when MURs are selected as the "case type" - Presumably, it does not apply to MURs._

- **Election/Report year(s)** This mechanism has two free-text fields for years, with a drop-down menu to select either  AND or OR logic. Like this:

> <img width="315" alt="screen shot 2016-11-23 at 1 50 29 pm" src="https://cloud.githubusercontent.com/assets/1450173/20576525/e960467a-b183-11e6-8861-489d9865fedb.png">


- **Final Commission Disposition** This is a list of checkboxes supporting multi-select - options below:
        - No RTB
        - RTB/NFA
        - No probable cause
        - Probably cause/NFA
        - Conciliation
        - Pre-Probable Cause
        - Probable Cause
        - Dismissed - low rated
        - Dismissed - stale
        - Dismissed - other
        - Other

- **Statutory citation(s) by case** This mechanism has two free-text fields, with a drop-down menu to select either  AND or OR logic. Like this:

> <img width="487" alt="screen shot 2016-11-23 at 1 52 28 pm" src="https://cloud.githubusercontent.com/assets/1450173/20576599/253caa94-b184-11e6-9059-0d0eb1ac7661.png">


- **Regulatory citation(s) by case** This mechanism has two free-text fields, with a drop-down menu to select either  AND or OR logic

- **Civil Penalty Amount by Respondent** This mechanism has two free-text fields, one for Minimum $ Amount and one for Maximum $ Amount. Like this:

> <img width="441" alt="screen shot 2016-11-23 at 1 53 16 pm" src="https://cloud.githubusercontent.com/assets/1450173/20576625/3f9685c2-b184-11e6-9fd9-9a332cd82cd5.png">


- **Civil Penalty / Fine amount by Cases** This mechanism has two free-text fields, one for Minimum $ Amount and one for Maximum $ Amount

- **Non-monetary terms** This is a list of checkboxes supporting multi-select - options below:
        - Acknowledge Violation
        - Admonishment
        - Adopt Policies/Guidelines/Manuals
        - Amend Reports/Register
        - Attend FEC Seminar
        - Other
        - Training
        - Termination
        - Use IT Software

- **Document dates** This mechanism includes fields for "After" [MM/DD/YYYY entry] and "Before" [MM/DD/YYYY])

**Comment by nickykrause** [comment]
Another note: The current EQS system does not display keyword matches by document type, but it does list the documents within a given MUR that produced the keyword match. 

For example, here is what I see when I search for "embezzlement":

First, I input the term, and I select "MURs" as the case type:
> <img width="476" alt="screen shot 2016-11-23 at 2 09 01 pm" src="https://cloud.githubusercontent.com/assets/1450173/20577106/6b7fad74-b186-11e6-8595-c7ae0bf8ceec.png">

After searching, my results are displayed as follows:
> <img width="704" alt="screen shot 2016-11-23 at 2 10 15 pm" src="https://cloud.githubusercontent.com/assets/1450173/20577149/9ff4ed76-b186-11e6-8f9f-24e4a30f3d76.png">

The search results interface does not show me a snippet of the document that matches on "embezzlement" -- the keyword appears no where in the results. However, the specific documents from within the MUR that contain the word "embezzlement" are pulled out for me as individual links. 

Note: Even if I change the "Presentation format," using the drop-down menu at the top of the search results page, none of the options available offer a view of search term matches. 

---

Our current search experience for MURs provides users with visual feedback that their search was successful by highlighting search term matches within a snippet of the MUR documents' contents. However, we have lost the ability to surface direct links to the specific documents in which those search terms appeared (which, as explained previously, is what the users are now asking for in the feedback we received.)

**Comment by nickykrause** [comment]
My first, not-technically-informed thoughts about the feasibility fields of implementing these filters for MURS. **My assessment is made for current MURs only.**

---

- **Word/phrase** - ➕  We are already doing this, but we aren't doing it by document type ➖  , as discussed previously. Searching by keyword within specific documents will be a technical lift, as we would need to depart from our current search implementation, which puts all the document text together prior to search.

- **Document type**  ➕  Again, my understanding is that we don't have the ability to limit the search to specific document types, per the issue mentioned above.

- **Subjects** ➕  ❓  The subject already appears to be a discrete field in the MURs on beta, so I imagine this filter would be fairly straightforward.
    - **Sub-topics.** ❓ However, I don't see anything in the MURs currently that pertains to sub-topics within a "Subject." I am not sure if we can filter on this. 

- **Case #** ➕  We are already able to call up specific cases by number, in the existing beta search.
- **Case/Committee Name** ➕  ❓  Unless I am mistaken, the Case name typically is the name of the Committee involved in the case, with some exceptions. For example, [MUR 5813](https://fec-stage-proxy.18f.gov/data/legal/matter-under-review/5813/) appears to be called "Georgia Medical Political Action Committee," but [MUR 6048](https://fec-stage-proxy.18f.gov/data/legal/matter-under-review/6048/) is named after the primary respondent, "Maureen Duffy." Because this seems to be a discrete field, I am guessing we could filter against it fairly easily
- _**Committee ID** This field is disabled in EQS when MURs are selected as the "case type" - Presumably, it does not apply to MURs._ 
- _**AF challenged cases** This is a single check box. It does not visibly appear to be disabled for MURs, but, in actuality, it is not selectable when MURs alone are being searched. It only seems to be enabled for Administrative Fines._
- **Cases opened:** ➕ ❓  For the current MURs on the beta site, I don't see a clear way to determine when the case was opened and when it was closed (e.g., [MUR 6048](https://fec-stage-proxy.18f.gov/data/legal/matter-under-review/6048/)). However, for the archived MURs, this information is clearly displayed, as can been seen with [case 2860](https://fec-stage-proxy.18f.gov/data/legal/matter-under-review/2860/). Assuming that we have access to the open and close dates for current MURs, as we do with archived MURs, then I imagine we could filter on this fairly easily.
- **Cases closed:**  ➕ ❓See previous comment
- **Respondent(s):**  ➕ ❓ This appears to be a discrete field within both the current and archived MURs, so, again, I assume filtering would be possible 
- **Complainant(s):**  ➕ ❓ Same as previous
- **Respondent’s Counsel(s)/Representative:** ➕ ❓ Same as previous
- _**Report type** This field is disabled in EQS when MURs are selected as the "case type" - Presumably, it does not apply to MURs._
- **Election/Report year(s)** ❓ Not sure about this one
- **Final Commission Disposition** ➕ This appears to be a discrete field in the MURs on beta, where individual respondents are associated with specific dispositions, like so:
> <img width="723" alt="screen shot 2016-11-23 at 3 18 34 pm" src="https://cloud.githubusercontent.com/assets/1450173/20579063/22137b3e-b190-11e6-8404-9a8261c9ad91.png">


- **Statutory citation(s) by case** ➕ ❓ I assume this refers to the citations depicted in the above^^ screenshot, which would suggest that we do have this information for MURs, but I am not sure if/how we distinguish between "statutory" citations and "regulatory" citations.
- **Regulatory citation(s) by case** ➕ ❓ See previous comment.
- **Civil Penalty Amount by Respondent** ➕❓This information is quite clearly displayed in the EQS system, but it does not seem to match exactly what we are displaying on beta. For example, here is a comparison for [MUR 4322](https://fec-stage-proxy.18f.gov/data/legal/matter-under-review/4322/), from EQS and beta:
><img width="691" alt="screen shot 2016-11-23 at 3 25 03 pm" src="https://cloud.githubusercontent.com/assets/1450173/20579263/5baaf72c-b191-11e6-9271-cd1c0dbd2c73.png">
><img width="709" alt="screen shot 2016-11-23 at 3 26 33 pm" src="https://cloud.githubusercontent.com/assets/1450173/20579264/62e2042c-b191-11e6-820c-57d8f82663a8.png">

The EQS system shows all respondents and their penalties, whereas beta is only showing a single respondent (the one whose penalty amount was zero).

- **Civil Penalty / Fine amount by Cases** ❓ I am not sure how to find this

- _**Non-monetary terms** This mechanism does not visibly appear to be disabled for MURs, but, in actuality, it is not selectable when MURs alone are being searched. It only seems to be enabled for ADRs._

- **Document dates** ❓ I assume this refers to the dates for specific document types, when individual types are selected, but I am not sure.

**Comment by nickykrause** [comment]
Update: Meeting with @vrajmohan to discuss this later today.

**Comment by nickykrause** [comment]
Spoke with @vrajmohan. We're moving this assessment off of GitHub and into [this spreadsheet](https://docs.google.com/spreadsheets/d/1qpjMrOQrwuOYq8wpo6fq1_wo61CqpCrT-0LK6WwVQac/edit#gid=0), to make things easier. 

for now, the spreadsheet contains the following things:
- the name of the refinement mechanism in EQS
- the type of mechanism it is (free text, drop-down, etc.)
- a description of what the mechanism does
- My initial thoughts about transferring this functionality to the beta site
- The technical effort involved in adding the functionality to beta (to be completed by Vraj)
- The business benefit of including the field (to be filled in by me, after connecting with users about what makes the field useful)

**Comment by noahmanger** [comment]
Logging something that came out of our grooming session this morning: Jennie raised the user need to be able to search for a committee name and view all MURs and ADRs they had against them (which both contain the committee name as a field) as well as all fines levied against them. Fines don't have a discrete committee field, but do include the committee name in the title. Not sure how this figures into your process but wanted to capture it.

**Comment by nickykrause** [comment]
In speaking with Jennie and Jeff yesterday, we learned that the schemas for ADRs and AFs are the same as the ones used for MURs, although it is not the case that all case types will contain all the same information. The types of information available within an ADR will differ only slightly from the information available in a MUR, but the information available in an ADF is significantly different (and much less substantial).

In EQS, these differences are apparent when selecting MURs/ADRs/AFs as the "case type." Selecting AFs, for example, will visibly disable many of the advanced search mechanisms, and it will automatically set the "document type" filter to "administrative fine cases." However, it is not _always_ the case that the fields appear disabled: Sometimes they _look_ like they are available, when, in reality, they are not.

To keep track of the filters available across all the case types, I have updated the aforementioned [filter-tracking spreadsheet](https://docs.google.com/spreadsheets/d/1qpjMrOQrwuOYq8wpo6fq1_wo61CqpCrT-0LK6WwVQac/edit#gid=0) to show which filters are available for which case types.

**Comment by nickykrause** [comment]
The completion criteria for this issue were:

- 1:  [ ] Documentation around the schemas for ADR/AF/MUR data 
- 2: [ ] List of desired filters
- 3: [ ] Generate a set of issues for implementing filters: for the existing filters on the current site, what would the technical lift be to implement each of them?

Regarding item 2 -- creating a list of desired filters -- we have discussed that we should probably just plan to achieve parity with the existing EQS system, assuming that the technical lift of implementing the filters is not too great (see item 3). So, we tentatively have a list of desired filters, which appear in the [spreadsheet](https://docs.google.com/spreadsheets/d/1qpjMrOQrwuOYq8wpo6fq1_wo61CqpCrT-0LK6WwVQac/edit#gid=0).

I am not sure about the status of items 1 and 3: I will leave commentary on those to @vrajmohan 

Finally, regarding the user research plans that have been mentioned above: That exercise will inform more than just the approach to enforcement matters filtering, which is why the thread regarding this research idea appears in several different issues (including this one). 

Currently, I plan to track that research process and the results using this issue: https://github.com/18F/fec-testing/issues/16, where all the threads have been collected.

**Comment by vrajmohan** [comment]
Item 1 above (documentation around schema) is done - we had a meeting to discuss the schemas, where we were told that they were similar to MURs but simpler. A _cursory_ check of the actual DB confirmed this statement. We haven't actually documented anything, but, IMO, the objective of the task has been met.

Item3 (implementing filters) - the work to estimate the technical lift remains. It should be taken up at the start of the upcoming sprint.

**Comment by noahmanger** [comment]
Seeing that @vrajmohan has added estimates to the spreadsheet, is there anything else to do on this issue before closing? It seems like the next step is to go from that spreadsheet to actually grooming stories.

**Comment by nickykrause** [comment]
@noahmanger that seems right to me. The only other things I can think of are:

(a) addressing any questions that Vraj might have, because I think he had some in there 
and
(b) thinking about how the research which ended this morning (and which I'm currently synthesizing) will impact filter/feature prioritization

**Comment by noahmanger** [comment]
Great. I'm going to close this as those are two things we can discuss in grooming tomorrow.
