### ISSUE TITLE
Make it clear that only current MURs are available on beta site in first release

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1704]
We are releasing current MURs before archived MURs (both combined are the entire MUR universe) so that we can get them out sooner and start getting feedback. 

We need to make sure that users understand that they are not seeing results for archived MURs when they use the beta site, and so could possibly be missing information useful to their research. 

Possibly a content & UX task, I'm glad to take on the UX side because it looks like Nicky has a lot going on already.

cc @emileighoutlaw / @nickykrause

**Comment by nickykrause** [comment]
Sounds good to me - thanks Jen!

**Comment by emileighoutlaw** [comment]
Yep — this sounds like a great item for pairing. Would you want to look at this together sometime @jenniferthibault ?

**Comment by emileighoutlaw** [comment]
Okay! So with some complications, I think I see a path forward.

My understanding is that archived MURs are MURs that were originally published on microfilm between 1975 and 1998. There are non-archived MURs published during that same time, so we can't use chronology to differentiate between the two (which is a bummer). 

Ultimately, making clear exactly what and why and how the search is incomplete isn't necessary for our users. What they need to know is: _the search is incomplete_, and where to go to get any missing pieces. So I kept Jen's smart idea of an alert pattern and imagined what it could look like for the combined legal resources search results, the enforcement specific search results, and the enforcement landing:

![screen shot 2016-11-22 at 4 32 48 pm](https://cloud.githubusercontent.com/assets/10552702/20549829/7658492c-b0f5-11e6-80ac-aa113d1143ef.png)
_^^Combined legal search. Additionally, this updates the "Enforcement matters" heading to say "Matters Under Review," which is more technically correct (and will be until way down the line when we launch ADRs and Administrative Fines)_
.
.
.
.
![screen shot 2016-11-22 at 8 29 53 pm](https://cloud.githubusercontent.com/assets/10552702/20549847/9d68903a-b0f5-11e6-9050-11160cc18b2e.png)
_^^MUR-specific search. This also updates the "Enforcement matters" heading to say "Matters Under Review," which is more technically correct (and will be until way down the line when we launch ADRs and Administrative Fines)_
.
.
.
.
![screen shot 2016-11-22 at 8 32 03 pm](https://cloud.githubusercontent.com/assets/10552702/20549868/baab88d2-b0f5-11e6-8a05-c5a738ac7627.png)
_^^Enforcement landing. This lacks the call to action of "visit FEC.gov" that the others have, but in this instance, that feels okay to me._


So that's my jumping off point. Thoughts?

**Comment by jenniferthibault** [comment]
I was able to figure some of this out! Check out this work in progress PR: https://github.com/18F/openFEC-web-app/pull/1707 where I've showed screenshots of what I could implement, and asked for help where I got a little stuck.

I wanted to get this in as a PR because I'll be out Weds–Fri, and wanted it to be easy for someone else to pick up.

**Comment by noahmanger** [comment]
Resolved by #1707
