### ISSUE TITLE
Design display of amendments for filings

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1715]
In order for users to understand both (1) what the most recent version of a filing is and (2) which previous filing an amendment is amending, we need to design a way to show these relationships and states. 

---

On both the [filings page](https://beta.fec.gov/data/filings), [reports pages](https://beta.fec.gov/data/reports/presidential/), and committee pages ([e.g.](https://beta.fec.gov/data/committee/C00577130/?tab=filings)), we need a way to do the following:

1. If a filing has been amended, show:
    - The fact that it has been amended, both in the table columns and in the details panel
    - Link to the final version

2. If a filing has amended another, show:
    - Link to the previous version of this filing 

3. If a filing is the most recent, unamended report, show it as such

---

**Completion criteria:**
- [ ] Design interaction / UX 
- [ ] Visual designs for each of the scenarios above

cc @jenniferthibault @nickykrause

**Comment by jontours** [comment]
Initial prototyped work for this is starting to form, in the issue (https://github.com/18F/openFEC/issues/2073) a current version of how the amendments can be chained together.  We will probably need to formulate what the links should be, but the relation is defined, at least for electronic filings.

**Comment by jenniferthibault** [comment]
I think this is more about how it works than how it's styled, so I'd like to insert "UX/interaction prototypes" ahead of visual designs in the criteria of this issue. 
It will need both, but I don't think it's primarily about styling.

**Comment by noahmanger** [comment]
Good call. Just added a bullet.

**Comment by noahmanger** [comment]
Ok, I have something to throw out for target practice here. For starters, I have proposed language for what we call the various states of a filing (cc @emileighoutlaw ). 

Basically we always want to keep track of:
- 1. Document type: If a filing was an original (i.e. the first iteration of a) filing vs. an amendment
- 2. Amended state: If it ha been amended or if it is the latest version

Here's how that could work in a the filings table: 
![image](https://cloud.githubusercontent.com/assets/1696495/20950743/60b2487a-bbd6-11e6-9a27-1ff7cd959f99.png)

And then when you open a filing's details panel, we would show the document type, the amended state and the entire history of amendments for that filing:

![image](https://cloud.githubusercontent.com/assets/1696495/20950811/c8b859d2-bbd6-11e6-9cc8-94a8c5473527.png)

For more details of how the details panel flow works, I put several stages [into an InVision prototype.](https://gsa.invisionapp.com/share/Y59MPNTP7#/210070767_Step_4_-_Latest_Amendment)

The visual design / icons / etc. are all just rough suggestions. I think _some_ sort of icons here would be helpful. Not sure if there's a universally understood symbol for when something has changed, but I thought a triangle/delta might be a start.

Last, regarding what things link to, this is currently a little challenging because we don't have a way to link to a specific filing in the table, and they don't currently have pages. So the only option as far as I see it is to include a link to a certain view of that filing, whether that's a PDF, CSV, .fec file or what have you. But maybe @LindsayYoung has a different understanding.

Ok. Curious what you think @jenniferthibault @nickykrause !

**Comment by nickykrause** [comment]
so fast, @noahmanger! like lightning! ⚡️

 Here are some thoughts: 

I love the revision history, and I agree with highlighting the version you're currently on (which you've done in bold) -- so that it shows what's after and what has come before (rather than just stopping the history with the file that you're on). 

I also really think it will be important to have icons of some kind, or something that makes it easy to scan the table more easily, in search of the "latest" files. The delta makes sense to me, but I'm not sure about the check mark. Perhaps it reads to much like "selected" for me. My first thought for another possible icon was something that conveys time - like "latest" - but that may be ambiguous. I will keep thinking.

One thing that I found a bit confusing was the phrasing for "previous amendment" vs "latest amendment." When looking at the details panel, it is clearer what this means, but when it is listed in the table, I thought I was reading it incorrectly because it felt redundant. The icon for the check mark was already saying "this is the latest thing," and the delta was saying "this thing has been changed," so then I thought maybe a "previous filing" was a thing in itself. I am not sure if that makes sense, but I wonder if it is sufficient to just say "[delta] Amendment" when it is a "previous amendment"? I am curious what others think here, because I also see an argument that including both the word and the icon serves to reinforce the concept we're trying to communicate.

Last thing: I am wondering how this column would sort (assuming all the columns are meant to sort?), given that it combines two types of information about the filing: the type and the status. Maybe it would put anything "latest" at the top, with amendments ranking higher than original files? I  have no idea if this is something users would even want to do, but I wasn't sure. 

Similarly, as a broader question: When we add columns like this, do we also typically add filtering mechanisms in the filter panel? (Meaning: Would users be able to filter the data table to show only original filings?)

**Comment by jenniferthibault** [comment]
What would be the scenario that would even cause a "🔺 Previous amendment" to show up in the table? It feels like if it recognizes there is a later amendment, it ought to be showing that, and thus " 🔴 Latest amendment"  . 

I have the same type of confusion about the two types of original filings — If the system knows there is a later document, enough so that it labels it with an amended icon, why would it not show that latest document instead of the "original"?

<img width="122" alt="screen shot 2016-12-07 at 9 49 49 am" src="https://cloud.githubusercontent.com/assets/11636908/20972469/e7789c4c-bc62-11e6-9c30-b2d6dfc43cdf.png">

<img width="113" alt="screen shot 2016-12-07 at 9 49 55 am" src="https://cloud.githubusercontent.com/assets/11636908/20972470/e7792a4a-bc62-11e6-8fc2-3d02977cc1d6.png">


The Amendment History timeline feels super smart to me 👍 

Would the `CSV` | `PDF` bits be linked?

<img width="266" alt="screen shot 2016-12-07 at 9 55 40 am" src="https://cloud.githubusercontent.com/assets/11636908/20972613/691b6266-bc63-11e6-939f-94bd9b6b304b.png">

+1 to @nickykrause 's observation that the amendment language and concepts are a bit opaque to the unititiated. How might we be able to include either glossary terms or possibly relabel some of the "amendment"-y terms to be more plain language? (maybe a question for @emileighoutlaw at a later stage)

**Comment by noahmanger** [comment]
Good questions and observations. It's a super tricky concept 😖 

To @jenniferthibault 's first questions: the system will always retain and make available _all_ versions of a filing (in this case, the 2014 Year-end report). You're right that more often than not, what you want is the latest, unamended version of a report, but for research purposes you also need to be able to get to the previous versions. Those previous versions could include the now-amended original or a previous amendment. 

So the goals of this UI are:
- Communicate the status of this specific document: has it been amended or is it the latest version?
- Communicate the type of this specific document: is it the first version (i.e. original) of a filing or is it an amendment to an original?
- Nudge people towards the latest version for the most up-to-date info
- Allow people to navigate back in time to previous versions

To @nickykrause 's point about language, this observation is the crux of it to me:

> I wonder if it is sufficient to just say "[delta] Amendment" when it is a "previous amendment"? I am curious what others think here, because I also see an argument that including both the word and the icon serves to reinforce the concept we're trying to communicate.

I see how it could clarify things to always just make the **type** property a binary: calling it an `original` vs. an `amendment` and then having the **status** property a binary that's communicated through the icon: ✅  vs. 🔺 . But yeah, I really don't know what's best. 

Also, yes, the PDF / CSV text are meant to be links. They just lost their underline.

**Comment by noahmanger** [comment]
Oh, and to your question about sorting... I'm not sure. But for filtering, both the status and type should be filterable.

**Comment by emileighoutlaw** [comment]
To Noah's great point about what we're trying to track: 
> - Document type: If a filing was an original (i.e. the first iteration of a) filing vs. an amendment
> - Amended state: If it has been amended or if it is the latest version

I'd like to further hone the second point to:

> - State: Is this thing (be it an original filing or an amendment) the most _up to date_ thing, or is it an _outdated_ thing?

With that in mind, for _State_: I like something more along the lines of

> 💚  Current version
> 🔺 Outdated version

Because, ultimately, what folks are trying to identify is "Is this the most recent thing or not the most recent thing?"

For _Amended state_: In general, I try to avoid terms like "Previous" and "Next," because they can be temporally confusing to readers. 

_(For example, think of navigating through a blog archive: Does the "previous" link take you to the older (previously published) thing, or is it the more recent (previously viewed) thing? It could really be either, depending on the context.)_

In my experience, context clues, like dates are the most valuable thing. I think we could consider categorizing things as either `Filing` or `Amended filing`. 

In the table that would look like this:
> 💚  Filing
> 🔺 Filing

or

> 💚  Amended filing
> 🔺 Amended filing


In a history view, it would look like this:

> **Filing history**

> 💚  Amended filing
3/1/2016

> 🔺 Amended filing
6/1/2015

> 🔺 Amended filing
1/1/2015

> 🔺 Filing
12/24/2014

**Comment by noahmanger** [comment]
Good honing. I agree that the "current" vs "outdated" distinction is basically what we're going for. I'm not sure that that's the right language, though I can't put my finger on it. I agree that anything like "latest" or "previous" isn't great.

I agree less about "filing" and "amended filing". "Amended filing" also sounds like "this specific instance of the filing has been amended" as well as "this is an amended version of a previous, original filing". I think calling them "amendments" is clearer in this front, and I believe is also the language the FEC uses elsewhere.

**Comment by emileighoutlaw** [comment]
Ahhhh, I see what you're saying! So the correct thing to convey is:

> This is an amended version of a previous, original filing

? yes? And, if so, is `Filing amendment` possibly more clear than `Amendment` or `Amended filing`? 

What I'm wondering is:

1. If we have a `Filing` option and an `Amendment` option, it might create a false dichotomy. (i.e., when they don't share the word _filing_, an `Amendment` seems like it might be an unrelated, specific thing: not a `Filing` but instead an `Amendment`). I was hoping that by finding a way to include "filing," we could help users draw the connection between the two. 

1. If I have something called `💚 Original filing`, even though the icon shows that it's current, the word _original_, makes me feel the thing I'm looking at is the _beginning_ of the thing (and thus wonder where the end of the thing is?)

**Comment by LindsayYoung** [comment]
I love the detail panel. That might require some extra data work but it is so great.

I wonder if we could simplify the list by adding the "is an amendment" logic to the doc name and "amended" or  on the filing status part.


filer | document | amendment status | date
---|---|---|---|
name | march quarterly | amended | jan 30
name | march quarterly (amendment) | latest filing | feb 1

**Comment by jenniferthibault** [comment]
I have the same two confusion points as @emileighoutlaw . Not a helpful comment, but a +1 for clarification please :)

Sorry, this has always been a confusing area with opaque words to me!

**Comment by noahmanger** [comment]
@emileighoutlaw I think I like the "Filing amendment" term. Here's how that could look:

![image](https://cloud.githubusercontent.com/assets/1696495/20999994/110889fe-bccd-11e6-9e96-9c22509edc7c.png)

And here's how that would look in the table:

![image](https://cloud.githubusercontent.com/assets/1696495/21000032/4cea496c-bccd-11e6-8906-91159c31036b.png)

@LindsayYoung 's idea is interesting. Basically showing the _document type_ (first version vs a amendment version) in the document column and _status_ in the separate column. Here's how that would look:

![image](https://cloud.githubusercontent.com/assets/1696495/21000038/56c372e2-bccd-11e6-835e-6a0629d05682.png)

Happy to discuss this synchronously too. I'm going to show it to my critique group on Thursday as well.

**Comment by jenniferthibault** [comment]
I would appreciate a synchronous discussion before I start refining icons for this. 

Seeing @LindsayYoung 's breakdown in Noah's mockup makes it more clear to me which item in the table is "an amendment" but I'm still confused how items like this....

<img width="672" alt="screen shot 2016-12-08 at 9 30 11 am" src="https://cloud.githubusercontent.com/assets/11636908/21013655/ef0ae0fc-bd28-11e6-9334-548afa3ea4a2.png">

have a status of "amended versions" but aren't themselves amendments. 

I don't like throwing out unhelpful points of confusion without being able to offer constructive feedback on how to improve, but I just don't understand enough here to do so, really sorry!

**Comment by jenniferthibault** [comment]
Restating that question a different way: what's the difference between these two items in the table?

<img width="678" alt="screen shot 2016-12-08 at 9 32 09 am" src="https://cloud.githubusercontent.com/assets/11636908/21013764/42d7bde0-bd29-11e6-8128-9ca0830a1c87.png">

**Comment by jontours** [comment]
Also just thought I'd mention that some of the chain's had depths up to 11, that's for Presidential filings.  There is certainly the case to believe that the filings tree can get deeper than that.  Something to keep in mind.

**Comment by emileighoutlaw** [comment]
To my ear "Current version" and "Outdated version" felt good as one-word descriptions. But I trust that if Noah, Nicky, and Jen all feel it isn't quite right then, well, it isn't quite right. 😃 

I'm going to add my notes (from when I was drafting content options yesterday) below. Perhaps something in them will be helpful to Noah as he keeps designing. Let me know if I can work on more options or help out in another way with content. 


> Status:
💚 Current version
🔺 Outdated version

> Status:
💚 Up to date
🔺 Out of date

> Status:
💚 Current version
🔺 Past version

> Status:
💚 Current
🔺 Not current (has been amended)

**Comment by noahmanger** [comment]
Re: language, can @PaulClark2 @AmyKort or @jwchumley weigh in? The question on the table is: is there a better term we can use for filing that have been amended vs those that haven't been amended? Emileigh's suggestions above area few different passes. 

The problem we're trying to solve for is that calling something an "Amended filing" is ambiguous as to whether the filing itself is an amendment or if it has been amended by a more recent version. We want to allow users to clearly understand if the information they're looking at is the most recent, up-to-date. But I imagine there's some term-of-art issues here too and I don't want to introduce brand new language that might confuse power users.

**Comment by AmyKort** [comment]
This is tricky. @PaulClark2 and @jwchumley know much more about this than I do.

Terms of art: On the forms and in the guides, we refer to the first filing as the "original report." An amendment is called an "amendment." The amendment is made to a "previous report" in cases where there is more than one amendment.

Based on that, I'm partial to Noah's mock up from three days ago. Unamended v Amended and Latest Amendment, Original Filing and Previous Amendment.

I'm not sure I understand the distinction you are making between an "amended filing" and the "amendment." The amended filing is the amendment. Is this just for efilings? In that case, the Latest Amendment is the amended version of the report. For paper filings, if I'm understanding this right, we would not necessarily link to a version of the entire report again, but just the amended portions, which is all the filer is required to submit. In that case, I think Latest Amendment is more accurate than Filing Amendment.

I also liked Noah's version of 3 days ago because it appeared to me to not presuppose that every filing would be followed by a series of amendments. I think the default is for the original filing to be the only filing, although there are many cases where we require committees as a matter of course to amend their reports. I'm looking at page 100 of the candidate guide for reference.

Paul and Jeff--jump in and correct my many inaccuracies.

**Comment by PaulClark2** [comment]
I agree with the above comments, "Previous amendment" is unclear to me. It helped to to look a amendment chains of one committee.

There are four (4) document types / statuses we need to convey:

- Original not amended
- Original has been amended
- Amendment has been amended
- Amendment most recent version

It seems to be we need four (4) icons to convey this information. @emileighoutlaw @AmyKort can probably think of more concise descriptions than the four I have above. But, these are the 4 states we need to describe.


Filer name	|	Report	|	Document type / status	|	Receipt date
----	|	----	|	----	|	----
NRSC	|	April Monthly	|	Original not amended	|	4/18/2014
NRSC	|	May Monthly	|	Original not amended	|	5/20/2014
NRSC	|	June Monthly	|	Original has been amended	|	6/20/2014
NRSC	|	June Monthly	|	Amendment has been amended	|	7/24/2014
NRSC	|	June Monthly	|	Amendment has been amended	|	8/19/2014
NRSC	|	June Monthly	|	Amendment most recent version	|	10/8/2014
NRSC	|	July Monthly	|	Original has been amended	|	7/18/2014
NRSC	|	July Monthly	|	Amendment most recent version	|	7/24/2014
NRSC	|	August Monthly	|	Original not amended	|	8/20/2014
NRSC	|	September Monthly	|	Original has been amended	|	9/19/2014
NRSC	|	September Monthly	|	Amendment has been amended	|	9/29/2014
NRSC	|	September Monthly	|	Amendment most recent version	|	3/3/2015
NRSC	|	October Monthly	|	Original not amended	|	10/17/2014
NRSC	|	Pre-General	|	Original has been amended	|	10/23/2014
NRSC	|	Pre-General	|	Amendment most recent version	|	10/31/2014
NRSC	|	Post-General	|	Original not amended	|	12/4/2014
NRSC	|	Year-End	|	Original has been amended	|	1/30/2015
NRSC	|	Year-End	|	Amendment most recent version	|	2/10/2015

**Comment by PaulClark2** [comment]
I also like Noah's mock up from 3 days ago (https://github.com/18F/openFEC-web-app/issues/1715#issuecomment-265325463) .   If folks agree with my comment above, we'd need to work out 4 filing statuses / states / types and icons that convey the 4 types I identified above.

**Comment by PaulClark2** [comment]
@noahmanger I really like the entire amendment chain (amendment history) in the details panel.

**Comment by noahmanger** [comment]
As far as the four states, what I was proposing was to just use an icon to represent the _amended state_ , whether something has not been amended or not, which would be applied to both originals and amendments. Would that work?

Slightly separate question (in service of the bigger question): I know that users need to filter to be able to find the most recent version of a report (e.g. by _amended state_). Do they also need to be able to filter down to see _only_ original reports or _only_ amendments?

**Comment by PaulClark2** [comment]
Question 1: 
I'm not sure it does. It seems to me to leave the user uncertain about the filing if the filing state is _amended_. Am I in the middle of an amendment chain or are the end of the amendment chain? If we aren't going to clearly identify all four states in the filings table, an alternative might make more sense. What if we mark with an icon only those filings that have not been amended? So, original filings that have not been amended and amendments that are the last filing in an amendment chain would have a "most recent filing" icon. I can probably be convinced your approach will work for users. 

I'm curious what @ChristianHilland thoughts are about this.

Question 2:
The most common query will be for the most recent filing. Users with specific needs will want to see the original and the entire amendment chain. The sort order @jwchumley mentioned earlier this week would be very helpful for these types of users.

**Comment by noahmanger** [comment]
@PaulClark2 I _think_ we're saying the same thing here. Every document basically falls somewhere in this 2x2 matrix: 

| | Most recent version | Previous, out of date version |
|-------|-------|-------|
| Original filing |  |  |
| Amendment |  |  |

Take this option:
![table](https://cloud.githubusercontent.com/assets/1696495/21000038/56c372e2-bccd-11e6-835e-6a0629d05682.png)

In the "Document" column, we denote an original filing from an amendment by adding "(Amendment)" to the document title. 

And then we use "Document status" column to basically do what you said here:
> What if we mark with an icon only those filings that have not been amended? So, original filings that have not been amended and amendments that are the last filing in an amendment chain would have a "most recent filing" icon.

The icon + word "latest version" or "amended version" could be applied to original filings or amendments. 

This is definitely turning into a bit of word salad at this point, and I think we're all basically proposing the same thing, so if it'd be easier to chat on the phone Monday we should probably do that.

**Comment by emileighoutlaw** [comment]
Not sure if y'all got a chance to talk about this yesterday. I'm definitely on board with this approach and want to keep helping out with content (apologies for my absence!)

If I'm understanding the latest design correctly, we're using two versions of the word "amend" in two places to describe two different things:
- `Amendment` (i.e., an amended filing, aka not an original filing)
- `Amended version` (i.e., a version that is now out of date; can be either an out-of-date original or an out-of-date amendment)

For reader comprehension, I strongly recommend that we don't use the same word to describe two different things. 

Are we all in agreement none of `Outdated version`, `Out-of-date version`, or `Past version` _won't work_ in this situation?

**Comment by ChristianHilland** [comment]
Perhaps something along these lines?

![amendments](https://cloud.githubusercontent.com/assets/16327334/21187672/d2ea5994-c1e6-11e6-8644-3b21b50388ec.JPG)

**Comment by noahmanger** [comment]
Seeing @ChristianHilland 's screenshot above, I think "most recent version" works well. I also really like specifying the amendment number (Amendment 1, Amendment 2, etc.), as I think it further reinforces the concept that a document can be amended over and over.

As for including the link to the most recent version in the table, I tend to think that we should only include the links to the actual record (whether it's the most recent version or not) in the table. To access most recent versions, users will be able to either:
- Filter to only "most recent versions"
- Find a link to download the most recent version in the details panel,
- Or, depending on their view, see the most recent version in the same table, designated with an icon / wording

Here's my updated proposal:
![image](https://cloud.githubusercontent.com/assets/1696495/21201571/4caa356a-c200-11e6-8a5b-828b2bedc7be.png)

![image](https://cloud.githubusercontent.com/assets/1696495/21201574/4f7078a4-c200-11e6-8731-446f6b0425a2.png)

**Comment by emileighoutlaw** [comment]
I think that looks fantastic. Gets a big content design thumbs up from me.

**Comment by AmyKort** [comment]
I like it too. Thank you!

**Comment by PaulClark2** [comment]
I like it!   Thanks!

**Comment by jenniferthibault** [comment]
Now that the logic is 👍 , I have some small fine-tuning design tweaks:

- New icons: specific subjects for each that are a bit more complex than symbol shapes, and use more outlines than fills to call slightly less attention. Bright color only assigned to the "Most recent version" for easier scanning 
- Since all instances of the icons appear with the "Most recent version" / "Past version" text, we don't need a key in the table.
- Moving the "Version history" info text that would have been in a tooltip to a paragraph below the headline. I'm not sure if we know what this text will be, but it seems like it wouldn't need to be hidden
- The pink circles just flag areas where @emileighoutlaw and I made the dates follow consistent format guidelines, and should be adjusted to match these mockups during implementation


![screen shot 2016-12-15 at 12 19 11 pm](https://cloud.githubusercontent.com/assets/11636908/21234683/a22ce0c0-c2c1-11e6-9484-8786a018672b.png)
![screen shot 2016-12-15 at 12 19 31 pm](https://cloud.githubusercontent.com/assets/11636908/21234682/a2257574-c2c1-11e6-8d99-794d26c9d7df.png)

**Comment by noahmanger** [comment]
Great stuff! Thank you. Closing in favor if implementation task https://github.com/18F/openFEC-web-app/issues/1738

@jenniferthibault can you add the icons to that issue when you have the chance?
