### ISSUE TITLE
Design ADR and AF pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1737]
So that legal researchers can view the details about an ADR or AF case, present all case information on a single case page. 

---

This is a design issue to design the pages for Alternate Dispute Resolution cases and Administrative Fines. Both of these case types are structured similarly to MURs, so this can be an adaptation of the MUR designs.

**Completion criteria:**
- [ ] Design for ADR page ready for implementation
- [ ] Design for AF page ready for implementation

**Comment by nickykrause** [comment]
The ADRs are structured very similarly to the MURs, except that the options for `document type` are different, as are the options for `final commission disposition`.

That said, the case page for an ADR can closely follow the pattern for a MUR case page, and it would look like this (displaying content for actual ADR 760):

![adr_760](https://cloud.githubusercontent.com/assets/1450173/21437224/3c86d730-c848-11e6-91d0-1a72ea9b6aa1.png)

One concern I have with this design, which is directly patterned off our MUR design, is that it carries over [a known design issue that we have for the display of `Disposition`](https://github.com/18F/fec-eregs/issues/294) within the `Summary` section on the MUR case pages.

Ideally, we could resolve that issue in conjunction with implementing an ADR design, so that it would fixed for both MURs and ADRs. @noahmanger: Do you think that's possible, given our current sprint/quarter priorities? I'm happy to chat about the linked issue, if you are not familiar with it.

**Comment by nickykrause** [comment]
One more thing: We don't have much (if any) user research to suggest what aspects of the ADR would be most helpful to surface on the case page, so it'll be wise to review this ADR page with the appropriate user group in usability testing.

**Comment by nickykrause** [comment]
After talking with @jenniferthibault and @noahmanger, we are in agreement that it makes sense to remove the `Disposition` from the `Summary` on the MUR canonical pages until we have identified a better source for that information. See https://github.com/18F/fec-eregs/issues/325, which builds on https://github.com/18F/fec-eregs/issues/325

Given that decision, I have updated my mockup for the possible ADR canonical page to assume that it _also_ excludes the `Disposition` from the `Summary`, which results in the following display:

![adr_no_disposition](https://cloud.githubusercontent.com/assets/1450173/21504343/a622145a-cc23-11e6-9360-334da0a8e333.png)

**Comment by nickykrause** [comment]
@jenniferthibault @noahmanger 

Here is a design for the AF canonical page:

![af1](https://cloud.githubusercontent.com/assets/1450173/21528283/11f4db76-ccf7-11e6-914a-303548cad18f.png)

Some things to note here:
- This is an adaptation of the existing pattern for MURs
- The AFs contain more limited information than other enforcement matters. 
- Most of the information within them seems to be details about the penalty (amount and how/if it was paid), as well as dates for various events
- There is only one document per AF, which is why I have listed it as a button within the `Summary`, instead of as its own table
- Knowing that we are encountering some concerns about removing the `Disposition` from the `Summary` for MURs, I have taken a stab at handling that information for AFs, under the `Votes` heading. I am not sure if this approach would work for ADRs and MURs as well, but AFs seem to have the benefit of involving only one "Commission Action" and one set of votes (as compared to some of the MURs, which can have many). 

I am wondering: 
- Do you have any concerns with this layout?
- Does the new `Votes` section seem logical/workable to you, at least for AFs?
    - If it seems logical/workable for AFs, then I think we should try including some version of it for MURs and ADRs. This would help with consistency and could address the problem of removing the `Disposition` from the `Summary` of MURs.

**Comment by nickykrause** [comment]
For reference, here is what the ADR that I mocked up previously would look like if we took the `Disposition` information out of the `Summary` and instead it included as a `Votes` section (this is the actual ADR content):

![adr_votes](https://cloud.githubusercontent.com/assets/1450173/21528742/4f3efa04-ccfa-11e6-94fc-7595a3f6ae20.png)

**Comment by noahmanger** [comment]
These are great. I like pulling out the votes information into its own thing. After seeing how the current system shows the votes, it seems like it would be a better alternative to the way we show the disposition. I wonder if the votes should be the first section after the basic info?

**Comment by jenniferthibault** [comment]
Layout largely 👍 to me, hooray for template patterns!

One thing I'm wondering (fresh from a deep dive into our citation patterns [in this issue](https://github.com/18F/openFEC-web-app/issues/1736#issuecomment-269565852) ) is if we need to accommodate any citation lists for these documents? I don't know much about alternative dispute resolutions or administrative fines, but hoping you might by now @nickykrause 😀 

Looking at these as a whole, one category sticks out like a sore, jargony thumb to me as someone who doesn't have a detailed understanding of this subject matter: on the Administrative Fines page, the **Dates** section

<img width="881" alt="screen shot 2016-12-28 at 8 16 58 pm" src="https://cloud.githubusercontent.com/assets/11636908/21534820/adb2c6c0-cd3a-11e6-9409-5a8f3dc8b47d.png">


Do users think of "dates" as a section or category of its own, or are dates more closely associated to documents? If "Dates" = "History" would a pattern more close to the Amendment activity timeline be more like what we're looking for? I don't want to keep throwing out solutions that may be ill-fitting because I don't have enough context to what Dates actually means to users here!
<img width="484" alt="screen shot 2016-12-28 at 8 20 09 pm" src="https://cloud.githubusercontent.com/assets/11636908/21534850/0edcd814-cd3b-11e6-99f9-2ffe67ea296f.png">

**Comment by noahmanger** [comment]
I think a timeline view would be interesting. Curious what people more familiar with the data think though.

**Comment by nickykrause** [comment]
Okay, setting aside commentary on (a) the possible inconsistency of this AF page with other legal resource pages, and (b) the outstanding questions about how to format citations, I am posting the below AF design for @jenniferthibault's  👀  

All I am trying to solve for, at the moment, is the weirdness of the `Dates` section. I don't have any more user insights than I had before, but I did some reading about the Administrative Fine process that might help.

After the Commission finds a "Reason to Believe" (RTB) that a violation occurred, the respondent (the alleged violator) has a chance to "challenge" the RTB finding. Then, later, the Commission makes its final determination about the violation, and the respondent now has a chance to "petition" the final determination. However, it seems as though respondents can only file a "petition" with the courts if they also filed a "challenge" earlier on:

> Within 30 days of its receipt of the final determination letter, the committee and its treasurer can file suit in the U.S. District Court in which the committee or treasurer resides or does business.  Note that the failure to raise an argument in the administrative (challenge) process in a timely manner is deemed a waiver of the committee’s or treasurer’s right to present that argument to the District Court.  Please see 11 CFR 111.38.  _(Quoted from [here](http://www.fec.gov/pages/brochures/admin_fines.shtml))_

All this is to say that "Challenges" and "Petitions" are the terms EQS uses to describe the two processes by which respondents attempt to resist the Commission's decisions. However, the EQS system does not seem to discretely offer any information about these processes other than the `Challenge Date`, the `Petition Court Filing Date` and the `Petition Court Decision`. So, there are no "Challenge" or "Petition" documents to include.

Given that the Challenges and Petitions are a unique part of the process, I am thinking we could break them out into their own section, rather than jumbling together a bunch of dates:

![af_v2](https://cloud.githubusercontent.com/assets/1450173/21555416/933fbcb4-cddd-11e6-83e3-78ece27fa46b.png)

**Comment by nickykrause** [comment]
Also ^^ cc @emileighoutlaw, if you have time/thoughts

**Comment by nickykrause** [comment]
@noahmanger: Although we have draft designs of ADR and AF pages, we have open questions about how these pages should be structured, relative to other canonical pages. 

So, I think we should close this issue in favor of https://github.com/18F/fec-eregs/issues/326, where we can look at the canonical page designs relative to each other. Thoughts?
