### ISSUE TITLE
Compile research and feedback around candidate and committee pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1765]
The time has come: we're finally ready to tackle a bunch of the interrelated UX challenges around the candidate and committee pages. This is a big, complex design task, the first part of which is (I believe) to synthesize all the existing research, usability findings and feedback that we've received on these pages. This data lives in a few places:

- As issues submitted via the feedback tool, labeled [candidate-page](https://github.com/18f/fec/issues?q=is%3Aopen+is%3Aissue+label%3A%22theme%3A+candidate-page%22) and [committee-page](https://github.com/18f/fec/issues?q=is%3Aopen+is%3Aissue+label%3A%22theme%3A+committee-page%22)
- As feedback collected from the FEC, which lives in this repo under the labels [candidate page](https://github.com/18F/openFEC-web-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22Theme%3A+Candidate+page%22) and [committee page](https://github.com/18F/openFEC-web-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22Theme%3A+Committee+page%22)
- As usability / user research in [Drive](https://drive.google.com/drive/u/0/folders/0B_D8iMs9xIXzfkotVlpYZjRmMUN0Tmo5THBiaWdwYXYxYktmcDZER2ZqcUg5UG13eUkyQmc) (maybe additional folders as well)

Let's start by combing through this stuff to create a concise list of needs and challenges, and then plan next steps from there.

cc @nickykrause @jenniferthibault (and @onezerojeremy just because I think it might make you happy to know we're doing this).

**Comment by nickykrause** [comment]
Short update: 
Met this morning with Jeremy/Emileigh. Meeting this afternoon with Noah. 

I need some flow-state time to dive into the usability testing synthesis reports; I will do that tonight after my meetings marathon today. 

My goal is to share something asynchronously with the team on Friday. I scheduled time to connect about C&C stuff synchronously for Monday, which looked to be the first time we'd all be available.

**Comment by nickykrause** [comment]
cc: @noahmanger @jenniferthibault @emileighoutlaw @onezerojeremy 

Okay, I ended up behind schedule (soooo many meetings at the end of last week), so I tried to catch up today. Here is what I have so far as a list of themes from the research/GitHub issues, as well as some of the challenges associated with each:

https://docs.google.com/document/d/1q_f910WsByM_3xEh92PQbIGzSWqR4qpetSQqa66Pzpg/edit#

One issue I have encountered while doing this is my own ignorance of the shape of the data. Some of the things that the users find confusing are things that I also find confusing, so I sometimes had trouble following what they were talking about (in the interview transcripts). I found myself clicking through the data constantly just to educate myself about what the beta site offers. Confronting my learning curve was more time-consuming than I expected.  Anyway, I hope I have captured things in a way that makes sense to you all and that is consistent with your memories of what users have struggled with. 

**Please please feel free to add your thoughts to the document!** There is more to react to now than we I spoke with you last week, so I assume that additional, exciting thing will pop into your brains as you review this. Also, of course, feel free to disagree with me about my interpretations.

Last thing: In some cases, I have linked to existing GitHub issues as examples of a theme, but I have not listed out _every_ GitHub issue that we have, because it seemed like a redundant exercise. 

Ok! We have time tomorrow to sync about this stuff, so we'll talk then, if not through the doc itself

**Comment by noahmanger** [comment]
We now have design issues and a great research doc, so I'm closing this. Nice work!

**Comment by nickykrause** [comment]
Great - thanks!
