### ISSUE TITLE
Review HTML titles for usefulness and SEO

### ISSUE THREAD

**Issue by dogweather** [18F/openFEC-web-app#1774]
I've found several `<title>`s  which are pretty terse and could be edited to be more helpful to potential site visitors. This is because titles are a major part of SERPs as well as how pages appear in a person's browser history.   E.g.:

[Spending Breakdown | FEC](https://beta.fec.gov/data/spending/) — even just the addition of the word "Campaign" to the front would help inform a person's decision whether to visit the page.

Compare to this page's title, which gives the potential viewer enough knowledge to know whether to click:

[Browse Presidential committee reports | FEC](http://localhost:3000/reports/presidential/?data_type=processed&is_amended=false) — (in the current develop branch).

Another example is the home page:

![screen shot 2017-01-03 at 7 25 05 pm](https://cloud.githubusercontent.com/assets/150670/21630910/625e9c3a-d1ea-11e6-8a6f-90f7463253e7.png)

Compare to descriptive and friendlier USDA:

![screen shot 2017-01-03 at 7 26 33 pm](https://cloud.githubusercontent.com/assets/150670/21630930/943d37a2-d1ea-11e6-9522-4de4c005c111.png)

**Comment by dogweather** [comment]
I just noticed that the home page's HTML `<description>` will need to be updated when we switch over. Let's add an issue for that if it's not already on a checklist somewhere.

**Comment by emileighoutlaw** [comment]
Hooray for fresh eyes!  Love the idea of updating these. For the homepage, were you thinking 

> **Federal Election Commission**

Or something more than that?

The spending breakdown title is a tricky, sticky wicket. I'd love to borrow your brainpower to think through this with me, @dogweather!

**Comment by emileighoutlaw** [comment]
### Spending
I fear that using the word "Campaign" may be a little misleading (i.e., lead users to believe they're looking at just campaigns' spending, when really the chart accounts for lots of different types of groups and spending).

What do you think about something more like:

> Spending in federal elections

or 

> Federal election spending

(My concern about the second one is that content-wise it's just Federal Election Commission with the last word swapped out.)

### Home
We've really struggled to write something both concise and descriptive for the FEC. There are a ton of words that are sticky wickets for the agency (including, for example "regulation"). 

In the past we've toyed with stuff like:

> U.S. Federal Election Commission | Campaign finance for everyone

But I'm not sure that actually contains much helpful information. Something like:

> U.S. Federal Election Commission | Campaign finance data, law and information
 
is more in line with the way we've been explaining the three big buckets of stuff on the website. So maybe that's headed more in the right direction? What do you think?

Also, we've been using the pipe instead of a dash thus far; any reason we shouldn't continue that?


Thanks for helping me think through this @dogweather !

**Comment by noahmanger** [comment]
@emileighoutlaw I know you're going to be looking at this. Not to add extra work, but just FYI: it's also easy to add custom meta descriptions to pages via Wagtail, which can help for SEO (both public and with our own site search).

**Comment by emileighoutlaw** [comment]
I never had a chance to get to this, but it's something I _do_ think we should look at in the future. 💟
