### ISSUE TITLE
PageSpeed is 63/100 Mobile and 67/100 Desktop

### ISSUE THREAD

**Issue by dogweather** [18F/openFEC-web-app#1775]
[PageSpeed Insights report for beta.fec.gov.](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fbeta.fec.gov%2F&tab=mobile)

Make the recommended changes to bring the score into the "Passing" zone, such as:

- [ ] Enable compression
- [ ] Optimize images
- [ ] Leverage browser caching

**Comment by noahmanger** [comment]
I spent some time looking into this and have a few findings, but will need help addressing.

First of all, there's slightly different issues for the CMS vs web app. For the CMS:
- We need to enable gzip compression for SVGs. It's apparently not an issue for other static assets, but is for these.
- We need to enable browser caching for static resources

For the web app:
- Enable browser caching of static resources
- Minify JS and CSS

I'm confused by the minify one, because it looks like we have our build process set to minify js and css if `FEC_WEB_ENVIRONMENT` is `stage` or `prod`, so I'm not sure why that's not happening.

Anyone have insight into how we can address these?
