### ISSUE TITLE
Redesign candidate pages to include more financial data

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1784]
So that users can easily find all of the financial data they need for a candidate, surface the data directly on the candidate page.

---

From the [research synthesis](https://github.com/18F/openFEC-web-app/issues/1765), we know that users have a need to see more financial information at the candidate level, including:

- Show more robust financial summary that combines totals for all authorized committees
- Surface aggregate subtotals (like the breakdown of contributions by state or employer) on the candidate page
- Show more totals for outside spending, such as total spent for and against
- Make it easier to get to the raw itemized data from these pages

One thing I'm not sure about is whether or not to include committee reports on candidate pages as well. We show their candidate filings (like Statement of Candidacy). If we're showing more robust financial info, maybe we should include these, or we could just link to a view of reports for their authorized committees.

**Completion criteria:**
- [x] Designs ready for implementation

**Comment by nickykrause** [comment]
Quick update. As Jen & I are wrapping up our collaboration efforts from this week, it occurs to me that we haven't been updating the issue, and the evolution of our thinking won't be transparent for others when I upload the more recent designs later this afternoon. 

So, I'm not looking for feedback here, because these designs are from a few days ago, but I wanted to post an image of the early thinking, to give some context for the mockups that are yet to come: 

![previous_work](https://cloud.githubusercontent.com/assets/1450173/22383826/157ce746-e491-11e6-9f5c-2169bc7e4e88.png)

**Comment by jenniferthibault** [comment]
🖌  [Full Candidate profile redesign mockups](https://gsa.invisionapp.com/share/ESA8FN046#/216609962_Candidate_-_Financial_Summary)

### GOALS and updates relevant for this issue:

#### GOAL 1: Surface more financial information on the Candidates pages (aka: Acknowledge that users' mental model focuses on Candidates rather than Committees)

- We pulled the Individual Contributions and Disbursement tabs from the Committee pages onto the Candiate pages, to show aggregate data from the candidate's relevant committees.
- To address the possibility that users might be struggling to find interesting information, even though that information is indeed there, we also restructured overall page layout. The new layout eliminates the tab navigation, which users sometimes overlooked, and replaces it with a new sidebar navigation that makes it easier for users to see the different types of information available for a Candidate.

#### GOAL 3: Show more totals and subtotals on Candidate pages

- On the Individual Contributions, Disbursements, and Spending by others to support/oppose pages, we are showing totals for the relevant data, as well as some context for those totals (e.g., how total individual contributions relate to total receipts). In these sections, we have also included graphical representations of the totals to make this data both more compelling and easier to read.

#### GOAL 5: Make it easier to access itemized data

- We have included more links to itemized data (e.g., in the form of underlined numbers) whenever possible. We have also renamed and changed the location of the button that jumps users into the full data tables. We believe this will help users who are looking at "slices" of data on the Candidate pages to understand how the full dataset can be accessed and filtered.


We'll be going through this in more detail in today's demo
