### ISSUE TITLE
Redesign committee filings tab

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1785]
So that users can better understand the trends and contents of a committee's filings, redesign the committee pages' filings tab to have an improved order and grouping of filings.

---

Rather than sort all reports (and non-financial filings + RFAIs) in a single table, ordered by date, we need to group and organize in a more logical way. Here's my understanding of what needs to happen:

1. Group filings by the year they apply to https://github.com/18F/openFEC-web-app/issues/1449
2. Group and sort filings by _type_ (i.e.  miscellaneous, 48-hour notices, monthly/quarterly, etc.)
3. Group all reports together with their amendments (so, the original April Monthly is followed by all amended April Monthlies)
4. Include RFAIs after the report they apply to

Additionally, we should remove financial columns (https://github.com/18F/openFEC-web-app/issues/1473) and add more relevant columns. 

This design issue should address:
- What columns to include
- How to separate by year 
- Whether or not to visually group the filings in any other way to support the above points
- The exact order to use, which we'll need for implementation

**Completion criteria:**
- [x] Designs ready for implementation
- [x] @jwchumley celebrates

**Comment by noahmanger** [comment]
I unfortunately didn't get to this this week, so tagging in @nickykrause and @jenniferthibault to either pick it up or we can wait until next sprint.

**Comment by jenniferthibault** [comment]
@nickykrause & I chatted today & based on remaining capacity & existing tasks, we can't take it on this sprint. We also think that you know more about this subject area, @noahmanger so it will take you less time than us combined! 

Moving to sprint 6.

**Comment by noahmanger** [comment]
Ok, I have some things to share. This has broadened to include the filings for candidate pages as well, so I have those too. 

First, committees. My idea here is to have to views: an "All" view ([InVision](https://gsa.invisionapp.com/share/ESA8FN046#/217323103_Committee_-_Filings_-_All)) that includes all filings — miscellaneous reports, statements of organization, RFAIs, all current and previous versions of financial reports — laid out in the order they currently are on fec.gov (more details about what this means in the comments in InVision).

And then the second view that can be toggled to is "Current versions of reports only" ([InVision](https://gsa.invisionapp.com/share/ESA8FN046#/217323104_Committee_-_Filings_-_Reports))which _only_ shows the current version of regularly filed financial reports (e.g. monthlies and quarterlies). So this hides RFAIs, previous versions, and anything else in order to give a condensed view. Additionally the columns change to a set that makes sense for financial reports (but not for non-financial filings). 

Again, more details in the InVision.

--- 

Ok, now for the candidate page ([InVision](https://gsa.invisionapp.com/share/ESA8FN046#/217323102_Candidate_-_Details)) . For this, my thinking changed the more time I spent with it.  First, I don't think we should include the candidate's committee's reports on their page. That's not the current behavior of fec.gov or beta.fec.gov (so we're not taking anything away), and I think it makes sense to keep those as the kind of detailed info that are attached to the committee itself.

Candidates _do_ have a few types of documents attached to them though. On fec.gov they are in a "filings" tab, which when compared to the "filings" tab on committee pages, is very different and I believe we've heard some people are confused about why the two are different. 

And so! My suggestion is that actually we do away with the concept of "filings" for candidates and instead present it in what I'm calling "Candidate details", which is an adaptation of the "Elections and committees" tab we were talking about. So this tab becomes the place for all metadata about candidates and the original documents that metadata comes from.

---

So, that's what I got. The visual styling isn't meant to be final, just a sketch to get across the idea. The data is fake, but I tried to make it all "real-ish". Lemme know what you think here or in InVision, or we can hop on a call.

cc @jenniferthibault @nickykrause @jwchumley @PaulClark2

**Comment by nickykrause** [comment]
@noahmanger Awesome! 

Some initial thoughts on things you said:

*Committees*
---

> And then the second view that can be toggled to is "Current versions of reports only" (InVision)which only shows the current version of regularly filed financial reports (e.g. monthlies and quarterlies).

🤔 This seems like a very useful feature. I am not actually super familiar with researching speaking to the user need here (i.e., seeing the most current versions of reports), but I assume that need is there, especially given the work that we've been doing with amendment chains.

---
In the InVision, you made this comment about the `Year` info:
> Within a two-year period, the filings are broken into two tables, one for each year. The year in this case refers to the year the report is for. (e.g. the 2016 Year-end report is filed in January 2017, but is considered a 2016 report).
![image](https://cloud.githubusercontent.com/assets/1450173/22596439/2bc041be-e9f1-11e6-862f-aa305a336e28.png)

🤔 I am a bit confused by this, but it may just be my ignorance. The `Election Cycle` selection is for a two-year period, but the tag for `Report Year` shows just one year (2016). Is it possible for users to look at 2015, given the controls you've offered? (It doesn't seem like it?) Or, maybe, looking at 2015 is not something users need to do?

---

In the InVision, you mentioned that the RFAIs would appear directly alongside the reports they are related to:
<img width="634" alt="screen shot 2017-02-03 at 9 16 48 am" src="https://cloud.githubusercontent.com/assets/1450173/22596572/b9dc18ba-e9f1-11e6-87c2-52e732766b46.png">

🤔 This makes a lot of sense to me, but I had a question: Is it not possible, in the RFAI listing, to somehow link it to the relevant report (beyond just being contiguous in the list of filings)? This is possibly a general question for our filing tables. I am just curious. 

---

*Candidates*
---

> First, I don't think we should include the candidate's committee's reports on their page. That's not the current behavior of fec.gov or beta.fec.gov (so we're not taking anything away), and I think it makes sense to keep those as the kind of detailed info that are attached to the committee itself. 

🤔 I agree. If we did include the reports, it would need to be the aggregate of all the committees' reports, and I don't know what user need that would be addressing, if any...?

---

In the InVision, you showed that the date control we have used elsewhere could be applied to these pages to show details about the Candidate, which may change depending on the date selected (e.g., `incumbent` status, the statements of candidacy):

<img width="683" alt="screen shot 2017-02-03 at 9 21 06 am" src="https://cloud.githubusercontent.com/assets/1450173/22596764/74e2d1e4-e9f2-11e6-8c20-985ca42bbd57.png">

🤔 This seems like a great application of the pattern we're establishing on the Candidate pages, and it makes sense to me. I am wondering a few things:
- Does the `Statement of Candidacy` document actually change depending on the election cycle chosen, or am I misunderstanding that?
- Where exactly does the `Compare all candidates in this race` button take the user? Is it to an election page?
    - If so, I am wondering about the card pattern for linking to elections, versus the button. Just thinking out loud: We have used buttons like this to essentially say "Click here to be taken to the more complete view of this kind of thing." (e.g., `All Filings` or `Filter this data`, which take users to the full data tables). So, this button could maybe be said to behave in a conceptually similar way if it took users to "everything about candidates in this election," right?

---

> ...present it in what I'm calling "Candidate details", which is an adaptation of the "Elections and committees" tab we were talking about.

🤔 When we met yesterday about the equivalent kind of page for the `Committees` pages, we talked about calling this section `About this committee`, rather than `Committee details`. I don't actually recall why, but maybe it would make sense to call this `About this candidate`, for consistency? (Or, more likely: this kind of wordsmithing still needs to happen throughout, as Emileigh hasn't really been tagged in yet.)

**Comment by noahmanger** [comment]
Had a good chat about these with @jenniferthibault and @nickykrause today. I incorporated a couple changes and added two new screens to test some ideas out. 

The first ([InVision](https://gsa.invisionapp.com/share/ESA8FN046#/217484630_Committee_-_Filings_-_All_-_Alternate)) is an alternate idea for showing filings. It breaks them out into separate tables by the type of filing, but within each table, keeps both years together and orders them reverse-chronologically so that the most recent is at the top. Personally, this view makes more sense to me, as it creates clearer separation between the filing types, presents a clear order to them all, but still gives the advantage of presenting them all on the same screen so you can get the complete picture of a committee's activity in a two-year period.

The second ([InVision](https://gsa.invisionapp.com/share/ESA8FN046#/217484632_Committee_-_Filings_-_All_Copy_2)) does a similar thing, but instead of one long view, it breaks it out into toggles.

Anyway, we'll talk more on Monday. I also really want @jwchumley and @llienfec 's eyes on these because I know it's critical for power-users to get this right.

**Comment by jenniferthibault** [comment]
Really interested in the idea of showing separate tables for separate filings on the same page. The toggle view between tables feels like it saves space, but you lose the ability to do a quick scan of everything in one place.

**Comment by PaulClark2** [comment]
I like first mockup 

@noahmanger `orders them reverse-chronologically` by report type? That seems to be the way the reports are displayed in the mockup. That's good because I think we'd want the reports to be together by type.

**Comment by PaulClark2** [comment]
Comment from Judy and Christian about "current version" and "previous version." They think these terms will cause confusion. Perhaps use "Latest Version" and "Prior Version."

**Comment by jwchumley** [comment]
I think they are confusing too or at least not helpful.  I believe what would help the most is a better default sort and the ability to sort by filer name  and by document.

**Comment by noahmanger** [comment]
The question of language is a good candidate for user testing (I made an issue for that here: https://github.com/18F/fec-testing/issues/30). 

As for the ordering, I just chatted with Jeff and Lauren. There was agreement that breaking the types of filings out into separate tables (i.e. "Regularly-filed financial reports", "24- and 48-hour", "statements of organization") was helpful, but that within a table, they should be ordered _chronologically_ rather than _reverse-chronologically_. This gives a chronological view of all activity, which also maps to the way an internal system that analysts use orders them, which makes comparisons between the two easier. 

So here's another version, which breaks them out by year and report type, but within each table, orders chronologically: https://gsa.invisionapp.com/share/ESA8FN046#/217705294_Committee_-_Filings_-_Divided_-_Chronological

**Comment by llienfec** [comment]
Thanks, Noah.  Looks great.  Is this something that gets user tested?

**Comment by nickykrause** [comment]
@llienfec yes! We can do some usability testing on this tab, as well as the rest of the pages that we're working on that associated with the committees.

**Comment by noahmanger** [comment]
After talking about this with the design team, I think we're still not sure if it's best to show these in chronological or reverse-chronological groupings, but this is something we can test and the tweak is really minor to switch. So if the rest of the design is good to go (which it sounds like it is), I move we table that decision for the time being and bump this over to @jenniferthibault for visual design.

**Comment by PaulClark2** [comment]
I'll ask Judy and Christian if they have thoughts or preferences about chronological or reverse-chronological.

**Comment by jenniferthibault** [comment]
One data point: feedback came in this morning from RAD specifically mentioning reverse-chronological https://github.com/18F/FEC/issues/614

**Comment by noahmanger** [comment]
The piece of feedback requested reverse-chronological by year (i.e. 2016 filings and then 2015 filings) and then within years, grouped by report (but no mention of whether chronological or reverse-chronological).

**Comment by PaulClark2** [comment]
Judy's preference is reverse chronological order. 

Like, https://gsa.invisionapp.com/share/ESA8FN046#/screens/217484630_Committee_-_Filings_-_All_-_Alternate

**Comment by llienfec** [comment]
Sounds like I'm outvoted!  Let's go reverse!

**Comment by noahmanger** [comment]
Alright! @llienfec let's give it a shot and we can see how cumbersome it is for your folks.

**Comment by jenniferthibault** [comment]
🖌  [Updated mockups](https://gsa.invisionapp.com/share/ESA8FN046#/218195103_Committee_-_Filings) for the committee filings tab are on InVision.

This sounds like it's ready for moving to implementation issues, so I'm moving it to the "Done" column until those issues can be made.

Thanks all!

**Comment by noahmanger** [comment]
Lookin sharp!
