### ISSUE TITLE
Design new layout and content for candidate and committee profile pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1786]
So that users can better understand all of the data on candidate and committee pages, redesign the base templates.

---

This is a broad design issue that is meant to address a few challenges holistically:

- The difficulty users have understanding the current time period they're looking at
- The fact that some users have had difficulty with the tab layout (and that this layout doesn't work well when there's many tabs or tabs with long titles)
- Address the fact that some users have had difficulty with the large headers
- Address any other design changes we want to make it more consistent with our overall system as it has matured

**Completion criteria:**
- [x] Designs ready for implementation

**Comment by jenniferthibault** [comment]
🖌  [Full Candidate profile redesign mockups](https://gsa.invisionapp.com/share/ESA8FN046#/216609962_Candidate_-_Financial_Summary)

## Preview of new page template & layout

![candidate - indiv contribs](https://cloud.githubusercontent.com/assets/11636908/22428763/43354a9c-e6d6-11e6-95b0-ada897f93618.png)


### GOALS and updates relevant for this issue:

#### GOAL 1: GOAL 1: Surface more financial information on the Candidates pages (aka: Acknowledge that users' mental model focuses on Candidates rather than Committees)

- To address the possibility that users might be struggling to find interesting information, even though that information is indeed there, we also restructured overall page layout. The new layout eliminates the tab navigation, which users sometimes overlooked, and replaces it with a new sidebar navigation that makes it easier for users to see the different types of information available for a Candidate.

#### GOAL 4: Alleviate confusion and increase awareness about the date controls

- We have moved the date controls out of the page header and into the body content area of the Candidate pages. We believe this change will not only increase visibility of the date control, but it will also help users to understand that selecting different dates will change the data on the page. This is because the control is now located directly alongside the content (data) that it affects. 

#### GOAL 5: Make it easier to access itemized data

- We have included more links to itemized data (e.g., in the form of underlined numbers) whenever possible. We have also renamed and changed the location of the button that jumps users into the full data tables. We believe this will help users who are looking at "slices" of data on the Candidate pages to understand how the full dataset can be accessed and filtered.

#### GOAL 6: Alleviate tension between the page header and the body content

In the previous version of the Candidate pages, the header contained broad summary information about the candidate (e.g., all the elections the person was in) that sometimes seemed to conflict with content of the page, which focused on a "specific slice of time." There was also some concern that the header space was too large, causing the content/data to lose some prominence. 

- We have slimmed down the header space and reduced it to core info
- We moved the election information and associated committee information into a new page that focuses on relevant Elections & Committees for the Candidate.

**Comment by jenniferthibault** [comment]
So that we can re-use this issue for committee page redesign work, which will likely be almost entirely similar, I'm moving this into sprint 6 and the "Ready" column.

**Comment by jenniferthibault** [comment]
🖌 :person_fencing:  [Complete candidate profile mockups](https://gsa.invisionapp.com/share/ESA8FN046#/218195097_Candidate_-_Financial_Summary)
🖌 👥 [ Complete committee profile mockups](https://gsa.invisionapp.com/share/ESA8FN046#/218195104_Committee_-_Financial_Summary)

Ready for implementation issues!
