### ISSUE TITLE
Design filters for ADRs and AFs

### ISSUE THREAD

**Issue by nickykrause** [18F/openFEC-web-app#1797]
We currently have filter designs for MURs and AOs, which are in the process of being implemented, but we have not yet produced designs for filters pertaining to ADRs and AFs.

Designs for these filters should pick up, as much as possible, from existing design patterns and attempt to establish consistency with the other legal resources.

We can also reference [this spreadsheet](https://docs.google.com/spreadsheets/d/1G1c3Arz_jO1PN597dRFeCck7i2RLQm9XLvo1nwnqkbg/edit) :lock: , which is where we are tracking the desired filters by resource type.

**Completion criteria**
[ ] Filter designs for ADRs
[ ] Filter designs for AFs

**Comment by nickykrause** [comment]
I started mocking up these filters while referencing the [filters spreadsheet](https://docs.google.com/spreadsheets/d/1G1c3Arz_jO1PN597dRFeCck7i2RLQm9XLvo1nwnqkbg/edit#gid=0) :lock:, and I realized that our initial mockups for MUR filters (made pre-spreadsheet, and which we didn't really discuss collaboratively) was incomplete, in terms of reaching feature parity with EQS. 

So, although this issue is about ADRs and AFs, I actually had to take a look at the MUR filters as well, in order to get a complete picture. 

The result of my review is the following sequence of draft filter designs, on which I have noted a variety of comments/questions for discussion:

**MURs**
![mur-filters](https://cloud.githubusercontent.com/assets/1450173/22138070/70637168-dea4-11e6-9aa5-eaaa18b07387.png)

**ADRs**
![adr_filters](https://cloud.githubusercontent.com/assets/1450173/22138081/7a3d776a-dea4-11e6-98ab-34303b78d873.png)

**AFs**
![af_filters](https://cloud.githubusercontent.com/assets/1450173/22138089/8090c838-dea4-11e6-9fa1-575bbdc3ce5f.png)

Of course, after completing all of this and preparing to update this issue, I realized that I forgot to include one filter on both the MURs and ADRs: The **Subject** and **Related Subject** drop-down menus, which appear in EQS:
<img width="809" alt="screen shot 2017-01-20 at 12 09 04 am" src="https://cloud.githubusercontent.com/assets/1450173/22138117/af8a2968-dea4-11e6-92f9-dec39c748e11.png">

So, I suppose that means we need to add the `Subject` fields to the list of outstanding questions for MUR/ADR filters.

Seems like the next step would be for me and @jenniferthibault to sync up about the filters and try to make some decisions where we can. This seemed to work well for the canonical pages and the search results display. @jenniferthibault: I will be sporadically available tomorrow, if you'd like to dedicate any time to this. If so, please DM me and we can find time to connect!

PS: Here are some related items that I could dig up, in the giant web of legal-filter-related issues:
- Implement filter refinement for AOs https://github.com/18F/fec-eregs/issues/276
- Mockup AO filter interactions https://github.com/18F/openFEC-web-app/issues/1619
- Pending AO filter doesn't seem to work https://github.com/18F/openFEC-web-app/issues/1794
- Implement citation filter for MURs and AOs https://github.com/18F/openFEC-web-app/issues/1764
- Implement front-end MUR filters https://github.com/18F/openFEC-web-app/issues/1735
- Research and identify filters necessary for enforcement actions https://github.com/18F/openFEC-web-app/issues/1703
- Design interface for searching through MUR document types: https://github.com/18F/openFEC-web-app/issues/1718
- Design a solution for displaying reclassified statutes https://github.com/18F/openFEC-web-app/issues/1736

**Comment by jenniferthibault** [comment]
@nickykrause this is really really really great. I've collected a list of thoughts/questions, but they are pretty raw, often me wondering out loud. Working on the more>less philosophy of feedback on this issue, and welcome you to take what's useful to you & leave the rest without worry :) 

**Missing filters (which you've already mentioned some of)**
- MUR/ADR: 
  - Subject field
  - If there was a disgorgement 
- AFs: 
  - If there was a challenge received
  - If there was a petition filed

## Filter review

**All/universal comments**
- Panel title should be “Edit filters”. This says consistent with the others in data and solves our space problem. 
  - Should also include # of filters applied in parenthesis: “Edit filters (2)"
- "Search the text of cases” Interesting!  this wouldn’t necessarily work for AOs, right? There’s summary text from FEC record, not sure if the keyword search includes that. Maybe this is an enhancement for later since it’s not so straightforward and double-checks something @emileighoutlaw has been trying to make consistent across the site?
- Case name + Case number field: Wonder if theres an interaction that allows us to combine these intelligently?
  - If we keep both for now, put case # before case name? This is how URLs are structured anyways, and might be slightly more memorable?
- Since Respondents are key to these cases, worth bringing that field out of participants and into the top-level panel? This will also force us to figure out how to make the case name/number/respondent fields less redundant. (Same for ADR/AF…AO’s, would be complainant field instead)
- Time period panel: election cycle above open/close date for consistency
  - Election cycle would probably need to be two-year periods, to be consistent across the site. [Example from filing data page](https://beta.fec.gov/data/filings/?data_type=processed&cycle=2012&max_receipt_date=01%2F21%2F2017)
  - <img width="299" alt="screen shot 2017-01-20 at 11 21 23 am" src="https://cloud.githubusercontent.com/assets/11636908/22157532/112cca34-df06-11e6-8fce-46c3414b11ac.png">
- Participants: I don’t _think_ we need to repeat “Name” for each participant field
- Panel order overall: slight hunch that maybe we want outcome higher than time period, maybe even higher than citations? 
- Agreed that the relationship between doc type filter & pending/archived stage documents is a separate issue to put aside for now
- 💭 this would definitely be something for later if it proved worth pursuing, because it would be a new filter, BUT! I wonder if it would be useful or interesting to have a category/filter for to show which commissioners voted in the case. The scenario I could picture here is if you wanted to see all MUR cases that any commissioner voted on. Possibly combined with an "abstained, affirmed, denied" filter to pair. Strong disclaimer of 💭 :) 

**MURs**
- Archived MURs: agreed, ok to leave filter out until Archived MURs are reprioritized
- Final disposition: Conciliation seems logical to surface
  - We don’t always have to surface any options, or a certain number of them. Could be just one.
- Civil penalty/fines: total vs individuals—might be worth having both? They are different ways of looking at cases, $ by respondent feels like it stays consistent with how the case is organized by respondent overall. 
  - If we do include both, these two will likely have interaction/logic dependencies on one another 
 - Probably should add a treasurer search field
  - Makes me wonder: 💭 overall what if there was just one search field for “Participants”  (or participants other than respondent, which feels specific) that searches across all those fields?

**ADRs**
 - Doc type + disposition categories: maybe we surface nothing out of the dropdowns for now, then use analytics + research to decide later?

**AF**
- Case name + committee ID fields feel redundant to me as well….maybe combine to “Committee” field which accepts committee names & IDs and matches to both fields?
- Election cycle & report type are part of the same unit in these cases: it’s the type of report that had the violation & when that report happened….also closely related to Open date. I’m not sure yet now to fix, but it feels like maybe report type should be closer to election cycle

Glad to take this to synchronous review whenever you'd like, just thought it would be helpful to have these written out somewhere.

**Comment by noahmanger** [comment]
Just a couple small UI thoughts to add:
- Because the logical relationship on the citation filters is `AND` rather than our typical `OR`, we might want to show that in the actual filter somehow.
- Re: time period, I think it actually makes sense to not have this be a two-year period because what it's referring to is the year of the election for which a violation or such occurred. I think it probably makes more sense for that to be a single year in that case. 

Last parting thought, with all the conversation and back-and-forth here, it would be really helpful to close this issue out with a link to final designs and some documentation around all the decisions so that its easiest to pick up and implement.

Nice work!

**Comment by nickykrause** [comment]
@jenniferthibault - 

New MUR filter designs, per our conversation this morning. I haven't yet applied these to ADRs - waiting for final comments, because a lot of the changes to ADRs will be similar. (Still working on AFs).

Any final thoughts here?

Also, @emileighoutlaw, we'll need your content :eyes: at some point (there are already some items in pink there that will need your review), but I'm happy to connect synchronously when we have MURs/ADRs/AFs together, and you're not in a string of meetings. Maybe near the end of the day today or tomorrow morning. :smile:

![mur_filters_v3](https://cloud.githubusercontent.com/assets/1450173/22214848/d2a82ec4-e15e-11e6-83f2-d02d8385e48a.png)

**Comment by nickykrause** [comment]
@jenniferthibault: I updated the MUR filters mockup to include the correct searchbar buttons, and I've annotated it with the questions that we have. Hopefully we can sort through some of this in grooming today, if there is time. 

Comments are in pink. Questions are in yellow/orange.

(cc: @emileighoutlaw: There are some content questions in here, which will probably come up in grooming. And of course, you may also have other content thoughts, which we welcome)

![mur_filters_annotated](https://cloud.githubusercontent.com/assets/1450173/22253409/1fdc598c-e217-11e6-96fd-25c8dcf8c9c9.png)

**Comment by nickykrause** [comment]
Scratch that previous screenshot. I uploaded the wrong version! Hold please...

**Comment by nickykrause** [comment]
Here is the right one:
![mur_filters_annotated](https://cloud.githubusercontent.com/assets/1450173/22253660/110b5dda-e218-11e6-8750-5bbf97dfef70.png)

**Comment by jenniferthibault** [comment]
This is great @nickykrause ! Since the questions coming up in these MUR filters are also universally applicable to the ADR & AF filters, I think we're in a great spot for grooming this afternoon.

🔆 heads up @anthonygarvan / @vrajmohan / @dogweather for the third part of our legal grooming installment today :)

**Comment by nickykrause** [comment]
Before closing this, I wanted to be sure to add the most recent version of the filter designs for all three of the legal resource types discussed here (MURs, ADRs, and AFs). We had a chance to discuss the MUR filters (and, by extension, the ADR filters) with the dev team during grooming this week. 

The AF filters should be similar, but it is worth noting that the AF filter designs do not include a citation search. There is no citation search for AFs currently in EQS, so we are not losing feature parity by excluding it, but we can discuss in a future sprint whether or not we think it is needed/possible.

Finally, @emileighoutlaw: There are a few content questions in these filter designs. I am not sure if you think it would make sense to create a separate issue for us to discuss any thoughts you might have? 

![mur_filters_v3](https://cloud.githubusercontent.com/assets/1450173/22376670/8de60c52-e474-11e6-8276-8fef449efd76.png)

![adr_filters_v3](https://cloud.githubusercontent.com/assets/1450173/22376643/731e37a0-e474-11e6-97ff-9ada6dc9c1b3.png)

![af_filters_v3](https://cloud.githubusercontent.com/assets/1450173/22377375/43176790-e477-11e6-8c40-88c2ed7b2a2b.png)

**Comment by emileighoutlaw** [comment]
Sounds good, @nickykrause ! Tracking content here: https://github.com/18F/openFEC-web-app/issues/1814

**Comment by noahmanger** [comment]
Closing this issue as the design is done, but future implementation work is iceboxed.
