### ISSUE TITLE
Add new language for amendments without available version information

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1806]
Options first (for folks who want to weigh in), thoughts second (in case anyone wants to know what's on my mind) 😃. 

Y'all should feel equally welcome to either weigh in or let me know that you have decision fatigue and just want me to make an informed decision. cc @noahmanger @jenniferthibault @nickykrause @xtine 

**Option 1**
> Past version
Current version
Version unknown

**Option 2**
> Past version
Current version
Version not available

**Option 3**
> Past version
Current version
Version information unknown

My thoughts on this to follow.

There were a couple decision points here.

1. First, which word (as defined) comes closest to the concept we're trying to convey:
    - **Unknown:** _not known; not within the range of one's knowledge, experience, or understanding_
    - **Unidentified:** _not recognized or or established as being a particular person or thing_
    - **Unavailable:** _not suitable or ready for use; of use or service; at hand_
    - **Not available:** _not readily obtainable; accessible_

     I decided `unknown` and `not available` got us closest.

1. Second, do we want to have one modifying adjective, or two:
- Version _(unknown/not available)______
or
- Version information _(unknown)_____

Related: https://github.com/18F/openFEC-web-app/issues/1738

**Comment by nickykrause** [comment]
FWIW, I like "version unknown," because 

(a) it is simple/short,
(b) it gets close to the meaning we want to convey, as you said, and 
(c) I think that the "not available" option could _maybe_ connote a kind of withholding, almost closer to "not disclosed." (As if to say, "The version is not available to you, user, even though we might know it.") 

Item (c) is probably quite a stretch, but it's what came to mind when I tried to articulate to myself why "unknown" seems more forthright

**Comment by xtine** [comment]
¯\_(ツ)_/¯

No but seriously, I do prefer "Version unknown." I do like "Version information unknown" but it is a bit long for the current column width. We have a version, we just don't know which it is. I would confuse a "not available" as the while thing is not available, rather than the information about the version is unavailable.

**Comment by jenniferthibault** [comment]
+1 `Version unknown`, but if the details below change your recommendation @emileighoutlaw sounds like we are all following your lead.

For comparison! We have little bit of precedent in the Archived MUR search results (which are currently hidden behind a flag, but @vrajmohan kindly helped me track down).

There, [when the close date is null](https://github.com/18F/openFEC-web-app/blob/94db01205d407b0fb2816e72871f0af9755870bf/openfecwebapp/templates/partials/legal-search-results-mur.html#L27) we used `Unknown`, which happens to fields that can't be read from archived MURs because the document data/text isn't readable. 

![screen shot 2017-01-20 at 9 53 23 am](https://cloud.githubusercontent.com/assets/11636908/22153712/698333e0-def6-11e6-8e7c-ed9679a8eeb0.png)


Then, [on the Archived MUR canonical page, we use](https://github.com/18F/openFEC-web-app/blob/develop/openfecwebapp/templates/legal-archived-mur.html#L125) `No content available` so....we have done both?

![screen shot 2017-01-20 at 9 55 13 am](https://cloud.githubusercontent.com/assets/11636908/22153744/9152753e-def6-11e6-983c-09be143afbf6.png)


When this came up, I remember we had talked about making that "Unknown _for Archived MURs_" or "Unavailable _for archived MURs_" because that would tell the user more about why it wasn't available, but that discussion likely fizzled when Archived MURs got removed from the release and deprioritized.

**Comment by noahmanger** [comment]
I'll defer to y'all, but just raising the thought that `Version unknown` might make it sound like the FEC as an agency doesn't know what the version is, when it's really just a matter of the _system_ not knowing. Take that fwiw.

**Comment by emileighoutlaw** [comment]
For the sake of not expending too much time and energy on this, let's move forward with implementing "Version unknown." 

Good hunting down of the "No content available" style, Jen! The "No content available" is divergent (and more precise), but it only works because it doesn't stand alone: there's space available to explain what we really mean below it. So in this instance, I don't think a similar approach would work.

**Comment by jenniferthibault** [comment]
👍 @xtine "Version unknown" is ready for your implementation.

**Comment by noahmanger** [comment]
Shipped in the last release.

**Comment by jenniferthibault** [comment]
Filling in some logic detail for documentation:

The "version unknown" scenario happens mostly with paper filings when we cannot determine the amendment chain. It can happen with electronic filings if the previous file number is missing for some reason. — @PaulClark2

**Comment by jontours** [comment]
Yes that was an edge case that I think will be fixed here: https://github.com/18F/openFEC/pull/2361

**Comment by jenniferthibault** [comment]
Oh that's awesome—thanks for tying the two together @jontours !
