### ISSUE TITLE
Implement committee financial summary tab

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1832]
So that users can better understand a committee's financial totals for a two-year period, present the financial summary tab in a cleaner, balance-sheet format.

---

[Design](https://gsa.invisionapp.com/share/ESA8FN046#/218195104_Committee_-_Financial_Summary)

The design breaks the financial summary information into three tables: Total raised, total spent and cash summary. Each one of these presents totals, sub-totals and sub-sub-totals. 

A few more notes:

- The design shows glossary icons for everything, but we do not have glossary definitions for each term, so it's ok to not include all. 
- Also, there's four ways to show these, depending on the type of committee (presidential, pac/party, ie-only and house/senate). So this should implement the new view for each.
- Intro copy is still being worked out, so that doesn't need to be included in the first round.
- When possible, we should link to the datatable page showing the itemized transactions for subtotals 

**Completion criteria:**
- Create new templates for: 
  - [x] Presidential committees financial summary
  - [x] House/senate committees financial summary
  - [x] Pac/Party committees financial summary
  - [x] IE-Only financial summary
- [x] Show the coverage dates for the totals (that's what the `01/01/2015-12/31/2016` numbers refer to
- [x] When possible, link labels to glossary terms
- [x] Link "Total receipts" to beta.fec.gov/data/receipts with the appropriate filters
- [x] Link "Total disbursements" to beta.fec.gov/data/disbursements with the appropriate filters

**Comment by noahmanger** [comment]
The way this is set up makes it kind of a pain to get the glossary terms / linking individual numbers to. How does this work for y'all (@nicky / @jenniferthibault ) as a first step:

![image](https://cloud.githubusercontent.com/assets/1696495/22850535/abe7889c-efbf-11e6-991c-c076ddb335d8.png)

**Comment by jenniferthibault** [comment]
@noahmanger the categories & subcategories above are different than the ones @nickykrause had outlined in the wireframes, so I'm wondering where does the difference comes from, and if it's intentional or not. (I had interpreted the wireframes as real intention to represent these categories, but maybe I'm wrong.)

I have one visual change request for now. 
- Each table section should be inside a white slab that groups tables separately. It's subtle, but is a helpful tool for visually grouping information

![screen shot 2017-02-13 at 9 46 14 am](https://cloud.githubusercontent.com/assets/11636908/22887951/07684ad0-f1d2-11e6-850c-eb30af4db812.png)

**Comment by nickykrause** [comment]
@noahmanger @jenniferthibault 

Seeing these come together is very exciting! To address Jen's point:

Yes, the arrangement of categories in the table was intentional. I found the layout on the existing committee disclosure portal to be confusing and thought the information would be more scannable if it were arranged differently.  For reference, here is the previous version:
<img width="423" alt="screen shot 2017-02-13 at 9 04 37 am" src="https://cloud.githubusercontent.com/assets/1450173/22888478/774fe54e-f1cb-11e6-8273-847ad4210d21.png">

As you can see, there are some bolded items that appear as totals of the items _above_ them, but, in some cases, not _everything_ above them is included. For example, at first glance, `Total loans` looks like it could include "Transfers from authorized committees" as well as "candidate loans" and "other loans," but that's not the case. The new ordering in the wireframes was intended to avoid those issues. 

BUT, I'm now wondering if the `Financial Summary` elements can change for different committee types, because I'm seeing different things in your list, @noahmanger, than I do in the list for Tammy Baldwin's committee (see the screenshot I added above).

For example, your list includes `Levin Funds` and `Non-Federal Transfers`. Can you say more about where those things came from, Noah?

Also, I am wondering if there is a reason for changing the table titles from `Total raised` to `Raising`, as well as `Total spent` to `Spending`, etc. ?

**Comment by noahmanger** [comment]
Thanks for the close eye! Yeah, I still need to go through and make sure everything lines up. There's a couple hiccups I ran into:

- Like Nicky noted, different committees have slightly different fields
- Some of these fields seem to be missing in the API at the moment (so we'll need to add)

**Comment by jontours** [comment]
@nickykrause which committee was this table pulled from?  Would be nice to reference for some verification.  Thanks!

**Comment by jontours** [comment]
Ah Tammy Baldwin it seems.

**Comment by nickykrause** [comment]
Yes @jontours! it was the committee called Tammy Baldwin for Senate

**Comment by noahmanger** [comment]
@nickykrause @jontours I _think_ I got all these formatting / missing field issues fixed, except for a couple instances where we need additional API fields. 

Presidential

Screenshots:
- [House-senate](https://cloud.githubusercontent.com/assets/1696495/22952126/9df648c8-f2c0-11e6-8c4d-9ff3776f37ef.png)
- [Presidential](https://cloud.githubusercontent.com/assets/1696495/22952128/9df82792-f2c0-11e6-9b8c-1e1d114b7076.png)
- [Pac-party](https://cloud.githubusercontent.com/assets/1696495/22952127/9df841f0-f2c0-11e6-9ef7-27a448ee5c71.png)

**Comment by noahmanger** [comment]
Now that #1848 has been merged in, we can count this as complete.
