### ISSUE TITLE
So that users have a more clear sense of what's currently available on the site, clarify copy in Enforcement intro

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1851]
On:
https://beta.fec.gov/legal-resources/

<img width="778" alt="screen shot 2017-02-24 at 4 09 28 pm" src="https://cloud.githubusercontent.com/assets/11636908/23321060/a497333e-faab-11e6-88d2-ab706a4b2f34.png">

The language indicates that ADRs and AFs are available on the site (which they are not yet) and also indicates that the full set of MURs back to 1975 is available, which isn't true since we delayed the release of archived MURs. From @AmyKort :
> Will we want to revise this to address how we're going to let folks access EQS and the archived MUR search on the old site from the new site, or just adjust this language to say search MURs dating back to 1999(8?) or should we delete the year all together, etc. 

cc @emileighoutlaw

**Comment by emileighoutlaw** [comment]
Hey @AmyKort ! One thing that's changed since we wrote this issue is that we're now ready to launch our Alternative Dispute Resolution Program and the Administrative Fine Program pages. 

So when folks click the the Enforcement section, they'll have the option to:
- Search closed MURs (with the big warning that results don't include most cases closed between 1975 and 1998)
- Navigate to the legacy FEC.gov search for closed MURs from 1975 to 1988
- Navigate to the AF page, which has its own research information
- Navigate to the audits page, which has its own research information
- Navigate to the ADR page to learn about that program 

All that being the case, I started feeling like it would be very hard to try and explain to folks how to use/navigate the Enforcement section before they've clicked into it. It seemed savvier, perhaps, to adjust our language to introduce users to the things they can do inside Enforcement, and let the Enforcement page do the work for the _how to do it_. 

Does that make sense? This is what I was thinking about for a revised blurb:

> **Enforcement**
> The FEC has exclusive jurisdiction over the civil enforcement of the federal campaign finance law. 

> FEC enforcement programs include Matters Under Review (MURs), the Alternative Dispute Resolution Program and the Administrative Fine Program. Additionally, the FEC regularly conducts audits of political committees. 

> Enforcement cases are primarily handled by the Office of General Counsel and must be kept confidential until the cases are closed. 

> Learn more about each program or search closed enforcement cases.

**Comment by AmyKort** [comment]
From what page will folks get to our legacy EQS, if they wanted to search closed ADR and AF cases.

**Comment by AmyKort** [comment]
Let me have some experts over here take a look at the blurb.

**Comment by emileighoutlaw** [comment]
This is getting a little into design so I want to tag in @jenniferthibault for visibilty. But to my thinking, it seems like the Enforcement home is the right place to highlight and clarify the two search systems. That would happen here:

![screen shot 2017-03-13 at 2 12 29 pm](https://cloud.githubusercontent.com/assets/10552702/23871433/5f142362-07f8-11e7-962a-fee93b7796a5.png)

I think there should probably also be links to EQS on the [Administrative Fines page](https://beta.fec.gov/legal-resources/enforcement/administrative-fines/) and the [Alternative Dispute Resolution page](https://beta.fec.gov/legal-resources/enforcement/alternative-dispute-resolution/), so folks have the option of searching closed cases after reading about those programs, too.

**Comment by AmyKort** [comment]
Ok. We'll also need to find a home for the audit search system. Will the audit page be a direct link from ^^^ as well?

Sorry--I think I'm having a hard time with the blurb because I don't understand what I'm blurbing about.

**Comment by emileighoutlaw** [comment]
No need to be sorry! These are great questions and really important to think. We do have a link to all the audits on the [Audit page](https://beta.fec.gov/legal-resources/enforcement/audit-reports/)

**Comment by AmyKort** [comment]
How about something more like this?

Enforcement

The FEC has exclusive jurisdiction over the civil enforcement of the federal campaign finance law.

FEC enforcement matters, called Matters Under Review (MURs), are primarily handled by the Office of General Counsel. Enforcement cases must be kept confidential until the cases are closed.

Other programs designed to augment the Office of General Counsel’s enforcement role include the Alternative Dispute Resolution Program, Administrative Fine Program and Audit Program.

Learn more about each program or search closed cases and audits.

**Comment by emileighoutlaw** [comment]
Yep! I love it.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/866
