### ISSUE TITLE
Committee Cycle Bug

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC-web-app#1852]
I believe there are multiple instances of this bug, so if this logic were fixed, I think it will fix a lot of committee broken links. This is related to this issue #1845 

This bug seems to happen when `election_full=true`. If the committee filing does not exist for a given year (whether it be because they were terminated or has not filed yet), the `url_for` function needs to have logic to accommodate for those particular instances. Right now, I believe it is just taking the submitted cycle parameter as is with no additional logic? cc @jwchumley @PaulClark2 @LindsayYoung @ccostino 

# Terminated Committee Example
## GARN, E. J. JAKE
Link: https://beta.fec.gov/data/candidate/S4UT00027/?cycle=1986&election_full=true
### Campaign Committees
GARN CAMPAIGN COMMITTEE links for Money raised, Money spent, Reports filed are all broken because it is trying to pull a non-existent cycle (1986), even though the committee was terminated in 1984. 

### Joint fundraising committees
GARN/CFTR RECEPTION COMMITTEE link is broken because it is trying to pull a non-existent cycle (1986), my assumption is that this committee was also terminated in 1984.

# Not Yet Filed Committee Example
## COCHRAN, THAD
https://beta.fec.gov/data/candidate/S8MS00055/?cycle=2020&election_full=true

### Campaign Committees
CITIZENS FOR COCHRAN link is broken because it is trying to pull 2020 cycle information for the committee, but they have not filed yet for that cycle.

**Comment by LindsayYoung** [comment]
What if for the campaign committee links on a full cycle candidate page, we don't add the cycle to the call that will take you to the most recent records for the committee? I think that might be the quickest cleanest fix for now.

It might be awkward if you are looking back in time because it may jump you forward but, if our timing is clearly labeled, it should be something people can deal with and get where they want to go.

**Comment by PaulClark2** [comment]
I don't think this is going to fix the problem.

If I'm on a candidate page, https://beta.fec.gov/data/candidate/S8MS00055/?cycle=2020&election_full=true, then I click on "Money raised" https://beta.fec.gov/data/committee/C00091892/?cycle=2020&tab=receipt, I get a response that doesn't make sense. I get an "Oops!" message. 

Cochran has raised money during the period between 2015 and 2020 (technically 2015 and 2017).  

This isn't ok.  His committee has just over $1 million dollars in receipts.

**Comment by LindsayYoung** [comment]
I'm saying we should change the money raised link to: https://beta.fec.gov/data/committee/C00091892/
that will give a valid response. The user will be a click away from what they want, it's not perfect but it is much better.

**Comment by PaulClark2** [comment]
Slack conversation around this issue:

Lindsay Young [10:30 AM] 
I am saying to make the link https://beta.fec.gov/data/committee/C00091892/ (edited)


Paul Clark [10:53 AM] 
Doesn't that defeat the purpose of having "money raised" and "money spent" links? We'd need to remove those, right?

Lindsay Young [11:12 AM] 
It takes you to the financial summary, so that seems reasonable to me. We could take them out but, that seems less helpful. Is that something we coudl do a quick test with users @nicky or @jeremy ?

Paul Clark [11:15 AM] 
I guess I don't see the point of "money raised" and "money spent" links if they take the user to the financial summary. The "committee name" link takes you to the financial summary. So, we'd have three links in one blue box that takes users to the same place.

Lindsay Young [11:21 AM] 
Good point about the display. Now, when there is a cycle discrepancy, none of the links work. So, for the full cycle view, we could replace the first general link with https://beta.fec.gov/data/committee/C00091892/ and get rid of the other two (edited)

Noah Manger [12:21 PM] 
Another approach is to say that on the most recent cycle on candidate pages, we don’t include the `cycle` parameter when linking to committee pages, but do include it when looking at past ones


[12:21]  
So when you’re looking at the most recent time period on a candidate page, it will default to the most recent period on committee pages, whatever that may be

Carlo Costino (18F | DC) [12:22 PM] 
@manger that makes sense to me

Lindsay Young [12:26 PM] 
I think that is what I am saying

[12:26]  
I might be missing a subtlety

Carlo Costino (18F | DC) [12:27 PM] 
D'oh!  It is

Noah Manger [12:27 PM] 
oh, sorry if i misunderstood. i thought you were saying to _always_ exclude the cycle parameter, rather than just excluding it on the most recent year

[12:27]  
side-note: what do folks think about a #data channel where we can rabbit-hole on some of these wonkier issues?


Lindsay Young [12:33 PM] 
I think we may want to exclude it for full cycle in President and Senate, because it is mostly in the new ones but I think terminations and such make the problem broader than that

**Comment by jwchumley** [comment]
Thanks!


________________________________

**Comment by noahmanger** [comment]
Turns out the code to get this working like we wanted it was under our noses all along and just wasn't being utilized in the templates. 

[This step here](https://github.com/18F/openFEC-web-app/blob/develop/openfecwebapp/views.py#L188) adds a `related_cycle` to the `committee` template variable that is the latest cycle a committee has filed for, if it hasn't filed for the current selected cycle. This is great because we can keep the logical time-period links when looking at prior cycles. 

I'm making this change in my upcoming PR implementing the new financial summaries.

**Comment by noahmanger** [comment]
This was resolved by #1915 . You can see here https://fec-stage-proxy.app.cloud.gov/data/candidate/S4UT00027/?cycle=1986&election_full=true
