### ISSUE TITLE
Implement Citations Accordion

### ISSUE THREAD

**Issue by anthonygarvan** [18F/openFEC-web-app#1857]
This requires reworking javascript, either cleaning existing code to be more extensible or introducing a new pattern for legal.

**Comment by noahmanger** [comment]
Here's [the latest designs](https://cloud.githubusercontent.com/assets/1450173/23368218/bb18fa10-fcd2-11e6-83a2-42227fc8882e.png). To flesh this out a bit more, these are the components to this pattern, as I understand them (we probably want to break these out into separate issues). I think of this as having a couple phases:

## Phase 1
This is the core of the interaction that will allow the functionality to be usable at a basic level. (I'm not sure if this needs to also include AJAX loading of the results, which would need to be another bullet. It might be enough to have JS for the typeahead but then load results on page refresh.)

1. **Accordions:** Simply grouping things into accordions that can be expanded and collapsed. The document accordion should be open by default. This is possible with the existing codebase just by adding the right markup. 

2. **Statutory citation filter:** A text `<input>` that initializes a typeahead. This should:
  - Show the current citation and the former (reclassified) citation in the typeahead suggestions
  - Match against both the old (2 U.S.C.) and new (52 U.S.C.) citation 
  - Show all matching suggestions that match the user's input
  - When selecting an option, generate a checkbox with the value of the new code 
  - Unchecking a checkbox removes the filter
  - If multiple checkboxes are present, they have an "OR" relationship

3. **Regulation citation filter:** A text `<input>` that initializes a typeahead. All behavior same as the statute except it doesn't need to show any "reclassified" anything. 

4. **AND/OR toggle**: This allows users to link together multiple citation searches with an "AND" relationship rather than the default "OR".
![image](https://cloud.githubusercontent.com/assets/1696495/23387509/cd1c063c-fd11-11e6-866c-018b0eb240e0.png)

## Phase 2
These are interaction enhancements that bring in the existing patterns used on the finance data tables. 

**Filter count:** When filters are applied or removed, both the accordion header and filter header should update to show the number of filters applied.

**Filter tags:** Adding filters generates tags above the results. These can be X'd out. 

**Status update messages:** This is the green success (or red error) messages that show up when results are added or removed.
![image](https://cloud.githubusercontent.com/assets/1696495/23387568/4160deb4-fd12-11e6-8886-35d2b6290faa.png)

**Enhanced results layout:** There are designs for more complex layouts of the table of results.

---

What do you think @anthonygarvan ? I'm down for you to bite off as much of this this sprint as you think makes sense, but wanted to at least spec out the expected behavior. Happy to chat through synchronously before sprint planning, too.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1871
