### ISSUE TITLE
Develop content strategy for  "Advanced data" blurbs

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1885]
So that users understand what each data set consists of and can pick the right one, develop a content strategy for the new "Advanced data" page.

---

There's a few pieces to this. First, there's the blurbs for each dataset, like: 
![image](https://cloud.githubusercontent.com/assets/1696495/23878783/a748f046-0806-11e7-87b4-27eca8d35e26.png)

There's also the categories that could use text:
![image](https://cloud.githubusercontent.com/assets/1696495/23878795/b56ce3da-0806-11e7-8028-213f2cb8c474.png)

And then the blurbs that are linking back to the legacy data, which were just lifted directly from fec.gov

Some questions that I think could/should be addressed by this strategy:
- Why would someone use this data set? What will they find?
- What is the timelineness? When is it reported and when is it up to date in the system?
- What is *not* included or not reported in the data set? What data might a user expect to find but that's not collected by the FEC?
- What form is it reported on? Who needs to report it?

**Completion criteria:**
- [ ] Create content strategy for what should be included in each blurb
- [ ] Write copy for each data set

**Comment by noahmanger** [comment]
@jameshupp updated the original description to reflect the new strategy task.

**Comment by jameshupp** [comment]
Working through this here: 
https://docs.google.com/document/d/1OuK_gf4DUxd_7zlt3mAQBHbusO8PswgeSKyJAD6FDcc/ 🔒 

I didn't try to write everything, since in some cases the data itself isn't ready yet, and in others we don't have _any_ kind of blurb yet and I figure I can work through it with the FEC folks directly if the strategic direction makes sense.

This is still rough and I expect a few questions, and it'll get clean once I'm able to resolve those questions. Comments welcome on both the substance and the structure of it. (What's just plain wrong? What's not adequately addressed? What is confusing to look at?)

**Comment by jameshupp** [comment]
I've cleaned up the WIP document just a little bit. This is now closed pending other in-progress data design work.
