### ISSUE TITLE
Link to FECA brochure from the statutes page

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1901]
So that users can access the FECA brochure, add a link to it from the statutes page.

---

The task is to add a link to [this brochure](http://www.fec.gov/pages/brochures/fecfeca.shtml) from the [statutes page](https://beta.fec.gov/data/legal/statutes/).

**Completion criteria:**
- [x] Design placement for this link - @jenniferthibault 
- [ ] Add link

**Comment by jenniferthibault** [comment]
Had a quick chat with @emileighoutlaw before starting this task to find out where in the content hierarchy the brochure might go, and we realized that the brochure is a lot bigger than statutes. It covers statutes, regulations, AOs, and enforcement. It catches a lot of things about all things legal resources.

In that sense, it feels like it might be better placed as a card on the [legal resources landing page](https://beta.fec.gov/legal-resources/). We've done this before on the [Registration & reporting essentials pages](https://beta.fec.gov/registration-and-reporting/essentials-house-and-senate-candidates-and-committees/).

This would need a new icon, since it's not a PDF with a cover (and the custom covers I've been making don't work very well that small) but it could look like this:

![screen shot 2017-03-29 at 6 14 29 pm](https://cloud.githubusercontent.com/assets/11636908/24479114/b5f7fe8c-14ab-11e7-9663-140c7fb189cc.png)

**Comment by noahmanger** [comment]
I like it!

**Comment by emileighoutlaw** [comment]
I like it too! 

I'm channeling Robb here a little and wondering if we need a header at all? I think the title does an excellent job explaining what the content is (a brochure about federal law and the FEC).

At the same time, I suspect a heading could be valuable for folks context on _why_ they might want to read the brochure. So it could be something like:
>  Learn more about the law and its history

Any preference, @jenniferthibault or @noahmanger ?

**Comment by noahmanger** [comment]
👍

**Comment by jenniferthibault** [comment]
Works for me! Sounds like this is ready for implementing.
