### ISSUE TITLE
Add pre-release banner to fec.gov

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1908]
So that visitors to fec.gov know that the change is happening, add a banner pre-flip notifying people of the change.

---

First, we need to determine when we want this to go up. I'm not sure what all needs to happen before we make this call. 

Second, we need to develop it.

**Comment by johnnyporkchops** [comment]
Is this essentially same as https://github.com/18F/fec-cms/issues/928?-- adding the same banner to the old site as the one added to the betsa site inhttps://github.com/18F/fec-cms/issues/928?

**Comment by noahmanger** [comment]
It's similar, though the language (and obviously where it happens in the code base) are different. But yeah, probably makes sense to make use of similar styles and markup.

**Comment by johnnyporkchops** [comment]
I am taking this task (1908) over for Pat since I was lighter this sprint. I was thinking I could build it for the legacy site and then pair with @xtine to implement basically  the same code On the CMS and web app. I have an idea of how to implement it there but may need some help. I was going to offer to take the task for #923 in sprint planning anyway but had not looked at the specs yet.

**Comment by johnnyporkchops** [comment]
Update: This block is used on https://beta.fec.gov/about/leadership-and-structure/
