### ISSUE TITLE
Accessibility review 

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1935]
As we near the flip, we should take another close pass through the site and make sure that our a11y game is up to par with everything in the [Accessibility Guide](https://pages.18f.gov/accessibility/index.html).

**Comment by xtine** [comment]
Ran most pages on CMS and web app through HTML_CodeSniffer and Chrome Accessibility Audit. Results overall were pretty good, and I've updated a few key issues on PRs https://github.com/18F/fec-cms/pull/1012, https://github.com/18F/fec-style/pull/684, and https://github.com/18F/openFEC-web-app/pull/1981

Keyboard navigation is good on all pages and free of traps, however there are "invisible" targets that are part of the Feedback popup even while closed so we need to figure out a way to have the links in the Feedback popup untabbable until open again.

There were some warnings that we might think of addressing but aren't critical:
- Anchor elements that don't have `href` because they are used as JS triggers
- More descriptive labels for buttons like "Learn More" on sections
- More logical nesting of header (h2/h3/etc) elements on some sections

There was also a warning about the Homepage hero text not having a proper color contrast ratio and links in the footer being obscured, but those might be false positive checks.

Additionally, datatable pages need more review as I encountered several warnings about missing names on fieldsets, invalid labels on certain elements and datatable rows, missing aria attributes; I may need some assistance figuring those out.

**Comment by noahmanger** [comment]
Re: the invisible targets, I thought we had a utility for this, and it turns out we do! https://github.com/18F/fec-style/blob/master/js/accessibility.js

That will remove tabindexes (and restore them) on hiding/showing.

Those other things sound like good to address as we can. Do you have a list anywhere you're tracking them all in?

The color contrast thing seems to be a false positive. I did a spot color check with a tool and it's showing up around 6.9:1.

And I'm happy to help out with datatable stuff. I know some issues can come up around the typeahead, because there's a hidden input or two.

**Comment by xtine** [comment]
Another pass of notable errors and warnings from CodeSniffer and Chrome Audits on <a href="https://docs.google.com/spreadsheets/d/1lVRrzdKEqqMwi9uVxf0_CyFgh6u7kHAR1-RZ8dzIxtg/edit#gid=0">this google spreadsheet</a> 🔒 Errors are highlighted in red.

**Comment by xtine** [comment]
I've done another round of accessibility updates on webapp and cms and updated the spreadsheet accordingly. There are some remaining issues that we can choose to address or not that are mostly content related (wagtail content or descriptive labels or captions) that are really just suggestions from the auditors. They are things we can consider later, but are really low on the priority list.

**Comment by noahmanger** [comment]
Awesome stuff. Thanks for finishing this out! I'm going to close this.
