### ISSUE TITLE
authorized committee profiles - add party/state/district information

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1969]
post-flip

For a candidate's authorized committee, can we add the candidate's party/state/district information?

https://beta.fec.gov/data/committee/C00545467/?cycle=2018
![image](https://cloud.githubusercontent.com/assets/11817734/25276581/eec020c2-2668-11e7-81d5-ece2e5d8b2b4.png)

 
https://beta.fec.gov/data/candidate/H0TX23086/
![image](https://cloud.githubusercontent.com/assets/11817734/25276587/f8f4b814-2668-11e7-892a-b35cf2828d57.png)

**Comment by noahmanger** [comment]
This was just requested from the public https://github.com/18F/FEC/issues/4118

**Comment by nickykrause** [comment]
We do have a place in the committee profile that links to information about the candidate -- maybe it would make sense to put something there, rather than in the committee's header? (Not sure if that is being suggested, but just wanted to weigh-in):

![group](https://cloud.githubusercontent.com/assets/1450173/26467889/04b9fd24-415a-11e7-9e6c-62f4b5a65aab.png)

In this case, maybe there would be another line for `Candidate's state and district` that reads `Missouri - 01`. 

Anyway, I'm open to the committee header, too, but I recall that we were intentionally trying to simplify the headers by moving some info to the `About this committee` and `About this candidate` pages.

**Comment by noahmanger** [comment]
How about this for house:
![image](https://cloud.githubusercontent.com/assets/1696495/26470615/3be6d74c-4153-11e7-9fa6-353bb52e217b.png)

And senate:
![image](https://cloud.githubusercontent.com/assets/1696495/26470643/51b8dc28-4153-11e7-8a7f-32693e8ca1fb.png)

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/2081
