### ISSUE TITLE
Add loading state to AO search

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1977]
So that users understand that the system is loading results (rather than finding 0 results), add a loading state to the AO react search.

---

Currently, when you go to the AO search page, the "No results" message flashes briefly while the results load. I think this should be replaced with a loading state, which should also appear in the time between adding a new filter and when the results are updated.

We have a loading state on finance data pages, but we might want to redesign slightly for this use case.

**Completion criteria:**
- [x] Design loading state
- [x] Implement loading state on initial page load
- [x] Show loading state after applying filters

**Comment by jenniferthibault** [comment]
We should use the loading state we use elsewhere on tables, designed wayyyyy back here: https://github.com/18F/fec-style/issues/24 and implemented in https://github.com/18F/fec-style/pull/46

**Comment by noahmanger** [comment]
My only thought was if we wanted a different, less "data-y" icon.

**Comment by anthonygarvan** [comment]
This one drives me nuts actually. I'm frequently confused if something is broken or if it's just loading. Will support getting this done soon because this time, it's personal.

**Comment by jenniferthibault** [comment]
Drives me nuts too @anthonygarvan :)

I've been thinking about this a lot, and I don't think it makes sense to have a loader specific to each part of the site—I'd rather we keep the approach simple and have one graphic.

I feel like the flag graph can work because it's not specifically financial, but is unique enough that you know it was created just for this site.

This opportunity was a good one for me to go back and rebuild the graphic so that it's a little less rough around the edges, which I had been wanting to do for some time. It's embedded below, but again since it's near-white on a transparent background, you won't be able to see it until you click to open it in a new window 👇 

![flag-animate_0-85](https://cloud.githubusercontent.com/assets/11636908/25635696/0d00c4d2-2f4d-11e7-8e6d-e2ca7e116e71.gif)


If we're ok with this approach, this issue is ready for implementation (I'm guessing we can follow the first implementation issue for patterns https://github.com/18F/fec-style/pull/46 ). 

If we don't want this design, I'd still advocate for making a more generic graphic that would be the loader used for every page/table on the site.

**Comment by noahmanger** [comment]
Works for me! Implementation-wise, adding this should do it:

```html
<div class="overlay__container">
  <div class="overlay is-loading"></div>
</div>
```

**Comment by jenniferthibault** [comment]
Status update: I sent @noahmanger a rebuilt animation in svg + js form last week, and he's working on figuring out the best way to integrate that as a new approach

**Comment by noahmanger** [comment]
Let's not have the creation of the new animation be a blocker for this. I think we should get it going first with the loading gif and styles we have in place and then we can swap it out once we figure out the better animation.

**Comment by jenniferthibault** [comment]
Sounds good!

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/2021

Thanks @anthonygarvan !
