### ISSUE TITLE
Design "total disbursements" figure on candidate and committee pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#2019]
So that users visiting the disbursements tab of a candidate or committee page can see the total, design a way to show it.

---

While we haven't implemented them yet, we have designs for showing totals on the individual contributions and other spending tabs; but we've learned from usability testing that users would like to see it on this tab as well.

**Completion criteria**
- [x] Designs ready for implementation

cc @nickykrause

**Comment by jenniferthibault** [comment]
Here's one way we could visualize this, with inspiration for the model of spending breakdowns in https://beta.usaspending.gov/:

We could re-introduce the categories seen on the financial summary page as percentages, and even give a bit more detail about what the category consists of. This would appear above the itemized disbursements table.

![screen shot 2017-05-10 at 5 00 20 pm](https://cloud.githubusercontent.com/assets/11636908/25921145/62699d4e-35a2-11e7-9ea0-624b4f4eaeb1.png)

On mobile, they could stack vertically:
![screen shot 2017-05-10 at 5 04 07 pm](https://cloud.githubusercontent.com/assets/11636908/25921234/beecce38-35a2-11e7-9c26-ec0532a6be14.png)

I think there's some thinking that still needs to be done specifically around how we link people back to the filterable data-table, but I wanted to get the idea out for feedback before that. @nickykrause ?

**Comment by jenniferthibault** [comment]
I'm going to back up from this idea one second—there are a few elements to this issue:

**Navigators expect a consistent model.**
People have shown that they expect consistency in the structure and contents of each tab. If the

**Comment by jenniferthibault** [comment]
Button fumble while writing an update, closed by mistake! Re-opening.

**Comment by jenniferthibault** [comment]
@nickykrause updated write-up above for your 👀

**Comment by nickykrause** [comment]
Looks great, @jenniferthibault! A concise summary of what we discussed, I think, and I'm glad we ended up picking up the piece we consciously left out from our last round of C&C page updates (but that we didn't log anywhere 😬 ). Thank goodness for your excellent brain.  😄

**Comment by jenniferthibault** [comment]
I believe this issue is done & ready to move to implementation, but defer to @noahmanger 's judgement

**Comment by jenniferthibault** [comment]
Had a great review session today with @llienfec and @jwchumley which helped reign this back in a bit.

Overall:
- We think that restructuring the side nav to use Raising and Spending is a good idea in order to keep the model consistent across the site
- We think that extending the side nav pattern to add child elements will support this structure
- We're interested in visualizations (maybe even the ones in this format), but think they are better suited for the financial summary page, since they can better show the information already on that page.

So we decided to just show the numeral of total receipts and disbursements, to keep it simple and give folks what they needed, but not over deliver. (This also let me focus on where/how to use the buttons that direct folks to the data tables). Here's what I'm thinking:

![screen shot 2017-05-31 at 8 07 33 pm](https://cloud.githubusercontent.com/assets/11636908/26659189/f94cabb6-463c-11e7-802f-9bdaf6e2e425.png)
![screen shot 2017-05-31 at 8 08 09 pm](https://cloud.githubusercontent.com/assets/11636908/26659190/f952f9bc-463c-11e7-852b-f2132c1e103e.png)

**Next**
Thoughts & review from @llienfec @nickykrause @noahmanger @jwchumley ?

**Comment by nickykrause** [comment]
@jenniferthibault This makes sense to me, and I like its simplicity. It will be a good place to start for testing, to see if the totals are meeting people's needs, which it seems like they will.

It is an interesting and useful idea to include the link to the financial summary, as you have, beneath the filter button. 

I assume that the committee pages would be similar to what you have here?

**Comment by jenniferthibault** [comment]
Oh yes! Thanks for flagging that, I omitted the committee profile mockups as shorthand since they'd be the same, but forgot to call that out. The copy would just be specific to data from a single committee instead of data from all of a candidate's authorized committees.

**Comment by llienfec** [comment]
Thanks for the amazing work on this @jenniferthibault and @noahmanger  

I talked to Brad Matheson, and he's happy to help out with any data visualization that you may need, even if it's just to bounce around ideas.

**Comment by jenniferthibault** [comment]
After a quick review in today's design pairing, here's a few new changes and some fresh mockups that I made sure matched current real functionality on the site:

- We decided not to duplicate the "Filter this data" button on the disbursements tab, since it would take you to the exact same data tables (no additional filters applied for sorting)

### Candidate receipt and disbursement pages
![screen shot 2017-06-02 at 3 10 17 pm](https://cloud.githubusercontent.com/assets/11636908/26741202/671c2b66-47a6-11e7-8abb-06332f9784d8.png)



### Committee receipt and disbursement pages
![screen shot 2017-06-02 at 3 09 22 pm](https://cloud.githubusercontent.com/assets/11636908/26741216/79780154-47a6-11e7-8fd7-3be44b65e34b.png)

@noahmanger I think this is now ready to go.

This issue also addresses #1869 , so I'm going to close that

**Comment by noahmanger** [comment]
Looks good! I'll flesh out the implementation issue now.
