### ISSUE TITLE
downloads issues

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#2023]
I am not getting good results out of dev, staging or prod, sometimes they work. most of the time they are not working for me. This is probably a performance killer too.

**Comment by LindsayYoung** [comment]
I am going to try deleting and recreating the redis service on stage

**Comment by LindsayYoung** [comment]
that did not help, seeing a lot of pool overflow errors

**Comment by ccostino** [comment]
D'oh, if the DB connection pools are overflowing with downloads too it sounds like https://github.com/18F/openFEC/issues/2371 might be related; there has to be something that changed recently that is now contributing to the connection pools overflowing and timing out.

**Comment by ccostino** [comment]
It appears that downloads are working again in `dev` (though they were failing last night).  I'm not sure what changed there, likely another deployment, so we should keep our eyes open.

`stage` is still not working because the Redis service is not bound to any of the applications.  When we create the next set of release branches, that should fix the issue and we can retest then.

For completeness sake, `prod` downloads have been working fine.

**Comment by ccostino** [comment]
With the redeploy of the apps to staging, downloads are working there again as well!

**Comment by ccostino** [comment]
This was an issue due to the Redis service being unbound.  I think it's okay to consider this done and if it comes up again we can re-open this.
