### ISSUE TITLE
Design interaction for boolean searches for legal resources

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#2069]
So that users can create boolean searches when searching legal resources, design an interaction for how they do this.

---

In our last legal grooming meeting we determined that there might not be enough data on this, but agreed that it could be worth starting design efforts if we have time.

cc @nickykrause

**Comment by nickykrause** [comment]
Assembling some examples of complex academic/legal/other searches in [this Mural](https://app.mural.ly/t/gsa6/m/gsa6/1496932933078/e6ffbd3d2d5c58047511a6cf9800cbf8c5314d53) 🔒 , for future reference and inspiration:

**Comment by nickykrause** [comment]
Wanted to offer an update here. 

We talked in the design pairing last Friday about the potential for this task to quickly expand in scope, depending on: (a) whether or not we offer boolean search for facets other than keywords (e.g., combinations of requestors or citations or dates), and (b) to extent to which we make boolean searching available outside of the filter tables for AOs, MURs, etc.

In that meeting, we decided that it would be helpful to focus only on offering boolean searching for keywords, both on and off the filter tables for legal resources.

This led me to explore two approaches, so far, which I discussed with @jenniferthibault this morning, and which I am summarizing here in separate InVisions. These files contain comments that explain the thinking behind the designs:

**Accordions** [design](https://gsa.invisionapp.com/share/ECC5Y1MBG#/screens/238949338/comments)

**Separate search page** [design](https://gsa.invisionapp.com/d/main/#/console/11303809/238953395/comments). This one is very short and has no comments on it. The idea is that advanced "keyword search" functionality would exist as its own page, rather than as an accordion. This does not address how the search would work on the filter panel, however.  

One thing that Jen and I discussed was that these two solutions seem to exist at two extremes: The accordion approach attempts to keep the user "in context" as much as possible, while the separate page approach pushes the user "out of context" completely, by taking the person elsewhere.

So, as a next step, I'm exploring a more middle-ground option of using a modal / dialog window to present a special context for filling out the special keyword fields. 

Finally, one important thing to note is that none of this, as of yet, reflects any conversation with devs about what is/is not possible for boolean search using our current structure. 

@noahmanger - If you have thoughts, feel free to jump in. I am also happy to chat synchronously. Who should I consult with in dev, by the way, if I have questions? Tony/Vraj?

**Comment by noahmanger** [comment]
Smart thinking on this! The idea of including it in the main search entry hadn't occurred to me, but it seems to make a lot of sense here, particularly because it gives you the chance to learn how to use the different operators. And because it keeps the filter panel from getting too crazy, I think I lean towards this view, especially if you can use the same operators in the regular keyword filter box. Maybe worth doing something to denote that the field supports boolean logic?

As a slight *yes and*, On the filter side, I could also see something like we do on the data side where we generate checkboxes for each search term, but that translates the operator into a word, like:
![image](https://user-images.githubusercontent.com/1696495/27157967-370e8cbc-5119-11e7-9c93-45d2eeaf9965.png)

And from a development angle, seems like we could start by providing this functionality from the API and users who are aware of it (i.e. internal folks we tell) could make use of it with regular inputs, and then we could add the front-end functionality to expose it. 

@anthonygarvan could speak to what's possible from the ElasticSearch angle.

**Comment by nickykrause** [comment]
@noahmanger: Thanks! I like the checkbox idea, too -- I will add that thinking to this last design that I'm exploring with the modal window. Also, I agree it would be helpful to somehow denote that the main field supports boolean logic.

In the meantime, assuming that I understand your point, I agree that we can start on the dev of it and make the main search box capable of supporting the boolean operators, even as we figure out the front-end

Planning to update this again later today. 

Thanks for weighing in, Noah and Jen!

**Comment by nickykrause** [comment]
Just adding this as an FYI: I spoke with a couple people from the FEC policy division today. They provided general feedback about the AO search experience (as well as the broader legal resources search experience), and added their concern about the ability to conduct and/or searches in particular. 

Seems like more fuel for the argument that getting the ability to do this in the keyword box (even without an elegant front-end) would be helpful for the internal FEC folks to whom we can provide info about how the boolean searches can be composed.

**Comment by nickykrause** [comment]
Alright. After some research into best practices for modal experiences, I have explored a **modal window option** ( 🎨 [see here](https://gsa.invisionapp.com/d/main/#/console/11316408/239213570/comments)) that resolves the accordion-within-an-accordion issue mentioned above. 
- As a part of these designs, I am also showing what the "checkbox" approach might look like for the advanced filter panels, as opposed to leaving the boolean search string in the search box itself. 
- **Check out my comments on the InVision and feel free to add comments, if you wish**.

---

@noahmanger and @jenniferthibault -- I'd love to chat about this in the design sync tomorrow. We can also use that time to introduce the thinking to @jameshupp, whom I should have tagged in sooner (sorry, James! 😞 )

**Comment by nickykrause** [comment]
Closing this issue because we have [discussed with dev](https://github.com/18F/openFEC-web-app/issues/2162) and are moving future discussion to the [implementation issue](https://github.com/18F/openFEC-web-app/issues/2170)
