### ISSUE TITLE
Make it easier to access bulk downloads from data pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#2074]
As reported in https://github.com/18F/FEC/issues/4076, the link from a data page to the bulk downloads is hard to access in the tooltip. We should make it easier.

Probably worth starting by looking at the interaction design. There's probably a better way to send people to this page than through a link in the tooltip.

cc @nickykrause

**Comment by nickykrause** [comment]
cc @noahmanger, also @jenniferthibault if you are watching this issue at all:

Some initial thoughts on how to address this issue, at least in the short term. I prefer option 1. 

![bulk data](https://cloud.githubusercontent.com/assets/1450173/26467610/028b707e-4159-11e7-8220-578c29d981f8.png)

**Comment by jenniferthibault** [comment]
@nickykrause 1 or 4 feels like a better match to me because they don't replace the button. What do you think about positioning the alert on the left-hand side of the button instead so that it appears/disappears without needing to bump the button over as it does, which feels like it would be disruptive.

Overall the info alert in 4 feels like a correct (but new!) use of the pattern, so I'd guess we'd need to adjust a new small-format class for it. I think I lean most to 4 with the swapped position of the alert, then button.

**Comment by nickykrause** [comment]
@jenniferthibault . option 4 was my second favorite, so I'm cool with that. Also, 💯 to your comment about moving the button. I agree! Here's option 5, then, with your comments incorporated:

---

![5](https://cloud.githubusercontent.com/assets/1450173/26468121/ea5bde6a-415a-11e7-8217-bc06b1e6f954.png)

Not sure about the microcopy here. Maybe it would be better not to start with the dependent clause, and just to say: `Use the bulk data exporter to export more than 100,000 records.` I didn't go for that originally because it puts the link in the top line, which puts the underlining in the middle of the two lines, like so:

![group](https://cloud.githubusercontent.com/assets/1450173/26468241/4d08d13a-415b-11e7-8c75-af6f776010b0.png)

But perhaps that is fine.

**Comment by jenniferthibault** [comment]
@jameshupp could you lend us your expertise on interface copywriting here? Is it better to put the dependent clause before or after the instruction?

**Comment by noahmanger** [comment]
This makes a lot of sense to me. Nice work!

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/2083
