### ISSUE TITLE
IE Suggestion

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC-web-app#2107]
A suggestion that may make it easier to use: Looking at independent expenditures today, I found it confusing that you had to filter the data by either regularly scheduled reports or 24/48 hour reports. To get a comprehensive view of outside money spent in the Montana House race, I had to download both separately then combine them in Excel. Maybe I’m missing the reason why you set it up the way you did, but I think it would be better to have the view default to show both types of reports, then let the user filter by one if he or she wants to. 

Reported from webmanager's inbox

**Comment by noahmanger** [comment]
@LindsayYoung can probably fill in more details, but this was a design decision made in order to reduce potential confusion. Because the same transaction may be reported first on a 24/48 hour report and then again on a Form 3X, it would be potentially confusing and misleading to show them all in the same view.
