### ISSUE TITLE
Difficulty finding electronic filing information

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#2132]
Users need to find information about electronic filing.

Several users have reported difficulty finding the electronic filing information they need, specifically the FECfile download, 

Related issues: https://github.com/18F/FEC/issues/4221 and an email from a compliance professional 
(https://github.com/18F/FEC/issues/4228 is about broken links/redirects but the user was looking for electronic filing information)

Possible solutions/ Suggestions to help users find electronic filing information:
One good short-term aid might be to expand the descriptive text in the main nav menu for Help for Candidates and Committees. The title ("help") signals there are resources to do your work there, but the current blurb underneath it, to me, suggests descriptions of groups and requirements rather than offering resources to do it. We could play with expanding that blurb a bit?

Putting eFiling on the mini-menu for Help for candidates and committees, calling it out the way we just did for individual contributors on the data menu.

Efiling is the same across all of the pages.  It’s built into the candidate page, and so we need to move it out of that section in wagtail and into the general help for candidates and committees sections.  It’s going to take some link testing to do it and make sure everything continues to work. 

- [x] Make sure search results are getting folks to eFiling support where appropriate
- [x] Add eFiing support to search suggestions
- [ ] Create redirect for old eFiling page
- [ ] Explore options for adding eFiling to menu options

**Comment by jenniferthibault** [comment]
Looking into the search logs from 7/01/17–8/24/17, here are the relevant search phrases (out of the top 100 search phrases) to electronic filing. 

| Search ranking | Term | Number of searches  |
| ------------- |-------------| -----:|
| 5.   |`fecfile` | 160 |
| 6.   |`electronic filing` | 124 |
| 15.  |`password` | 75 |
| 27.  |`fec file` | 57 |
| 65.  |`efiling` | 33 |

I chose this period because it covered several filing deadlines. 

I then repeated these searches to see if the results returned were adequate. 

**In two cases the results returned were adequate and helpful:**
- [Search results for `fecfile`](https://www.fec.gov/search/?query=fecfile&type=candidates&type=committees&type=site)
- [Search results for `electronic filing`](https://www.fec.gov/search/?query=electronic+filing&type=candidates&type=committees&type=site)

**In the remaining three, the results would not help you find what you were looking for, and could be improved through assigning some "Best bets" results**
- [Search results for `fec file`](https://www.fec.gov/search/?query=fec+file&type=candidates&type=committees&type=site)
- [Search results for `efiling`](https://www.fec.gov/search/?query=efiling&type=candidates&type=committees&type=site)
- Search results for `password`

**Comment by jenniferthibault** [comment]
Oops! Hit comment too soon...still writing ^

**Comment by jenniferthibault** [comment]
I set up a best bets match for each of those keywords to ensure they're bringing people to the most relevant page at the top of the list:
![screen shot 2017-08-24 at 11 49 53 am](https://user-images.githubusercontent.com/11636908/29676640-988823c4-88c6-11e7-872f-f8f1c35e9ef0.png)

In https://github.com/18F/FEC/issues/4221 we also heard that finding the filing software download was a little difficult—I made a small improvement that turned the download link into a call to action button through custom HTML to make it more visible, as well as labeling the button with the version that's being downloaded so users know if they have the most recent version available.
(_previous on left, updated on right_)
![screen shot 2017-08-24 at 12 44 39 pm](https://user-images.githubusercontent.com/11636908/29677835-666bb9d8-88ca-11e7-83ec-71708125b8ae.png)


________________________
## Next steps

- I've been taking this on in small pieces, but now ready to look straight at the elephant 🐘 in the corner...moving Efiling in to the main nav feels like a big step , and I'm wondering if some of these smaller changes will start improving the experience. If efiling guidance and resources are one of the top-sought information from this section, I've been thinking about how we might work that into a different approach to the landing page in #2185 . Curious to hear what other folks think about holding off on moving into the nav for now.

 - @patphongs @johnnyporkchops , are there any outstanding redirects still needed?

**Comment by AmyKort** [comment]
Thanks, Jen! I think it would make sense to implement these changes now and then take a little time to see how it works for folks before we make changes to the nav bar.

**Comment by jenniferthibault** [comment]
@patphongs @johnnyporkchops can you confirm if there are any redirects still needed? 

If not, let's close the issue. If there are, let's identify them and track the work in sprint 3.5.

**Comment by patphongs** [comment]
@jenniferthibault @llienfec For redirects regarding this ticket, I am unsure whether or not the filing pages will be moving? If so, there could be new URLs that need to be redirected in wagtail. Current redirects that are set up are the following below. @llienfec Can you please confirm that this is all the redirects that are needed? If so, we'd like to close this issue. Thanks! 

https://www.fec.gov/help-candidates-and-committees/electronic-filing
https://www.fec.gov/help-candidates-and-committees/paper-filing
https://www.fec.gov/help-candidates-and-committees/get-filing-software

**Comment by jenniferthibault** [comment]
After a quick check with Lauren and Pat, it looks like the redirects put in place for https://github.com/18F/FEC/issues/4228 that Pat mentioned above should cover our first pass at completing this issue.

A [testing issue has been filed](https://github.com/18F/fec-testing/issues/78) to measure the success of users trying to find efiling information that suits their needs. Closing this issue
