### ISSUE TITLE
Identify and prioritize homepage objectives 

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#2157]
To help users effectively navigate the website and easily find the content they're looking for, we're beginning work on version 2 of the homepage. Step one in this project is to identify and prioritize our homepage objectives.

**Comment by jenniferthibault** [comment]
Carrying over existing issues identified in https://github.com/18F/fec-cms/issues/1101

#### Home page issues
- [Unclear about difference between "What's happening" and "Upcoming events" #4198](https://github.com/18F/FEC/issues/4198)
    > “I find the difference between the "What's happening" and Upcoming events" sections to be unclear. Both contain future items– sometimes the same item– blurring the difference.”
- [Request: more content above the fold on the home page #4095](https://github.com/18F/FEC/issues/4095)
- [Can't find individual contributors data #4224 (most common issue)](https://github.com/18F/FEC/issues/4224)
- Make it easier to post a temporary update on the home page (with expiration, links)
- How are we using the featured/pinned items now? Can we improve guidance on what/how to use titles and links? This is confusing and not used well
  - <img width="1013" alt="screen shot 2017-06-23 at 6 41 13 pm" src="https://user-images.githubusercontent.com/11636908/27502647-a548edae-5843-11e7-8700-19183291f501.png">
__________
Will follow up shortly with principles and goals assessment: right now I'm trying to figure out how to untangle all of these related issues

**Comment by jenniferthibault** [comment]
To get a clear picture of where we stand, I wanted to assess what v1 of the home page was doing well, what could be improved, and what it wasn't doing well. A retro informed by the goals we initially set for v1, and feedback reported from the public and the project team.

The full collection of that research is in this [Google Doc](https://docs.google.com/a/gsa.gov/document/d/1AyqIQetCoCrmIEWIf0do_e3VRFf0YkrU_m3IHVU_jWY/edit?usp=sharing) 🔏 .

## Summary:

### What the home page is doing well (keep)
- States a clear purpose and value proposition
- Unbiased, informative perspective
- Help users learn about upcoming events and news/announcements at the agency
- Alerting users that they can provide feedback on the site

### What the home page could do better (improve)
- Provide an entrypoint for commission meetings (could be home page, could be nav in general)
- Prioritize & clarify through reducing less effective content & clutter
- Highlight topics that are relevant to the news cycle that aren’t necessarily in the regular publication pattern (ex: foreign nationals)

### What the home page isn’t doing well (& should start doing; needs not met)
- Find a better mechanism featured content that allows the FEC to show “featured” specific content, AND communicate a time-sensitive message simultaneously (like an ongoing meeting or filing deadline). Right now you can only do one or the other, since it’s the same module and position.

### What’s not working on the home page
- Not able to use spaces designed to surface cyclical content for specific groups. This creates a lot of seemingly duplicated links and content, especially in the “Help for…” section.

___________
This seems like it could be a concrete, actionable list of improvements and goals we can work with for v2. I don't _yet_ think we need to prioritize between them, but I would expect that different design options may offer us choices about what gets higher priority. 

**Next steps:**

- @AmyKort & @johnnyporkchops,  want to take a look at this and see if it makes sense to you? Glad to meet and talk things through
- Jen to start mocking up next iterations in #2159

**Comment by AmyKort** [comment]
Super-smart! Thanks for the research document.

**Comment by jenniferthibault** [comment]
Moved to design in #2159
