### ISSUE TITLE
Improve findability of meeting agendas and information

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#2158]
Users are having difficulty locating current and historical meeting agendas and documents from the website. Currently, these documents are housed in Latest Updates and announced via the FEC calendar. We need to determine more intuitive location(s) for these items to ensure that users can:

Keep track of upcoming meetings and events
Attend/watch meetings
Find agenda documents from current meetings as they become available
Find (search and sort?) historical meeting announcements and agenda documents

Related to https://github.com/18F/fec-cms/issues/1094

**Comment by jenniferthibault** [comment]
Here is a collection of meeting-specific issues initially gathered in https://github.com/18F/fec-cms/issues/1101

- [Can't find recordings of hearings #4206](https://github.com/18F/FEC/issues/4206)
- [Trouble finding past open meetings #4229](https://github.com/18F/FEC/issues/4229)
- [Difficulty finding meeting agendas #4172 (closed)](https://github.com/18F/FEC/issues/4172)
- [Easier path to commission meeting pages #2079](https://github.com/18F/openFEC-web-app/issues/2079)
- [Confusion around meeting pages being published from the future in latest updates #1094](https://github.com/18F/fec-cms/issues/1094#issuecomment-313676868)
- Where do meeting pages live?
- Via calendar: hard to find a commission meeting from the past
- People expect list they can easily scan by date, similar to old site

I'll come back around for more analysis, right now I'm trying to figure out how to break down this plus home page work.

**Comment by jenniferthibault** [comment]
## Quick improvements:
The first quick win we can make in this direction is happening via the homepage in #2159:
- Create a predictable, fixed position for finding the next meeting. This would link to the latest updates feed filtered to meetings, which allows users to sort meeting by year than the calendar does.

![screen shot 2017-07-14 at 10 57 07 am](https://user-images.githubusercontent.com/11636908/28217484-38837d10-6883-11e7-8cae-f56bb18f48ad.png)

## Additional steps we could take

### Move information about the agency's activities into a more prominent position
If users think of meetings and news as a way to find out about what the FEC does & what's going on in it's world, it makes sense to align those with "About". To help people stay up to date on this info more easily, and find it more predictably (referencing the filed issues above), we could try placing "About" in the top nav—a common pattern for sites in general.
![screen shot 2017-07-14 at 11 06 04 am](https://user-images.githubusercontent.com/11636908/28217815-7887bfec-6884-11e7-97d5-8e8596ed4e17.png)

There could be a follow-up task here to think about how/if we should integrate these two links on the About landing page, but I don't see that as a true dependency for integrating it in the nav.

### Separate Meetings from News and announcements (formerly Latest updates)
Events and publications weren't working well together in one feed, so let's separate them. This brings us closer to the previous model the FEC used, and will feel familiar.

A feed of Commission meetings needs less preview data than a feed of mixed publications, so I think an adjusted format from the standard feed pattern would do that best. (but we can still make use of other patterns, like our tables!)

Here's a few starting options that definitely would benefit from time discussed in design pairing:

#### A. Two feeds, notices live on meeting pages only
- This is the best use of space and is quickly scannable for meeting dates
- ![screen shot 2017-07-14 at 11 25 54 am](https://user-images.githubusercontent.com/11636908/28218677-3f512904-6887-11e7-9d86-917d64e2ff43.png)

#### B. Two feeds, notices accessible from feed and meeting page
- This page appears more cluttered and longer, but helps the FEC show compliance with the SunShine Act from one place.
- Surfacing Sunshine Act Notices on this page easily lets the FEC show that they are complying with that Act from one screen—however, the notices also live on each meeting page, so this _may_ not be totally necessary, it would just change how they've done things.
- ![screen shot 2017-07-14 at 11 27 07 am](https://user-images.githubusercontent.com/11636908/28218732-6fc8a09e-6887-11e7-91b3-312ec1618129.png)

#### C. One sortable feed, notices accessible from feed and meeting page
- This would create the longest page, but it appears less cluttered and easier to scan, while still viewing Sunshine Act notices in one place. I think we'd need to incorporate pagination to help with page length.
- ![screen shot 2017-07-14 at 11 27 17 am](https://user-images.githubusercontent.com/11636908/28218737-772f66d8-6887-11e7-83b0-b5427d1f3483.png)


### Next steps:
- Discuss in today's design pairing ( 👀  @noahmanger @rhoughfec )

**Comment by rhoughfec** [comment]
Thanks Jen, this looks great!

**Comment by jenniferthibault** [comment]
Had a great review in design pairing today, and I have an update based on that feedback:

- We do want to pursue the "About" nav item 
- We do want to pursue a separate meeting page slightly different than the options above. The page should:
  - Separate the kinds of meetings: open meetings and public hearings will always be more useful to outside audiences because members of the public can attend or follow along from home.
  - Incorporate a side nav (tabbed or jump) so it's easier to scan the list of options to view.
  - Incorporate search by keyword
  - The lists should default to displaying all years (but add pagination to make this more manageable) 
  - The year should be a select, not a text field, since digital meeting records don't go that far back
  - If we can keep the layout uncluttered by simplifying meeting titles and dropping the type of meeting from the label, we should surface the Notices on the landing page to help the commission show compliance with the Sunshine Act with more easily

**Design questions to consider**
- There are only a few hearings per year—previously they were listed with open meetings. Should they stay with them, or be separated out? In this mockup, I made them their own category because it helped reduce the labeling needed in the table items (we could drop the meeting type from the title) and because it seems like it would help find the hearing needles in the open meeting haystack more easily.

![screen shot 2017-07-14 at 5 50 22 pm](https://user-images.githubusercontent.com/11636908/28232110-fc5f8aec-68bc-11e7-8a06-661d4442844f.png)

We'll be demo-ing this on Monday 😎

**Comment by jenniferthibault** [comment]
Moved to implementation in https://github.com/18F/fec-cms/issues/1138
