### ISSUE TITLE
Design version two of homepage

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#2159]
Need to create design of version 2 of homepage

**Comment by jenniferthibault** [comment]
The goals of v2 (and how we got to them) were outlined in #2157 , but I'll quickly recap them here as to show how we got to the design choices in this draft:

- In order to prioritize attention better, we reduced many content elements that were either going unused, or weren't able to be used as we had originally designed them. Re eliminated the page sections that gave previews of what each section contained.
  - This keeps the page focused on what's recent and relevant at the FEC
  - We left the "Introduction to campaign finance and elections" section because that provides a gateway for novice users, and surfaces two commonly accesses features on the site (election zip search and contribution limits), which are used by many user groups
- To provide greater distinction between "What's happening" and "Upcoming events", we suggest renaming the sections to "News and announcements" and "Events and deadlines" (or something in that neighborhood).  This may mean we should rename "Latest updates" to match.
  - The "News" section would now show the most recent publication in each category instead of the 4 most recent things published. If there is a pinned item, "Weekly digest" item drops out of position, since it is a summary of the other items.
  - Similarly, in "Events" the next upcoming _in each category_ would be shown instead of the next 4 chronological of any category. This allows us to show the breadth of what's in the calendar, and importantly **positions the link to meetings in a predictable fixed location on the homepage** (which helps us toward #2158 )
- In order to separate the time-sensitive announcement from the publication cycle, we've used our existing informational alert pattern to make a separate module. The functionality (setting time and expiration) would stay the same, but this should be a home page feature instead of a temporary latest update page. When there's no time-sensitive announcement, the red spacing slab would disappear.
- In order to lighten the feel of the page and create more readable text, we've restyled the layout of the hero image and text box following the US Web Design standards pattern.

An implication of this design is that by removing the obvious repetitions and descriptions of the site sections, we've ensured that users will rely on the site nav bar to find their way around—since it mostly looked like users weren't engaging much with the expanded home page slabs, I expect this will be ok, but worth mentioning.

![home-v1 copy 25](https://user-images.githubusercontent.com/11636908/28149129-417a3560-6759-11e7-924d-a690cab56a24.png)


____________________________________
Since we largely aren't changing or adding new components, I haven't specified any new mobile layouts, but could do that as a next step if needed.

@AmyKort , @johnnyporkchops and I reviewed this concept with a few other variations today, and decided to move forward with testing this one.

## Areas for research/testing
- Can users reliably find committee meetings and their agendas?
- Do users immediately recognize when there's a time-sensitive thing happening at the FEC?
- Have we changed the ability for data seekers to find what they need?
- Have we changed the ability for members of the regulated community to find what they need?

**Comment by jenniferthibault** [comment]
In order to check some of the areas we're interested in without the benefit of as much testing as we'd hoped for this sprint, I looked into the current home page analytics and found something that suggests we make one change for the first iteration:

Over the last month, here are the % clicks on each section's slab on the home page:

![screen shot 2017-07-14 at 3 58 44 pm](https://user-images.githubusercontent.com/11636908/28272649-1dbea7a8-6ada-11e7-86f4-756a03d9447a.png)
![screen shot 2017-07-14 at 3 58 27 pm](https://user-images.githubusercontent.com/11636908/28272662-27e0144c-6ada-11e7-8ed2-d30f28ca16b4.png)
![screen shot 2017-07-14 at 3 58 11 pm](https://user-images.githubusercontent.com/11636908/28272670-2e43dbb6-6ada-11e7-89aa-1198eb5d3ac4.png)
<img width="1255" alt="screen shot 2017-07-14 at 3 57 49 pm" src="https://user-images.githubusercontent.com/11636908/28272673-309f7000-6ada-11e7-9681-3e4049d1627f.png">

The _Help for candidates and committees_ section was getting pretty significant engagement, while the other sections got little or none. 

I hypothesize the reason for this stems from this issue: 
 - A few users who open H4CC menu seem to think that all it has are forms, deadlines, trainings. [testing-#67 ](https://github.com/18F/fec-testing/issues/67)

The current _Help for candidates and committees_ section embeds the "choose the type of thing you are" onto the landing page, so we hadn't created a separate link for it. But the home page traffic and that testing issue shows that it would help point people in the right direction if we _did_ include a link. 

**Current menu**
![screen shot 2017-07-17 at 10 35 00 am](https://user-images.githubusercontent.com/11636908/28273213-b62ccfb4-6adb-11e7-85d0-3e0a8d27cb70.png)


**Proposed change to menu**
![screen shot 2017-07-17 at 10 35 09 am](https://user-images.githubusercontent.com/11636908/28273218-ba480fbe-6adb-11e7-8e31-d50b0453d156.png)

This also gives us new criteria to measure v2 with through analytics:
- Does simplifying the rest of the page improving engagement (by clicks) with the _Introduction to campaign finance and elections_ section?
- Do people click "Campaign guidance" in the help for candidates and committees menu?
