### ISSUE TITLE
Elections work-stream: Research other design solutions / inspiration board

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#2163]
Clarification on this issue for @patphongs:

When we do decide to tackle the actual design process for the election map and the compliance map, the purpose of this issue is to remind us to review other solutions to similar design problems. 

The user stories that we generate from our research will make it clear what our users' needs are. In addition to brainstorming our own solutions to meet their needs, it can be helpful to ask: How have other people solved similar problems? 

Also, when we start to sharpen our focus onto specific feature ideas (e.g., specific data visualizations, specific interactions, etc.), we can ask: What are some ways that other designers have handled this feature? What seems to be working, and what doesn't? Do there seem to be common, well-established interaction patterns (will users have expectations for how this will work)?

The inspiration board will be something that we return to throughout the design process. There isn't exactly an identifiable moment when it is fully "finished"

We can talk more during our sync about the timing of this issue.

**Comment by nickykrause** [comment]
@noahmanger -- It seems like this issue is not really necessary, so I thought I'd give you a heads-up about it prior to grooming. Basically, we made this issue during PI planning to call out the process of looking at other solutions while we approach our design process for the elections stuff. 

It was always going to be an optional thing, depending on what we thought was needed at the design stage.

**Comment by noahmanger** [comment]
Agreed.
