### ISSUE TITLE
Elections work-stream: Research/consider cyclical nature of election data

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#2165]
Research/consider cyclical nature of election data

**Comment by nickykrause** [comment]
I don't think we actually need this to be an issue. We had it on the PI planning board as more of a reminder, rather than its own task. We didn't want to forget that the elections data may be of more interest to people at certain points of the cycle than others, and so we should consider what that means for our designs.

However, this is something that came up clearly in our research, so it is already captured there.

I'm closing this
