### ISSUE TITLE
Boolean keyword search implementation (AOs)

### ISSUE THREAD

**Issue by nickykrause** [18F/openFEC-web-app#2170]
This is a placeholder issue for the next phase in the development of the boolean keyword search functionality for AOs. 

I am not sure yet on the details of how we will approach the dev work, so a more helpful description may need to be filled in for this issue during legal grooming or sprint planning. 

The designs can be found [here](https://gsa.invisionapp.com/share/9XC6RNVW5#/screens/239213570_Legal-Home-Modal-Default), with the following notes: 
-  We will likely need to wordsmith some of the microcopy once we have more details from dev about how exactly the search works
- After talking with @patphongs and @anthonygarvan in the design/dev pairing, we think that the “but not” search should use a minus sign instead of %
- Also after talking with Pat and Tony in the design/dev pairing, we think that of the two options shown in the design for the advanced search filter panel, we would prefer to use the checkbox pattern (rather than stuffing the whole string into the keyword search box), but we are open to shifting if that is complex. (Or maybe we make that its own issue, to come later.)

This will be implemented in 2 parts:
1. Implement parsing logic on backend, so that existing keyword box can be used with AND / OR etc.
2. Implement front end design, including query builder and tags.

**Comment by AmyKort** [comment]
pinging @jenniferthibault to look at design

**Comment by jenniferthibault** [comment]
Thanks for the ping, Amy!

I made a few styling adjustments to the icon, the modal styles, and placed the checkboxes between the field label & search field:

![screen shot 2017-07-18 at 2 50 21 pm](https://user-images.githubusercontent.com/11636908/28334635-b5e6e5f0-6bc9-11e7-85bc-76f84f75badc.png)
![screen shot 2017-07-18 at 2 50 27 pm](https://user-images.githubusercontent.com/11636908/28334633-b5e4f2ae-6bc9-11e7-9965-a904b44d7633.png)
![screen shot 2017-07-18 at 2 50 53 pm](https://user-images.githubusercontent.com/11636908/28334634-b5e5c45e-6bc9-11e7-83a0-b22a45745ad1.png)

**Comment by jenniferthibault** [comment]
This morning, Nicky, Tony & I clarified that:
- Queries will be reflected in tags, checkboxes, and the text string in the search field. Editing one will update the other two, and start the updated search
- entering any text in the keyword field without operators will treat the terms like an "or" search, consistent with how the rest of the site works
- When you enter an invalid search, then choose `more keyword options`, the fields will be populated with your last valid search combination

### Updated screenshots:
![screen shot 2017-07-19 at 1 15 35 pm](https://user-images.githubusercontent.com/11636908/28381157-d3058de4-6c87-11e7-9856-92d1c26cc89e.png)

### Notes:
- The error state is a pattern _I know_ exists, but don't have in my design files. @xtine sorry to drop you into an unrelated issue, but this is the same pattern we should be using in the data-side server error messages. Do you know how to summon one of those so that @anthonygarvan  can use the same pattern here?
- **Microcopy content design need:** @jameshupp could you lend your expertise and let us know if we should do anything different for the error message here? 
  - `Invalid search.  Try using keyword options to create your search terms`
  - For comparison, in the date picker, we use the following message: `You entered a date that's outside the two-year time period. Please enter a receipt date from 2017-2018` which I believe was structured to tell people what went wrong, then tell them how to fix it.

**Comment by jameshupp** [comment]
I don't think the explanation here can be quite as clarifying as it was for the date picker, since there are several ways someone could create an error here but there's really only the one there.

One thought I had while looking at this: invalid searches often return either all results or no results. If we're giving them their previous results we probably ought to tell them that explicitly. @jenniferthibault The most recent screenshot you shared shows no existing search, so presumably they get all results without a filter added. But what about one where they already had results and then entered an invalid search? Will it look like the third screenshot, only with the red text instead of green?

Here are a couple versions of text that I think could work for both an existing search and no existing search. One that is heavily focused on filtering:

`Invalid search, no filter added. Use keyword options to create a search with multiple filters.`

One that's just explicit about it in the first line but is otherwise really similar to what you already have:
`Invalid search, no filter added.  Try using keyword options to create your search.`

I think the plain meaning of search "terms" includes the keywords but not the operators, so I didn't really like suggesting `keyword options` would create the terms.

Not sure about space constraints on any of this, can probably cut down if that seems excessive.

**Comment by jenniferthibault** [comment]
Good call - @anthonygarvan can you confirm what James is asking about what happens when the search is invalid?

**Comment by anthonygarvan** [comment]
If the search is invalid it will show previous results (hope that answers your question).

**Comment by jameshupp** [comment]
@anthonygarvan It's a little narrower than that. In addition to the results, does it also show the checkbox(es) from the previous search, the same way it would show the checkbox(es) from a new successful search?

**Comment by anthonygarvan** [comment]
@jameshupp yup, same search results / tags.

**Comment by AmyKort** [comment]
Great! Are we ready to close this issue? Or are there next steps on this one?

**Comment by jameshupp** [comment]
I'm a little bit lost now on whether #2235 is going to handle this. The title sounds like it is, and you can see on this issue page that it was at one point referred to in #2235, but that reference is no longer there on that issue. @noahmanger, since you're working on that other issue, should we ignore this one for now, or do we need to close this independently?

**Comment by noahmanger** [comment]
Oh sorry. Yeah we can go ahead and close this. Thanks @jameshupp .
