### ISSUE TITLE
Design new button linking to candidate comparison pages from candidate profile

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#2198]
So that users can easily compare candidates running in a race, create a more prominent link to comparison pages from candidate profile.

---
Concept:
![concept](https://user-images.githubusercontent.com/1450173/28283639-ecdddae0-6af3-11e7-9881-4f7638b985ce.png)

Follow-up from https://github.com/18F/openFEC-web-app/issues/2167

**Completion criteria:**
- [x] Figure out where the button lives on the page
- [x] Figure out what the button text is
- [x] Figure out style of the button
- [x] Design end-to-end interaction for the button: where does it take you, how do you get back?

**Comment by jenniferthibault** [comment]
### Button style & placement
Since this needs more attention than a regular link, but it a little much text for a regular button, it feels like a good case for our small card pattern.

We had initially marked out space for a quick intro line to the Financial summary (and other) sections, so I've pieced that in as part of this since it helps with some of the layouts.

👀 ing three different locations:

1. Fixed below the menu, which keeps it accessible from any tab but competes in visual hierarchy for attention with the menu

![screen shot 2017-07-27 at 8 58 19 pm](https://user-images.githubusercontent.com/11636908/28698211-c0b46a00-730f-11e7-8726-af01e3212b4e.png)

__________________________
2. Fixed in the title space. Would need to drop the standard card pattern for a large button instead, since the space is too short, but would keep it available from any tab

![screen shot 2017-07-27 at 8 58 01 pm](https://user-images.githubusercontent.com/11636908/28698216-c78cddb2-730f-11e7-84aa-4ff2513d01c3.png)

__________________________
3. In the right-hand column. This feels like a really good place for a card element, since it's a familiar use of space, but puts it only on the financial summary tab. Since this is usually the first tab, that's ok, but we'd probably want to repeat it _at the least_ on the "About this candidate" tab

![screen shot 2017-07-27 at 8 57 04 pm](https://user-images.githubusercontent.com/11636908/28698219-ce9a7b64-730f-11e7-8a01-b884b0d22d93.png)


__________________________
### End to end experience: how do users get back

- Selecting the candidate from the list on the election page
- Using the browser "back" button

<img width="990" alt="screen shot 2017-07-27 at 9 01 58 pm" src="https://user-images.githubusercontent.com/11636908/28698247-11a7b0c0-7310-11e7-8093-15d0f0c6e5f7.png">


I'm inclined _not_ to add in any other "back" design at the moment, until we see if people struggle to go back, or desire to go back after landing on the election page.

_____________

Visually, I prefer option 2 or 3. I think 1 competes a little too much with the menu and title to me. Being able to access the button from any tab also feels like it can better accommodate people at any stage of exploration.  This is all based on some speculation though, so I'd love to hear what other people gravitate toward as a first option to try. @patphongs @noahmanger

**Comment by jenniferthibault** [comment]
In design pairing today, we discussed that:
- it feels better to be able to access the functionality from any tab
- the card pattern is too large, bold, and attention-grabbing. We prefer the large button style with icon.

So  back to this concept:

![screen shot 2017-07-28 at 1 51 56 pm](https://user-images.githubusercontent.com/11636908/28730129-d7f959ae-739c-11e7-8dc7-c49bfa30e600.png)

Which I think is ready to go to implementation!

**Comment by noahmanger** [comment]
Closing this since the design is done and implementation is happening in #2231.
