### ISSUE TITLE
Consider changing "memo code" to "memo item" on details panel

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#2212]
So that users can more easily understand memo items reported on various financial forms. 

Currently we display _memo code true_ or _memo code false_. It might be easier to understand and to explain if we use _memo item yes_ and _memo item no_.

Related to https://github.com/18F/FEC/issues/4407

**Comment by noahmanger** [comment]
This could also be a good thing to add to the glossary.

**Comment by PaulClark2** [comment]
Tagging @jameshupp in.   James part of this discussion is in https://github.com/18F/FEC/issues/4407

**Comment by jameshupp** [comment]
Yes, and yes. My initial reaction in reviewing https://github.com/18F/FEC/issues/4407 is that `Memo item: yes/no` makes a ton of sense.

Honestly, the clearest pattern to me, I would think, is:

1. Switch to `Memo item: yes/no`, as described above.
2. Reverse the position of `Memo item` and `Reported on` to separate `Memo item` from `Memo`, since I don't think _whether_ it's a memo item has anything to do with whether there is a memo on it. And having them next to each other looks awfully confusing.
3. Add glossary definitions for `Memo` and `Memo item`. I just can't imagine people aren't going to be confused by these in general.

**Comment by PaulClark2** [comment]
Does it help to call `memo` `memo text` and `memo code` `memo item`?  Memo (memo text) is an additional description of the transaction provided by the filing committee.

**Comment by AmyKort** [comment]
Issue moved to [18F/fec-cms #1574](https://github.com/18F/fec-cms/issues/1574) via [**ZenHub**](https://www.zenhub.com/)
