### ISSUE TITLE
Design architecture and interactions for what was formerly "Committee summary" data

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#2222]
People want to be able to get a list of committees with financial data all in a single spreadsheet so that they can compares.  Also, an added layer of view PACs related to specific candidates and other means of linking PACs

- [ ] filter for a group of committees
- [ ] be able to download a single spreadsheet to compare financial activity among committees 

-----------------
_Committee summary_

So that we can replace the committee summary dataset, http://classic.fec.gov/data/CommitteeSummary.do?format=html, we need to consider how best present this information, and how best to help users find this information.

Provide download functionality.

Option:
Consider creating committee type pages similar to the candidate specific pages we have for House, Senate and President.

This might replace the following datasets: committee summary, leadership PACs and lobbyist/registrant PACs

http://classic.fec.gov/data/CommitteeSummary.do?format=html
http://classic.fec.gov/data/Leadership.do?format=html
http://classic.fec.gov/data/Lobbyist.do?format=html

Overview of committee and candidate search enhancements: 18F/openFEC-web-app#2220

include in Monday's demo. 
- [ ] Paul and Jeff review

**Comment by jenniferthibault** [comment]
@PaulClark2 a few questions came to mind that will help make sure we have what we need to start design:

- What information can people get from the committee summary data set that isn't available on the current site? (understand the use case)
- Are there data/API tasks that need to be completed that impact the design options?
- Are there existing API constraints that impact the design options?

@noahmanger if you have time to check this issue out to make sure we know what's needed before sprint planning that would be helpful

**Comment by jenniferthibault** [comment]
Had a really helpful intro with Paul & Jeff on this to help wrap my head around the use case and data:

The current committee pages ( https://www.fec.gov/data/committees/ ) list organizational information about the committees:

![screen shot 2017-07-25 at 2 55 05 pm](https://user-images.githubusercontent.com/11636908/28589189-094a5fac-714b-11e7-8873-fa6cf1a8fe70.png)

The Committee Summaries on classic.fec ( http://classic.fec.gov/data/CommitteeSummary.do?format=html ) include financial data (total receipts, total disbursements, and cash on hand) that allows users to quickly compare these committees. here are additional financial columns included in the downloaded file. For example, this allows you to get a list of superPACs and sort by total receipts to see which superPAC raised the most at a given point. 

![screen shot 2017-07-25 at 4 19 05 pm](https://user-images.githubusercontent.com/11636908/28591843-11063fc2-7155-11e7-8d4d-0038af2aa778.png)

To compare a similar situation on the current site, the Candidate data table ( https://www.fec.gov/data/candidates/?has_raised_funds=true ) also shows organizational information

![screen shot 2017-07-25 at 4 19 13 pm](https://user-images.githubusercontent.com/11636908/28591880-33376ce2-7155-11e7-85e6-96f94001a34d.png)

But tables for candidates by office surfaces financial columns ( https://www.fec.gov/data/candidates/president/?election_year=2016&cycle=2016&election_full=true )

![screen shot 2017-07-25 at 4 19 22 pm](https://user-images.githubusercontent.com/11636908/28591922-59d04310-7155-11e7-9560-fdfe41676fa1.png)


### Next steps
- Determine how to present this data (is it really a separate data set, or is it new columns on an existing data set?) through understanding where users expect to find the info. 
- Design filters 
- Design which columns are surfaced in the table interface on web (and what will be in the file that's downloaded)

**Comment by noahmanger** [comment]
After discussing with @jenniferthibault and @patphongs and a little more thinking, here's my suggestion for a first pass at how to present this data. The idea is to create four new pages that mirror the four main categories of committee that we reference on the Help for Candidates and Committees section, separating out presidential and house-senate because they file on different forms and so therefore have different financial totals. Additionally, because users have the need to search for leadership PACs by sponsor name, there would be a page for leadership PACs as well. So the final list looks like:

- Presidential candidate committees
- House and Senate candidate committees
- All PACs
- Leadership PACs
- Party committees
- SSF committees

I created a [Google Doc](https://docs.google.com/document/d/1J2wJiD5e-YCxcuGV-SBVItAX8Qk4NWAAaFxGxVKgYh4/edit#) 🔒 for outlining the filters, columns and orderable fields needed for each one.

Next steps:
- Can @jwchumley and @PaulClark2 review the Google doc and weigh in on if this idea sounds like it addresses the user and business needs outlined above
- Can @LindsayYoung chime in on the data logic to make sure it all makes sense

Once the plan looks "good enough" we can close this issue.

**Comment by noahmanger** [comment]
I think we can close this. The doc is there for future reference.

**Comment by jenniferthibault** [comment]
Are there next steps issues we should file now? Or will we need to remember to come back to this issue when we're ready to take that work on and do it then?

**Comment by noahmanger** [comment]
The immediate next step is this issue: https://github.com/18F/openFEC-web-app/issues/2274 and subsequent next steps will be fleshed out when y'all do the grooming of Waltham requirements.

**Comment by jenniferthibault** [comment]
Awesome, thank you! I needed the issue link trail :)
