### ISSUE TITLE
Creating MUR filter for date opened and date closed

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#2314]
Users searching our MUR holdings still have difficulty searching MURs opened or closed during specific time periods. We need to add a filter option to allow users to set date opened and date closed filters for MURs.

Jen may already have much of this work completed. 

- [ ] create the filter
- [ ] write test for filter

**Comment by jenniferthibault** [comment]
:female_detective: GitHub archeology is one of my favorite things because I get to rediscover the awesome work and thinking our teammates have already done!

Nicky documented the most up-to-date filter designs and concepts for MURs, ADRs, and Admin fines  in https://github.com/18F/openFEC-web-app/issues/1797#issuecomment-275701188 This will be a good issue to keep handy.

Pulling out the MUR filters specifically, and zooming in on the time period concepts, the question in orange was a content design question about the field label:

<img width="392" alt="screen shot 2017-10-03 at 4 49 25 pm" src="https://user-images.githubusercontent.com/11636908/31148557-0b8aedf8-a85b-11e7-8095-f9dd344abc45.png">

@xtine can you help assess if the components on the API/back end are in place for the case data & violation date concepts to work?

**Comment by jenniferthibault** [comment]
Rebumping to @xtine for taking a look at the front end needs 👋

**Comment by lbeaufort** [comment]
@jenniferthibault if it's not too much work, there were two recent requests to add MUR number to the search, like the AO search: 

https://github.com/18F/FEC/issues/4583
https://github.com/18F/FEC/issues/4460

**Comment by AmyKort** [comment]
I think we've had that functionality for a while, but it was difficult to find https://www.fec.gov/data/legal/search/enforcement/?search=&search_type=murs

Am I misunderstanding @jenniferthibault ? (because that has been the theme of my day) Are you suggesting we integrate the filters differently?

**Comment by lbeaufort** [comment]
@AmyKort @jenniferthibault Sorry I was unclear - I think the request was to make it easier to find, or on the search landing page, similar to the AO search (below). I met a new EA today who mentioned she had recently submitted feedback, and when I was looking through the feedback I discovered two requests for MUR number search that I thought could have come from our internal users.
![image](https://user-images.githubusercontent.com/31420082/31688904-d2158752-b35b-11e7-894b-e960e3e36797.png)

**Comment by AmyKort** [comment]
Super! Thanks @lbeaufort !

**Comment by jenniferthibault** [comment]
@lbeaufort what you're looking for has already been added via https://github.com/18F/fec-cms/pull/1276 and you can take a look [on staging](https://fec-stage-proxy.app.cloud.gov/legal-resources/enforcement/). It will go out with the release. 🎉 

This issue is about adding the date opened/closed filters to the actual full filter list available in the advanced MUR search sidebar, at this link: https://www.fec.gov/data/legal/search/enforcement/?search_type=murs

And will be seen here:
<img width="1418" alt="screen shot 2017-10-17 at 11 23 11 pm" src="https://user-images.githubusercontent.com/11636908/31699675-31530a06-b392-11e7-8ff6-1f482f2ddce4.png">


This is a piece of an issue where we had all the research and designs for the full filter list finished a long time ago, (check them out in https://github.com/18F/openFEC-web-app/issues/1797#issuecomment-275701188!) but haven't had the engineering support available to implement them, so we're adding them piece by piece.


Does that clear things up am I misunderstanding and adding more confusion?

**Comment by jenniferthibault** [comment]
PS: @lbeaufort this is also a good reminder using my own bad example: no matter how "urgent" the fix or how inexperienced the dev (me, in this case!) including a proper pull request description and linking the PR to existing issues filed is a core part of working in the open and documenting what/how/why we're making these changes. Thanks you for training the trainers 😄

**Comment by lbeaufort** [comment]
@jenniferthibault That is awesome, thanks!

**Comment by AmyKort** [comment]
cc @johnnyporkchops

**Comment by jenniferthibault** [comment]
Thanks to @lbeaufort 's awesome demo today, it looks like 
 her pull request https://github.com/18F/openFEC/pull/2712 adds the work that makes this information available to use on the front end via a change to the endpoint. (I think, but may be misrepresenting.)

So if it's available, this is a front end implementation issue to add the feature to the MUR search filters!

**Comment by jenniferthibault** [comment]
Issue moved to [18F/fec-cms #1533](https://github.com/18F/fec-cms/issues/1533) via [**ZenHub**](https://www.zenhub.com/)
