### ISSUE TITLE
Enable filtering and sorting by Form 1 Filing Date on /committees

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#289]
**Goal:** Users should be able to filter for committees registered on (or after?) a particular date and also to sort by filing date.

**Completion Criteria:** Implemented on site.

**Steps:**
- [x] Define behavior
- [x] Design interface
- [ ] Implement

**Screen:**
This is referring to another filter and column to add to the committee browse page: 
![screen shot 2015-06-29 at 12 47 25 pm](https://cloud.githubusercontent.com/assets/1696495/8416809/166c95c6-1e5d-11e5-9b48-13c73bc10a80.png)

**Comment by noahmanger** [comment]
I'm starting to work on this now. First question to figure out is if we want this to be a "Filed on or after this date" or "Filed between these dates" or have the ability to do either. Anyone with any immediate thoughts? 

The overall user need I believe we're solving is for people to see the most recently filed committees, which makes me think that an "On or after this date" approach makes more sense.

**Comment by noahmanger** [comment]
Here's a few different ways this could happen. @jenniferthibault or @onezerojeremy any reactions to these? I'll update the issue with more context right now.

![date options](https://cloud.githubusercontent.com/assets/1696495/8416773/c819c52e-1e5c-11e5-9d8a-44fe17e790ea.png)

**Comment by jenniferthibault** [comment]
@noahmanger I'm digging the specificity of the language in the last option (5: Suggestions + custom) because it seems to be in the terms of how a user would think as they are doing research. The radio buttons seem to also be the quickest way to this info—avoids typing. 

*Question:* In the custom range, which field is the most recent in history? Top or bottom?
Reason I ask is that you could replace the default text in the empty field with "dd/mm/yyyy" to reduce the number of text elements, and still have "today" as a link in its place. When I went to visualize this, I wasn't sure which field was farthest away in time. If we don't specify, it could create search errors.

Also.....Do we know which time ranges are the most relevant to users? I could imagine alternative lists being: Today, This quarter, This year, Custom. Is "Month" specifically relevant here? Or just smaller than quarter?

**Comment by noahmanger** [comment]
Good questions. I hadn't thought of the "which comes first" thing. I was thinking top is earlier, but I now could easily see it being later. Probably helps if they're next to to each other instead.

And yeah, I wasn't sure what to do about the placeholder text vs the label text. I'd rather just have 'mm/dd/yyyy' as placeholder text, but I've also heard that doing that is bad for usability because you lose the instructions as soon as you start typing. *BUT!* We could you something (like this)[http://igorescobar.github.io/jQuery-Mask-Plugin/] to auto-format the input.

As for which ranges are most relevant, I'm not exactly sure but I think you might be right. We already have the "two-year cycle" filter there, but if people may rather filter down to the year than the month.

**Comment by noahmanger** [comment]
Updated:
![custom date - new](https://cloud.githubusercontent.com/assets/1696495/8421625/659626ac-1e86-11e5-9aae-002bdadea1f8.png)

**Comment by jenniferthibault** [comment]
Nice. I also really like the aids for time periods This quarter: (Q2 2015) etc.
It gets my vote to go on to testing! Whaddya think @onezerojeremy ?

**Comment by noahmanger** [comment]
I feel good on design on this but I'm guessing @msecret or @jmcarp will have better luck implementing. Does someone want to take it?

**Comment by jmcarp** [comment]
I'll take a look at this one.

**Comment by LindsayYoung** [comment]
I think you might want to use the report_year and report type. Recipt date would not be good for filtering because there are so many amendments. I think coverage end date would be more useful. That applies to the data in the form and not just the day the form arrived.

**Comment by jmcarp** [comment]
If we use report year, then the filtering interface needs to be redone too, since the granularity we're talking about above (today, this month, this quarter) would be finer than what we're actually doing (filtering by year).

Thoughts @LindsayYoung @noahmanger?

**Comment by LindsayYoung** [comment]
Sorry, I thought we were talking about filings-

F1s don't have a coverage date. They are not submitted on a regular schedule. I don't think that filtering scheme makes sense or would be useful. 

It would be helpful to have the first filing date and be able to sort on it because that is an easy way to find new committees, but that doesn't need ranges either.

**Comment by noahmanger** [comment]
To be clear, the idea with setting a range on F1s was not to see their coverage dates, but was to say "Show me all F1s filed between this date and that date".

**Comment by noahmanger** [comment]
So to summarize from Slack, we're no longer including these filters on the Committee page, but we do want to display a column for "Original Filing Date" (is that the right language?) that can be *sortable* but not *filterable*.

**Comment by jmcarp** [comment]
Status update: I'm working on implementing a few last filters, but this is in a good place for @noahmanger or @msecret to start on styling.
