### ISSUE TITLE
Discuss browser support and js support

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#299]
Back when we were doing a smaller scale public release, they told us to just worry about IE 10 and up. But for August we may want to re-open the discussion and support older browsers. Just putting this in here so we can remember to talk about it.

**Comment by onezerojeremy** [comment]
From discussions, it sounds like we're still targeting IE 10 and up for our initial launch. 

I'm not sure if this is where this goes, but one usability test subject indicated that the site did not work in IE 11. Specifically, the elections page.

**Comment by msecret** [comment]
If we want to support IE10 and up, we should probably specify the devs should manually test them when making changes. I'm a little concerned about getting the site looking ok on below IE10, because we haven't been paying much attention to it.

To have the site work without JS, I think we'll have to re-implement the data tables, although there is a section on server-sided rendering: https://datatables.net/examples/server_side/. That would probably mean we'll have to serve with nodejs though. Given how hard data tables has been to work with, I'm not sure I'd be comfortable implementing it server-side.

We'd also have to get some of the modals working as they're currently using js templates to render now.

**Comment by leahbannon** [comment]
@noahmanger is this still relevant?

**Comment by noahmanger** [comment]
We may want to revisit post-launch, but I'm fine closing out for now.

On Mon, Aug 31, 2015 at 10:38 AM, Leah Bannon <notifications@github.com>
wrote:

> @noahmanger <https://github.com/noahmanger> is this still relevant?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/299#issuecomment-136439187>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by leahbannon** [comment]
Let's just keep it open but out of the backlog. Removing priority labels.
