### ISSUE TITLE
Review and refine Filing table on committee page

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#318]
**Goal:** Finalize the designs for the filings table on committee pages.

**Criteria:** Stakeholder approval on designs.

**Steps:** 
- [x] FEC reviews comps and approve
- [x] Make refinements if necessary

**Comment by noahmanger** [comment]
Here's the current design (see below for notes):

![committee reports](https://cloud.githubusercontent.com/assets/1696495/8552365/7cb8f70e-2491-11e5-8bd4-5f6839054497.png)

![committee reports - details](https://cloud.githubusercontent.com/assets/1696495/8552366/7e82c7c2-2491-11e5-9d6a-f17aa4c9296f.png)

- Please ignore all report names, dates, and amounts. They were just clumsily copy and pasted. 
- The "More" button in the filter box would contain all options for filing types. 
- Clicking a filing name opens the preview panel
- All columns are sortable
- If a report has been amended, it will be listed first, with all previous versions nested below. Clicking the + icon next to "Amended" expands the list
- For RFAI's and Form 1s and anything else that doesn't include a financial summary, the preview will include an embedded PDF view of that filing (at least I think that's possible, right?)
- I removed the "Last deadline" and "Next deadline" text for the time being.

**Comment by PaulClark2** [comment]
Filings Tab
List of Filings & Download Options
Is it possible to move the "PDF," "HTML," and ".FEC" links to the top level?  

"View" List
If I select "Contributions," or "Expenditures" from the "View" list is the result a download of all relevant transactions?  

"FECfile" should be .fec file or ."FEC File" or "Electronic Filing" or something. FECFile is an application – FEC's free electronic filing software.  

Green "New:"  
Does this mean the most recent filing?  If yes, if a committee files multiple filings in a single day to they all get marked as "New?"    For example, a committee files a Q2 New and amends their Q1.  Or, a committee files a Q2 New, amends their Q1 and amends their Statement of Organization (F1) all on the same day.  

How long does the "New" indicator stay?   If the committee is a quarterly filer a "new" filing could be nearly three months old.  

Filter Filings
Our suggestion is to make the following filters available:   "Financial Filings,"  "Statements," "Requests for Additional Information," and "Other Documents."

Default Sort for Filings
Since all the columns are sortable, we will need a way to get users back to the default sort.  The default sort will be more complicated and a single column sort.

**Comment by noahmanger** [comment]
Thanks, Paul. 

### View options
We _could_ put this in the top level table view, but I'm concerned about column width, so let's wait and see how we're doing. This will also be a good thing to investigate in usability testing. 

### View list
The "Contributions" and "Expenditures" links take you to the new browse/query view of Schedule A / Schedule B, filtered down to those from this report. 

Thanks for the clarification on .fec file. I think I prefere ".fec file" as it's clearer that it's a special file type.

### New indicator
Great question. The user need that this is meant to address is for those who regularly check in for the latest filings to easily be able to find them. But I'm not sure if there's a time period that immediately makes sense. I do think that if there's multiple filings submitted, it would be displayed on all of them. Maybe it's for one week?

### Filters
I like simplifying these. What's included in Statements?

### Default sort
What do you mean? Wouldn't it just be by date?

**Comment by PaulClark2** [comment]
Is it interesting to look at contributions by types of contributor? So, the amount from different types of committees vs. the amount from individuals?

**Comment by PaulClark2** [comment]
Number of individual contributors?   

Multiple issues to overcome to do this:  
Because we don't have unique contributor IDs, the number of individual contributors to a committee is unknowable from our data.  The  number of individual contributions that make up the unitemized individual contribution total is unknowable.  

We can look at the itemized contributions (a partial answer to the # of contributors questions) and try to count the number of unique contributors.  This can also be problematic because of inconsistent name reporting (nicknames, initials, etc.) address changes or multiple addresses.

**Comment by PaulClark2** [comment]
Filters:   Statements would include both Statements of Organization (Form 1 filings) and Statements of Candidacy (Form 2 filings).

**Comment by LindsayYoung** [comment]
Ok, my rough draft that I have going locally is:
![screen shot 2015-07-13 at 5 49 51 pm](https://cloud.githubusercontent.com/assets/4406333/8661726/a16d4a82-2987-11e5-9f0f-a06917995329.png)

I think we need to make the amendment indicator, easier to read, formation the "Form type" column so it doesn't show the explainer text in the brackets. I also need to add Misc. or add additional file types when the form type is not mapping. 

This has the PDF link, I need to generate the other links. 

I need to add currency filters and date filters, so that looks better. 

I also like the idea of report date and receipt date. 


 +1 to @PaulClark2 comment about number of donors
I am not sure where the number of contributors conversation ties in, but I am strongly against displaying that as a stat, because we don't know how many unitemized donors there are. Showing the tally of itemized donors disadvantages campaigns who have a lot of small donors. 

This can really sway things is big races, for example, if you just looked at itemized donations, it looks like Romney out-raised Obama, which was not the case.

**Comment by noahmanger** [comment]
I updated the designs to use the same component as #317. Nothing major changes here. 

![filings 1](https://cloud.githubusercontent.com/assets/1696495/8687699/ce1073be-2a47-11e5-93b7-3bb33b51d580.png)
![filings 2](https://cloud.githubusercontent.com/assets/1696495/8687698/ce0e1664-2a47-11e5-805d-2f6d18890bf8.png)

Also, here's how it would look when looking at an RFAI or Statement of Organization. We want to embed the PDF like this, right?

![filings 3](https://cloud.githubusercontent.com/assets/1696495/8687706/de8b257c-2a47-11e5-896d-66c5055c0c62.png)
