### ISSUE TITLE
Tooltip / legend for state contribution map

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#331]
I added a very basic tooltip to the state contribution map. It shows total contributions for the state on hover (sorry, the mouse didn't show up in the screenshot):
<img width="683" alt="screen shot 2015-07-14 at 3 12 13 pm" src="https://cloud.githubusercontent.com/assets/1633460/8682428/edcf2374-2a3a-11e5-8230-07b033513e27.png">
I think we could either make the tooltip nicer, or use a legend or sidebar instead, so that clicking or hovering on a state brings up detailed information (state name, total contributions, link to data table) on the right.

Preferences @noahmanger @jenniferthibault?

**Comment by noahmanger** [comment]
Yep, there should definitely be a legend that shows the the ranges for each
shade, and I like everything you mentioned for including in the tooltip.

On Tue, Jul 14, 2015 at 12:15 PM, Joshua Carp <notifications@github.com>
wrote:

> I added a very basic tooltip to the state contribution map. It shows total
> contributions for the state on hover (sorry, the mouse didn't show up in
> the screenshot):
> [image: screen shot 2015-07-14 at 3 12 13 pm]
> <https://cloud.githubusercontent.com/assets/1633460/8682428/edcf2374-2a3a-11e5-8230-07b033513e27.png>
> I think we could either make the tooltip nicer, or use a legend or sidebar
> instead, so that clicking or hovering on a state brings up detailed
> information (state name, total contributions, link to data table) on the
> right.
>
> Preferences @noahmanger <https://github.com/noahmanger> @jenniferthibault
> <https://github.com/jenniferthibault>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/331>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by jmcarp** [comment]
So that's actually a third option. I was thinking of a sidebar, so that you'd click "MI", and then see a detail view on a separate panel to the right of the map. Tooltips are fine, but it can be annoying to include things like links in them, since it's easy for the state to lose focus and the tooltip.

**Comment by noahmanger** [comment]
Oh! I misunderstood. You're right, I think best not to rely on the toolips.
What about a hybrid where you can toggle between this map and a regular
table that includes State name, Amount raised, and a link to the
transactions? I can sketch it out if that would help.

On Tue, Jul 14, 2015 at 12:54 PM, Joshua Carp <notifications@github.com>
wrote:

> So that's actually a third option. I was thinking of a sidebar, so that
> you'd click "MI", and then see a detail view on a separate panel to the
> right of the map. Tooltips are fine, but it can be annoying to include
> things like links in them, since it's easy for the state to lose focus and
> the tooltip.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/331#issuecomment-121361514>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by noahmanger** [comment]
But I do think that the map should have a legend that explains what the
colors mean.

On Tue, Jul 14, 2015 at 1:11 PM, Noah Manger - XFB <noah.manger@gsa.gov>
wrote:

> Oh! I misunderstood. You're right, I think best not to rely on the
> toolips. What about a hybrid where you can toggle between this map and a
> regular table that includes State name, Amount raised, and a link to the
> transactions? I can sketch it out if that would help.
>
> On Tue, Jul 14, 2015 at 12:54 PM, Joshua Carp <notifications@github.com>
> wrote:
>
>> So that's actually a third option. I was thinking of a sidebar, so that
>> you'd click "MI", and then see a detail view on a separate panel to the
>> right of the map. Tooltips are fine, but it can be annoying to include
>> things like links in them, since it's easy for the state to lose focus and
>> the tooltip.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/18F/openFEC-web-app/issues/331#issuecomment-121361514>
>> .
>>
>
>
>
> --
> Noah Manger
> 18F <http://18f.gsa.gov> | Work: 415-696-6146
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by jmcarp** [comment]
Not sure about togging between a map and a table. If I'm looking at the map and decide that I'm interested in details about Kansas, I have to understand that the information I'm looking for lives behind the toggle, click the toggle, and page or scroll down the table until I find Kansas. I think I'd rather just click on the state that I want to know more about.

**Comment by noahmanger** [comment]
True. Yeah, I guess I'm thinking there's a need for both a table view as well as a map view, presenting (ideally) the same information on both. Whether those live along side each other or with some sort of toggle, I don't know. There's a very similar need on the election page, so @jenniferthibault we should try to put our heads together on this today (if you've got time).

**Comment by jenniferthibault** [comment]
@jmcarp Here's a quick screen shot of what this could be in "open" state , adapted from what I've been working on for the Elections page. Since the data is broken down into zip codes, I think a more traditional chloropleth is a better representation than the hexagons. This double-panel view is becoming a pattern for detailed views of table elements. 

![screen shot 2015-07-15 at 4 27 05 pm](https://cloud.githubusercontent.com/assets/11636908/8709162/7c404b50-2b0e-11e5-951a-06fe29b6e6e6.png)

**Comment by jmcarp** [comment]
* Not sure of the relevance of zip codes--that's not what we're showing in these aggregates. Do you want to show contributions by zip code instead of state here?
* Is the idea that we start with the data table and add the map as a second panel when the user clicks a row in the table? Can users see a country-level map at any point, or just the zoomed-in view in the example?
* I don't mean to be obtuse, but I'm still not seeing the purpose of showing two representations of the same data side by side. What's the added value of the zoomed-in map overlay? In this example, the map overlay basically tells the user where California is.
* The implementation of a side panel here will probably borrow from the implementation of same for other data tables. @msecret are you working on that? Anything I can help with?

**Comment by noahmanger** [comment]
I can speak to some of these:

So we were talking on the election page about wanting to show zip-code totals, but only on the map. The idea is that for smaller races, where more funding is drawn from fewer states, _where_ from within that state the money comes matters. This is definitely something that's better shown with a map rather than a table of zip codes.

After talking with Jen and others, I think that it makes sense to actually show the zip code totals on the committee page as well. Sorry that this goes contra the original hex map. 

And so in this case, clicking on a state pulls up a zip code choropleth, so yeah, it would actually be showing granular data that this example doesn't (that was on old mock of mine).

And yes, there would also be a full country-level view. The advantage of showing it as a table is that you can easily see which states were the source of the most money, a comparison that isn't possible with a map alone that shows ranges. 

And yep, it definitely makes sense to have this side panel be the same as it is for other data tables.

**Comment by LindsayYoung** [comment]
I feel like zip code and state should be the same map By default it should be by state, and then, when you zoom in, it would show break down by zip code.

**Comment by noahmanger** [comment]
+1. That's what I was trying to say, but put much better :)

**Comment by jmcarp** [comment]
Thanks for clarifying.

Maps by zip code are more challenging than state-level maps, since we're working with much more data (45k data points vs 53). I'll do some evaluation and figure out what's feasible.

**Comment by noahmanger** [comment]
To be clear, without selecting a state it simply shows the full country map. If we are at this scale, I think it woudl be ok to _just_ show state totals. And then selecting a state shows zip totals just for that state. Does that simplify things?

**Comment by jenniferthibault** [comment]
Sorry for lack of clarity! I'm working on some additional screens that should help us all clear some more things up, but....

that doesn't _quite_ make sense to me though, because:
1) the map is only activated when you select a state for more details (in my understanding)
2) how would you be able to use the same color scale for both zip codes and states? I'm imagining the amounts would be way different

**Comment by LindsayYoung** [comment]
I for the zipcodes, I am thinking we would only show one state at a time, or limit the amount of zipcodes shown at any one time. 

I I have seen a demo with fusion tables. I hope there are some good open source tools but maybe I am thinking of things that mapbox or other experts make. 

Should we see if there are people at 18F with mapping experience?

**Comment by jenniferthibault** [comment]
Here's the summary of tonight's discussion that left it at a state-level view instead of zip code-level.
Are we interested in doing a full-switch to table view/map view, like in #297 ? Definitely possible here.

I hope I haven't left too much to imagination. Please ping me if so @jmcarp !

![screen shot 2015-07-15 at 9 11 57 pm](https://cloud.githubusercontent.com/assets/11636908/8713399/36f39ade-2b36-11e5-8050-ff4ab365c642.png)

**Comment by leahbannon** [comment]
No longer relevant to current style of maps
