### ISSUE TITLE
Implement location look up tool

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#354]
Most recent mockups here, and discussion in #313 :
![district 1 copy 4](https://cloud.githubusercontent.com/assets/11636908/8836594/ee2b521a-308f-11e5-9c35-8b8626c79cd4.png)
![district 1 copy 5](https://cloud.githubusercontent.com/assets/11636908/8836595/ee2c5368-308f-11e5-84b8-e753bc00b0c2.png)

**Comment by jmcarp** [comment]
@jenniferthibault @noahmanger do we want an option to select an election cycle here, or is the idea to restrict to upcoming elections?

**Comment by noahmanger** [comment]
Good question. I think it's ok to leave it off. Because the results are actually Districts, I think it makes sense to not have the option. You can view past cycles by going to an election page and changing the cycle there. 

I also like the simplicity of having this just be a 1 or 2 question tool. We may learn that people want a cycle select, but I think it's ok to not have it for now.

**Comment by jmcarp** [comment]
This exists.
