### ISSUE TITLE
To make date inputs more usable to users with screen readers, convert date inputs to groups of three fields

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#389]
Investigate the best way to do input masking on the date inputs.

**Comment by noahmanger** [comment]
[The research](https://www.filamentgroup.com/lab/politespace.html) I'm seeing says that input masks are really harsh for screen readers. The Filament group has one that they recommend, but it seems to make more sense for credit card numbers or phone numbers rather than dates. 

So I think we should go with the [US Web Design Standards' recommendation](https://pages.18f.gov/designstandards/form-controls/) which is to use multiple fields for month, day and year, thus avoiding input masking entirely. 

It would look something like this:
![screen shot 2015-09-22 at 6 08 49 pm](https://cloud.githubusercontent.com/assets/1696495/10035952/feb8112c-6154-11e5-98f4-84c3dd4e0101.png)

I've got the markup in the branch `feature/input-mask` but I think @jmcarp should handle the JS. Now, I think all we need as far as validation is if you enter something that doesn't make a full date, it displays an error or warning. 

Eventually it would be nice to have dynamic validation of the inputs so if you enter a day or month out of range, the input turns red (or whatever). And also it would be nice to only show the custom inputs if the "custom date" radio button is selected / if there's custom dates passed in the url.

@jenniferthibault or @onezerojeremy do you have design feedback on this plan?

**Comment by noahmanger** [comment]
Also: I wouldn't consider this launch critical. This is a small part of the overall app and even if we need to keep the mask there I think it will be ok.

**Comment by onezerojeremy** [comment]
This seems right to me. 

also the screen reader video in the article you linked to is :banana: s 
https://docs.google.com/file/d/0B9rGmqNcHo-mRGpMS0xQbzVzeGM/edit

**Comment by onezerojeremy** [comment]
Thoughts that are possibly bad (that I had late last night):
can input boxes have background images (of, for example, masks?)

can we auto advance the cursor to the next box after they put two digits in? (putting an exception for tab press)

Just trying to limit the clicks for folks to enter a date. :\

**Comment by noahmanger** [comment]
Not bad thoughts. I think it would be better to go with placeholder text
(in addition to the hint text below the input) rather than a background
image, so that you're not covering up the image with the text. That would
look weird.

Re: auto-advancing, the US Web Design Standards recommend against that. I
don't know the research to support that, but I'm inclined to go with their
word.

On Wed, Sep 23, 2015 at 12:06 PM, Jeremy Canfield <notifications@github.com>
wrote:

> Thoughts that are possibly bad (that I had late last night):
> can input boxes have background images (of, for example, masks?)
>
> can we auto advance the cursor to the next box after they put two digits
> in? (putting an exception for tab press)
>
> Just trying to limit the clicks for folks to enter a date. :\
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/389#issuecomment-142649550>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by jenniferthibault** [comment]
Late to the game, but I'm :+1: +:100: for following the US Web Design Standards' recommendations.

**Comment by onezerojeremy** [comment]
right on. 

We should try to figure out a pattern to counter users from having to click 6 times to enter dates. While it is true that some people know to use tab, but many do not. Does US wds have anything to help us with  that?

**Comment by noahmanger** [comment]
Not that I know of, but that's a good point

On Wed, Sep 23, 2015 at 3:03 PM, Jeremy Canfield <notifications@github.com>
wrote:

> right on.
>
> We should try to figure out a pattern to counter users from having to
> click 6 times to enter dates. While it is true that some people know to use
> tab, but many do not. Does US wds have anything to help us with that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/389#issuecomment-142698928>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by mollieru** [comment]
cc @carodew who I believe helped us think through this the most, and can give a lil insight into the date field design

**Comment by mollieru** [comment]
also, some thoughts from across the pond on the matter:

https://designpatterns.hackpad.com/Dates-vpx6XlVjIbE

**Comment by carodew** [comment]
There's a lot of convo to catch up on here, so I'll try to weigh in on what we learned in researching the design standards based on issues raised above without being too overbearing. 

Auto-advancing focus is bad for people who are using screen readers, so it's an accessibility issue. It has to do with them being able to go back and check/edit their inputs or understanding what is going on with the page.

Note that with placeholder text there are also issues. One is that often the light gray of the text does not usually meet color contrast requirements. Making it darker could mean that sighted users think the field is already filled out. We recommend putting any hitns and tips inside the `label` tag so that they are still associated with the form input (and screen-reader accessible). The other issue with placeholder text is that it disappears as soon as the user starts typing, so if they go back and check they can't see the original tip. 

Input masks (to suggest formatting) are indeed tricky for screen readers. Filament Group's PoliteSpace seems to be the only one cognizant of this issue but it presents other (arguably more minor) problems for sighted users, in that the masking is not in place when the user is typing, only when the input loses focus. There doesn't seem to be an easy fix for this but seems the lesser of two evils. 

Now that I've taken away all your fun toys … :)

We based a lot of our recommendations on the hackpad convo that Mollie linked to above and what GDS has in their design standards. https://www.gov.uk/service-manual/user-centred-design/resources/patterns/dates.html (also this is my favorite design manual page in existence anywhere). 

I think in the long term we'd also like to offer alternative date inputs (like a calendar picker, or possibly a single box when appropriate) with guidance on what contexts they work best in.

**Comment by noahmanger** [comment]
Thanks for the thoughts @carodew and @mollieru . This all makes a ton of sense, and I think suggests that we should move forward on my proposal above.

**Comment by jenniferthibault** [comment]
No consensus yet, but there is more discussion happening over here since the web standards have launched: https://github.com/18F/web-design-standards/issues/751
I'll keep an eye on it and see if helpful recommendations come up

**Comment by noahmanger** [comment]
https://18f.storiesonboard.com/m/fec/!card/RyWLKPXPXCzX7jnUEHzR2Q
