### ISSUE TITLE
Implement map tooltip

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#420]
When hovering over a state on a map, show the value associated with that state in a tooltip.

This needs design, but that should probably be done as part of the overall visual component work. In the mean time, a basic tooltip can be implemented that can be styled later.

**Comment by noahmanger** [comment]
There are two needs here:
1. Map states need a hover state to show users that they're clickable.
2. If you're looking at a map that does not have a table next to it, states should have a tooltip when you click on them. If the map is next to a table (like on the committee receipts tab), clicking on a state highlights the row. 

Is this the right behavior? Or should we have the tooltip on both?

Tasks to completion:
- [ ] Decide if this is the interaction we want (cc @onezerojeremy )
- [ ] @jmcarp implement basic html tooltip
- [ ] @jenniferthibault do visual design

**Comment by jenniferthibault** [comment]
Thank you @noahmanger for an excellently organized issue!

**Comment by onezerojeremy** [comment]
the former! No tooltip on map-state-click when the data table lives next to it, but otherwise, yes, love it.

**Comment by noahmanger** [comment]
:+1:

**Comment by jenniferthibault** [comment]
@jmcarp @noahmanger here's what I'm thinking for styling:

The default state borders would all be 1pt Federal Blue (#022C53)
When a state is hovered, the outline changes to 4pt or 5pt Federal Blue (or large enough so that when you hover you can clearly distinguish a different weight without changing the color) California and North Carolina are hovered in the below example, though obviously you could only do one at a time. Just trying to cut down on screenshots.

The tooltip could look like this:
If the Aqua is too much, we could also make the headers Ivory

![screen shot 2015-08-27 at 7 24 21 pm](https://cloud.githubusercontent.com/assets/11636908/9535621/445f67a2-4cf1-11e5-8220-f5c83cc5689d.png)

**Comment by jenniferthibault** [comment]
Also a more subtle option with solid #FFFFF9 as a background.
I think I like this one better:

![screen shot 2015-08-27 at 7 36 03 pm](https://cloud.githubusercontent.com/assets/11636908/9535740/b63f50ac-4cf2-11e5-8276-d6fba018aadf.png)

**Comment by noahmanger** [comment]
Remaining task on this is to reposition the tooltip. Re-assigning this to Josh for that.
