### ISSUE TITLE
Election lookup filter behavior

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#471]
One question that has come up in conversation with @jenniferthibault and @noahmanger is whether we should show results in the election lookup tool if the user specifies a state without a district. Right now, we don't. This is nice because we never get large result sets and don't have to worry about scrolling, pagination, etc., but users may also find the current interface confusing, or want to see all the upcoming elections in a state. I'm filing this issue for discussion, but if folks are happy with the current behavior, no action is needed.

Maybe something to look out for in usability testing @onezerojeremy.

**Comment by LindsayYoung** [comment]
I think it would be good to list all the races in a state, especially for state reporters. That wouldn't have to be something we need right out of the gate.

**Comment by onezerojeremy** [comment]
The state thing did come up in testing. People were a little confused about where the results would appear (especially when results didn't show up), and the fact that there weren't buttons. Full usability results in this doc: https://docs.google.com/document/d/114La8si6a18gUVBt6ZS9w9QWub5lFPs30ImLWC2P5Qs/edit#
Dug into how folks felt about the split district zip code issue, and it seems like most people we tested with wanted to use an address look-up. 


Couple of wireframes we're chewing on: Simplest change is just to link to an address look-up (house.gov has one), and we can also link to our browse page for all state candidates, i think, rather than adding that functionality here (not sure how widespread that one is, including a link lets our metrics tell us if we should support it here)
![district lookup simplest changes](https://cloud.githubusercontent.com/assets/474916/9311420/12ca906e-44e4-11e5-824b-56f7f6e070fb.png)

Another version, very similar, but horizontal. 
![district lookup simple horizontal](https://cloud.githubusercontent.com/assets/474916/9311513/b4b5667e-44e4-11e5-911b-25f5fbe5ed5a.png)



Also played around with more substantial changes (including address lookup), but am going to not show those now. see here if you're interested: https://drive.google.com/open?id=0B_FgIWl2WPMEWmNYNk1kYjU4SVk

**Comment by jenniferthibault** [comment]
@onezerojeremy / @noahmanger these style the wireframes above. Thoughts?

![location search 1](https://cloud.githubusercontent.com/assets/11636908/9398575/88ab84a2-4776-11e5-9ee6-87f0227f346d.png)
![location search 2](https://cloud.githubusercontent.com/assets/11636908/9398574/88aa01c2-4776-11e5-939c-4f0faa4a1653.png)

**Comment by noahmanger** [comment]
Ooooh I'm really liking this. 
- +1 to color-matched icons. I _think_- we'd have maybe a max of 3 or 4? Ideally we'd also be able to apply a label to the map so we're not solely relying on color (anti-508 to do so).
- I like the way the "either / or" division in the search box works. 
- Thinking through components, I _think_ we'd want this search interface to match the other instances of filters and results controls that are in the body of a page (as opposed to in a slide-out sidebar). By my count, that pattern lives in these places as well:

### The search box above the candidate / committee search results
![screen shot 2015-08-21 at 11 24 28 am](https://cloud.githubusercontent.com/assets/1696495/9415924/5b894b9a-47f7-11e5-8351-ae529bb39774.png)

### The filters above the filings table
![screen shot 2015-08-21 at 11 24 39 am](https://cloud.githubusercontent.com/assets/1696495/9415920/565821d2-47f7-11e5-8ddf-4f0c7557709f.png)

### The candidate select box on the election page
![screenshot-02](https://cloud.githubusercontent.com/assets/1696495/9415917/5144bdd6-47f7-11e5-9e6c-376dfec7324d.png)

**Comment by jenniferthibault** [comment]
To the third point, I think #444 addresses consistency in search results, and #521 addresses consistency in election pages searches. All should be matchy matchy now
