### ISSUE TITLE
Redesign data home page mockup

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#481]
- [x] Remove elections & filing cards from group of 6 — @jenniferthibault
- [x] Integrate elections module into larger standalone element — @jenniferthibault
- [x] Design most recent filings ticker (development coming soon) — @jenniferthibault
- [x] Solve interaction of search bar — @noahmanger

**Comment by jenniferthibault** [comment]
cc @manger

- This integrates @onezerojeremy 's mockups from #471 
- Brings in redesigned icons from https://github.com/18F/fec-alpha/issues/60
- Does not bring in the Open FEC icon. Are we ok with that? Still open Q.

The most recent filings preview is a very condensed version of the data @onezerojeremy asked to be showed, is that ok? I don't think it should be a huge feature, just a way to get people into the data, and a neat preview.

Question: I used an icon & button pair on the most recent filings section. If we don't like the double-icon, we could use this pair everywhere. Whichever we decide, they should be consistent.

![data home 3](https://cloud.githubusercontent.com/assets/11636908/9366734/12e3b4d2-4687-11e5-86d0-bf79921c3a89.png)

**Comment by onezerojeremy** [comment]
Thoughts: 
Nice work! I don't mind the icon/button. 

Filer name might also be a committee name, so you might want to try some of those to see if it gums up your space with wrapping issues. The committee names can be pretty long. Like: "A BRTHD AIMED TOWARD EDUC OF IL FED ELEC DEVICE FOR POLITICALLY ACTIVE MOTORCYCLISTS..."
(that's committee C00308460) (part of me wants to run stats on the distribution of length for that, because at some point you can just elipsis it but I think you'll need more characters than you have now)


Election Data: 
I think we can simplify it! What about a version of this widget including just the zip code and assume the current cycle, and allow them to tweak on the results page. We can provide a link to the page for state search and everything else.

**Comment by noahmanger** [comment]
Ooooh. I'm liking the direction a lot. A few disconnected thoughts:

**On icons**
- I like where you're going with the magnifying glass with bar chart to signify "browse the data" -- my only concern is if it's weird that it will always only take you to a table, not charts?
- The combination of the circular icon with the rectangular browse seems really out of place. What if it's just a larger button with a circular icon inside? And maybe that pattern is repeated for the headings in the cards above, so instead of the search icon intersecting with the category icon, it's locked up with the "All...data »" heading?
- Otherwise I _really_ like the way these icons are working. Smart way to illustrate these kind of abstract concepts.

**On election search**
- I don't mind having the state + district selects on this page. That seems valuable to me, imo.
- I wonder if it this module should be more connected with the presidential stats above. It feels a little weird to have it next to the recent filings module as they're so different. Pairing it with the states could lead to a very elegant call to action along the lines of "This is what's going on in the presidential race, now go see what's happening near you"

**On filings feed**
- I'm very interested to see how this works. I can't tell what I think about it just yet. But for what it is, I like how you've designed it.

**Comment by noahmanger** [comment]
Oh, and re: the question of ditching the openFEC icon, I'm completely unmarried to it. So if you don't see a place for it I think that's just fine.

**Comment by jenniferthibault** [comment]
Great thoughts here! I'll work up the next iteration in a jiffy.

**Comment by jenniferthibault** [comment]
Another option @noahmanger, early on I designed this icon for the charts, then abandoned it for the magnifying glass. Maybe this makes more sense to bring back into a button, but by itself instead of paired?

![screen shot 2015-08-20 at 11 49 59 am](https://cloud.githubusercontent.com/assets/11636908/9388064/7b6d63cc-4731-11e5-8ef1-59b8d8c66173.png)

**Comment by noahmanger** [comment]
Ah yep! I think that could definitely work.

On Thu, Aug 20, 2015 at 8:50 AM, Jennifer Thibault <notifications@github.com
> wrote:

> Another option @noahmanger <https://github.com/noahmanger>, early on I
> designed this icon for the charts, then abandoned it for the magnifying
> glass. Maybe this makes more sense to bring back into a button, but by
> itself instead of paired?
>
> [image: screen shot 2015-08-20 at 11 49 59 am]
> <https://cloud.githubusercontent.com/assets/11636908/9388064/7b6d63cc-4731-11e5-8ef1-59b8d8c66173.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/481#issuecomment-133057869>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by jenniferthibault** [comment]
Sorry to have not consolidated these comments, but @noahmanger do you think it would be possible to take a first go at the data example statements in each of the four categories today? I'm working through the design changes, and could incorporate all in one swoop.

**Comment by noahmanger** [comment]
Oh yep! I got that.

On Thu, Aug 20, 2015 at 9:39 AM, Jennifer Thibault <notifications@github.com
> wrote:

> Sorry to have not consolidated these comments, but @noahmanger
> <https://github.com/noahmanger> do you think it would be possible to take
> a first go at the data example statements in each of the four categories
> today? I'm working through the design changes, and could incorporate all in
> one swoop.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/481#issuecomment-133070736>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by jenniferthibault** [comment]
This layout allowed for a bit more info on the filings ticker.
I don't *love* how that filing icon is floating at the bottom, so might keep playing with it.

![data home 4](https://cloud.githubusercontent.com/assets/11636908/9395181/fb005954-475a-11e5-8d1d-5fab6575d4a9.png)

**Comment by noahmanger** [comment]
Ooooh I'm loving this. Only thing I'm catching is that the button on the presidential stat panel should send people to the presidential election page, which should probably use the election icon.

**Comment by jenniferthibault** [comment]
Ssounds like that panel should be joined, and share a headline with one icon?

**Comment by noahmanger** [comment]
Maybe? I was specifically referring to the icon in the button, but that might help too.

**Comment by jenniferthibault** [comment]
I shuffled a few things about while I was at it, and it feels a bit more at rest now. 

![data home 4](https://cloud.githubusercontent.com/assets/11636908/9397143/d3aa2a76-4767-11e5-812d-818d528067e3.png)

**Comment by jenniferthibault** [comment]
Minor change: I was using the wrong background color on the top icons, which is why they looked so dark. This should address that: 

![screen shot 2015-08-20 at 6 24 06 pm](https://cloud.githubusercontent.com/assets/11636908/9397238/90e22620-4768-11e5-88e9-7dcb592dd4de.png)

**Comment by noahmanger** [comment]
Excellent. I love it.

**Comment by jenniferthibault** [comment]
Closing to move any remaining changes on this to implementation
