### ISSUE TITLE
Design more prominent and consistent button to itemized browse tables

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#482]
Goal: From the committee aggregate receipt and disbursement tabs, we need a prominent and consistent way to send people to the browse view to look at all itemized receipts and disbursements for that committee. (This arose as an issue in usability testing).

Here's Jeremy's wireframe:
![committees disbursements jc tweaks](https://cloud.githubusercontent.com/assets/1696495/9338639/95657ef6-459a-11e5-83a5-e8f1a40af551.png)

Steps:
- [ ] Settle on language - @emileighoutlaw 's help would be valuable
- [ ] @jenniferthibault design component

**Comment by jenniferthibault** [comment]
This is the button style & language I've been using in #481 , I think it would be nice to keep the consistency here, since I believe they direct you to the same tables. Is that correct?
@emileighoutlaw your thoughts on lingo?

![screen shot 2015-08-20 at 8 19 32 pm](https://cloud.githubusercontent.com/assets/11636908/9398755/b4a94b78-4778-11e5-87c1-88f4f18f8dc0.png)

**Comment by noahmanger** [comment]
I like the button style / icon. We'll need different copy for when it's sending you to data that's been filtered down by some parameters (i.e. "view all of a committees contributions in this time period"...except shorter).

**Comment by noahmanger** [comment]
assigning to me to be implemented

**Comment by noahmanger** [comment]
Implemented in #559
