### ISSUE TITLE
Design and implement empty results for data tables

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#512]
Some data tables may be empty frequently (e.g., electioneering, communication costs). We should design and implement some text and/or visuals to show when a table is empty, or decide that the current behavior is adequate. Here's how this looks now (e.g. https://fec-dev-web.18f.gov/elections/house/NY/01/2012/?tab=spending):
<img width="989" alt="screen shot 2015-08-24 at 3 35 35 pm" src="https://cloud.githubusercontent.com/assets/1633460/9450302/e038258e-4a75-11e5-8ac5-b17b7b921489.png">

**Comment by jenniferthibault** [comment]
Does this mean that there are no results, or for some reason the data is unavailable?

Distinction is kind of like Value = 0, or Value = can't find

**Comment by jmcarp** [comment]
Now that you mention it, we may want to design a better error behavior than we have now, but this issue is about the case in which there are no results, like in the electioneering table in the link above.

**Comment by noahmanger** [comment]
Ah, so this is what happens when there's a table on a candidate or
committee page without data? I would treat that differently than if a
browse table has no results. And both of them should display different
messages if there was an error retreiving data.

In the case of an empty table on a candidate/committee page, I think it's
valuable to show the *section* (in this case, Electioneering), but have a
placeholder where the table would be, rather than showing an empty
table...if that makes sense.

On Tue, Aug 25, 2015 at 6:44 PM, Joshua Carp <notifications@github.com>
wrote:

> Now that you mention it, we may want to design a better error behavior
> than we have now, but this issue is about the case in which there are no
> results, like in the electioneering table in the link above.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/512#issuecomment-134787517>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by noahmanger** [comment]
^ Does this solution work for folks? If so, @jmcarp do you want to take this?

**Comment by jmcarp** [comment]
That sounds reasonable. Just to be clear, we typically don't know that a table's going to be empty until after we've rendered it and fetched the results. So we'd wind up showing the table with the loading screen, then replacing it with the placeholder once it loads and we notice that it doesn't have any results. Is that what you had in mind @noahmanger? I'd be happy to add it.

**Comment by noahmanger** [comment]
Yep, that works. I was wanting to add the loading screen to tables before they render anyway (I think it currently only shows up on a table redraw).
