### ISSUE TITLE
Browse Candidates - Browse Committees - Default Election Cycle

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#546]
![untitled](https://cloud.githubusercontent.com/assets/11817734/9582583/35d1d4aa-4fd4-11e5-9762-9d47af034a87.png)

Why default select three election cycles?  It seems more confusing than helpful.   Aren't most people looking for current cycle information?

**Comment by LindsayYoung** [comment]
I think that is true of people who know what they are doing, but when we talked about it before, it was to make sure that we will have info on the sitting president and senators so people could always find the people who represent them. Otherwise, people were confused why they couldn't find their Senator or the President.
