### ISSUE TITLE
Access/link to the API documentation 

### ISSUE THREAD

**Issue by wluoFEC** [18F/openFEC-web-app#562]
there is no obvious way to access to the API documentation library.

**Comment by LindsayYoung** [comment]
Great point!

**Comment by wluoFEC** [comment]
In addition to a link to the API docs lib, I suggest to add API as one of new features on the beta home page.

![image](https://cloud.githubusercontent.com/assets/7440932/9612150/de7e28b4-50b1-11e5-831e-b385e73a783a.png)

**Comment by noahmanger** [comment]
That makes a lot of sense to me.

On Tue, Sep 1, 2015 at 11:02 AM, Wei Luo <notifications@github.com> wrote:

> In addition to a link to the API docs lib, I suggest to add API as one of
> new features on the beta home page.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/7440932/9612150/de7e28b4-50b1-11e5-831e-b385e73a783a.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/562#issuecomment-136813610>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by jenniferthibault** [comment]
@emileighoutlaw / @LindsayYoung do we have short simple text somewhere that introduces the API?

Need: 
 - [ ] text for the blue card (headline/intro sentence)
 - [ ] description text underneath the card

**Comment by jenniferthibault** [comment]
ping! @emileighoutlaw : thoughts on intro text here?

**Comment by emileighoutlaw** [comment]
Thanks for the ping! I've been thinking about this a lot, because I don't want non-tech-savvy folks to be confused and think the API documentation might be a place where they should go to search for information. 

How about something like:

*Headline/intro:* Check out our API documentation
*Description:* Take a look at our interactive documentation; this API is the backbone of betaFEC's campaign finance data.


thoughts @LindsayYoung ?

**Comment by LindsayYoung** [comment]
Sounds good to me

**Comment by jenniferthibault** [comment]
As I started poking around in the layout, I found that we could actually give it a little more breathing space if we moved allowed it to be it's own element, instead of a 5th card. Since the API itself is geared toward heavily technical users, I don't want to raise it too far up the page, and interrupt the experience of less-technical user who aren't looking for it. On the other hand, I thought it deserved a size-able amount of page space, so that the people who would use it, definitely see it. 

I borrowed from the text above and form @LindsayYoung's EXCELLENT intro to API's blog post draft for the text I've included here, which makes it extremely approachable for all audiences. @emileighoutlaw I didn't mean to make a u-turn on the text needed, it just came out through the design! Would love your help improving it!

cc @noahmanger — thoughts?

![screen shot 2015-09-15 at 9 06 03 am](https://cloud.githubusercontent.com/assets/11636908/9877178/3486d42c-5b89-11e5-9018-a00db390bbce.png)

**Comment by emileighoutlaw** [comment]
I LOVE this introduction and text.

**Comment by emileighoutlaw** [comment]
Also! We should eliminate the comma after "programs," because FEC does not use the serial comma!

**Comment by LindsayYoung** [comment]
<3 Love it Jenn!

**Comment by wluoFEC** [comment]
LOVE the design Jenn! You Are The Best!
