### ISSUE TITLE
Election table styling

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#572]
A few minor issues on styling election tables (screenshots below):
* Value bars for one cell can run into the next
* The contribution location table is hard to read with too many candidates selected

@noahmanger and @jenniferthibault: I'm guessing you're already aware of these--just filing the issue so we get these in better shape before launch.

<img width="576" alt="screen shot 2015-09-02 at 11 50 53 pm" src="https://cloud.githubusercontent.com/assets/1633460/9650231/3a9ec15e-51ce-11e5-8cd0-b0c3ed6f4ed7.png">
<img width="985" alt="screen shot 2015-09-02 at 11 51 05 pm" src="https://cloud.githubusercontent.com/assets/1633460/9650242/3fdc4358-51ce-11e5-85c5-f55ad76e43a8.png">

**Comment by noahmanger** [comment]
I'm fixing the issue of bars running into one another with https://github.com/18F/openFEC-web-app/pull/581.

Not sure how to handle the issue of too many candidates. Any ideas?

**Comment by jmcarp** [comment]
I was hoping that we could just use the `scrollX` option in DataTables (https://datatables.net/reference/option/scrollX), but I tried, and it seemed to conflict with something in our styles. If that behavior seems reasonable, maybe @noahmanger or @msecret could take a look at getting `scrollX` to work, or pairing with me to debug.

**Comment by jenniferthibault** [comment]
Table cells definitely need more padding between each other— not sure if your fix addresses this @noahmanger , but one way I did that in the mockups was to left-align the cell copy with the column title copy, instead of the sorting arrow. Here's an existing mockup for how a scrolling table could look (including the cell alignment), which, I *think* is what `scrollX` does, as far as I can tell?

![screen shot 2015-09-04 at 4 16 24 pm](https://cloud.githubusercontent.com/assets/11636908/9693728/a59c479e-5320-11e5-9e50-ecacbd2ae7c0.png)

**Comment by noahmanger** [comment]
I'm running into snags trying to get the `scrollX` working. @jmcarp do you mind taking a look?

**Comment by jmcarp** [comment]
@noahmanger I got a decent start on this but could use a second pair of eyes on a few last issues--see description in #661.

**Comment by noahmanger** [comment]
This has been resolved.
