### ISSUE TITLE
Improve initial election map behavior

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#596]
As @noahmanger pointed out in #592, the initial view of the election map shows every district in the continental US and can look pretty cluttered (although it's a little better now that we have thinner district borders):
<img width="486" alt="screen shot 2015-09-08 at 11 57 25 am" src="https://cloud.githubusercontent.com/assets/1633460/9740073/dc49c9d0-5620-11e5-8789-e5bbe05b5a1f.png">

@noahmanger's proposal:
* Show state outlines on load
* On clicking a state or selecting a state in the dropdown menu, zoom in and show districts

A few issues to think about:
* Should we change from states to districts on zoom, or just on clicking a state?
* Once the user has selected a state or district, should they have a way to show the original map with all states again?

Thoughts @noahmanger @jenniferthibault @onezerojeremy? Do we want this to happen pre-launch? Shouldn't take a whole lot of time to implement.

**Comment by noahmanger** [comment]
First, I don't think this is a necessary pre-launch thing, but if it happens, cool. 

I think it should show districts at a certain zoom level, and that zoom level should probably be the same as whatever it sets it to when you click on the state. 

And then yeah, I think if you zoom out beyond that level it should go back to just showing state outlines and also reset the results.

**Comment by jenniferthibault** [comment]
Thanks @jmcarp for the well organized thoughts!

I dig @noahmanger 's proposal, and would also suggest removing the labels for bodies of water, if we can, since they're a bit distracting, and not what we're actually looking at here. (Gulf of Mexico, Hudson Bay, Caribbean Sea above)

 - On zooming: I can imagine that turning state to districts on zoom will be useful—if only to avoid confusion if someone were to zoom in 3 or four times but not see anything different. While this may not be our preferred behavior, (I'm guessing clicking a state is preferred) it would prevent someone from getting stuck.
 - On showing the original map: Keen to hear others' thoughts, but I'm not sure we'd need to give more options than the zoom out button.

This is more style oriented, but if this could be implemented with the consistent styles outlined here pre-launch,  https://github.com/18F/openFEC-web-app/issues/420#issuecomment-135582800 that would be + :100:

**Comment by jmcarp** [comment]
All sounds good to me! Minor complication re. @noahmanger's point:

> I think it should show districts at a certain zoom level, and that zoom level should probably be the same as whatever it sets it to when you click on the state.

There isn't a fixed zoom level for clicking on a state or district--we dynamically zoom to the size of the current overlays, so the zoom level for California is different from the zoom level for Maryland. So we can pick a reasonable zoom level for toggling from state to district overlays, but it won't have exactly the same behavior as the existing auto-zoom behavior.

**Comment by noahmanger** [comment]
Oh ok. That makes sense to me.
