### ISSUE TITLE
In order to fit users' mental models of a candidate's election listings, determine the chronological order dates should appear in.

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC-web-app#614]
The dates on the site appear in descending order from left to right. This seems a little odd to me, especially when they appear as a range, e.g., 1994 - 1982. Usually dates appear ascending from left to right, right?

**Comment by jmcarp** [comment]
Agreed that date ranges should usually / always be presented in increasing order. Can you add a URL or screenshot? The ranges I'm seeing (e.g. in https://fec-dev-web.18f.gov/candidates and https://fec-dev-web.18f.gov/?search_type=candidates&search=obama) look right so far.

**Comment by leahbannon** [comment]
There were 2 spots I noticed it. The first is in the list of election years on a candidate page. The second was a range, but I can't remember where it was right now. I'll track it down.

![screen shot 2015-09-10 at 10 13 42 am](https://cloud.githubusercontent.com/assets/4323988/9790642/290a1880-57a5-11e5-99fe-8c25e6e94612.png)

**Comment by noahmanger** [comment]
Do we still want to do this? I think it makes more sense for them to be listed in descending order, so the most relevant election is first. It would be weird on a candidate like [Pelosi](https://beta.fec.gov/data/candidate/H8CA05035/?cycle=2016) to show 1987 first I think.

**Comment by jenniferthibault** [comment]
My inclination is also to put the most recent election first, then followed by older elections (meaning, most recent election --> most distant election). 

If we want to test this, we could ask users to do a card sorting activity, where we give them an unsorted jumble of election years for a candidate, and ask the user to order them so that we can learn what type of ordering people expect to see. Paging @onezerojeremy for testing!
