### ISSUE TITLE
In order to help users see their search criteria clearly, clarify interaction of elections by location search results

### ISSUE THREAD

**Issue by wluoFEC** [18F/openFEC-web-app#617]
1. No easy way to return back to US national map after users select a state/distract.
2. Need to improve presentation for Alaska state/district map.
   ![image](https://cloud.githubusercontent.com/assets/7440932/9790369/a7cab7c6-57a3-11e5-9387-a402fd289105.png)

**Comment by jmcarp** [comment]
Submitted a fix for the Alaska zoom issue in #619. On returning to a national map: if you zoom out enough, we revert to a national map, but that might not be clear to users. I've been talking with @noahmanger about adding a "clear" button as well. Let's discuss after the next round of user testing.

cc @jenniferthibault @onezerojeremy

**Comment by jenniferthibault** [comment]
Based on this and a few other things we heard in usability testing, I have a few proposed design tweaks (based on a quick consultation with @onezerojeremy ):

 - Include a tag field where users can x out of filters they've selected, possibly including a "clear all" button. Here the year range shouldn't be able to be x'ed out of, because there's no scenario where we'd show all Massachusetts (or state) elections/candidates for all of history.
  - this will help bring greater visual distinction to the search parameters. Users were not immediately aware of how the search results changed when they made a second search, since the "US President" result doesn't change for a new search.
 - Include a color key to the map's district pins
  - Users didn't immediately correlate the map color scheme to the colored pins for various districts in the search results
 - Change the detail results copy from Gandhi Serif to Karla Regular, which is the pattern we've been using for any data results. Headlines should still be Gandhi bold
 - Not necessary, but likely an improvement: Move the map up so that it touches the border of the search results. Users were not immediately aware that there was a map on this page (it is currently below the fold, and at least one was happy to see it when she scrolled down)

All of these changes would look like the following. What do you think @noahmanger ?:
![screen shot 2015-09-11 at 6 59 51 pm](https://cloud.githubusercontent.com/assets/11636908/9828125/576883fc-58b7-11e5-8a73-20780f081d8f.png)

**Comment by noahmanger** [comment]
Storymap card: https://18f.storiesonboard.com/m/fec/!card/y0knqjMo79Db7znT6n3rfw
