### ISSUE TITLE
Link to Definition of Candidates on Essentials for House and Senate page

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#688]
https://fec-dev-cms.18f.gov/registration-and-reporting/essentials-house-and-senate-candidates-and-committees/

Can you link to the glossary definition of candidates on the essentials page?

Congressional *candidates* are people running for elected office in the Senate or House of Representatives.

Congressional *candidates* must designate at least one campaign committee. These authorized candidate committees take in contributions and make expenditures for the candidate’s campaign.

@emileighoutlaw

**Comment by noahmanger** [comment]
Do we want both instances to be linked or just the first? It would be good to have a rule on this. I tend to think that only the first instance of a term on a page should be linked.

@emileighoutlaw I can show you how to do this. It's pretty easy.

**Comment by AmyKort** [comment]
I'm fine either way.

**Comment by emileighoutlaw** [comment]
@noahmanger I'd love you to show me! I also tend to think that just the first link is probably sufficient.

**Comment by amypike** [comment]
This may be a silly question but here goes:  What is the purpose of this sentence - "Congressional candidates are people running for elected office in the Senate or House of Representatives?"  Is it to explain to a novice user that "Congressional" includes both the Senate and the House?   That is a basic Civics issue and I'm not saying it isn't valid but I anticipate feedback from OGC that goes something like this:  Not all Congressional candidates have to register with the FEC, the statute and regs use the term "federal candidate," meaning someone running for any federal office who has ALSO raised or spent more than $5,000.   When we say "Congressional candidates," instead of "Federal candidates running for the House or Senate," we are sort of introducing a new term that we never use again.  I know we are putting the definition of candidate (that include in excess of 4%,oo party) in the glossary and linking to it on these pages but I am wondering what the value is of saying "Congressional candidates." We are meeting with OGC this afternoon so I'm just trying to identify their targets and prepare to articulate a response.

**Comment by AmyKort** [comment]
How about:

https://fec-dev-cms.18f.gov/registration-options/

U.S. House and Senate Candidates and Committees
An individual running for a seat in the U.S. House of Representatives or U.S. Senate becomes a candidate [link] under the campaign finance law when she raises or spends in excess of $5,000 in contributions [link] or expenditures [link]. 
Once an individual becomes a candidate, she must register with the FEC within 15 days. Candidates must also designate at least one committee to serve as her principal campaign committee. [link]

@emileighoutlaw

**Comment by emileighoutlaw** [comment]
Not a silly question at all @amypike! I definitely see what you're getting at, but I would like to keep this from becoming super wordy, if we can. 

As a jumping off point, could we say something like:

Generally, a candidate is a person running for office in the House or Senate. See the full, legal definition of a *candidate*(glossary).

Candidates must designate at least one campaign committee. These *authorized committees*(glossary) take in contributions and make expenditures for the candidate’s campaign.

**Comment by emileighoutlaw** [comment]
OR. Could we go with what's on the page before (https://fec-dev-cms.18f.gov/registration-options/):

*Candidates* are people running for elected federal office. Federal office is the House of Representatives, the Senate, or the office of the president.

Candidates must designate at least one campaign committee. These *authorized groups* are called candidate committees.

**Comment by AmyKort** [comment]
I think that we're running into a couple or problems here, as we start to get internal testers' responses to the language. There's a sense that we need to get to the registration threshold sooner--either this applies to you or not. There's also a sense that "candidate" has a specific meaning under the campaign finance law. So, by the time we get to the "essentials page," we'd better be getting around to telling people what we mean by candidate. 

U.S. House and Senate Candidates and Committees

An individual running for a seat in the U.S. House of Representatives or U.S. Senate becomes a candidate [link] under the campaign finance law when she raises or spends in excess of $5,000 in contributions [link] or expenditures [link].

Once an individual becomes a candidate, she must register with the FEC within 15 days.  Candidates must also designate at least one political committee as her principal campaign committee [link]. In addition, she may designate other authorized committees [link].
