### ISSUE TITLE
Register as A House or Senate Candidate Language Change

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#694]
What if we add:

Congressional candidates register with a Statement of Candidacy (Form 2) within 15 days of becoming a candidate. [An individual seeking nomination for election, or election, to a federal office becomes a candidate for the purposes of the campaign finance law when he or she (or agents working on his or her behalf) raises contributions or makes expenditures that exceed $5,000.]

@emileighoutlaw

**Comment by amypike** [comment]
Yes! It's a lot of text but if the purpose of these pages is to help newbies register, I think it is important to underscore when someone becomes a candidate - a newbie may find that she/he is not required to register because they haven't exceeded (or maybe do not plan to exceed) the $5,000 threshold which would be super helpful, methinks.
