### ISSUE TITLE
Name change to "Learn How to Comply with Fed Campaign Finance Law

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#699]
The phrase "Learn how to conduct election activity and run a campaign" is not appropriate. The FEC is not charged with teaching people this at all. We do teach them how to comply with federal campaign finance laws, but we're not going to help them with tactics, strategy, ballot access, etc.... I'd revise to read "Learn how to comply with federal campaign finance law". Also there are other laws they need to learn, that we have no jurisdiction over: ballot access,tax laws, etc. So again, the focus on our site should not be "federal election activity" (which is a specific term of art for party committees, by the way), but "federal campaign finance laws". 

https://fec-dev-cms.18f.gov/registration-and-reporting/

Comment from Dorothy Yeager

@emileighoutlaw 
@amypike

**Comment by amypike** [comment]
Agree!  Now that I am looking at the language with fresh eyes, "run a campaign" is misleading.  "Learn how to comply with federal campaign finance laws" is much clearer.  I am glad that Dorothy flagged the term "federal election activity" (FEA) because that is a statutory term that applies to specific activities undertaken by state, district and local party committee so we should avoid using that it except when referring to those specific activities.

**Comment by emileighoutlaw** [comment]
Agreed, and changed!
