### ISSUE TITLE
To provide feedback and transparency to users in the event of errors, add error handling for datatables ajax

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#733]
When datatables encounters an error or timeout on loading table data from the API, it currently doesn't do anything. We should probably add some error-handling logic here: for example, on error, insert text above the table informing the user that something went wrong. This won't take long to implement, but there are many ways it could be designed, so probably best for @noahmanger and/or @jenniferthibault to weigh in before I start writing code.

IMO, this would be nice to have before launch, but not critical.

Handle errors on: 
- [ ] Fetching data for data tables
- [ ] Election summary (homepage widget)
- [ ] Election search
- [ ] State maps

**Comment by jenniferthibault** [comment]
This seems like a really good idea, and might even be worth trying to sneak in before launch if we can, so that  if/when people encounter errors and report them, they can give us useful error messages to triage. 

What kind of message should be displayed @jmcarp ? (ping to @emileighoutlaw for future wordsmithing and @noahmanger for any ways we should suggest users to get out of the error situation? e.g., "try another search" or "come back later" or links elsewhere?)

**Comment by jmcarp** [comment]
Something like "Error fetching search results. Please try another search."

Or maybe this: http://www.cc.com/jokes/skuh9m/stand-up-mitch-hedberg--mitch-hedberg--please-try-again

**Comment by emileighoutlaw** [comment]
I'd lean toward something like:

"Error loading search results. Please try a different search." 

I think "fetching" could confuse some lower-level readers. With "loading" (let me know if loading isn't an accurate thing to say), they should know it's a processing issue, not a them issue.
