### ISSUE TITLE
Weird data issues

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#742]
While reviewing the IE tab on candidate pages, I noticed a couple interesting things in the data and wanted to flag them for further investigation.

First, Citizens United SuperPAC LLC shows as having spent a lot to both support and oppose [Clinton](http://localhost:3000/candidate/P00003392?tab=other-spending):

![screen shot 2015-09-22 at 4 00 53 pm](https://cloud.githubusercontent.com/assets/1696495/10034244/ec355c00-6143-11e5-8b93-64d1abe7e53e.png)

Second, on [their committee page](http://localhost:3000/committee/C00497420?tab=filings), the Independent Expenditure column isn't showing any data, even though there's numbers reported in the 48 hour reports:

![screen shot 2015-09-22 at 4 07 49 pm](https://cloud.githubusercontent.com/assets/1696495/10034263/1d2850ba-6144-11e5-923c-9180818f50a3.png)

**Comment by PaulClark2** [comment]
So I don' think the "Other spending" tab is available on DEV:  https://fec-dev-web.18f.gov//candidate/P00003392?tab=other-spending

![untitled](https://cloud.githubusercontent.com/assets/11817734/10046240/7b2a9e5c-61d5-11e5-9362-bfd4d96d0d49.png)

Citizens United Super PAC LLC filed three (3) F24s for this independent expenditure.  The original indicated support for Clinton.  On the same day, 6/10, the committee amended the original to correct the support-oppose information to oppose.   On 7/2 the committee amended the report again to provide additional information about the state and update the cost estimate.  

Since I can't see this on the DEV candidate page, are we really going to try to show users 24-hour and 48-hour IE reports?   It think it's ok if we do but these data can get messy and it's always complicated.  I think we'll need lots of language to help users understand what they are looking at.

**Comment by jmcarp** [comment]
A few thoughts:

* @PaulClark2: Right, this is a proposed feature that hasn't been merged yet.
* @noahmanger: It looks like this PAC checked the "support" box by accident: http://docquery.fec.gov/cgi-bin/fecimg/?15951462974. This filing was amended later, but I'm not sure how to exclude it--all Schedule E transactions between this PAC and Hillary Clinton appear to be marked as amendments. @PaulClark2: how should we handle this kind of thing?
* @PaulClark2: The committee filings tab is currently showing all filings for the relevant committee. If some form types might be confusing to users, we can add more explanatory text, or potentially restrict the form types we're showing--although I always prefer not to hide data.

**Comment by noahmanger** [comment]
That makes sense. But yeah we definitely need to figure out how to handle
amendments in this regard.

On Wed, Sep 23, 2015 at 10:30 AM, Joshua Carp <notifications@github.com>
wrote:

> A few thoughts:
>
>    - @PaulClark2 <https://github.com/PaulClark2>: Right, this is a
>    proposed feature that hasn't been merged yet.
>    - @noahmanger <https://github.com/noahmanger>: It looks like this PAC
>    checked the "support" box by accident:
>    http://docquery.fec.gov/cgi-bin/fecimg/?15951462974. This filing was
>    amended later, but I'm not sure how to exclude it--all Schedule E
>    transactions between this PAC and Hillary Clinton appear to be marked as
>    amendments. @PaulClark2 <https://github.com/PaulClark2>: how should we
>    handle this kind of thing?
>    - @PaulClark2 <https://github.com/PaulClark2>: The committee filings
>    tab is currently showing all filings for the relevant committee. If some
>    form types might be confusing to users, we can add more explanatory text,
>    or potentially restrict the form types we're showing--although I always
>    prefer not to hide data.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/742#issuecomment-142619341>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146
