### ISSUE TITLE
So users can easily browse districts in their state, we will show all districts in ascending # order

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#766]
Washington State election results look weird: https://fec-proxy.18f.gov/data/elections/?cycle=2016&state=WA

The districts are out of order, there's a district 99, and it's missing 1 and 6, which do have pages.

**Comment by leahbannon** [comment]
Most of the states with more than 2 or 3 districts show the districts out of order and are missing some.

**Comment by jmcarp** [comment]
Looks like there are a few distinct issues here:

1. Elections aren't sorted by district. This is fixed in https://github.com/18F/openFEC/pull/1272.
1. Some elections for which candidates have filed aren't displayed. This is fixed in https://github.com/18F/openFEC/pull/1273.
1. Elections for which no candidates have filed aren't displayed. This is expected (from my point of view), but can be changed. That change might be part of a larger reorganization of the election search page that @jenniferthibault and @noahmanger started talking about a few weeks back.
1. Some elections for district 99 are showing up. AFAICT, this is related to some data errors around office districts that I just described in https://github.com/18F/openFEC/issues/1271. We can add a filter to exclude district 99 for now, but a longer-term fix would to be figure out why we're seeing these districts in the first place (note for @LindsayYoung: the district 99 values don't seem to be specifically related to F2z records).

1. and 2. are fixed. Since I think there's some ongoing discussion around 3., I'd like to defer for now. For 4., we can wait and see if there's a quick fix on the FEC side, or put in a workaround that hides district 99 values on our side. What do you think @LindsayYoung?

**Comment by noahmanger** [comment]
This sounds right on. You're right that we began [rethinking the elections search](https://invis.io/244KD9TRX), so no need to touch that yet. These fixes will make it consistent with the logic we originally designed.

**Comment by jmcarp** [comment]
All right, all the interim solutions we've been talking about here have been implemented. Based on discussion in https://github.com/18F/openFEC/issues/1271, we may have a better solution to the district 99 problem, but that's probably beyond the scope of this issue. Can this be closed @noahmanger?
