### ISSUE TITLE
feedback tool for every page

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC-web-app#806]
- [x] @emileighoutlaw & @onezerojeremy write the questions
- [x] @jenniferthibault design the wireframe
- [x] @jmcarp implement tool

Needed functionality:
- send directly to github issues
- one of the fields should capture the URL

**Comment by jmcarp** [comment]
GitHub issues need to be filed on behalf of a user. We'll probably want to create a special user without write access for this purpose. How about something like fec-issues? Should I go ahead and create that account?

**Comment by jenniferthibault** [comment]
That makes sense semantically to me. We could also make it clear that it's a bot (or non-person account) if that's important, such as FEC-IssueBOT ?

**Comment by leahbannon** [comment]
This might be helpful WWBD https://github.com/benbalter/redliner

**Comment by leahbannon** [comment]
Also! https://github.com/benbalter/problem_child

**Comment by emileighoutlaw** [comment]
Are we envisioning a widget-thingy on the bottom of every page? Let me know if I'm off base, but in my head, I'm imagining something along the lines of:

`Report a problem`
which, when clicked, expands to a box with a field for the URL and a field for the issue itself. 

Things we'll need: A disclaimer not to enter personally identifiable information in the text boxes. I like this tweak of the CFPB's:

*Don’t include sensitive information like your name, contact information, or social security number in this field*

**Comment by noahmanger** [comment]
Problem child looks like it could be useful, but may end up being more than we need. @emileighoutlaw you're right. I believe we want a button on every page that can trigger a modal of some sort with a form. 

Good call on the disclaimer. And I like the idea of `fec-issue-bot` or something along those lines.

**Comment by jmcarp** [comment]
Looks like problem child is written in ruby, so using it here isn't an option, but we can still use Ben's code for inspiration. By the way, sorry if I'm missing something, but why would we have the user submit the URL of they page they're on? That's information we get automatically, so the only reason to include that field would be to let users report bugs about pages they aren't looking at anymore.

**Comment by noahmanger** [comment]
Oh if we can get that automatically let's just do that.

On Mon, Oct 5, 2015 at 2:49 PM, Joshua Carp <notifications@github.com>
wrote:

> Looks like problem child is written in ruby, so using it here isn't an
> option, but we can still use Ben's code for inspiration. By the way, sorry
> if I'm missing something, but why would we have the user submit the URL of
> they page they're on? That's information we get automatically, so the only
> reason to include that field would be to let users report bugs about pages
> they aren't looking at anymore.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/806#issuecomment-145678057>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by jmcarp** [comment]
Started in #810.

**Comment by noahmanger** [comment]
Ok, very simple, but here's a couple ideas:

The button could be a simple "Report a problem" on the bottom:

![button - bottom](https://cloud.githubusercontent.com/assets/1696495/10350133/1eb12de4-6cf7-11e5-9bfe-3a7a54ee52a8.png)

Or on the side:

![button - side](https://cloud.githubusercontent.com/assets/1696495/10350140/26b1bb08-6cf7-11e5-81d3-600c89d93c6e.png)

And it triggers either a modal:
![modal](https://cloud.githubusercontent.com/assets/1696495/10350238/b487fdfc-6cf7-11e5-933d-f3a2c60d4532.png)

Or a box slides up from the bottom:
![bottom](https://cloud.githubusercontent.com/assets/1696495/10350236/af095d9e-6cf7-11e5-8685-193dc1fce921.png)

I could see a couple ways of capturing feedback (as seen in both examples): either a single box that just dumps into the body of the issue, or we could split it up into "Bug" and "expected behavior" to try to get more structured data. In this case, it would still show up in the body of the issue, but might give us better information. We'll also be able to automatically capture the page they're on and (roughly) their browser, so no need to ask for that info.

I include disclaimer language like Emileigh mentioned above, and also we should have a line that explains this will be posted publicly on github with a link to the issues.

Looking for feedback on general UI (Don't worry about exact visual feedback, I just chose to do it loosely in the style because it was easy):
- Does the button work better on the bottom or side? 
- Do you like the modal or bottom box more? 
- Does this include all the fields we want?

**Comment by leahbannon** [comment]
imho, fwiw...
* I like the bottom box more because it will allow people to more easily see or copy and paste the page, especially if they're having a data issue that they want to copy and paste.
* I like the disclaimers you have. I think we might even be able to get away with just the "describe the problem" field.
* I like the tan background more than blue on blue.

**Comment by PaulClark2** [comment]
I agree with Leah's 3 points and would add the button should probably just say "Feedback."  Should the feedback form text be more generic?  If a user wants to tell us he's confused about the presentation that's different from a link didn't work or Joe Six-pack was never an incumbent.  

A question about the feedback button position -- right side or bottom.  If it's on the right side will the user be able to dismiss it if it's blocking their view of any text or data?   If it's at the bottle will it float of the bottom of the screen or will it be at the bottom of the page?

**Comment by jenniferthibault** [comment]
@noahmanger / @PaulClark2 / @leahbannon a third alternative that wouldn't involve a modal or popup that overlaps anything would be how the UK digital service team solicits feedback: a link or button right above the footer. It asks two main questions:

- What were you trying to do? [text box]
- What went wrong? [text box]

To which we could add an alternate
 - OR: Just give us some feedback [text box]

And keep @emileighoutlaw 's excellent disclaimer/sensitive data message, and the link to where comments go in GitHub

![feedback](https://cloud.githubusercontent.com/assets/11636908/10371180/1c6d3578-6db0-11e5-9e01-7c6df57d1eb8.gif)

I find this approach interesting because it doesn't overlap any of the page, so users can still copy/paste text or see what they were trying to do in the first place as they write, AND because the prompt language encourages users to help us problem-solve.

If anyone else finds this interesting or worth seeing, I'm glad to wireframe it up too

**Comment by emileighoutlaw** [comment]
Oh I really like this idea, @jenniferthibault

**Comment by PaulClark2** [comment]
:+1:

**Comment by jenniferthibault** [comment]
Sounds like it's at least worth a wireframe. I'll get on that now and hopefully will have it right in time for those west coasters to wake up :)

**Comment by jenniferthibault** [comment]
Here's a take on that in the betaFEC style & with @emileighoutlaw 's language. I'm keen to hear @noahmanger 's thoughts overall on the interaction, since this would include the box above the footer on every page, so users would only see it at the bottom, instead of a button fixed to the edge of a screen.

#### Closed:
![screen shot 2015-10-08 at 12 56 36 pm](https://cloud.githubusercontent.com/assets/11636908/10373561/42f22a8a-6dbc-11e5-8d26-eeb25276b95c.png)

#### On click:
![screen shot 2015-10-08 at 12 56 25 pm](https://cloud.githubusercontent.com/assets/11636908/10373576/4f3697f4-6dbc-11e5-92a4-9c00a1a8a867.png)

#### Confirmation after hitting "Send"
![screen shot 2015-10-08 at 1 02 18 pm](https://cloud.githubusercontent.com/assets/11636908/10373670/eab22aae-6dbc-11e5-956d-9d07f017d4cf.png)

**Comment by emileighoutlaw** [comment]
Oh I love this. How would people feel about changing `Is there anything wrong with this page?` to either 
`Is anything wrong with this page`or (I prefer) `Is something wrong with this page?`

**Comment by amypike** [comment]
The box and button look wonderful! I agree with @PaulClark2  comment, above,  that "Is something wrong with this page?" sounds like a link didn't work or the data seems inaccurate, not that the interface is confusing.  I offer that the, shall we say, "intense interest" in the feedback box was very much to get "user's thoughts," not just report that something is wrong.  @emileighoutlaw , "Is something wrong with this page? Want to tell us something?"  Is that too long? Too many thoughts in one string?  I'm not sure how to make it clear that we're looking for both problems and feedback.

**Comment by noahmanger** [comment]
Ah! Ok, this is all helpful. For starters, I like the interaction above, but wonder if it still might be better to have it fixed to the bottom of the screen? Slightly worried that people will miss it if they don't scroll all the way down. The only change I'd make to the interaction for sure though is when it's open there should be a cancel or close button.

As far as language, this raises a good point. The thing with collecting general feedback through a tool like this is it really needs to be taken with a grain of salt, and it gives a very limited picture of what's working vs not. My understanding from more seasoned researchers than me is that for one, you get some self-selection bias (e.g. you're more likely to get feedback from the loud, opinionated users rather than a representative sample), and two, as you can imagine, the feedback will likely skew more negative as people give feedback if they're unhappy. 

Which isn't to say that it's not valuable data to get, but just that it's also important that it's part of a broader research program that includes continued moderated usability testing. Which I know we'll continue to do. I just don't want to get into a situation where we're overvaluing the feedback we get through this tool.

This is why I originally went with the "report a bug"-style language. This feedback is a) more actionable and b) prompts for _a_ (not _the_) specific type of feeedback that's useful to us, which is actual bugs or errors in the data.

Now, I understand the interest in crafting language that doesn't make people lose confidence in the site, but I think there's gotta be a way to do it so that people understand if they do find a data error they should report it.

Just my $.02

**Comment by leahbannon** [comment]
To Noah's point, if this was something like a sticky banner across the bottom, this could also be a good opportunity to remind people this is a beta and that fec.gov is still the main place

**Comment by AmyKort** [comment]
For the feedback box:  Our primary concern is to make commenting as easy as possible for users. We think a sticky box/banner is key to this. Whatever part of your screen you're looking at, we want you to be able to make a comment. The box needs to be labeled "feedback" or something to that effect rather than "report a problem." It is important to us to cast a very wide net to catch comments from our users. Our preference is to have the stick box unroll from the side of the screen. Also, would it be more visible to users as a circle/button rather than as a line/bar?

**Comment by PaulClark2** [comment]
I'll repeat what I said above and I'll agree with Amy's comment above the box or circle needs to be labeled "feedback"

**Comment by onezerojeremy** [comment]
I know and respect the need to get input from users. We want it. Absolutely. Full stop. 

Apologies if you all know all this, but I feel like I wouldn't be doing my job if I didn't raise a slight concern about an open ended feedback box. One of the weirdest parts of learning to be a user experience designer is learning that you can't actually just ask your users what they think. Some of us call it *the Henry Ford problem*, based on the famous quote about how if he asked his users what they wanted, they would've asked for a faster horse. 

I'm not asking you to take my word for it, though. This is from Jacob Nielsen, head of NNG, one of the foremost user research groups in the world:

>So, do users know what they want? No, no, and no. Three times no.

>Finally, you must consider how and when to solicit feedback. Although it might be tempting to simply >post a survey online, you're unlikely to get reliable input (if you get any at all). Users who see the survey >and fill it out before they've used the site will offer irrelevant answers. Users who see the survey after >they've used the site will most likely leave without answering the questions. 

from: [First rule of usability: don't listen to your users](http://www.nngroup.com/articles/first-rule-of-usability-dont-listen-to-users/)

Now this is not to say we shouldn't solicit input! We absolutely should! We just need to give people some guard rails, so that we don't get a really noisy signal, and make sure we combine that signal with what we're watching users do. That's in part why we're pushing to go live with the beta: once live, we can implement other kinds of tests beyond the moderated usability tests which we've relied on, such as getting metrics on how users navigate the site (e.g., what users do), and experiments that involve subtle tweaks to find out which actually work better for people (as opposed to what they think will).
