### ISSUE TITLE
To help users make specific inquiries, add additional departments to Contact Us page

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#825]
Current contact page includes:
- Electronic Filing Office
- Information Division
- Reports Analysis Division
- Public Records Office

We'd like to include any additional offices that would be *especially useful to users* with specific questions for FEC.

Steps:
- [x] @amykort @amypike help identify outstanding offices needed for page
- [x] Incorporate into new Contact Us page that Jen is designing

**Comment by AmyKort** [comment]
I would add the Press Office (202-694-1220)

**Comment by emileighoutlaw** [comment]
Awesome! Anything else?

**Comment by AmyKort** [comment]
I think those are our primary, public-facing offices. The only other 
numbers we might add at some point are our Congressional Affairs Office 
(202-694-1006) and our general number (202-694-1000). But, I don't think 
either of those offices support the content we currently have on the beta 
site. We might want to expand the list as we add functionality.

**Comment by amypike** [comment]
I tend to agree with you, AK (shocking!) that Congressional Affairs is 
unnecessary at this juncture because we speak to incumbents, not 
challengers, and the content is for lay users.  My (and Duane's) only 
hesitation is that our office plans to do some outreach to our oversight 
committees in preparation for the launch to get them interested and having 
our number there makes them feel included so if it's all the same, go 
ahead and put our 202 -694-1006 on the beta. 




AmyKort <notifications@github.com> 
10/14/2015 11:00 AM
Please respond to
18F/openFEC-web-app 
<reply@reply.github.com>


To
18F/openFEC-web-app <openFEC-web-app@noreply.github.com>, 
cc
amypike <apike@fec.gov>
Subject
Re: [openFEC-web-app] To help users make specific inquiries, add 
additional departments to Contact Us page (#825)






I think those are our primary, public-facing offices. The only other 
numbers we might add at some point are our Congressional Affairs Office 
(202-694-1006) and our general number (202-694-1000). But, I don't think 
either of those offices support the content we currently have on the beta 
site. We might want to expand the list as we add functionality.

**Comment by AmyKort** [comment]
I absolutely agree with you, AP. Let's put in Congressional Affairs.
