### ISSUE TITLE
Bug: Unexpected behavior for All independent expenditure committees active 2015-2016 link

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#853]
The All independent expenditure committees active 2015-2016 link misbehaves.   It takes the user to a list of 2016 committees.   Using Firefox if you hit the back button the IE filter become populated.  

https://beta.fec.gov/data/
https://beta.fec.gov/data/committees/?committee_type=I&committee_type=O&committee_type=U&cycle=2016

![untitled](https://cloud.githubusercontent.com/assets/11817734/10550971/070f6ade-7418-11e5-9814-553d7d7c294b.png)

Notice the filers are not pre-selected and there are authorized committees in the list
![untitled](https://cloud.githubusercontent.com/assets/11817734/10551007/3033bfc8-7418-11e5-8867-079e50ae0b5b.png)

Using Firefox press the back button
![untitled](https://cloud.githubusercontent.com/assets/11817734/10551036/6eb01012-7418-11e5-8ed9-d4b9df8158bc.png)

**Comment by jmcarp** [comment]
I just tried to reproduce this but didn't see the error--on clicking the IE link, I got a list of I, O, and U committees for 2016, and the filters were all populated without clicking back. I tried in Chrome and Firefox. It's possible that there was a bug that was fixed in an unrelated patch, but I'm not sure.

@PaulClark2, would you mind trying this again and letting me know if you're still seeing this behavior?

**Comment by PaulClark2** [comment]
@jmcarp It's behaving as expected now.   I think we can close this issue.

**Comment by jmcarp** [comment]
Thanks!
