### ISSUE TITLE
Bug: Report totals missing from details panel

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#874]
Just happened to notice this while clicking around on [this page](https://fec-proxy.18f.gov/data/filings/?cycle=2012&committee_id=C00431445&amendment_indicator=N&form_type=F3&form_type=F3P)
![image](https://cloud.githubusercontent.com/assets/1696495/10644860/9efb0612-77df-11e5-829a-e322cbd03b40.png)

The details panel is missing all kinds of numbers, but those are [reported on the form](http://docquery.fec.gov/pdf/468/12971298468/12971298468.pdf) and on the [committee page](https://fec-proxy.18f.gov/data/committee/C00431445/?cycle=2012&tab=filings) the numbers are there:
![image](https://cloud.githubusercontent.com/assets/1696495/10645029/695a7a3c-77e0-11e5-9ab4-b637987da073.png)

Not sure how we can figure out if this is a broader pattern.

**Comment by noahmanger** [comment]
Update! I realized that in one case I was looking at the Amended report (that's the one that has the data) and one was looking at the New report. The New one in both pages misses the data.

**Comment by noahmanger** [comment]
And even in this case, do we want the links to "Source forms" to only link to New reports?

**Comment by jmcarp** [comment]
There's a discrepancy between the way we handle filings in general and the way we handle F3* forms. We discard all F3, F3P, and F3X forms with non-null expiration dates (meaning they've been amended). For filings in general, we keep both new and amended filings. The result is that when we try to load detailed data for a filing that's been amended, we don't get any results, because we've discarded F3* data for those records.

To fix, it seems like we'll want to make the behavior consistent by either including both amended and non-amended F3* forms, or by discarded amended filings in general. I generally lean toward exposing more data, so my first thought would be the first option.

What do you think @noahmanger @LindsayYoung @PaulClark2?

**Comment by jmcarp** [comment]
Just to be clear, we'll definitely want to continue to exclude F3* forms from our two-year aggregates.

**Comment by LindsayYoung** [comment]
I like the idea of adding the amended report details. We would need to amend the api call that makes the charts on the financial summary on the committee pages. 

![screen shot 2015-10-22 at 12 06 13 pm](https://cloud.githubusercontent.com/assets/4406333/10670801/545e411a-78b5-11e5-89c3-80debe2dab90.png)

When these were on the committee pages, we showed nulls as none with a link to none in the glossary. Maybe that would be a good approach here.

**Comment by noahmanger** [comment]
Ah got it. This is tricky. I agree that it's good to show the original numbers and the new numbers, but this requires some design work, I think. I could see a couple options:

1. In the details panel for amended filings, show the original numbers and the new numbers above or below them.
2. Just show the old numbers, but with a banner saying that the filings has been amended and linking to the amendment.

Or maybe a combination of the two.

Still I don't get why some of the numbers on the amended form show up and not others? Shouldn't it all be blank?

**Comment by LindsayYoung** [comment]
We can't link to the new one yet. We don't have the "amended by" information but that is one of the things I think we will cover in the data meeting. 

We can add a banner saying that record has been amended.

**Comment by noahmanger** [comment]
So can we even show the new numbers in that case?

**Comment by LindsayYoung** [comment]
We show the new numbers on the new form. 

I am a little confused. I don't think I am understanding your question. This view is about the forms, so we would not want to show the numbers for another form on the form we are viewing, right?

**Comment by PaulClark2** [comment]
So the issue here is being able to show the summary/detailed summary information for all financial forms, new or amended, correct?  I guess there are a few ways to do this:  display the data on the details panel (this might take more time to do) or, perhaps, a short-term fix provide a link to the image for the filings that are not the most recent.

**Comment by jmcarp** [comment]
@PaulClark2: we proposed a fix in https://github.com/18F/openFEC/pull/1289. Instead of excluding all amended F3* records at the level of the materialized views, we're now including them and adding a filter to hide or show them as needed. That means we can fetch the relevant data for the details pane for records that have been amended.
