### ISSUE TITLE
Bug: many committees cycle selections not working 

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#875]
Just noticed

Not working:
https://fec-proxy.18f.gov/data/committee/C00507384/?cycle=2010
https://beta.fec.gov/data/committee/C00507384/?cycle=2010

Working:
https://fec-proxy.18f.gov/data/committee/C00507384/
https://beta.fec.gov/data/committee/C00508002/

More examples that work the same on dev and production:
https://beta.fec.gov/data/committee/C00443176/?cycle=2006
https://beta.fec.gov/data/committee/C00508002/?cycle=2010

**Comment by jmcarp** [comment]
Looks like we caused this in #1202. We're getting the list of active two-year periods from `vw_filing_history`, but we're populating most other fields in `ofec_committee_history_mv` using `dimcmteproperties`. So for committee C00507384, we think we'll get data for 2008-2016, but we only have records in `dimcmteproperties` from 2010-2016. That's because this committee filed a few F3s before its first F1--meaning we have fundraising data before we have basic information about the committee.

We probably don't want to roll back #1202, since that would reintroduce problems with ECs and CCs. We *could* use a full outer join to join `dimcmteproperties` on `cycles`, but then we'd wind up showing committee pages with mostly null values. We could also show the next available F1 for the committee, but that would mean sometimes looking into the future to populate the committee detail page, which strikes me as a bad idea.

What do you think @LindsayYoung? This may be another item to add to discussions on Friday.

**Comment by LindsayYoung** [comment]
I think that full outer join with showing committee pages with mostly null values might be the best we can do. Especially if we ever add back ballot candidates, they won't have any summary data or even filings.

**Comment by jmcarp** [comment]
@LindsayYoung and I put in a temporary fix for this to avoid problems during launch. Let's continue discussion of a better solution in https://github.com/18F/openFEC/issues/1287.
