### ISSUE TITLE
Bug: Some receipts links break back button

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#888]
We've almost squished this persistent bug, but I found two more locations where this happens:

From the committee page receipts tab, the links in the By Employer and By Occupation tables both send you to a receipts page that won't allow you to use the browser back button.

**Comment by jmcarp** [comment]
This should have been fixed by #889--the problem seems to have come from null employers and occupations, with links like "...&employer_occupation=&min_date=...", since the empty query parameters were removed from the URL on table initialization. Can this be closed @noahmanger?

Going forward, #895 should give us a more comprehensive solution to this kind of problem.
