### ISSUE TITLE
Bug: Safari browse tables jump user to custom date field when loaded

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#930]
In Safari, when you navigate to the Filings, Receipts, or Disbursements browse tables, you are automatically jumped down to the custom date field. This doesn't happen on the Committee or Candidate browse pages, and doesn't happen in Chrome or Firefox.

![table-bug](https://cloud.githubusercontent.com/assets/11636908/11001919/f2b1099c-8477-11e5-8a20-56b5b6d17271.gif)

**Comment by noahmanger** [comment]
Trying to troubleshoot this, and I'm finding that Safari just isn't even loading the datatables at all on develop (production works fine). There's no errors in the console and the debugger's being a pain, so a bit of a mystery.

**Comment by jmcarp** [comment]
@jenniferthibault: I saw the same problem on production, but not on develop, whether locally or at https://fec-proxy.18f.gov/data/receipts/, etc. The issue may have been fixed during recent refactors of the browse filters that haven't made it to production yet.

@noahmanger: I'm not replicating the problem you described about tables not loading in safari (version 9.0.1). The filter typeaheads are messed up, though:

<img width="290" alt="screen shot 2015-11-20 at 8 14 01 pm" src="https://cloud.githubusercontent.com/assets/1633460/11315633/54d96b86-8fc3-11e5-9f77-ad39fe9a17f3.png">

Looks like a recent regression, since I don't see it on production. I'll take a look.

**Comment by noahmanger** [comment]
Yep, I see that too.

**Comment by noahmanger** [comment]
I'm not seeing the jumping issue in safari any more. @jenniferthibault can you see if it's still happening for you? Might have just been a browser bug.

**Comment by jenniferthibault** [comment]
Nope, not seeing the jumping problem, but the search boxes are a different type of messed up:

![screen shot 2016-01-27 at 12 20 38 pm](https://cloud.githubusercontent.com/assets/11636908/12621843/7d1414e0-c4f0-11e5-9cdd-0c68e86a4e8a.png)
![screen shot 2016-01-27 at 12 20 52 pm](https://cloud.githubusercontent.com/assets/11636908/12621842/7d1065ca-c4f0-11e5-9833-73c9f22641b0.png)
![screen shot 2016-01-27 at 12 21 02 pm](https://cloud.githubusercontent.com/assets/11636908/12621844/7d1a4ed2-c4f0-11e5-9696-edc9bc6954ab.png)

**Comment by noahmanger** [comment]
Yep, that's logged here: https://github.com/18F/fec-style/issues/230

I'm totally stumped on that one. But this issue seems to be resolved, so I'm going to close.
