### ISSUE TITLE
Refine design of 2/4/6 selector

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#942]
In going with this option... 
![option b](https://cloud.githubusercontent.com/assets/11636908/10526105/cbe963a4-7356-11e5-85a2-474a9cf22800.png)

...there's a few design refinements that have been suggested by usability testing (via @onezerojeremy, with a couple edits):

1. People want Option B toggles in chronological order, after the full election cycle toggle.

2. There's the suggestion that when selecting the "All" option, you could visually show how it encompasses the other two or three options.

3. The links to the election pages now compete with the election drop down. We need to tweak this: possibly by only including a link to the drop-down selected election (as perhaps a more substantial call to action), not sure.

**Comment by jenniferthibault** [comment]
@onezerojeremy / @noahmanger , clarification on point 1 here: aren't both the drop-down and the toggle already in chronological order?

**Comment by jenniferthibault** [comment]
With clarification on 1st point outstanding, here's what I'm thinking:

The first state is nothing selected, second state is one period selected, third state is full cycle selected.
![cycle-select](https://cloud.githubusercontent.com/assets/11636908/11215362/b80c0b58-8d13-11e5-8cfd-5786c3e0d7f2.png)

On interaction, I'd think that you could choose any other item in the toggle in order to deselect the current state. So for "Full cycle" - clicking any other item in the toggle besides Full Cycle, would deselect the entire selection except the period which the user clicked to exit full cycle selection.  All in one click, and making it so we don't need a "clear selection" button of any sort. (hard to type out, glad to explain)

**Comment by noahmanger** [comment]
Nice. This is looking good. A couple things:
- Re: chronological order, sorry that was unclear. I think the suggestion was to reverse it so that the most recent two-year option was on the left (but the "all" options is still the left-most)
- I don't think we should ever have a "none selected" state. When you first load the page, one of the options will be selected, and then you'll just change it from there, right?
- I like the interaction of choosing "Full cycle" and the other options get selected. Though it might feel a little weird to then click one option and the others are de-selected. Typically in this kind of interaction, clicking a selected option de-selects it but keeps the others selected. I wonder if we want to try a third state that somehow signifies that the options are included in the "Full cycle" without making it seem like the _buttons_ are selected?
- If we're showing the increments as selected, we might be able to get away with removing the years from the "full cycle" button. I'd also be interested in seeing how it worked with the text of that button simply being "All". "Full cycle" feels a little insider-y, but could be just me.

**Comment by jenniferthibault** [comment]
1. Gotcha
2. :+1: What would you like the default state to be? Most recent cycle?
3. As I understood this, you can't select two of the three options from the toggle bar, just one at a time, so that's what I was getting at . I'm not quite sure I know what you mean by the second part, make it seem like it's selecting everything without selecting everything? Can you point to a pattern you've seen elsewhere? Or maybe we just need to chat this out quick.
4. I'm all for all! But the language is as it is now because of a specific request from one of the commissioners, so I'd like to make sure we test the "All" before it goes live to make sure we have justification for that change.

**Comment by noahmanger** [comment]
2: Per the discussion in Slack just now, the default should be the full cycle.
3: I can explain this over video.
4. Ah I forgot about that. Let's test the "All" option with users on Thursday with the working tool.

**Comment by jenniferthibault** [comment]
Thanks for holding on through these detail-based iterations all—here's where I think we've landed:

![screen shot 2015-11-17 at 7 49 07 pm](https://cloud.githubusercontent.com/assets/11636908/11229540/4c4f0d88-8d64-11e5-865d-4db5c7f35131.png)

- For testing this round, having the "All" button activate the active state for each toggle, which can be undone by simply clicking on any toggle button
- Default result when landing on a page is "All" in the most recent election
- Listing elections in the top profile section, but not making them active links to remove competition
- Adding a strong (visual) link to the election page associated with what the user has selected
  - For now, Using the election search icon as a placeholder, but when we're ready for more polish, using an icon of each state for Senate/House elections, and an icon of the whole US for presidential elections  
![screen shot 2015-11-17 at 7 48 13 pm](https://cloud.githubusercontent.com/assets/11636908/11229559/8b2521b4-8d64-11e5-9b18-e2e4244ed0a9.png)


Here's a mockup with grid lines for structural cues @noahmanger 
![screen shot 2015-11-17 at 7 47 53 pm](https://cloud.githubusercontent.com/assets/11636908/11229594/dd3c3cbc-8d64-11e5-8a46-8c1ff31f15b7.png)

Ping me with questions!

**Comment by jenniferthibault** [comment]
OH! One last thing — we should probably remove the tooltip here in implementation, since the disclaimer text isn't needed anymore. (I did so in the design)

**Comment by noahmanger** [comment]
Excellent! This looks great. Thank you! Will get to it in the morning.

**Comment by noahmanger** [comment]
Styles applied, deploying now. Any changes that need to be made based on usability testing can be logged separately.
