### ISSUE TITLE
display active menu items in mobile menu

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC-web-app#969]
So that users can more easily explore the active parts of the site, we should prioritize displaying the active menu items in the mobile nav over the inactive ones. Is it a heavy lift to switch to defaulting to showing the "Campaign finance data" menu item expanded instead of collapsed?
![img_6045](https://cloud.githubusercontent.com/assets/4323988/11406990/098bb6e8-9365-11e5-8d9d-c65a88e9c37a.jpg)

**Comment by jenniferthibault** [comment]
Very shortly, Reg/Reporting and calendar will be active. Contact should currently be active (though this screen doesn't show it as so, so that's an error). 

Since more content is launching soon, I'd say we should leave it as it. 

A good lesson to learn for future beta launches though Leah, thank you for pointing it out!
