### ISSUE TITLE
Make design tweaks to candidate page for cycle select

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#976]
**Goal:** Based on feedback from usability testing, make minor visual changes to the candidate pages in order to more clearly associate the cycle select with the data lower on the page. 

**Tasks:**
- [x] @jenniferthibault mockup
- [ ] I'll implement

**Comment by jenniferthibault** [comment]
Research note summary on the candidate's page from @onezerojeremy & @emileighoutlaw :

- [ ] Link terms under Candidate Committee section such as “Principal campaign Committee, and “Authorized Campaign Committees” to glossary
<img width="455" alt="screen shot 2015-12-07 at 1 27 20 pm" src="https://cloud.githubusercontent.com/assets/11636908/11635681/4684af7a-9ce6-11e5-882d-f4feb9cdad08.png">

### 2/4/6 cycle select
- The distance between the toggle and data being changed is quite large. This lead to confusion about what is changing. We recommend to:
  - not trigger a reload when making a change.
  - moving the explanatory text (which no one reads) to below the Campaign Committees dark blue box (Depicted below)
  - consider clarifying and dividing explanatory text for “Candidates receive and spend money …” text copy. It seems that it may pertain to different parts of the page and site.

<img width="631" alt="screen shot 2015-12-07 at 1 28 47 pm" src="https://cloud.githubusercontent.com/assets/11636908/11635744/9479b55e-9ce6-11e5-9ff3-5674c8a60322.png">

I'll be basing the next mockups on the above, but expect to have some differences^

**Comment by emileighoutlaw** [comment]
I think the issue of clarifying and dividing explanatory text could be solved by leaving the paragraph in it's proposed spot (under **Campaign committees**) and tweaking the wording:

> Candidates receive and spend money through committees. The combined financial totals on this page are for all authorized committees. Learn more about each committee's fundraising and spending on its page.

**Comment by jenniferthibault** [comment]
A few small additions and tweaks to try out in the mockup above:

<img width="708" alt="screen shot 2015-12-08 at 6 13 17 pm" src="https://cloud.githubusercontent.com/assets/11636908/11671568/6a47ee6c-9dd7-11e5-8e00-7729a260e3dd.png">

- Add an h2 class of the year range selected before the tab navigation
- make "Combined financial totals" and "Campaign committees" h3
- Not relevant to this interaction, but for design simplicity, I cleaned up the committee cards a bit.


<img width="709" alt="screen shot 2015-12-08 at 6 06 15 pm" src="https://cloud.githubusercontent.com/assets/11636908/11671600/8f34bf20-9dd7-11e5-9e38-3302518cd370.png">

- Make this part of the piece that shows up as you scroll down the page so that you can tell it applies to the whole shebang as you're moving about.
 - This part should appear when the tabs hit the top of the screen as you're scrolling. Right now, it happens below this, at the start of the copy. It would be ideal if we could make this transition a little more seamless, so that it looks like it just stays, instead of disappears and reappears.  (hard to describe, glad to talk though on a call @noahmanger )

**Comment by noahmanger** [comment]
Nice! I love all of this. Great idea to put the years in the tab bar.

You know I appreciate you thinking about heading levels, but to my eye making the years an H2 just looks off. I think because they're a different size than the tabs. I'll happily cede to your judgement, but just my $.02. 

I'll get to work implementing in general and we can refine as needed.

**Comment by noahmanger** [comment]
Small question: I just noticed those numbers were left-aligned on staging, but this was an accidental regression. Do you want them right aligned or left aligned?

**Comment by noahmanger** [comment]
So testing it out, I'm actually liking the year range as the H2, but I would like to pair with you on this to suss out some of the finer details. Shouldn't be much work, but it'll be good to get your eye.

**Comment by jenniferthibault** [comment]
Thanks @noahmanger — let's indeed wrap this up with a pairing session. Calendar invite coming your way!

**Comment by noahmanger** [comment]
Implemented https://github.com/18F/fec-style/pull/202 and https://github.com/jmcarp/openFEC-web-app/pull/17 . Will close once they're merged.
