### ISSUE TITLE
Improve and extend typeahead filters

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#982]
**[Story](https://18f.storiesonboard.com/m/fec/!card/0IUxlAq1iQGHnDnTzAVHwQ):**So that users can easily filter to the candidates they’re looking for, improve and implement autocomplete filters.

# Discussion:
This is one of the dev tasks we had previously identified, and it goes along with our general priority of improving filters. I'm finding I've got extra time this sprint, so even though we hadn't discussed it yet, I thought I'd at least start looking at it. 

## Current behavior
We currently have two different filters for _ostensibly_ searching for candidate and committee names, but I think it's possible (and desireable) to have one. Here's what we currently have:

### 1. On candidate and committee page:

![image](https://cloud.githubusercontent.com/assets/1696495/11729545/b55a0444-9f44-11e5-8a25-902eff01cba1.png)

Current behavior:
- This searches the `name` parameter of the API
- Only accepts a single argument. You can't search "obama, pelosi" for instance
- Does a simple text search, not matching by candidate or committee ID

### 2. On receipts, disbursements and filings pages, we have the typeahead filters:
![image](https://cloud.githubusercontent.com/assets/1696495/11729624/07177618-9f45-11e5-9527-e9d7e1623d21.png)

Current behavior:
- The user **must** select an option from the typeahead. 
- Selecting an option adds a value to a hidden field to actually search `candidate_id` or `committee_id` for the selected item's ID
- Simply submitting the field with just text will return no results because it's trying to search the '_id' for a name string, which can be confusing
- But! This allows us to precisely filter for transactions and filings associated with particular entities
- Supports multiple arguments, so you can stack filters for multiple entities

## Ideal behavior
I think the ideal solution would be a single type of field that behaves the same in all cases but serves the needs of both. Here's how I think it would work:
- User can submit basic text by typing and hitting enter. This submits the filter as a `name` value
- Doing so adds a checkbox above, but perhaps the string should be in quotes
- If the user selects an option from the typeahead list (either by clicking on it or tabbing to complete the field), the filter submits with the `id` value of the match
- This adds the selected option above as well
- If the user enters an `id`, the filter submits as an `id` and the name of the entity is added as a checkbox above

## Questions
- Could the receipts, disbursements and filings filters operate by searching for a `name` parameter?
- Can we accept multiple `name` arguments on the API?
- Should we instead of doing both `id` and `name` just do `name`? And in the case of the typeahead it will just allow you to get an exact match of the name rather than secretly submitting an `id`?
- Any downsides or questions?

Ok. Just wanted to get that out of my head. If anyone has thoughts, great. But I'm also happy to back burner this until we choose to prioritize.

**Comment by LindsayYoung** [comment]
Lots of good thoughts here!

The API takes multiple committee or candidate IDs in many places and that would be an easy thing to add. 

We did some work unifying search and If something doesn't show up in the typeahead, it is not going to show up in search, unless there is a result in a different category. (Correct me if I am wrong.)

I think you have a good point about consolidating filters, though we don't want to take it too far. Sometimes we would not want a candidate or committee to be populated in the same field. it doesn't make sense to search for candidates if there are not going to be any, but it would make people wonder why there are no results. 

I do think think the more confusing part it committee vs. non-committee results. The smallest fix is putting the non-committee field first. That is probably what they want.  We can probably come up with a better fix than that. The difference between committee and non-committee is which field they are searching. 

We could do text search, but that is really just removing tools. Name search is generally a bad way to find committees and candidates, because names are not unique and the same name can be reported differently in different places. I would be reluctant to diminish the power of the product as a data tool. I know we have talked about letting users add additional filters before; I think this is a problem that might be solved by doing that. Having a few default filters and then letting power users add the confusing ones.

For receipts, disbursements and IEs, we definitely want separate search fields for where the money is going and where the money came from. 

Also, I think we should add IDs to the typeahead select for power users.

**Comment by noahmanger** [comment]
Cool. Thanks for responding. But I want to try to clarify some things to make sure we're talking about the same thing:
- I'm not suggesting we unify candidate and committee typeahead results. We should continue to have different fields for searching candidates and committees. What I am suggesting is that we get unify the fields we have for searching **candidate name** and **candidate IDs (i.e. typeahead)** / **comittee name** and **committee IDs (i.e. typeahead)**.
- Doing this could allow us to combine the fields for "non-committee contributor" and "committee contributor" on the receipts page, but I could also be fine with keeping those separate.
- I'm not suggesting we unify search fields for source and recipient. I agree those need to be separate.
- And I agree we don't want to reduce the power as a data tool. I would never want to get rid of the ability to search by committee ID, just maybe disambiguating it from searching by text. (But also maybe not).

**Comment by LindsayYoung** [comment]
Thanks for clarifying! I was definitely misunderstanding some of what you were saying. I think we are mostly on the same page.

I think we should always have typeahead for candidate and committee names and you should be able to select multiple candidates or committees.

I don't think that there is a way to combine "non-committee contributor" and "committee contributor" on the receipts page without loosing functionality. If we are only doing text search, we lose the ability to  search the field that has committee ids in it.

**Comment by jenniferthibault** [comment]
Super good thoughts here, and what a gnarly thing this is! 

On the search interaction, my understanding of the ideal interaction (regardless of what field) closely tracks to how @noahmanger described:
- It should be possible for a user to search in any search field with basic text, have the type-ahead come up as a suggestion, but if they don’t want an entry from the typeahead, it will search as basic text across the available fields. If the user does want the options in type-ahead, and they select one of them, it will only show those results for type-ahead entry, until another is added through an additional search term entered. In this way, the field will always behave like a search field, with the option to choose an option from the type-ahead, (and it knows it's going to limit to that precise one) or not.

- On the question of whether a checkbox is generated, I would posture that since we are introducing the filter tags, the checkbox no longer needs to be created for any search. Any term entered in the search, through type-ahead or basic text, would generate a filter tag in the tag area. The guiding principle here, that if you are able to search by more than one query in one place (typeahead) you should be able to search by multiple queries or terms in all places (basic search). 

- I do like the idea of combining the fields for "non-committee contributor" and "committee contributor" on the receipts page, as "contributor" and allow that to search committees **and** non-committees. Can you help me better understand the barrier or lost functionality to that?

**Comment by jmcarp** [comment]
> On the question of whether a checkbox is generated, I would posture that since we are introducing the filter tags, the checkbox no longer needs to be created for any search.

Not sure about this, if I'm reading correctly. So far, the filter panel and the filter tags have a one-to-one correspondence: there's exactly one tag for each checked checkbox or non-empty text field, and vice versa--meaning that users can get a complete picture of the current filter rules from either the panel or the tags. Dropping checkboxes for typeahead searches would break that correspondence, and make the tags the only reliable indicator of filter rules. Which intuitively doesn't seem ideal. Sorry if I'm misinterpreting--let me know if I am.

**Comment by noahmanger** [comment]
No, you're reading correctly and that's a good point. I think I'm probably in favor of keeping the checkboxes for consistency's sake.

**Comment by noahmanger** [comment]
Takeaway from the meeting: let's sort this out over video. I'll add it to the agenda for our team check-in on Monday.

**Comment by jenniferthibault** [comment]
Here's what I understand as the take-away from Monday's conversation:

Using the contributor search as an example, we're going to combine both the functionality of basic search and typeahead search into one search bar, AND allow users to search by name or committee ID in ONE search bar.  This would either 
- a) accept a text string that can search against the "contributor name" column; 
- b) accept a typeahead suggestion option, which behind-the-scenes assigns a committee ID; or 
- c) accept a text string for committee ID and use that to search against the contributor ID column

This search bar would allow users to create multiple search terms through check boxes (and filter tags) once a user selects the term they want.

**The fields we have now:**
<img width="293" alt="screen shot 2016-01-13 at 10 16 05 am" src="https://cloud.githubusercontent.com/assets/11636908/12298348/9c9f0ff2-b9df-11e5-9e03-ff8aa02923d9.png">

**How we could make those two into one:**
<img width="290" alt="screen shot 2016-01-13 at 10 15 48 am" src="https://cloud.githubusercontent.com/assets/11636908/12298353/a0ecf506-b9df-11e5-9f8b-e4765410b2e0.png">




This same functionality and ID logic could and should be adapted to other fields as well, though I'm not sure what they are without hunting them down at the moment.

@jmcarp @LindsayYoung how does this square with what you took away from Monday?

**Comment by LindsayYoung** [comment]
Yes, that seems like what we agreed. 

Do you think that we could also use the glossary or a tool tip to explain why using an ID and using a string behave differently?

When I think about it, for receipts, if I really needed to find all receipts from a committee, I would want to search for the string of their name and their ID, because the filings are inconsistent and they don't always get all the fields the right. I would also want to double check those results with disbursement records of that committee.

**Comment by jenniferthibault** [comment]
I very very much see that concern as someone who knows what's going on behind the scenes, and love that you are looking out to make sure users understand what is happening!

This is a good thing to clarify. Since you could use this unified search field multiple times, could a user enter a candidate ID number, hit enter (so it would be a filter tag and check box) then enter the candidate name, hit enter (so it would be a filter tag and check box) and in that way, it would allow users to show results with matching name and ID for those who want to be ultra accurate? Like this:
<img width="444" alt="screen shot 2016-01-15 at 12 04 14 pm" src="https://cloud.githubusercontent.com/assets/11636908/12359384/2762deba-bb80-11e5-8a55-b80e39e8c09e.png">

**Comment by LindsayYoung** [comment]
We might want to add the name at the end of the ID so people know what they are looking for:
ID C8675309 (Americans for Joyfulness)  

Especially if you are looking at a few committees, this would be helpful.

To me, string searches in quotes would be intuitive, or as intuitive as any of this gets:
"Democracy for America"

**Comment by jenniferthibault** [comment]
THE QUOTES MAKE SO MUCH SENSE!

If it's a text string (meaning a user did not select it from a typeahead option) it should be in quotes. Yes. Yes yes yes. 

Looking at the [ID ########] [(Name)] , @emileighoutlaw has been looking at instances of tag length in other places, so I want to ping her on here just for a heads up and for help figuring out if that's too long. The logic does make sense to me though!

**Comment by emileighoutlaw** [comment]
I _think_ it'll work? I'd love to see it in action, but 

> ID: C8675309, "Americans for Joyfulness"

Is probably okay. How long do committee names get?

**Comment by jenniferthibault** [comment]
Sorry for leaving it unclear. The scenario here is for when a user enters a Committee ID from the typeahead filter, AND enters a basic text search query in addition. The question then, is what happens when the name of the Committee associated with the ID (or any resulting committee name provided by typeahead) is very long? You can see some names [here](https://beta.fec.gov/data/committees/), they do get very long.

I think we might want to truncate them after a specific number of characters. For example, here are two scenarios in which a user is looking for committee by ID, then also enter part or the full name of the committee as a basic text search to make sure they're seeing accurate results:

<img width="809" alt="screen shot 2016-01-15 at 3 54 28 pm" src="https://cloud.githubusercontent.com/assets/11636908/12365060/625f8476-bba0-11e5-970d-0490b9a05b72.png">

**Comment by LindsayYoung** [comment]
That looks good to me.  Even if the tag is a bit big, it is so much more helpful to have a name.

**Comment by emileighoutlaw** [comment]
Oh I see! And I love your construction in the mock-up. I agree with you, Lindsay that the big tag is worth it.

For the cutoff, it seems like 20 characters of text feels like a good line. In browsing group names, I noticed a couple content themes:

1. Groups that start with a candidate name or other salient info:
> Mirza for Congress
> Cops Lives Matter

These names will be clear and unique, wherever our character cutoff is. 

2. Groups that start with popular (and generic) words, many of which have a lot of characters. (I'm looking at you `Committee` `Americans` and `Friends of`). Making our cutoff 20 characters would add the extra space we need to get something sufficiently unique in the parenthetical.

Here are some samples at an 20 character cutoff
>(Committee for Campai..)
(Americans for Campa...)
(Millenials for Camp...)

Thoughts on that?

**Comment by jenniferthibault** [comment]
:+1: :+1:  Thank you for the testing! I think this is ready for implementation then.

**Comment by noahmanger** [comment]
Awesome. This all looks terrific. I love the quote marks to distinguish string searches. Thanks for hashing this out!

**Comment by noahmanger** [comment]
Implementation: https://github.com/18F/openFEC-web-app/issues/1022
